VIDA_INICIAL_AGONIX_BOSS_1:					equ	8
VIDA_TOTAL_INICIAL_BOSS_1:					equ	VIDA_INICIAL_AGONIX_BOSS_1
VIDA_ANCHO_BARRA_BOSS_1:					equ	99

PAGINA_REGRESO_BOSS_1:						equ	26

; VRAM / sprites
SPRITES_ATRIBUTOS_VRAM_BOSS_1:				equ	#4A00
SPRITES_COLOR_VRAM_BOSS_1:					equ	#4800
PATRONES_SPRITES_VRAM_BOSS_1:				equ	#4000
PAGE_1_VRAM_Y_BOSS_1:						equ	#0100
PAGE_2_VRAM_Y_BOSS_1:						equ	#0200
PAGE_X_VRAM_BOSS_1:							equ	#0000
SPRITES_LIMPIA_INICIAL_BOSS_1:				equ	10
SPRITES_LIMPIA_CANT_INICIAL_BOSS_1:			equ	22
RATA_PATRON_DERECHA_BOSS_1:					equ	100
RATA_PATRON_IZQUIERDA_BOSS_1:				equ	104
RATA_COLOR_DERECHA_BOSS_1:					equ	RATA_PATRON_DERECHA_BOSS_1/4
RATA_COLOR_IZQUIERDA_BOSS_1:				equ	RATA_PATRON_IZQUIERDA_BOSS_1/4
RATAS_MUERTE_CANTIDAD_BOSS_1:				equ	8
RATAS_MUERTE_SPRITE_INICIAL_BOSS_1:			equ	10
RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_1:			equ	SPRITES_ATRIBUTOS_VRAM_BOSS_1+RATAS_MUERTE_SPRITE_INICIAL_BOSS_1*4
RATAS_MUERTE_COLOR_VRAM_BOSS_1:				equ	SPRITES_COLOR_VRAM_BOSS_1+RATAS_MUERTE_SPRITE_INICIAL_BOSS_1*16
RATAS_MUERTE_PASOS_ENTRE_COPY_BOSS_1:		equ	8
RATAS_MUERTE_SALIDA_PAUSA_BOSS_1:			equ	1
RATAS_MUERTE_ENTRADA_PAUSA_BOSS_1:			equ	1
RATAS_MUERTE_Y_OCULTA_BOSS_1:				equ	217
RATAS_MUERTE_X_OCULTA_BOSS_1:				equ	255
RATAS_MUERTE_PASO_X_BOSS_1:					equ	3
COPY_SIN_OFFSET_BOSS_1:						equ	#00
COPY_LOGICA_NORMAL_BOSS_1:					equ	10010000b
COPY_LOGICA_RELLENO_BOSS_1:					equ	11000000b

; Proyectiles del boss
PROYECTILES_BOSS_1_CANTIDAD:				equ	8
PROYECTIL_BOSS_1_ESPERA_INICIAL:			equ	15
PROYECTIL_BOSS_1_SPRITE_INICIAL:			equ	22
PROYECTIL_BOSS_1_SPRITE_FINAL:				equ	30
PROYECTIL_BOSS_1_Y_OCULTO:					equ	217
PROYECTIL_BOSS_1_SPRITES_ACTIVOS_OFS:		equ	12
PROYECTIL_BOSS_1_ATRIBUTOS_VRAM:			equ	SPRITES_ATRIBUTOS_VRAM_BOSS_1+PROYECTIL_BOSS_1_SPRITE_INICIAL*4
PROYECTIL_BOSS_1_COLOR_VRAM:				equ	SPRITES_COLOR_VRAM_BOSS_1+PROYECTIL_BOSS_1_SPRITE_INICIAL*16
PROYECTIL_BOSS_1_PATRON_SPRITE:				equ	160
PROYECTIL_BOSS_1_OFFSET_DER_X:				equ	98-8
PROYECTIL_BOSS_1_OFFSET_IZQ_X:				equ	29-8
PROYECTIL_BOSS_1_OFFSET_Y:					equ	25-8
PROYECTIL_BOSS_1_DIRECCION_MIN:				equ	1
PROYECTIL_BOSS_1_DIRECCION_MAX:				equ	11
AGONIX_IMPACTO_DER_X_MIN_BOSS_1:			equ	94-8
AGONIX_IMPACTO_DER_X_ANCHO_BOSS_1:			equ	10
AGONIX_IMPACTO_IZQ_X_MIN_BOSS_1:			equ	24-8
AGONIX_IMPACTO_IZQ_X_ANCHO_BOSS_1:			equ	10
AGONIX_IMPACTO_Y_MIN_BOSS_1:				equ	19-8
AGONIX_IMPACTO_Y_ALTO_BOSS_1:				equ	10

; Salida y muerte de Agonix
COLOR_ALEATORIO_SIN_CAMBIOS_BOSS_1:			equ	1
AGONIX_PAUSA_BOCA_BOSS_1:					equ	100
AGONIX_LIMPIA_SPRITE_INICIAL_BOSS_1:		equ	10
AGONIX_LIMPIA_SPRITES_CANT_BOSS_1:			equ	20
AGONIX_MUERTE_Y_LIMITE_VISIBLE_BOSS_1:		equ	162
AGONIX_MUERTE_BUCLES_BOSS_1:                equ AGONIX_MUERTE_Y_LIMITE_VISIBLE_BOSS_1-(AGONIX_MUERTE_SY_BOSS_1+AGONIX_MUERTE_ALTO_BOSS_1)
AGONIX_MUERTE_FX_BOSS_1:					equ	31
AGONIX_MUERTE_FX_CANAL_BOSS_1:				equ	0
AGONIX_MUERTE_PAUSA_BOSS_1:					equ	8

AGONIX_MUERTE_SX_BOSS_1:					equ	0
AGONIX_MUERTE_SY_BOSS_1:					equ	66
AGONIX_MUERTE_DX_BOSS_1:					equ	0
AGONIX_MUERTE_DY_BOSS_1:					equ	67
AGONIX_MUERTE_ANCHO_BOSS_1:					equ	130
AGONIX_MUERTE_ALTO_BOSS_1:					equ	48
RATAS_MUERTE_Y_BOSS_1:                      equ AGONIX_MUERTE_SY_BOSS_1+AGONIX_MUERTE_ALTO_BOSS_1-16
RATAS_MUERTE_X_MIN_OFFSET_BOSS_1:			equ	20
RATAS_MUERTE_X_MAX_OFFSET_BOSS_1:			equ	AGONIX_MUERTE_ANCHO_BOSS_1-20
AGONIX_BUFFER_X_BOSS_1:						equ	0
AGONIX_BUFFER_Y_BOSS_1:						equ	0

DEPH_SALIDA_SPRITES_INICIO_BOSS_1:			equ	1
DEPH_SALIDA_SPRITES_CANT_BOSS_1:			equ	45

AGONIX_ANIMACION_OFFSET_INICIAL_BOSS_1:		equ	128
AGONIX_ANIMACION_OFFSET_FINAL_BOSS_1:		equ	0
AGONIX_ANIMACION_X_FINAL_BOSS_1:			equ	130
AGONIX_ANIMACION_SX_1_BOSS_1:				equ	0
AGONIX_ANIMACION_SX_2_BOSS_1:				equ	126
AGONIX_ANIMACION_SY_1_BOSS_1:				equ	0
AGONIX_ANIMACION_SY_2_BOSS_1:				equ	48
AGONIX_ANIMACION_PAUSA_BOSS_1:				equ	4
AGONIX_ANIMACION_FX_BOSS_1:					equ	29
AGONIX_ANIMACION_FX_CANAL_BOSS_1:			equ	0
AGONIX_ANIMACION_FX_CADA_COPYS_BOSS_1:		equ	00000011b

AGONIX_MOVIMIENTO_X_MAX_BOSS_1:				equ	126
AGONIX_MOVIMIENTO_Y_BOSS_1:					equ	66
AGONIX_MOVIMIENTO_PASO_X_BOSS_1:			equ	6
AGONIX_MOVIMIENTO_ESPERA_BOSS_1:			equ	6
AGONIX_MOVIMIENTO_PAG_DERECHA_BOSS_1:		equ	3
AGONIX_MOVIMIENTO_PAG_IZQUIERDA_BOSS_1:		equ	1
AGONIX_MOVIMIENTO_SX_1_BOSS_1:				equ	0
AGONIX_MOVIMIENTO_SX_2_BOSS_1:				equ	126
AGONIX_MOVIMIENTO_SY_1_BOSS_1:				equ	0
AGONIX_MOVIMIENTO_SY_2_BOSS_1:				equ	48
AGONIX_PARADO_SY_1_BOSS_1:					equ	96
AGONIX_PARADO_SY_2_BOSS_1:					equ	144
AGONIX_MOVIMIENTO_ANCHO_BOSS_1:				equ	130
AGONIX_MOVIMIENTO_ALTO_BOSS_1:				equ	48
AGONIX_MOVIMIENTO_BORRA_ANCHO_BOSS_1:		equ	6
AGONIX_MOVIMIENTO_BORRA_ALTO_BOSS_1:		equ	47
AGONIX_MOVIMIENTO_BORRA_COLOR_BOSS_1:		equ	#BB
AGONIX_MODO_MOVIMIENTO_BOSS_1:				equ	0
AGONIX_MODO_PARADO_BOSS_1:					equ	1
AGONIX_PARADO_DURACION_BOSS_1:				equ	50
AGONIX_MOVIMIENTO_AZAR_MAX_BOSS_1:			equ	100

CARGA_SPRITES_RATA_BOSS_1:

		call	PAGE_32_A_SEGMENT_2

		ld		hl,SPRITE_RATA
		ld		de,PATRONES_SPRITES_VRAM_BOSS_1+RATA_PATRON_DERECHA_BOSS_1*8
		ld		bc,8*4*2
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,COLOR_RATA
		ld		de,SPRITES_COLOR_VRAM_BOSS_1+RATA_COLOR_DERECHA_BOSS_1*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,COLOR_RATA
		ld		de,SPRITES_COLOR_VRAM_BOSS_1+RATA_COLOR_IZQUIERDA_BOSS_1*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		jp		PAGE_10_A_SEGMENT_2

RUTINA_BOSS_1:

		call	stpmus

		call	CARGA_SPRITES_RATA_BOSS_1

		ld      a,0
		ld      hl,SPRITES_ATRIBUTOS_VRAM_BOSS_1+SPRITES_LIMPIA_INICIAL_BOSS_1*4
		ld      bc,SPRITES_LIMPIA_CANT_INICIAL_BOSS_1*4
		call    FILVRM_RAM

.VARIABLES:

		ld		a,PAGINA_REGRESO_BOSS_1
		ld		(PAGINA_DE_REGRESO),a
		xor		a
		ld		(PROYECTIL_BOSS_1_DIRECCION),a
		ld		(PROYECTIL_BOSS_1_PASO_TABLA),a
		ld		(PROYECTIL_BOSS_1_X),a
		ld		(PROYECTIL_BOSS_1_SIGUIENTE_EMISOR),a
		ld		a,PROYECTIL_BOSS_1_ESPERA_INICIAL
		ld		(PROYECTIL_BOSS_1_ESPERA),a
		ld		a,PROYECTIL_BOSS_1_SPRITE_INICIAL
		ld		(PROYECTIL_BOSS_1_SPRITE_ACTUAL),a
		ld		(PROYECTIL_BOSS_1_SIGUIENTE_SPRITE),a
		ld		hl,SPRITES_ACTIVOS+PROYECTIL_BOSS_1_SPRITES_ACTIVOS_OFS
		ld		a,l
		ld		(PROYECTIL_BOSS_1_PUNTERO_SPRITES_ACTIVOS),a
		ld		a,h
		ld		(PROYECTIL_BOSS_1_PUNTERO_SPRITES_ACTIVOS+1),a
		ld		hl,PROYECTIL_BOSS_1_ATRIBUTOS_VRAM
		ld		a,l
		ld		(PROYECTIL_BOSS_1_DIRECCION_VRAM_ATRIBUTOS),a
		ld		a,h
		ld		(PROYECTIL_BOSS_1_DIRECCION_VRAM_ATRIBUTOS+1),a
		ld		hl,PROYECTIL_BOSS_1_COLOR_VRAM
		ld		a,l
		ld		(PROYECTIL_BOSS_1_DIRECCION_VRAM_COLOR),a
		ld		a,h
		ld		(PROYECTIL_BOSS_1_DIRECCION_VRAM_COLOR+1),a
		xor		a
		ld		(SPRITES_ACTIVOS+PROYECTIL_BOSS_1_SPRITES_ACTIVOS_OFS),a
		ld		(VALORES_EXPLOSION_CON_ROCK),a
		ld		(VALORES_EXPLOSION_CON_ROCK+1),a
		ld		(VALORES_EXPLOSION_CON_ROCK+2),a
		ld		(VALORES_EXPLOSION_CON_ROCK+3),a
		ld		a,VIDA_INICIAL_AGONIX_BOSS_1
		ld		(VIDA_AGONIX_BOSS_1),a
		xor		a
		ld		(AGONIX_BOSS_1_X),a
		ld		(AGONIX_BOSS_1_DIRECCION),a
		ld		(AGONIX_BOSS_1_FOTOGRAMA),a
		ld		(AGONIX_BOSS_1_MODO),a
		ld		a,AGONIX_MOVIMIENTO_ESPERA_BOSS_1
		ld		(AGONIX_BOSS_1_ESPERA_MOVIMIENTO),a
		call	NUEVO_TIEMPO_MOVIMIENTO_AGONIX_BOSS_1
		ld		a,PROYECTIL_BOSS_1_Y_OCULTO
		ld		(PROYECTIL_BOSS_1_Y),a
		call	INICIALIZA_POOL_PROYECTILES_BOSS_1

        ; Variables a reiniciar


        push    ix
        push    iy
        push    bc
        push    de

.COPIA_A_1_PARTE_ALTA:

        ld      ix,BOSS_1_PAGE_2_A_PAGE_1_COMPLETA
        ld      iy,DATAS_COPY_RECUP_SCROLL
        call    .BUCLE_PINTA_DATAS

        ld      iy,DATAS_COPY_RECUP_SCROLL
        ld      a,(PUNTO_DEL_SCROLL)

        ld      (iy+2),a
        ld      b,a
        ld      a,0
        sub     b
        ld      (iy+10),a
        push    af
        xor     a
        ld      (iy+11),a
        ld      hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY

.COPIA_A_1_PARTE_BAJA:
        
        ld      ix,BOSS_1_PAGE_2_A_PAGE_1_COMPLETA
        ld      iy,DATAS_COPY_RECUP_SCROLL
        call    .BUCLE_PINTA_DATAS

        ld      iy,DATAS_COPY_RECUP_SCROLL
        ld      a,(PUNTO_DEL_SCROLL)
        ld      b,a
        ld      a,0
        sub     b
        ld      (iy+6),a
        pop     af
        dec     a
        ld      b,a
        ld      a,#FF
        sub     b
        ld      (iy+10),a
        xor     a
        ld      (iy+11),a
        ld      hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY 
        call    VDPREADY

.GUARDA_DATOS_VIDA_AGONIX:

        ld      ix,BOSS_1_COPI_MARCADOR_BOSSES_CORAZONES_VACIOS
        ld      iy,DATAS_COR_EMPT_MALO
        call    .BUCLE_PINTA_DATAS

.GUARDA_DATOS_COPY_CORAZONES_EMPTY_DEPH:

        ld      ix,BOSS_1_COPY_CORAZONES_EMPTY_DEPH
        ld      iy,CORAZONES_DEPH_EN_BOSSES
        call    .BUCLE_PINTA_DATAS

.GUARDA_DATOS_COPY_PUNTOS_MAGIA:

        ld      ix,BOSS_1_COPY_PUNTOS_MAGIA
        ld      iy,PUNTOS_MAGIA_EN_BOSSES
        call    .BUCLE_PINTA_DATAS

.VARIABLES_DE_DEPH_RETOCADAS:

        ld      a,(PUNTO_DEL_SCROLL)
        ld      b,a
        ld      a,(Y_DEPH)
        sub     b
        ld      (Y_DEPH),a
        add     32
        ld      (Y_FALSA_PARA_DEPH),a

.PUNTO_DE_SCROLL_RETOCADO:

        ld      a,0
        ld      (PUNTO_DEL_SCROLL),a

.COLOCA_SPRITES_DEPH_EN_SU_SITIO:
        
        call    PINTA_SPRITE_DEPH

.CAMBIA_PAGE_PARA_OCULTAR:

        ld      a,1
        ld      (SET_PAGE),a

.COPIA_ESCENARIO_RECOLOCADO_A_PAGE_2:

 		ld	hl,BOSS_1_PAGE_1_A_PAGE_2_COMPLETA
		call	DOCOPY
        call    VDPREADY

.DEVUELVE_LA_PAGE_2:

        ld      a,2
        ld      (SET_PAGE),a

.CAMBIAMOS_MAS_VARIABLES_PARA_EL_CAMBIO_DE_SCROLL:

		ld	a,202
		ld	(DONDE_VA_LA_INTERRUPCION_LINEAL),a 

		ld	a,240
		ld	(Y_PINTA_SCROLL),a

 		ld	a,159
		ld	(LIM_Y_INF),a	
			
		ld	a,190
		ld	(LIM_MUERTE),a

		ld	a,195
		ld	(Y_LINEA_INT),a

.CARGA_AGONIX_PARTE_1:

        ld      a,50
        ld		b,51
        call	.CARGA_PANTALLA_COMPLETA

.COPIA_PAGE_1_A_PAGE_3:

		ld		hl,BOSS_1_DATOS_COPY_PAGE_1_A_PAGE_3
		call	DOCOPY
		call    VDPREADY
		jp		.CARGA_AGONIX_PARTE_2

.CARGA_AGONIX_PARTE_2:
		ld      a,52
		ld		b,53
		call	.CARGA_PANTALLA_COMPLETA

.CARGA_STATUS_BOSS:

        ld      a,45
        call	CHANGE_BANK_2

        ld		hl,STATUS_BOSS_1												; Carga gráficos fase
        ld		de,#0000+(256*200)/2
        ld		bc,(256*54)/2
        call	PON_COLOR_2.sin_bc_impuesta

        ld      a,10
        call	CHANGE_BANK_2  

.PINTA_STATUS:

        ld      b,15
        ld      hl,BOSS_1_COPIA_PARTE_PAGE_2_DE_STATUS
		call	DOCOPY 

        ld      b,15
        ld      hl,BOSS_1_COPIA_STATUS_BOSS_A_PAGE_2
		call	DOCOPY 
		call	PINTA_MARCADORES_VIDA_FINAL_BOSS_1

.BORRA_CORAZONES_QUE_SOBRAN:

        ld      a,(CORAZONES)
        ld      b,4
        
.BUCLE_BORRA_CORAZONES_DE_MAS:

        ex      af,af'
        ld      a,b
        ld      (CORAZONES),a
        call    .PINTA_CORAZONES_VIDA_DEPH_ADECUADOS
        ex      af,af'
        cp      b
        jp      z,.FINAL_BUCLE_CORAZONES
        djnz    .BUCLE_BORRA_CORAZONES_DE_MAS

.FINAL_BUCLE_CORAZONES:

        ld      (CORAZONES),a

.PINTA_MAGIAS_REALES:

	ld		ix,PUNTOS_MAGIA_EN_BOSSES
	ld		a,(MAGIAS)
[3]	add		a
	ld		c,25
	add		c
	ld		(ix),a
	ld		hl,PUNTOS_MAGIA_EN_BOSSES
	call	DOCOPY
		
.ANIMACION_AGONIX:

	ld		ix,BOSS_1_COPY_ANIMACION_AGONIX
	ld		iy,DATAS_COPY_RECUP_SCROLL
	call	.BUCLE_PINTA_DATAS
	ld		a,AGONIX_ANIMACION_OFFSET_INICIAL_BOSS_1
	ld		(VARIABLE_UN_USO),a
	xor		a
	ld		(VARIABLE_UN_USO2),a

.BUCLE_ANIMACION_AGONIX:

	ld		iy,DATAS_COPY_RECUP_SCROLL
	ld		a,(VARIABLE_UN_USO2)
	and		00000001b
	jr		z,.SX_1_ANIMACION_AGONIX
	ld		a,AGONIX_ANIMACION_SX_2_BOSS_1
	jr		.GUARDA_SX_ANIMACION_AGONIX

.SX_1_ANIMACION_AGONIX:

	ld		a,AGONIX_ANIMACION_SX_1_BOSS_1

.GUARDA_SX_ANIMACION_AGONIX:

	ld		c,a
	ld		a,(VARIABLE_UN_USO)
	add		c
	ld		(iy),a
	ld		a,(VARIABLE_UN_USO)
	ld		c,a
	ld		a,AGONIX_ANIMACION_X_FINAL_BOSS_1
	sub		c
	ld		(iy+8),a

	ld		a,(VARIABLE_UN_USO2)
	and		00000010b
	jr		z,.SY_1_ANIMACION_AGONIX
	ld		a,AGONIX_ANIMACION_SY_2_BOSS_1
	jr		.GUARDA_SY_ANIMACION_AGONIX

.SY_1_ANIMACION_AGONIX:

	ld		a,AGONIX_ANIMACION_SY_1_BOSS_1

.GUARDA_SY_ANIMACION_AGONIX:

	ld		(iy+2),a
	ld		hl,DATAS_COPY_RECUP_SCROLL
	call	DOCOPY
	call	VDPREADY
	ld		a,(VARIABLE_UN_USO2)
	and		AGONIX_ANIMACION_FX_CADA_COPYS_BOSS_1
	jr		nz,.SIN_FX_ANIMACION_AGONIX
	ld		a,AGONIX_ANIMACION_FX_BOSS_1
	ld		c,AGONIX_ANIMACION_FX_CANAL_BOSS_1
	call	TIRA_FX_BOSS_1

.SIN_FX_ANIMACION_AGONIX:

	ld		b,AGONIX_ANIMACION_PAUSA_BOSS_1

.PAUSA_ANIMACION_AGONIX:

	halt
	djnz	.PAUSA_ANIMACION_AGONIX

	ld		a,(VARIABLE_UN_USO2)
	inc		a
	ld		(VARIABLE_UN_USO2),a
	ld		a,(VARIABLE_UN_USO)
	cp		AGONIX_ANIMACION_OFFSET_FINAL_BOSS_1
	jp		z,.PREPARACION_PELEA
	sub		2
	ld		(VARIABLE_UN_USO),a
	jp		.BUCLE_ANIMACION_AGONIX

.PREPARACION_PELEA:
.EMPIEZA_LA_MUSICA:

		include	"../AUDIOS/INICIA MUSICA_BOSS.asm"


; todo el codigo de enfrentamiento

		jp	BUCLE_PELEA_BOSS_1

.CARGA_PANTALLA_COMPLETA:

		push	bc
        call	CHANGE_BANK_2
                                                                       
        ld		hl,#8000							; Posición de lectura			
        ld		de,#8000							; Posición de escritura
        ld		bc,16384							; Bits a leer
        call	PON_COLOR_2.sin_bc_impuesta

		pop		af
        call	CHANGE_BANK_2
                                                                        
        ld		hl,#8000									
        ld		de,#C000
        ld		bc,16384
        call	PON_COLOR_2.sin_bc_impuesta
		call	VDPREADY

		ld		a,10
        jp		CHANGE_BANK_2

.PINTA_CORAZONES_VIDA_DEPH_ADECUADOS:

	ld		ix,CORAZONES_DEPH_EN_BOSSES
	ld		a,(CORAZONES)
	ld		c,a
[9]	add		c
	ld		c,43
	add		c
	ld		(ix),a
	ld		(ix+4),a
    ld      hl,CORAZONES_DEPH_EN_BOSSES
	push	bc
	call   	DOCOPY
	pop		bc
	ret

.BUCLE_PINTA_DATAS:

        ld      b,15

.BUCLE_PINTA_DATAS_1:

        ld      a,(ix)
        ld      (iy),a
        ld      de,1
        add     ix,de
        add     iy,de
        djnz    .BUCLE_PINTA_DATAS_1
        ret

BUCLE_PELEA_BOSS_1:

		HALT
		ld		a,(CORAZONES)
		or		a
		jp		z,MUERTE_DEPH_EN_BOSS_1
		call	NUCLEO_DE_LA_PELEA_BOSS_1
		call	CONTROLA_INMUNIDAD_DEPH_BOSS_1
		
		call	MOVIMIENTO_DEPH_EN_BOSS_1
		call	SECUENCIA_PROYECTILES_PROPIOS_EN_BOSS_1
		call	PINTA_PROYECTILES_DE_DEPH_EN_BOSS_1
        call    REVISAMOS_COLISION_CON_AGONIX_Y_DEPH
		call	ON_SPRITE_GLOBAL_BOSS_1
		call	REVISAMOS_COLISION_CON_AGONIX_Y_PROYECTILES_DEPH
		call	MUEVE_AGONIX_BOSS_1
		call	PINTA_EXPLOSION_AGONIX_BOSS_1


        ld      a,(TIEMPO_DE_ADJUST)
        or      a
        jr      z,.CONTROL_POST_BUCLE_2
        dec     a
	ld      (TIEMPO_DE_ADJUST),a
	jr      nz,.CONTROL_POST_BUCLE_2
	xor     a
	ld      (COLOR_ALEATORIO),a

.CONTROL_POST_BUCLE_2:

		call	PINTA_PROYECTIL_BOSS_1
		jp	BUCLE_PELEA_BOSS_1

NUCLEO_DE_LA_PELEA_BOSS_1:

		call	SECUENCIA_PROYECTIL_BOSS_1
		ret

CONTROLA_INMUNIDAD_DEPH_BOSS_1:

		ld		a,(INMUNE)
		or		a
		ret		z
		dec		a
		ld		(INMUNE),a
		ret

INICIALIZA_POOL_PROYECTILES_BOSS_1:

		xor		a
		ld		(PROYECTIL_BOSS_1_SIGUIENTE_EMISOR),a
		ld		(PROYECTIL_BOSS_1_INDICE_ACTUAL),a
		ld		hl,PROYECTILES_BOSS_1_DIRECCION
		ld		b,PROYECTILES_BOSS_1_CANTIDAD

.INICIALIZA_DIRECCIONES_PROYECTIL_BOSS_1:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_DIRECCIONES_PROYECTIL_BOSS_1
		ld		hl,PROYECTILES_BOSS_1_PASO_TABLA
		ld		b,PROYECTILES_BOSS_1_CANTIDAD

.INICIALIZA_PASOS_PROYECTIL_BOSS_1:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_PASOS_PROYECTIL_BOSS_1
		ld		hl,PROYECTILES_BOSS_1_X
		ld		b,PROYECTILES_BOSS_1_CANTIDAD

.INICIALIZA_X_PROYECTIL_BOSS_1:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_X_PROYECTIL_BOSS_1
		ld		a,PROYECTIL_BOSS_1_Y_OCULTO
		ld		hl,PROYECTILES_BOSS_1_Y
		ld		b,PROYECTILES_BOSS_1_CANTIDAD

.INICIALIZA_Y_PROYECTIL_BOSS_1:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_Y_PROYECTIL_BOSS_1
		xor		a
		ld		hl,SPRITES_ACTIVOS+PROYECTIL_BOSS_1_SPRITES_ACTIVOS_OFS
		ld		b,PROYECTILES_BOSS_1_CANTIDAD

.INICIALIZA_SPRITES_ACTIVOS_PROYECTIL_BOSS_1:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_SPRITES_ACTIVOS_PROYECTIL_BOSS_1
		ld		a,PROYECTIL_BOSS_1_SPRITE_INICIAL
		ld		(PROYECTIL_BOSS_1_SIGUIENTE_SPRITE),a
		ld		(PROYECTIL_BOSS_1_SPRITE_ACTUAL),a
		ld		a,PROYECTIL_BOSS_1_ESPERA_INICIAL
		ld		(PROYECTIL_BOSS_1_ESPERA),a
		ret

ACTIVA_PROYECTIL_BOSS_1:

		call	RESERVA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_1
		ret		z
		ld		a,(AGONIX_BOSS_1_DIRECCION)
		or		a
		ld		a,(AGONIX_BOSS_1_X)
		jr		nz,.EMISOR_IZQ_PROYECTIL_BOSS_1
		add		PROYECTIL_BOSS_1_OFFSET_DER_X
		jr		.GUARDA_X_EMISOR_PROYECTIL_BOSS_1

.EMISOR_IZQ_PROYECTIL_BOSS_1:

		add		PROYECTIL_BOSS_1_OFFSET_IZQ_X

.GUARDA_X_EMISOR_PROYECTIL_BOSS_1:

		ld		b,a
		ld		(PROYECTIL_BOSS_1_X),a
		ld		a,AGONIX_MOVIMIENTO_Y_BOSS_1+PROYECTIL_BOSS_1_OFFSET_Y
		ld		c,a
		ld		(PROYECTIL_BOSS_1_Y),a
		ld		a,(PROYECTIL_BOSS_1_X)
		ld		b,a
		call	CALCULA_DIRECCION_BASE_PROYECTIL_BOSS_1
		ld		(PROYECTIL_BOSS_1_PASO_TABLA),a
		call	CREA_PROYECTIL_AGONIX_BOSS_1
		ld		a,(PROYECTIL_BOSS_1_PASO_TABLA)
		dec		a
		cp		PROYECTIL_BOSS_1_DIRECCION_MIN
		jr		nc,.CREA_PROYECTIL_ANTERIOR_AGONIX
		ld		a,PROYECTIL_BOSS_1_DIRECCION_MAX

.CREA_PROYECTIL_ANTERIOR_AGONIX:

		call	CREA_PROYECTIL_AGONIX_BOSS_1
		ld		a,(PROYECTIL_BOSS_1_PASO_TABLA)
		inc		a
		cp		PROYECTIL_BOSS_1_DIRECCION_MAX+1
		jr		c,.CREA_PROYECTIL_POSTERIOR_AGONIX
		ld		a,PROYECTIL_BOSS_1_DIRECCION_MIN

.CREA_PROYECTIL_POSTERIOR_AGONIX:

		call	CREA_PROYECTIL_AGONIX_BOSS_1
		ret

CREA_PROYECTIL_AGONIX_BOSS_1:

		ld		(PROYECTIL_BOSS_1_DIRECCION),a
		call	RESERVA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_1
		ret		z
		ld		a,(PROYECTIL_BOSS_1_X)
		ld		b,a
		ld		a,(PROYECTIL_BOSS_1_Y)
		ld		c,a
		call	GUARDA_POSICION_PROYECTIL_BOSS_1_ACTUAL
		call	OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_1_ACTUAL
		xor		a
		ld		(hl),a
		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(PROYECTIL_BOSS_1_DIRECCION)
		ld		(hl),a
		call	CARGA_COLOR_PROYECTIL_BOSS_1_ACTUAL
		ret

SECUENCIA_PROYECTIL_BOSS_1:

		ld		b,PROYECTILES_BOSS_1_CANTIDAD
		xor		a
		ld		(PROYECTIL_BOSS_1_INDICE_ACTUAL),a

.BUCLE_SECUENCIA_PROYECTIL_BOSS_1:

		push	bc
		call	LEE_DIRECCION_TABLA_PROYECTIL_BOSS_1
		or		a
		jr		z,.SIGUIENTE_PROYECTIL_BOSS_1
		cp		2
		jr		z,.PROYECTIL_2
		cp		1
		jr		z,.PROYECTIL_1
		cp		4
		jr		z,.PROYECTIL_4
		cp		3
		jr		z,.PROYECTIL_3
		cp		6
		jr		z,.PROYECTIL_6
		cp		5
		jr		z,.PROYECTIL_5
		cp		8
		jr		z,.PROYECTIL_8
		cp		7
		jr		z,.PROYECTIL_7
		call	DESACTIVA_PROYECTIL_BOSS_1
		jr		.SIGUIENTE_PROYECTIL_BOSS_1

.SIGUIENTE_PROYECTIL_BOSS_1:

		ld		a,(PROYECTIL_BOSS_1_INDICE_ACTUAL)
		inc		a
		ld		(PROYECTIL_BOSS_1_INDICE_ACTUAL),a
		pop		bc
		djnz	.BUCLE_SECUENCIA_PROYECTIL_BOSS_1
		ret

.PROYECTIL_2:

		call	INC_X_PROYECTIL_BOSS_1_ACTUAL

.PROYECTIL_1:

		call	SUB_2_Y_PROYECTIL_BOSS_1_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_1
		jr		.SIGUIENTE_PROYECTIL_BOSS_1

.PROYECTIL_4:

		call	INC_Y_PROYECTIL_BOSS_1_ACTUAL

.PROYECTIL_3:

		call	INC_X_PROYECTIL_BOSS_1_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_1
		jr		.SIGUIENTE_PROYECTIL_BOSS_1

.PROYECTIL_6:

		call	DEC_X_PROYECTIL_BOSS_1_ACTUAL

.PROYECTIL_5:

		call	INC_Y_PROYECTIL_BOSS_1_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_1
		jr		.SIGUIENTE_PROYECTIL_BOSS_1

.PROYECTIL_8:

		call	SUB_2_Y_PROYECTIL_BOSS_1_ACTUAL

.PROYECTIL_7:

		call	DEC_X_PROYECTIL_BOSS_1_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_1
		jr		.SIGUIENTE_PROYECTIL_BOSS_1

COMPRUEBA_LIMITES_PROYECTIL_BOSS_1:

		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		cp		5
		jp		c,DESACTIVA_PROYECTIL_BOSS_1
		cp		192
		jp		nc,DESACTIVA_PROYECTIL_BOSS_1
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		cp		251
		jp		nc,DESACTIVA_PROYECTIL_BOSS_1
		ret

DESACTIVA_PROYECTIL_BOSS_1:

		xor		a
		push	af
		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_1_ACTUAL
		pop		af
		ld		(hl),a
		push	af
		call	OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_1_ACTUAL
		pop		af
		ld		(hl),a
		push	af
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_1_ACTUAL
		pop		af
		ld		(hl),a
		call	OBTIENE_PUNTERO_SPRITES_ACTIVOS_PROYECTIL_BOSS_1
		xor		a
		ld		(hl),a
		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_1_ACTUAL
		ld		a,PROYECTIL_BOSS_1_Y_OCULTO
		ld		(hl),a
		call	OCULTA_SPRITE_PROYECTIL_BOSS_1_EN_VRAM
		ret

PINTA_PROYECTIL_BOSS_1:

		ld		b,PROYECTILES_BOSS_1_CANTIDAD
		xor		a
		ld		(PROYECTIL_BOSS_1_INDICE_ACTUAL),a

.BUCLE_PINTA_PROYECTIL_BOSS_1:

		push	bc
		call	PINTA_UN_PROYECTIL_BOSS_1
		ld		a,(PROYECTIL_BOSS_1_INDICE_ACTUAL)
		inc		a
		ld		(PROYECTIL_BOSS_1_INDICE_ACTUAL),a
		pop		bc
		djnz	.BUCLE_PINTA_PROYECTIL_BOSS_1
		ret

PINTA_UN_PROYECTIL_BOSS_1:

		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		or		a
		ret		z
		jp		CARGA_ATRIBUTOS_PROYECTIL_BOSS_1

PINTA_PROYECTIL_BOSS_1_1:

		ld		(hl),a
		call	OBTIENE_DIRECCION_ATRIBUTOS_PROYECTIL_BOSS_1
		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta
		ret

CARGA_ATRIBUTOS_PROYECTIL_BOSS_1:

		ld		hl,PROPIEDADES_PATRON_SPRITE
		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		(hl),a
		inc		hl
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		ld		hl,PROPIEDADES_PATRON_SPRITE+1
		ld		(hl),a
		inc		hl
		ld		a,PROYECTIL_BOSS_1_PATRON_SPRITE
		jr		PINTA_PROYECTIL_BOSS_1_1

CARGA_COLOR_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_DIRECCION_COLOR_PROYECTIL_BOSS_1
		ld		hl,TABLA_COLOR_SPRITE_CENTRAL_BOSS_1
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta
		ret

OCULTA_SPRITE_PROYECTIL_BOSS_1_EN_VRAM:

		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		a,PROYECTIL_BOSS_1_Y_OCULTO
		ld		(hl),a
		inc		hl
		xor		a
		ld		(hl),a
		inc		hl
		ld		(hl),a
		call	OBTIENE_DIRECCION_ATRIBUTOS_PROYECTIL_BOSS_1
		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta
		ret

OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL:

		ld		a,(PROYECTIL_BOSS_1_INDICE_ACTUAL)
		ld		e,a
		ld		d,0
		ret

OBTIENE_PUNTERO_X_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL
		ld		hl,PROYECTILES_BOSS_1_X
		add		hl,de
		ret

OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL
		ld		hl,PROYECTILES_BOSS_1_Y
		add		hl,de
		ret

OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL
		ld		hl,PROYECTILES_BOSS_1_DIRECCION
		add		hl,de
		ret

OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL
		ld		hl,PROYECTILES_BOSS_1_PASO_TABLA
		add		hl,de
		ret

GUARDA_POSICION_PROYECTIL_BOSS_1_ACTUAL:

		push	bc
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_1_ACTUAL
		pop		bc
		ld		(hl),b
		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_1_ACTUAL
		ld		(hl),c
		ret

INC_X_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_1_ACTUAL
		inc		(hl)
		ret

DEC_X_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_1_ACTUAL
		dec		(hl)
		ret

INC_Y_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_1_ACTUAL
		inc		(hl)
		ret

SUB_2_Y_PROYECTIL_BOSS_1_ACTUAL:

		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		sub		2
		ld		(hl),a
		ret

OBTIENE_PUNTERO_SPRITES_ACTIVOS_PROYECTIL_BOSS_1:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL
		ld		hl,SPRITES_ACTIVOS+PROYECTIL_BOSS_1_SPRITES_ACTIVOS_OFS
		add		hl,de
		ret

OBTIENE_DIRECCION_ATRIBUTOS_PROYECTIL_BOSS_1:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL
		ld		a,e
		add		a,a
		ld		e,a
		ld		d,0
		ld		hl,TABLA_DIRECCIONES_VRAM_ATRIBUTOS_PROYECTIL_BOSS_1
		add		hl,de
		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		ret

OBTIENE_DIRECCION_COLOR_PROYECTIL_BOSS_1:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_1_ACTUAL
		ld		a,e
		add		a,a
		ld		e,a
		ld		d,0
		ld		hl,TABLA_DIRECCIONES_VRAM_COLOR_PROYECTIL_BOSS_1
		add		hl,de
		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		ret

RESERVA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_1:

		ld		a,(PROYECTIL_BOSS_1_SIGUIENTE_SPRITE)
		ld		b,PROYECTILES_BOSS_1_CANTIDAD

.BUSCA_SPRITE_LIBRE_PROYECTIL_BOSS_1:

		ld		c,a
		sub		PROYECTIL_BOSS_1_SPRITE_INICIAL
		ld		e,a
		ld		d,0
		ld		hl,PROYECTILES_BOSS_1_DIRECCION
		add		hl,de
		ld		a,(hl)
		or		a
		jr		z,.RESERVA_SPRITE_LIBRE_PROYECTIL_BOSS_1
		ld		a,c
		inc		a
		cp		PROYECTIL_BOSS_1_SPRITE_FINAL
		jr		c,.SIGUE_BUSQUEDA_SPRITE_LIBRE_PROYECTIL_BOSS_1
		ld		a,PROYECTIL_BOSS_1_SPRITE_INICIAL

.SIGUE_BUSQUEDA_SPRITE_LIBRE_PROYECTIL_BOSS_1:

		djnz	.BUSCA_SPRITE_LIBRE_PROYECTIL_BOSS_1
		xor		a
		ret

.RESERVA_SPRITE_LIBRE_PROYECTIL_BOSS_1:

		ld		a,e
		ld		(PROYECTIL_BOSS_1_INDICE_ACTUAL),a
		ld		a,c
		ld		(PROYECTIL_BOSS_1_SPRITE_ACTUAL),a
		call	OBTIENE_PUNTERO_SPRITES_ACTIVOS_PROYECTIL_BOSS_1
		ld		a,1
		ld		(hl),a
		ld		a,c
		inc		a
		cp		PROYECTIL_BOSS_1_SPRITE_FINAL
		jr		c,.GUARDA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_1
		ld		a,PROYECTIL_BOSS_1_SPRITE_INICIAL

.GUARDA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_1:

		ld		(PROYECTIL_BOSS_1_SIGUIENTE_SPRITE),a
		ld		a,1
		or		a
		ret
CALCULA_DIRECCION_BASE_PROYECTIL_BOSS_1:
		ld      a,11
		ld		c,0
		call 	PAGE_31_A_SEGMENT_2
		call	ayFX_INIT
		call	PAGE_10_A_SEGMENT_2

		ld		a,(X_DEPH)
		ld		e,a
		ld		a,b
		add		8
		ld		d,a
		ld		a,e
		sub		d
		jr		nc,.DEPH_A_LA_DERECHA
		ld		a,d
		sub		e
		ld		h,7
		jr		.COMPARA_DISTANCIAS

.DEPH_A_LA_DERECHA:

		ld		h,2

.COMPARA_DISTANCIAS:

		cp		8
		jr		c,.CENTRO
		ld		l,a
		ld		a,(Y_DEPH)
		cp		c
		jr		c,.ANGULO_EXTREMO
		sub		c
		ld		e,a
		ld		a,l
		add		a,a
		jr		c,.ANGULO_EXTREMO
		add		a,a
		jr		c,.ANGULO_EXTREMO
		cp		e
		jr		c,.ANGULO_CERRADO
		jr		z,.ANGULO_CERRADO
		ld		a,l
		add		a,a
		jr		c,.ANGULO_ABIERTO
		cp		e
		jr		c,.ANGULO_DIAGONAL
		jr		z,.ANGULO_DIAGONAL
		ld		a,l
		cp		e
		jr		c,.ANGULO_MEDIO
		jr		z,.ANGULO_MEDIO
		ld		a,e
		add		a,a
		jr		c,.ANGULO_ABIERTO
		cp		l
		jr		c,.ANGULO_EXTREMO
		jr		z,.ANGULO_ABIERTO

.ANGULO_ABIERTO:

		ld		a,h
		inc		a
		inc		a
		inc		a
		ret

.ANGULO_DIAGONAL:

		ld		a,h
		inc		a
		inc		a
		ret

.ANGULO_MEDIO:

		ld		a,h
		inc		a
		ret

.ANGULO_CERRADO:

		ld		a,h
		ret

.ANGULO_EXTREMO:

		ld		a,h
		inc		a
		inc		a
		inc		a
		inc		a
		ret

.CENTRO:

		ld		a,1
		ret

LEE_DIRECCION_TABLA_PROYECTIL_BOSS_1:

		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		or		a
		ret		z
		cp		12
		jr		nc,.DIRECCION_INVALIDA
		dec		a
		ld		b,a
		add		a,a
		add		a,b
		ld		e,a
		ld		d,0
		ld		hl,TABLA_DIRECCIONES_PROYECTIL_BOSS_1
		add		hl,de
		push	hl
		call	OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_1_ACTUAL
		ld		a,(hl)
		ld		c,a
		inc		a
		ld		(hl),a
		cp		3
		jr		c,.NO_REINICIA_PASO_TABLA
		xor		a
		ld		(hl),a

.NO_REINICIA_PASO_TABLA:

		pop		hl
		ld		b,0
		add		hl,bc
		ld		a,(hl)
		ret

.DIRECCION_INVALIDA:

		xor		a
		ret

MOVIMIENTO_DEPH_EN_BOSS_1:

		include	"COMUN/MOVIMIENTO EN BOSSES.asm"

MUEVE_AGONIX_BOSS_1:

		push	af
		push	bc
		push	de
		push	hl
		push	ix
		push	iy

		ld		a,(AGONIX_BOSS_1_MODO)
		or		a
		jr		nz,.MODO_AGONIX_PARADO

		ld		a,(AGONIX_BOSS_1_TIEMPO_MODO)
		dec		a
		ld		(AGONIX_BOSS_1_TIEMPO_MODO),a
		jr		nz,.MODO_AGONIX_MOVIMIENTO

		ld		a,AGONIX_MODO_PARADO_BOSS_1
		ld		(AGONIX_BOSS_1_MODO),a
		ld		a,AGONIX_PARADO_DURACION_BOSS_1
		ld		(AGONIX_BOSS_1_TIEMPO_MODO),a
		jp		.FIN_MOVIMIENTO_AGONIX

.MODO_AGONIX_PARADO:

		ld		a,(AGONIX_BOSS_1_TIEMPO_MODO)
		dec		a
		ld		(AGONIX_BOSS_1_TIEMPO_MODO),a
		jr		nz,.PINTA_AGONIX_PARADO

		ld		a,AGONIX_MODO_MOVIMIENTO_BOSS_1
		ld		(AGONIX_BOSS_1_MODO),a
		call	NUEVO_TIEMPO_MOVIMIENTO_AGONIX_BOSS_1
		call	ACTIVA_PROYECTIL_BOSS_1
		jp		.FIN_MOVIMIENTO_AGONIX

.PINTA_AGONIX_PARADO:

		ld		a,(AGONIX_BOSS_1_ESPERA_MOVIMIENTO)
		dec		a
		ld		(AGONIX_BOSS_1_ESPERA_MOVIMIENTO),a
		jp		nz,.FIN_MOVIMIENTO_AGONIX

		ld		a,AGONIX_MOVIMIENTO_ESPERA_BOSS_1
		ld		(AGONIX_BOSS_1_ESPERA_MOVIMIENTO),a
		jr		.PINTA_AGONIX_MOVIMIENTO

.MODO_AGONIX_MOVIMIENTO:

		ld		a,(AGONIX_BOSS_1_ESPERA_MOVIMIENTO)
		dec		a
		ld		(AGONIX_BOSS_1_ESPERA_MOVIMIENTO),a
		jp		nz,.FIN_MOVIMIENTO_AGONIX

		ld		a,AGONIX_MOVIMIENTO_ESPERA_BOSS_1
		ld		(AGONIX_BOSS_1_ESPERA_MOVIMIENTO),a

		ld		a,(AGONIX_BOSS_1_DIRECCION)
		or		a
		jr		z,.MUEVE_AGONIX_DERECHA

.MUEVE_AGONIX_IZQUIERDA:

		ld		a,(AGONIX_BOSS_1_X)
		or		a
		jr		z,.CAMBIA_AGONIX_A_DERECHA
		sub		AGONIX_MOVIMIENTO_PASO_X_BOSS_1
		ld		(AGONIX_BOSS_1_X),a
		jr		.PINTA_AGONIX_MOVIMIENTO_IZQUIERDA

.CAMBIA_AGONIX_A_DERECHA:

		xor		a
		ld		(AGONIX_BOSS_1_DIRECCION),a
		jr		.PINTA_AGONIX_MOVIMIENTO

.MUEVE_AGONIX_DERECHA:

		ld		a,(AGONIX_BOSS_1_X)
		cp		AGONIX_MOVIMIENTO_X_MAX_BOSS_1
		jr		nc,.CAMBIA_AGONIX_A_IZQUIERDA
		add		AGONIX_MOVIMIENTO_PASO_X_BOSS_1
		ld		(AGONIX_BOSS_1_X),a
		jr		.PINTA_AGONIX_MOVIMIENTO_DERECHA

.CAMBIA_AGONIX_A_IZQUIERDA:

		ld		a,1
		ld		(AGONIX_BOSS_1_DIRECCION),a

.PINTA_AGONIX_MOVIMIENTO:

		call	.PINTA_AGONIX_MOVIMIENTO_COMUN
		jr		.ACTUALIZA_FOTOGRAMA_AGONIX

.PINTA_AGONIX_MOVIMIENTO_DERECHA:

		call	BORRA_RASTRO_AGONIX_BOSS_1
		call	.PINTA_AGONIX_MOVIMIENTO_COMUN
		jr		.ACTUALIZA_FOTOGRAMA_AGONIX

.PINTA_AGONIX_MOVIMIENTO_IZQUIERDA:

		call	.PINTA_AGONIX_MOVIMIENTO_COMUN
		call	BORRA_RASTRO_AGONIX_BOSS_1
		jr		.ACTUALIZA_FOTOGRAMA_AGONIX

.PINTA_AGONIX_MOVIMIENTO_COMUN:

		ld		ix,BOSS_1_COPY_MOVIMIENTO_AGONIX
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_1.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL

		ld		a,(AGONIX_BOSS_1_FOTOGRAMA)
		and		00000001b
		jr		z,.SX_1_MOVIMIENTO_AGONIX
		ld		a,AGONIX_MOVIMIENTO_SX_2_BOSS_1
		jr		.GUARDA_SX_MOVIMIENTO_AGONIX

.SX_1_MOVIMIENTO_AGONIX:

		ld		a,AGONIX_MOVIMIENTO_SX_1_BOSS_1

.GUARDA_SX_MOVIMIENTO_AGONIX:

		ld		(iy),a

		ld		a,(AGONIX_BOSS_1_FOTOGRAMA)
		and		00000010b
		jr		z,.SY_1_MOVIMIENTO_AGONIX
		ld		a,(AGONIX_BOSS_1_MODO)
		or		a
		ld		a,AGONIX_MOVIMIENTO_SY_2_BOSS_1
		jr		z,.GUARDA_SY_MOVIMIENTO_AGONIX
		ld		a,AGONIX_PARADO_SY_2_BOSS_1
		jr		.GUARDA_SY_MOVIMIENTO_AGONIX

.SY_1_MOVIMIENTO_AGONIX:

		ld		a,(AGONIX_BOSS_1_MODO)
		or		a
		ld		a,AGONIX_MOVIMIENTO_SY_1_BOSS_1
		jr		z,.GUARDA_SY_MOVIMIENTO_AGONIX
		ld		a,AGONIX_PARADO_SY_1_BOSS_1

.GUARDA_SY_MOVIMIENTO_AGONIX:

		ld		(iy+2),a

		ld		a,(AGONIX_BOSS_1_DIRECCION)
		or		a
		ld		a,AGONIX_MOVIMIENTO_PAG_DERECHA_BOSS_1
		jr		z,.GUARDA_PAGINA_MOVIMIENTO_AGONIX
		ld		a,AGONIX_MOVIMIENTO_PAG_IZQUIERDA_BOSS_1

.GUARDA_PAGINA_MOVIMIENTO_AGONIX:

		ld		(iy+3),a
		ld		a,(AGONIX_BOSS_1_X)
		ld		(iy+4),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY
		ret

.ACTUALIZA_FOTOGRAMA_AGONIX:

		ld		a,(AGONIX_BOSS_1_FOTOGRAMA)
		inc		a
		and		00000011b
		ld		(AGONIX_BOSS_1_FOTOGRAMA),a

.FIN_MOVIMIENTO_AGONIX:

		pop		iy
		pop		ix
		pop		hl
		pop		de
		pop		bc
		pop		af
		ret

NUEVO_TIEMPO_MOVIMIENTO_AGONIX_BOSS_1:

		ld		a,r
		and		01111111b
		cp		AGONIX_MOVIMIENTO_AZAR_MAX_BOSS_1
		jr		c,.GUARDA_NUEVO_TIEMPO_MOVIMIENTO_AGONIX
		sub		AGONIX_MOVIMIENTO_AZAR_MAX_BOSS_1

.GUARDA_NUEVO_TIEMPO_MOVIMIENTO_AGONIX:

		inc		a
		ld		(AGONIX_BOSS_1_TIEMPO_MODO),a
		ret

BORRA_RASTRO_AGONIX_BOSS_1:

		push	af
		push	bc
		push	hl
		push	ix
		push	iy

		ld		ix,BOSS_1_BORRA_MOVIMIENTO_AGONIX
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_1.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL

		ld		a,(AGONIX_BOSS_1_DIRECCION)
		or		a
		jr		nz,.BORRA_RASTRO_AGONIX_IZQUIERDA

		ld		a,(AGONIX_BOSS_1_X)
		sub		AGONIX_MOVIMIENTO_BORRA_ANCHO_BOSS_1
		jr		nc,.GUARDA_X_BORRA_RASTRO_AGONIX
		xor		a
		jr		.GUARDA_X_BORRA_RASTRO_AGONIX

.BORRA_RASTRO_AGONIX_IZQUIERDA:

		ld		a,(AGONIX_BOSS_1_X)
		add		AGONIX_MOVIMIENTO_ANCHO_BOSS_1

.GUARDA_X_BORRA_RASTRO_AGONIX:

		ld		(iy+4),a
		xor		a
		ld		(iy+5),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY

		pop		iy
		pop		ix
		pop		hl
		pop		bc
		pop		af
		ret

SECUENCIA_PROYECTILES_PROPIOS_EN_BOSS_1:

		include	"COMUN/SECUENCIA PROYECTILES PROPIOS EN BOSSES.asm"

PINTA_PROYECTILES_DE_DEPH_EN_BOSS_1:

		include	"COMUN/PINTADO PROYECTILES PROPIOS EN BOSSES.asm"

ON_SPRITE_GLOBAL_BOSS_1:

	jp	BUCLE_REVISION_TODOS_LOS_PROYECTILES_OJO_BOSS_1

PINTA_MARCADORES_VIDA_FINAL_BOSS_1:

		ld		a,(VIDA_AGONIX_BOSS_1)
		call	CONVIERTE_VIDA_FINAL_A_BARRA_BOSS_1

		or		a
		ret		z
		ld		b,a
		ld		a,VIDA_ANCHO_BARRA_BOSS_1
		sub		b
		ld		c,151
		add		c

		ld		ix,DATAS_COR_EMPT_MALO
		ld		(ix+4),a
		ld		a,b
		ld		(ix+8),a
		xor		a
		ld		(ix+9),a

	 	ld	    hl,DATAS_COR_EMPT_MALO
		jp		DOCOPY

CONVIERTE_VIDA_FINAL_A_BARRA_BOSS_1:

		ld		c,a
		ld		a,VIDA_TOTAL_INICIAL_BOSS_1
		sub		c
        ld      b,a
        xor     a
        ld      d,a
        ld      l,a

.BUCLE_ESCALA_VIDA_FINAL_BOSS_1:

        ld      a,b
        or      a
        jr      z,.FIN_ESCALA_VIDA_FINAL_BOSS_1

        dec     b

        ld      a,l
        add     a,VIDA_ANCHO_BARRA_BOSS_1

.AJUSTA_ESCALA_VIDA_FINAL_BOSS_1:

        cp      VIDA_TOTAL_INICIAL_BOSS_1
        jr      c,.GUARDA_RESTO_ESCALA_VIDA_FINAL_BOSS_1

        sub     VIDA_TOTAL_INICIAL_BOSS_1
        inc     d
        jr      .AJUSTA_ESCALA_VIDA_FINAL_BOSS_1

.GUARDA_RESTO_ESCALA_VIDA_FINAL_BOSS_1:

        ld      l,a
        jr      .BUCLE_ESCALA_VIDA_FINAL_BOSS_1

.FIN_ESCALA_VIDA_FINAL_BOSS_1:

        ld      a,d
        ld      h,a
        ld      a,l
        or      a
        ld      a,h
        ret     z
        inc     a
        ret

BUCLE_REVISION_TODOS_LOS_PROYECTILES_OJO_BOSS_1:

		ld		hl,PROYECTILES_BOSS_1_DIRECCION
		ld		ix,PROYECTILES_BOSS_1_X
		ld		iy,PROYECTILES_BOSS_1_Y
		ld		b,PROYECTILES_BOSS_1_CANTIDAD

.BUCLE_REVISION_PROYECTILES_OJO_BOSS_1:

        ld      a,(hl)
        or      a
        jr      z,.SIGUIENTE_PROYECTIL_OJO_BOSS_1

        ; --- Comprobar X ---
        ld      a,(X_DEPH)
        add     a,20
        sub     (ix+0)          ; A = X_DEPH + 20 - X_PROYECTIL
        cp      36              ; 20 + 16
        jr      nc,.SIGUIENTE_PROYECTIL_OJO_BOSS_1

        ; --- Comprobar Y ---
        ld      a,(Y_DEPH)
        add     a,20
        sub     (iy+0)          ; A = Y_DEPH + 20 - Y_PROYECTIL
        cp      36              ; 20 + 16
        jr      nc,.SIGUIENTE_PROYECTIL_OJO_BOSS_1

        ; Si llega aquí, hay colisión

		call	DESACTIVA_PROYECTIL_OJO_BOSS_1_ACTUAL
		call	DANO_DEPH_EN_BOSS_1
		ret

.SIGUIENTE_PROYECTIL_OJO_BOSS_1:

		inc		hl
		inc		ix
		inc		iy
		djnz	.BUCLE_REVISION_PROYECTILES_OJO_BOSS_1
		ret

DESACTIVA_PROYECTIL_OJO_BOSS_1_ACTUAL:

		push	hl
		or		a
		ld		de,PROYECTILES_BOSS_1_DIRECCION
		sbc		hl,de
		ld		a,l
		ld		(PROYECTIL_BOSS_1_INDICE_ACTUAL),a
		pop		hl
		jp		DESACTIVA_PROYECTIL_BOSS_1

REVISAMOS_COLISION_CON_AGONIX_Y_DEPH:

		ld		a,(AGONIX_BOSS_1_X)
		ld		c,a
		ld		a,(X_DEPH)
		add		20
		cp		c
		ret		c

		ld		a,(AGONIX_BOSS_1_X)
		add		AGONIX_MOVIMIENTO_ANCHO_BOSS_1
		jr		c,.COMPRUEBA_Y_COLISION_AGONIX_DEPH
		ld		c,a
		ld		a,(X_DEPH)
		cp		c
		ret		nc

.COMPRUEBA_Y_COLISION_AGONIX_DEPH:

		ld		a,(Y_DEPH)
		add		20
		cp		AGONIX_MOVIMIENTO_Y_BOSS_1
		ret		c
		ld		a,(Y_DEPH)
		cp		AGONIX_MOVIMIENTO_Y_BOSS_1+AGONIX_MOVIMIENTO_ALTO_BOSS_1
		ret		nc

		call	DANO_DEPH_EN_BOSS_1
	ret

DANO_DEPH_EN_BOSS_1:

	call	DANO_DEPH_EN_BOSS_COMUN
	call	RUTINA_BOSS_1.PINTA_CORAZONES_VIDA_DEPH_ADECUADOS
	ret

MUERTE_DEPH_EN_BOSS_1:

	call	PREPARA_VRAM_PARA_MUERTE_DEPH_EN_BOSS
	jp		MUERTE_POR_TOQUES_DESDE_BOSS

REVISAMOS_COLISION_CON_AGONIX_Y_PROYECTILES_DEPH:

		ld		iy,PROYECTILES
		ld		b,6

.BUCLE_PROYECTILES_DEPH_AGONIX_BOSS_1:

		push	bc
		ld		a,(iy+2)
		cp		#FF
		jp		z,.SIGUIENTE_PROYECTIL_DEPH_AGONIX_BOSS_1

		ld		a,(AGONIX_BOSS_1_DIRECCION)
		or		a
		jr		nz,.REVISA_IMPACTO_AGONIX_IZQUIERDA_BOSS_1

		ld		a,(AGONIX_BOSS_1_X)
		add		AGONIX_IMPACTO_DER_X_MIN_BOSS_1
		ld		c,a
		ld		d,AGONIX_IMPACTO_DER_X_ANCHO_BOSS_1
		jr		.REVISA_X_IMPACTO_AGONIX_BOSS_1

.REVISA_IMPACTO_AGONIX_IZQUIERDA_BOSS_1:

		ld		a,(AGONIX_BOSS_1_X)
		add		AGONIX_IMPACTO_IZQ_X_MIN_BOSS_1
		ld		c,a
		ld		d,AGONIX_IMPACTO_IZQ_X_ANCHO_BOSS_1

.REVISA_X_IMPACTO_AGONIX_BOSS_1:

		ld		a,(iy)
		cp		c
		jp		c,.SIGUIENTE_PROYECTIL_DEPH_AGONIX_BOSS_1
		sub		c
		cp		d
		jp		nc,.SIGUIENTE_PROYECTIL_DEPH_AGONIX_BOSS_1

		ld		a,AGONIX_MOVIMIENTO_Y_BOSS_1+AGONIX_IMPACTO_Y_MIN_BOSS_1
		ld		c,a
		ld		a,(iy+1)
		cp		c
		jp		c,.SIGUIENTE_PROYECTIL_DEPH_AGONIX_BOSS_1
		sub		c
		cp		AGONIX_IMPACTO_Y_ALTO_BOSS_1
		jp		nc,.SIGUIENTE_PROYECTIL_DEPH_AGONIX_BOSS_1

		ld		a,(VIDA_AGONIX_BOSS_1)
		or		a
		jr		z,.SOBRE_PROYECTIL_DEPH_AGONIX_BOSS_1
		call	CALCULA_DANO_PROYECTIL_AGONIX_BOSS_1
		ld		c,a
		ld		a,(VIDA_AGONIX_BOSS_1)
		cp		c
		jr		nc,.RESTA_DANO_AGONIX_BOSS_1
		xor		a
		jr		.GUARDA_VIDA_AGONIX_TRAS_IMPACTO_BOSS_1

.RESTA_DANO_AGONIX_BOSS_1:

		sub		c

.GUARDA_VIDA_AGONIX_TRAS_IMPACTO_BOSS_1:

		ld		(VIDA_AGONIX_BOSS_1),a
		push	af
		call	PINTA_MARCADORES_VIDA_FINAL_BOSS_1
		pop		af
		or		a
		jr		z,.MUERE_AGONIX_POR_PROYECTIL_BOSS_1

.SOBRE_PROYECTIL_DEPH_AGONIX_BOSS_1:

		call	.LIMPIA_PROYECTIL_TRAS_IMPACTO_AGONIX_BOSS_1
		pop		bc
		ret

.MUERE_AGONIX_POR_PROYECTIL_BOSS_1:

		call	.LIMPIA_PROYECTIL_TRAS_IMPACTO_AGONIX_BOSS_1
		pop		bc
		jp		MUERTE_DE_AGONIX_BOSS_1

.LIMPIA_PROYECTIL_TRAS_IMPACTO_AGONIX_BOSS_1:

		ld		a,5
		ld		c,0
		call	TIRA_FX_BOSS_1

		ld		ix,VALORES_EXPLOSION_CON_ROCK
		ld		a,(iy)
		ld		(ix+1),a
		ld		a,(iy+1)
		sub		8
		ld		(ix),a
		ld		a,23*4
		ld		(ix+2),a

		ld		a,(iy+12)
		ld		e,a
		ld		d,0
		ld		hl,#4A00
		add		hl,de
		ex		de,hl
		ld		hl,.SPRITE_OCULTO_TRAS_IMPACTO_AGONIX_BOSS_1
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta

		xor		a
		ld		(iy+8),a
		dec		a
		ld		(iy+2),a
		ld		(iy),a
		ld		a,(iy+12)
		call	SECUENCIA_PROYECTILES_PROPIOS_EN_BOSS_1.DEJA_LIBRE_SPRITE_EN_RAM
		ret

.SPRITE_OCULTO_TRAS_IMPACTO_AGONIX_BOSS_1:

		db		217,255,0

.SIGUIENTE_PROYECTIL_DEPH_AGONIX_BOSS_1:

		ld		de,16
		add		iy,de
		pop		bc
		dec		b
		jp		nz,.BUCLE_PROYECTILES_DEPH_AGONIX_BOSS_1
		ret

CALCULA_DANO_PROYECTIL_AGONIX_BOSS_1:

		ld		a,(iy+4)
		cp		2
		jr		z,.DANO_HACHA_AGONIX_BOSS_1
		cp		1
		jr		z,.DANO_FUEGO_AGONIX_BOSS_1

.DANO_FLECHA_AGONIX_BOSS_1:

		ld		a,8
		ret

.DANO_HACHA_AGONIX_BOSS_1:

		ld		a,2
		ret

.DANO_FUEGO_AGONIX_BOSS_1:

		ld		a,1
		ret

PINTA_EXPLOSION_AGONIX_BOSS_1:

		ld		ix,VALORES_EXPLOSION_CON_ROCK
		ld		a,(ix+2)
		or		a
		ret		z
		cp		25*4
		jr		nz,.PINTAMOS_EXPLOSION_AGONIX_BOSS_1

		xor		a
		ld		(ix+2),a

.PINTAMOS_EXPLOSION_AGONIX_BOSS_1:

		ld		de,#4A00+17*4
		ld		hl,VALORES_EXPLOSION_CON_ROCK
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta

		ld		de,#4800+17*16
		ld		hl,BOSS_1_COLOR_EXPLOSION_AGONIX
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,(ix+2)
		or		a
		ret		z
		add		4
		ld		(ix+2),a
		ret

INICIALIZA_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		ix,RATAS_MUERTE_AGONIX_X
		ld		iy,BOSS_1_RATAS_MUERTE_OFFSET_X
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_1

.BUCLE_INICIALIZA_X_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		a,(AGONIX_BOSS_1_X)
		add		a,(iy)
		ld		(ix),a
		inc		ix
		inc		iy
		djnz	.BUCLE_INICIALIZA_X_RATAS_MUERTE_AGONIX_BOSS_1

		ld		ix,RATAS_MUERTE_AGONIX_ESPERA
		ld		hl,BOSS_1_RATAS_MUERTE_VELOCIDAD
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_1

.BUCLE_INICIALIZA_ESPERA_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		a,(hl)
		ld		(ix),a
		inc		hl
		inc		ix
		djnz	.BUCLE_INICIALIZA_ESPERA_RATAS_MUERTE_AGONIX_BOSS_1

		ld		hl,RATAS_MUERTE_AGONIX_ACTIVA
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_1
		ld		a,1

.BUCLE_INICIALIZA_ACTIVA_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		(hl),a
		inc		hl
		djnz	.BUCLE_INICIALIZA_ACTIVA_RATAS_MUERTE_AGONIX_BOSS_1

		call	PAGE_32_A_SEGMENT_2
		ld		de,RATAS_MUERTE_COLOR_VRAM_BOSS_1
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_1

.BUCLE_COLOR_RATAS_MUERTE_AGONIX_BOSS_1:

		push	bc
		push	de
		ld		hl,COLOR_RATA
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta
		pop		de
		ld		a,e
		add		16
		ld		e,a
		jr		nc,.SIN_ACARREO_COLOR_RATAS_MUERTE_AGONIX_BOSS_1
		inc		d

.SIN_ACARREO_COLOR_RATAS_MUERTE_AGONIX_BOSS_1:

		pop		bc
		djnz	.BUCLE_COLOR_RATAS_MUERTE_AGONIX_BOSS_1
		jp		PAGE_10_A_SEGMENT_2

ENTRAN_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		ix,RATAS_MUERTE_AGONIX_X
		ld		hl,RATAS_MUERTE_AGONIX_ACTIVA
		ld		c,0

.BUCLE_PREPARA_ENTRADA_RATAS_MUERTE_AGONIX_BOSS_1:

		bit		0,c
		jr		nz,.RATA_ENTRA_DESDE_DERECHA_BOSS_1

		xor		a
		jr		.GUARDA_X_ENTRADA_RATA_MUERTE_AGONIX_BOSS_1

.RATA_ENTRA_DESDE_DERECHA_BOSS_1:

		ld		a,255

.GUARDA_X_ENTRADA_RATA_MUERTE_AGONIX_BOSS_1:

		ld		(ix),a
		ld		(hl),1
		inc		ix
		inc		hl
		inc		c
		ld		a,c
		cp		RATAS_MUERTE_CANTIDAD_BOSS_1
		jr		c,.BUCLE_PREPARA_ENTRADA_RATAS_MUERTE_AGONIX_BOSS_1

.BUCLE_ENTRAN_RATAS_MUERTE_AGONIX_BOSS_1:

		call	MUEVE_RATAS_ENTRADA_AGONIX_BOSS_1
		ld		a,RATAS_MUERTE_ENTRADA_PAUSA_BOSS_1
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		ld		a,(RATAS_MUERTE_AGONIX_CONTADOR)
		or		a
		jr		nz,.BUCLE_ENTRAN_RATAS_MUERTE_AGONIX_BOSS_1
		call	ACTIVA_RATAS_MUERTE_AGONIX_BOSS_1
		ret

ACTIVA_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		hl,RATAS_MUERTE_AGONIX_ACTIVA
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_1
		ld		a,1

.BUCLE_ACTIVA_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		(hl),a
		inc		hl
		djnz	.BUCLE_ACTIVA_RATAS_MUERTE_AGONIX_BOSS_1
		ret

MUEVE_RATAS_ENTRADA_AGONIX_BOSS_1:

		xor		a
		ld		(RATAS_MUERTE_AGONIX_CONTADOR),a
		ld		de,RATAS_MUERTE_AGONIX_ATRIBUTOS
		ld		c,a

.BUCLE_MUEVE_RATAS_ENTRADA_AGONIX_BOSS_1:

		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_AGONIX_ACTIVA
		add		hl,bc
		ld		a,(hl)
		or		a
		jr		z,.PINTA_RATA_ENTRADA_AGONIX_BOSS_1

		push	hl
		ld		hl,BOSS_1_RATAS_MUERTE_OFFSET_X
		add		hl,bc
		ld		a,(AGONIX_BOSS_1_X)
		add		a,(hl)
		ld		d,a
		ld		hl,RATAS_MUERTE_AGONIX_X
		add		hl,bc
		ld		a,(hl)
		bit		0,c
		jr		nz,.MUEVE_RATA_ENTRADA_IZQUIERDA_AGONIX_BOSS_1

.MUEVE_RATA_ENTRADA_DERECHA_AGONIX_BOSS_1:

		add		a,RATAS_MUERTE_PASO_X_BOSS_1
		cp		d
		jr		nc,.FIJA_RATA_ENTRADA_AGONIX_BOSS_1
		ld		(hl),a
		pop		hl
		jr		.SIGUE_RATA_ENTRANDO_AGONIX_BOSS_1

.MUEVE_RATA_ENTRADA_IZQUIERDA_AGONIX_BOSS_1:

		ld		e,a
		ld		a,d
		add		a,RATAS_MUERTE_PASO_X_BOSS_1
		cp		e
		jr		nc,.FIJA_RATA_ENTRADA_AGONIX_BOSS_1
		ld		a,e
		sub		RATAS_MUERTE_PASO_X_BOSS_1
		ld		(hl),a
		pop		hl

.SIGUE_RATA_ENTRANDO_AGONIX_BOSS_1:

		ld		a,(RATAS_MUERTE_AGONIX_CONTADOR)
		inc		a
		ld		(RATAS_MUERTE_AGONIX_CONTADOR),a
		jr		.PINTA_RATA_ENTRADA_AGONIX_BOSS_1

.FIJA_RATA_ENTRADA_AGONIX_BOSS_1:

		ld		a,d
		ld		(hl),a
		pop		hl
		xor		a
		ld		(hl),a

.PINTA_RATA_ENTRADA_AGONIX_BOSS_1:

		pop		de
		ld		a,RATAS_MUERTE_Y_BOSS_1
		ld		(de),a
		inc		de
		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_AGONIX_X
		add		hl,bc
		ld		a,(hl)
		pop		de
		ld		(de),a
		inc		de
		bit		0,c
		jr		nz,.PATRON_RATA_ENTRADA_IZQUIERDA_AGONIX_BOSS_1

.PATRON_RATA_ENTRADA_DERECHA_AGONIX_BOSS_1:

		ld		a,RATA_PATRON_DERECHA_BOSS_1
		jr		.GUARDA_PATRON_RATA_ENTRADA_AGONIX_BOSS_1

.PATRON_RATA_ENTRADA_IZQUIERDA_AGONIX_BOSS_1:

		ld		a,RATA_PATRON_IZQUIERDA_BOSS_1

.GUARDA_PATRON_RATA_ENTRADA_AGONIX_BOSS_1:

		ld		(de),a
		inc		de
		xor		a
		ld		(de),a
		inc		de
		inc		c
		ld		a,c
		cp		RATAS_MUERTE_CANTIDAD_BOSS_1
		jp		c,.BUCLE_MUEVE_RATAS_ENTRADA_AGONIX_BOSS_1

		ld		hl,RATAS_MUERTE_AGONIX_ATRIBUTOS
		ld		de,RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_1
		ld		bc,RATAS_MUERTE_CANTIDAD_BOSS_1*4
		jp		PON_COLOR_2.sin_bc_impuesta

MUEVE_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		ix,RATAS_MUERTE_AGONIX_X
		ld		iy,RATAS_MUERTE_AGONIX_ESPERA
		ld		hl,BOSS_1_RATAS_MUERTE_VELOCIDAD
		ld		de,RATAS_MUERTE_AGONIX_ATRIBUTOS
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_1

.BUCLE_MUEVE_RATAS_MUERTE_AGONIX_BOSS_1:

		ld		a,(iy)
		dec		a
		ld		(iy),a
		jr		nz,.PINTA_RATA_MUERTE_AGONIX_BOSS_1

		ld		a,(hl)
		ld		(iy),a
		ld		a,(ix)
		bit		0,b
		jr		nz,.MUEVE_RATA_DERECHA_MUERTE_AGONIX_BOSS_1

.MUEVE_RATA_IZQUIERDA_MUERTE_AGONIX_BOSS_1:

		sub		RATAS_MUERTE_PASO_X_BOSS_1
		ld		(ix),a
		ld		c,a
		ld		a,(AGONIX_BOSS_1_X)
		add		a,RATAS_MUERTE_X_MIN_OFFSET_BOSS_1
		cp		c
		jr		z,.PINTA_RATA_MUERTE_AGONIX_BOSS_1
		jr		c,.PINTA_RATA_MUERTE_AGONIX_BOSS_1

		ld		a,(AGONIX_BOSS_1_X)
		add		a,RATAS_MUERTE_X_MAX_OFFSET_BOSS_1
		ld		(ix),a
		jr		.PINTA_RATA_MUERTE_AGONIX_BOSS_1

.MUEVE_RATA_DERECHA_MUERTE_AGONIX_BOSS_1:

		add		a,RATAS_MUERTE_PASO_X_BOSS_1
		ld		(ix),a
		ld		c,a
		ld		a,(AGONIX_BOSS_1_X)
		add		a,RATAS_MUERTE_X_MAX_OFFSET_BOSS_1
		cp		c
		jr		nc,.PINTA_RATA_MUERTE_AGONIX_BOSS_1

		ld		a,(AGONIX_BOSS_1_X)
		add		a,RATAS_MUERTE_X_MIN_OFFSET_BOSS_1
		ld		(ix),a

.PINTA_RATA_MUERTE_AGONIX_BOSS_1:

		ld		a,RATAS_MUERTE_Y_BOSS_1
		ld		(de),a
		inc		de
		ld		a,(ix)
		ld		(de),a
		inc		de
		ld		a,b
		and		00000001b
		jr		nz,.PATRON_RATA_DERECHA_MUERTE_AGONIX_BOSS_1

.PATRON_RATA_IZQUIERDA_MUERTE_AGONIX_BOSS_1:

		ld		a,RATA_PATRON_IZQUIERDA_BOSS_1
		jr		.GUARDA_PATRON_RATA_MUERTE_AGONIX_BOSS_1

.PATRON_RATA_DERECHA_MUERTE_AGONIX_BOSS_1:

		ld		a,RATA_PATRON_DERECHA_BOSS_1

.GUARDA_PATRON_RATA_MUERTE_AGONIX_BOSS_1:

		ld		(de),a
		inc		de
		xor		a
		ld		(de),a
		inc		de

		inc		ix
		inc		iy
		inc		hl
		djnz	.BUCLE_MUEVE_RATAS_MUERTE_AGONIX_BOSS_1

		ld		hl,RATAS_MUERTE_AGONIX_ATRIBUTOS
		ld		de,RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_1
		ld		bc,RATAS_MUERTE_CANTIDAD_BOSS_1*4
		jp		PON_COLOR_2.sin_bc_impuesta

ESCAPA_RATAS_MUERTE_AGONIX_BOSS_1:

		call	MUEVE_RATAS_SALIDA_AGONIX_BOSS_1
		ld		a,RATAS_MUERTE_SALIDA_PAUSA_BOSS_1
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		ld		a,(RATAS_MUERTE_AGONIX_CONTADOR)
		or		a
		jr		nz,ESCAPA_RATAS_MUERTE_AGONIX_BOSS_1
		ret

MUEVE_RATAS_SALIDA_AGONIX_BOSS_1:

		xor		a
		ld		(RATAS_MUERTE_AGONIX_CONTADOR),a
		ld		de,RATAS_MUERTE_AGONIX_ATRIBUTOS
		ld		c,a

.BUCLE_MUEVE_RATAS_SALIDA_AGONIX_BOSS_1:

		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_AGONIX_ACTIVA
		add		hl,bc
		ld		a,(hl)
		pop		de
		or		a
		jr		z,.PINTA_RATA_OCULTA_SALIDA_AGONIX_BOSS_1

		ld		a,(RATAS_MUERTE_AGONIX_CONTADOR)
		inc		a
		ld		(RATAS_MUERTE_AGONIX_CONTADOR),a

		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_AGONIX_ESPERA
		add		hl,bc
		ld		a,(hl)
		dec		a
		ld		(hl),a
		pop		de
		jr		nz,.PINTA_RATA_ACTIVA_SALIDA_AGONIX_BOSS_1

		push	de
		ld		b,0
		ld		hl,BOSS_1_RATAS_MUERTE_VELOCIDAD
		add		hl,bc
		ld		a,(hl)
		ld		hl,RATAS_MUERTE_AGONIX_ESPERA
		add		hl,bc
		ld		(hl),a
		ld		hl,RATAS_MUERTE_AGONIX_X
		add		hl,bc
		ld		a,(hl)
		bit		0,c
		jr		nz,.MUEVE_RATA_DERECHA_SALIDA_AGONIX_BOSS_1

.MUEVE_RATA_IZQUIERDA_SALIDA_AGONIX_BOSS_1:

		cp		RATAS_MUERTE_PASO_X_BOSS_1
		jr		c,.MATA_RATA_SALIDA_AGONIX_BOSS_1
		sub		RATAS_MUERTE_PASO_X_BOSS_1
		ld		(hl),a
		or		a
		jr		z,.MATA_RATA_SALIDA_AGONIX_BOSS_1
		pop		de
		jr		.PINTA_RATA_ACTIVA_SALIDA_AGONIX_BOSS_1

.MUEVE_RATA_DERECHA_SALIDA_AGONIX_BOSS_1:

		add		a,RATAS_MUERTE_PASO_X_BOSS_1
		jr		c,.MATA_RATA_SALIDA_AGONIX_BOSS_1
		ld		(hl),a
		cp		255
		jr		z,.MATA_RATA_SALIDA_AGONIX_BOSS_1
		pop		de
		jr		.PINTA_RATA_ACTIVA_SALIDA_AGONIX_BOSS_1

.MATA_RATA_SALIDA_AGONIX_BOSS_1:

		ld		hl,RATAS_MUERTE_AGONIX_ACTIVA
		add		hl,bc
		xor		a
		ld		(hl),a
		ld		a,(RATAS_MUERTE_AGONIX_CONTADOR)
		dec		a
		ld		(RATAS_MUERTE_AGONIX_CONTADOR),a
		pop		de
		jr		.PINTA_RATA_OCULTA_SALIDA_AGONIX_BOSS_1

.PINTA_RATA_ACTIVA_SALIDA_AGONIX_BOSS_1:

		ld		a,RATAS_MUERTE_Y_BOSS_1
		ld		(de),a
		inc		de
		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_AGONIX_X
		add		hl,bc
		ld		a,(hl)
		pop		de
		ld		(de),a
		inc		de
		ld		a,c
		and		00000001b
		jr		nz,.PATRON_RATA_DERECHA_SALIDA_AGONIX_BOSS_1

.PATRON_RATA_IZQUIERDA_SALIDA_AGONIX_BOSS_1:

		ld		a,RATA_PATRON_IZQUIERDA_BOSS_1
		jr		.GUARDA_PATRON_RATA_SALIDA_AGONIX_BOSS_1

.PATRON_RATA_DERECHA_SALIDA_AGONIX_BOSS_1:

		ld		a,RATA_PATRON_DERECHA_BOSS_1
		jr		.GUARDA_PATRON_RATA_SALIDA_AGONIX_BOSS_1

.PINTA_RATA_OCULTA_SALIDA_AGONIX_BOSS_1:

		ld		a,RATAS_MUERTE_Y_OCULTA_BOSS_1
		ld		(de),a
		inc		de
		ld		a,RATAS_MUERTE_X_OCULTA_BOSS_1
		ld		(de),a
		inc		de
		xor		a

.GUARDA_PATRON_RATA_SALIDA_AGONIX_BOSS_1:

		ld		(de),a
		inc		de
		xor		a
		ld		(de),a
		inc		de

		inc		c
		ld		a,c
		cp		RATAS_MUERTE_CANTIDAD_BOSS_1
		jp		c,.BUCLE_MUEVE_RATAS_SALIDA_AGONIX_BOSS_1

		ld		hl,RATAS_MUERTE_AGONIX_ATRIBUTOS
		ld		de,RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_1
		ld		bc,RATAS_MUERTE_CANTIDAD_BOSS_1*4
		jp		PON_COLOR_2.sin_bc_impuesta

TIRA_FX_BOSS_1:

		call	PAGE_31_A_SEGMENT_2
		call	ayFX_INIT
		jp		PAGE_10_A_SEGMENT_2

MUERTE_DE_AGONIX_BOSS_1:
; paramos la música
		call	stpmus

; Nos aseguramos que el prota no está en modo transparente ni el fondo en colores varios
		ld		a,COLOR_ALEATORIO_SIN_CAMBIOS_BOSS_1
		ld		(COLOR_ALEATORIO),a
		xor		a
		ld		(INMUNE),a

; pequeña pausa
		ld		a,AGONIX_PAUSA_BOCA_BOSS_1
		call	BUCLE_PINTA_TILES.rutina_de_pausa

; limpiamos sprites
		xor		a
		ld		hl,SPRITES_ATRIBUTOS_VRAM_BOSS_1+AGONIX_LIMPIA_SPRITE_INICIAL_BOSS_1*4
		ld		bc,AGONIX_LIMPIA_SPRITES_CANT_BOSS_1*4
		call	FILVRM_RAM
		call	INICIALIZA_RATAS_MUERTE_AGONIX_BOSS_1
		call	ENTRAN_RATAS_MUERTE_AGONIX_BOSS_1


; animamos la muerte de AGONIX		
		ld		b,AGONIX_MUERTE_BUCLES_BOSS_1

.BUCLE_ANIMA_MUERTE_AGONIX_BOSS_1:

		push	bc
		
; audio de terremoto
		ld		a,AGONIX_MUERTE_FX_BOSS_1
		ld		c,AGONIX_MUERTE_FX_CANAL_BOSS_1
        call    PAGE_31_A_SEGMENT_2
		call	ayFX_INIT
        call   	PAGE_10_A_SEGMENT_2

		ld		ix,COPY_ANIMA_MUERTE_AGONIX_A_BUFFER_BOSS_1
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_1.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL
		ld		a,(AGONIX_BOSS_1_X)
		ld		(iy),a
		xor		a
		ld		(iy+1),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY

		ld		ix,COPY_ANIMA_MUERTE_AGONIX_DESDE_BUFFER_BOSS_1
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_1.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL
		ld		a,(AGONIX_BOSS_1_X)
		ld		(iy+4),a
		xor		a
		ld		(iy+5),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY

		ld		b,RATAS_MUERTE_PASOS_ENTRE_COPY_BOSS_1

.BUCLE_RATAS_ENTRE_COPY_MUERTE_AGONIX_BOSS_1:

		push	bc
		call	MUEVE_RATAS_MUERTE_AGONIX_BOSS_1
		pop		bc
		djnz	.BUCLE_RATAS_ENTRE_COPY_MUERTE_AGONIX_BOSS_1

		ld		a,AGONIX_MUERTE_PAUSA_BOSS_1
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		pop		bc
		djnz	.BUCLE_ANIMA_MUERTE_AGONIX_BOSS_1

		call	ESCAPA_RATAS_MUERTE_AGONIX_BOSS_1
		call	PREPARA_VRAM_PARA_MUERTE_DEPH_EN_BOSS

.REJAS_SUBEN:

        ld      ix,BOSS_1_COPY_REJAS_SUBEN
        ld      iy,DATAS_COPY_RECUP_SCROLL
        call    RUTINA_BOSS_1.BUCLE_PINTA_DATAS

        ld      a,55

.BUCLE_REJAS_SUBEN:

        push    af

        ; Cambiamos la Y destino del COPY.
        ; El dato Y está en el cuarto word del bloque:
        ; bytes 6 y 7 dentro de DATAS_COPY_RECUP_SCROLL.

        ld      iy,DATAS_COPY_RECUP_SCROLL
        ld      (iy+6),a
        ld      (iy+7),#02          ; page 2

        ; Sonido en cada paso

        ld      a,11
        ld      c,0
        call    TIRA_FX_BOSS_1

        ; Pintamos el rectángulo

        ld      hl,DATAS_COPY_RECUP_SCROLL
        call    DOCOPY
        call    VDPREADY

        ; Pausa de una décima aprox.
        ; En PAL/50Hz, 5 frames ≈ 0,1 segundos.
        ; Si lo pruebas en 60Hz, puedes poner 6.

        ld      a,5
        call    BUCLE_PINTA_TILES.rutina_de_pausa

        pop     af

        cp      20
        jp      z,TERMINANDO_LA_BATALLA_b1

        dec     a
        jp      .BUCLE_REJAS_SUBEN

TERMINANDO_LA_BATALLA_b1:

		include	"../AUDIOS/INICIA MUSICA_WIN.asm"

		ld		hl,TODOS_LOS_SPRITES
		call	PAGE_32_A_SEGMENT_2
		ld		de,PATRONES_SPRITES_VRAM_BOSS_1+DEPH_SALIDA_SPRITES_INICIO_BOSS_1*8*4
		ld		bc,DEPH_SALIDA_SPRITES_CANT_BOSS_1*8*4
		call	PON_COLOR_2.sin_bc_impuesta
		call	PAGE_10_A_SEGMENT_2
		call	VUELCA_DATOS_COLORES_DEPH_A_VRAM
		call	PAGE_10_A_SEGMENT_2

CAMINITO_A_PUERTA_b1:

		include	"../ANIMACIONES/PASEITO HASTA PUERTA.asm"		
SALUDO_b1:

		include	"../ANIMACIONES/SALUDO_GANA_FASE.asm"		

ULTIMO_DESPLAZAMIENTO_b1:

		include	"../ANIMACIONES/PASEITO DENTRO DE PUERTA.asm"	

VOLVEMOS_b1:

		jp		CARGA_SLOT_REGRESO_A_JUEGO

	include	"BOSS 1 DATA.asm"
