VIDA_INICIAL_ERRECENYX_BOSS_4:					equ	80
VIDA_TOTAL_INICIAL_BOSS_4:					equ	VIDA_INICIAL_ERRECENYX_BOSS_4
VIDA_ANCHO_BARRA_BOSS_4:					equ	99

PAGINA_REGRESO_BOSS_4:						equ	29

; VRAM / sprites
SPRITES_ATRIBUTOS_VRAM_BOSS_4:				equ	#4A00
SPRITES_COLOR_VRAM_BOSS_4:					equ	#4800
PATRONES_SPRITES_VRAM_BOSS_4:				equ	#4000
PAGE_1_VRAM_Y_BOSS_4:						equ	#0100
PAGE_2_VRAM_Y_BOSS_4:						equ	#0200
PAGE_X_VRAM_BOSS_4:							equ	#0000
SPRITES_LIMPIA_INICIAL_BOSS_4:				equ	10
SPRITES_LIMPIA_CANT_INICIAL_BOSS_4:			equ	22
RATA_PATRON_DERECHA_BOSS_4:					equ	100
RATA_PATRON_IZQUIERDA_BOSS_4:				equ	104
RATA_COLOR_DERECHA_BOSS_4:					equ	RATA_PATRON_DERECHA_BOSS_4/4
RATA_COLOR_IZQUIERDA_BOSS_4:				equ	RATA_PATRON_IZQUIERDA_BOSS_4/4
RATAS_MUERTE_CANTIDAD_BOSS_4:				equ	8
RATAS_MUERTE_SPRITE_INICIAL_BOSS_4:			equ	10
RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_4:			equ	SPRITES_ATRIBUTOS_VRAM_BOSS_4+RATAS_MUERTE_SPRITE_INICIAL_BOSS_4*4
RATAS_MUERTE_COLOR_VRAM_BOSS_4:				equ	SPRITES_COLOR_VRAM_BOSS_4+RATAS_MUERTE_SPRITE_INICIAL_BOSS_4*16
RATAS_MUERTE_PASOS_ENTRE_COPY_BOSS_4:		equ	8
RATAS_MUERTE_SALIDA_PAUSA_BOSS_4:			equ	1
RATAS_MUERTE_ENTRADA_PAUSA_BOSS_4:			equ	1
RATAS_MUERTE_Y_OCULTA_BOSS_4:				equ	217
RATAS_MUERTE_X_OCULTA_BOSS_4:				equ	255
RATAS_MUERTE_PASO_X_BOSS_4:					equ	3
COPY_SIN_OFFSET_BOSS_4:						equ	#00
COPY_LOGICA_NORMAL_BOSS_4:					equ	10010000b
COPY_LOGICA_RELLENO_BOSS_4:					equ	11000000b

; Proyectiles del boss
PROYECTILES_BOSS_4_CANTIDAD:				equ	8
PROYECTIL_BOSS_4_ESPERA_INICIAL:			equ	15
PROYECTIL_BOSS_4_SPRITE_INICIAL:			equ	22
PROYECTIL_BOSS_4_SPRITE_FINAL:				equ	30
PROYECTIL_BOSS_4_Y_OCULTO:					equ	217
PROYECTIL_BOSS_4_SPRITES_ACTIVOS_OFS:		equ	12
PROYECTIL_BOSS_4_ATRIBUTOS_VRAM:			equ	SPRITES_ATRIBUTOS_VRAM_BOSS_4+PROYECTIL_BOSS_4_SPRITE_INICIAL*4
PROYECTIL_BOSS_4_COLOR_VRAM:				equ	SPRITES_COLOR_VRAM_BOSS_4+PROYECTIL_BOSS_4_SPRITE_INICIAL*16
PROYECTIL_BOSS_4_PATRON_SPRITE:				equ	160
PROYECTIL_BOSS_4_OFFSET_DER_X:				equ	98-8
PROYECTIL_BOSS_4_OFFSET_IZQ_X:				equ	29-8
PROYECTIL_BOSS_4_OFFSET_Y:					equ	25-8
PROYECTIL_BOSS_4_DIRECCION_MIN:				equ	1
PROYECTIL_BOSS_4_DIRECCION_MAX:				equ	11
ERRECENYX_IMPACTO_DER_X_MIN_BOSS_4:			equ	94-8
ERRECENYX_IMPACTO_DER_X_ANCHO_BOSS_4:			equ	10
ERRECENYX_IMPACTO_IZQ_X_MIN_BOSS_4:			equ	24-8
ERRECENYX_IMPACTO_IZQ_X_ANCHO_BOSS_4:			equ	10
ERRECENYX_IMPACTO_Y_MIN_BOSS_4:				equ	19-8
ERRECENYX_IMPACTO_Y_ALTO_BOSS_4:				equ	10

; Salida y muerte de Agonix
COLOR_ALEATORIO_SIN_CAMBIOS_BOSS_4:			equ	1
ERRECENYX_PAUSA_BOCA_BOSS_4:					equ	100
ERRECENYX_LIMPIA_SPRITE_INICIAL_BOSS_4:		equ	10
ERRECENYX_LIMPIA_SPRITES_CANT_BOSS_4:			equ	20
ERRECENYX_MUERTE_Y_LIMITE_VISIBLE_BOSS_4:		equ	162
ERRECENYX_MUERTE_BUCLES_BOSS_4:				equ	ERRECENYX_MUERTE_Y_LIMITE_VISIBLE_BOSS_4-ERRECENYX_MUERTE_DY_BOSS_4
ERRECENYX_MUERTE_FX_BOSS_4:					equ	31
ERRECENYX_MUERTE_FX_CANAL_BOSS_4:				equ	0
ERRECENYX_MUERTE_PAUSA_BOSS_4:					equ	8

ERRECENYX_MUERTE_SX_BOSS_4:					equ	0
ERRECENYX_MUERTE_SY_BOSS_4:					equ	108
ERRECENYX_MUERTE_DX_BOSS_4:					equ	0
ERRECENYX_MUERTE_DY_BOSS_4:					equ	109
ERRECENYX_MUERTE_ANCHO_BOSS_4:					equ	130
ERRECENYX_MUERTE_ALTO_BOSS_4:					equ	48
RATAS_MUERTE_Y_BOSS_4:						equ	ERRECENYX_MUERTE_DY_BOSS_4+ERRECENYX_MUERTE_ALTO_BOSS_4-16
RATAS_MUERTE_X_MIN_OFFSET_BOSS_4:			equ	20
RATAS_MUERTE_X_MAX_OFFSET_BOSS_4:			equ	ERRECENYX_MUERTE_ANCHO_BOSS_4-20
ERRECENYX_BUFFER_X_BOSS_4:						equ	0
ERRECENYX_BUFFER_Y_BOSS_4:						equ	0

DEPH_SALIDA_SPRITES_INICIO_BOSS_4:			equ	1
DEPH_SALIDA_SPRITES_CANT_BOSS_4:			equ	45

ERRECENYX_ANIMACION_OFFSET_INICIAL_BOSS_4:		equ	128
ERRECENYX_ANIMACION_OFFSET_FINAL_BOSS_4:		equ	0
ERRECENYX_ANIMACION_X_FINAL_BOSS_4:			equ	130
ERRECENYX_ANIMACION_SX_1_BOSS_4:				equ	0
ERRECENYX_ANIMACION_SX_2_BOSS_4:				equ	126
ERRECENYX_ANIMACION_SY_1_BOSS_4:				equ	0
ERRECENYX_ANIMACION_SY_2_BOSS_4:				equ	48
ERRECENYX_ANIMACION_PAUSA_BOSS_4:				equ	4
ERRECENYX_ANIMACION_FX_BOSS_4:					equ	29
ERRECENYX_ANIMACION_FX_CANAL_BOSS_4:			equ	0
ERRECENYX_ANIMACION_FX_CADA_COPYS_BOSS_4:		equ	00000011b

ERRECENYX_MOVIMIENTO_X_MAX_BOSS_4:				equ	126
ERRECENYX_MOVIMIENTO_Y_BOSS_4:					equ	108
ERRECENYX_MOVIMIENTO_PASO_X_BOSS_4:			equ	6
ERRECENYX_MOVIMIENTO_ESPERA_BOSS_4:			equ	6
ERRECENYX_MOVIMIENTO_PAG_DERECHA_BOSS_4:		equ	3
ERRECENYX_MOVIMIENTO_PAG_IZQUIERDA_BOSS_4:		equ	1
ERRECENYX_MOVIMIENTO_SX_1_BOSS_4:				equ	0
ERRECENYX_MOVIMIENTO_SX_2_BOSS_4:				equ	126
ERRECENYX_MOVIMIENTO_SY_1_BOSS_4:				equ	0
ERRECENYX_MOVIMIENTO_SY_2_BOSS_4:				equ	48
ERRECENYX_PARADO_SY_1_BOSS_4:					equ	96
ERRECENYX_PARADO_SY_2_BOSS_4:					equ	144
ERRECENYX_MOVIMIENTO_ANCHO_BOSS_4:				equ	130
ERRECENYX_MOVIMIENTO_ALTO_BOSS_4:				equ	48
ERRECENYX_MOVIMIENTO_BORRA_ANCHO_BOSS_4:		equ	6
ERRECENYX_MOVIMIENTO_BORRA_ALTO_BOSS_4:		equ	47
ERRECENYX_MOVIMIENTO_BORRA_COLOR_BOSS_4:		equ	#BB
ERRECENYX_MODO_MOVIMIENTO_BOSS_4:				equ	0
ERRECENYX_MODO_PARADO_BOSS_4:					equ	1
ERRECENYX_PARADO_DURACION_BOSS_4:				equ	50
ERRECENYX_MOVIMIENTO_AZAR_MAX_BOSS_4:			equ	100

CARGA_SPRITES_RATA_BOSS_4:

		call	PAGE_32_A_SEGMENT_2

		ld		hl,SPRITE_RATA
		ld		de,PATRONES_SPRITES_VRAM_BOSS_4+RATA_PATRON_DERECHA_BOSS_4*8
		ld		bc,8*4*2
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,COLOR_RATA
		ld		de,SPRITES_COLOR_VRAM_BOSS_4+RATA_COLOR_DERECHA_BOSS_4*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,COLOR_RATA
		ld		de,SPRITES_COLOR_VRAM_BOSS_4+RATA_COLOR_IZQUIERDA_BOSS_4*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		jp		PAGE_10_A_SEGMENT_2

RUTINA_BOSS_4:

		call	stpmus

		call	CARGA_SPRITES_RATA_BOSS_4

		ld      a,0
		ld      hl,SPRITES_ATRIBUTOS_VRAM_BOSS_4+SPRITES_LIMPIA_INICIAL_BOSS_4*4
		ld      bc,SPRITES_LIMPIA_CANT_INICIAL_BOSS_4*4
		call    FILVRM_RAM

.VARIABLES:

		ld		a,PAGINA_REGRESO_BOSS_4
		ld		(PAGINA_DE_REGRESO),a
		xor		a
		ld		(PROYECTIL_BOSS_4_DIRECCION),a
		ld		(PROYECTIL_BOSS_4_PASO_TABLA),a
		ld		(PROYECTIL_BOSS_4_X),a
		ld		(PROYECTIL_BOSS_4_SIGUIENTE_EMISOR),a
		ld		a,PROYECTIL_BOSS_4_ESPERA_INICIAL
		ld		(PROYECTIL_BOSS_4_ESPERA),a
		ld		a,PROYECTIL_BOSS_4_SPRITE_INICIAL
		ld		(PROYECTIL_BOSS_4_SPRITE_ACTUAL),a
		ld		(PROYECTIL_BOSS_4_SIGUIENTE_SPRITE),a
		ld		hl,SPRITES_ACTIVOS+PROYECTIL_BOSS_4_SPRITES_ACTIVOS_OFS
		ld		a,l
		ld		(PROYECTIL_BOSS_4_PUNTERO_SPRITES_ACTIVOS),a
		ld		a,h
		ld		(PROYECTIL_BOSS_4_PUNTERO_SPRITES_ACTIVOS+1),a
		ld		hl,PROYECTIL_BOSS_4_ATRIBUTOS_VRAM
		ld		a,l
		ld		(PROYECTIL_BOSS_4_DIRECCION_VRAM_ATRIBUTOS),a
		ld		a,h
		ld		(PROYECTIL_BOSS_4_DIRECCION_VRAM_ATRIBUTOS+1),a
		ld		hl,PROYECTIL_BOSS_4_COLOR_VRAM
		ld		a,l
		ld		(PROYECTIL_BOSS_4_DIRECCION_VRAM_COLOR),a
		ld		a,h
		ld		(PROYECTIL_BOSS_4_DIRECCION_VRAM_COLOR+1),a
		xor		a
		ld		(SPRITES_ACTIVOS+PROYECTIL_BOSS_4_SPRITES_ACTIVOS_OFS),a
		ld		(VALORES_EXPLOSION_CON_ROCK),a
		ld		(VALORES_EXPLOSION_CON_ROCK+1),a
		ld		(VALORES_EXPLOSION_CON_ROCK+2),a
		ld		(VALORES_EXPLOSION_CON_ROCK+3),a
		ld		a,VIDA_INICIAL_ERRECENYX_BOSS_4
		ld		(VIDA_ERRECENYX_BOSS_4),a
		xor		a
		ld		(ERRECENYX_BOSS_4_X),a
		ld		(ERRECENYX_BOSS_4_DIRECCION),a
		ld		(ERRECENYX_BOSS_4_FOTOGRAMA),a
		ld		(ERRECENYX_BOSS_4_MODO),a
		ld		a,ERRECENYX_MOVIMIENTO_ESPERA_BOSS_4
		ld		(ERRECENYX_BOSS_4_ESPERA_MOVIMIENTO),a
		call	NUEVO_TIEMPO_MOVIMIENTO_ERRECENYX_BOSS_4
		ld		a,PROYECTIL_BOSS_4_Y_OCULTO
		ld		(PROYECTIL_BOSS_4_Y),a
		call	INICIALIZA_POOL_PROYECTILES_BOSS_4

        ; Variables a reiniciar


        push    ix
        push    iy
        push    bc
        push    de

.COPIA_A_1_PARTE_ALTA:

        ld      ix,BOSS_4_PAGE_2_A_PAGE_1_COMPLETA
        ld      iy,DATAS_COPY_RECUP_SCROLL
        call    .BUCLE_PINTA_DATAS

        ld      iy,DATAS_COPY_RECUP_SCROLL
        ld      a,(PUNTO_DEL_SCROLL)

        ld      (iy+2),a
        ld      b,a
        ld      a,0
        sub     b
        ld      (iy+10),a
        push    af
        xor     a
        ld      (iy+11),a
        ld      hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY

.COPIA_A_1_PARTE_BAJA:
        
        ld      ix,BOSS_4_PAGE_2_A_PAGE_1_COMPLETA
        ld      iy,DATAS_COPY_RECUP_SCROLL
        call    .BUCLE_PINTA_DATAS

        ld      iy,DATAS_COPY_RECUP_SCROLL
        ld      a,(PUNTO_DEL_SCROLL)
        ld      b,a
        ld      a,0
        sub     b
        ld      (iy+6),a
        pop     af
        dec     a
        ld      b,a
        ld      a,#FF
        sub     b
        ld      (iy+10),a
        xor     a
        ld      (iy+11),a
        ld      hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY 
        call    VDPREADY

.GUARDA_DATOS_VIDA_ERRECENYX:

        ld      ix,BOSS_4_COPI_MARCADOR_BOSSES_CORAZONES_VACIOS
        ld      iy,DATAS_COR_EMPT_MALO
        call    .BUCLE_PINTA_DATAS

.GUARDA_DATOS_COPY_CORAZONES_EMPTY_DEPH:

        ld      ix,BOSS_4_COPY_CORAZONES_EMPTY_DEPH
        ld      iy,CORAZONES_DEPH_EN_BOSSES
        call    .BUCLE_PINTA_DATAS

.GUARDA_DATOS_COPY_PUNTOS_MAGIA:

        ld      ix,BOSS_4_COPY_PUNTOS_MAGIA
        ld      iy,PUNTOS_MAGIA_EN_BOSSES
        call    .BUCLE_PINTA_DATAS

.VARIABLES_DE_DEPH_RETOCADAS:

        ld      a,(PUNTO_DEL_SCROLL)
        ld      b,a
        ld      a,(Y_DEPH)
        sub     b
        ld      (Y_DEPH),a
        add     32
        ld      (Y_FALSA_PARA_DEPH),a

.PUNTO_DE_SCROLL_RETOCADO:

        ld      a,0
        ld      (PUNTO_DEL_SCROLL),a

.COLOCA_SPRITES_DEPH_EN_SU_SITIO:
        
        call    PINTA_SPRITE_DEPH

.CAMBIA_PAGE_PARA_OCULTAR:

        ld      a,1
        ld      (SET_PAGE),a

.COPIA_ESCENARIO_RECOLOCADO_A_PAGE_2:

 		ld	hl,BOSS_4_PAGE_1_A_PAGE_2_COMPLETA
		call	DOCOPY
        call    VDPREADY

.DEVUELVE_LA_PAGE_2:

        ld      a,2
        ld      (SET_PAGE),a

.CAMBIAMOS_MAS_VARIABLES_PARA_EL_CAMBIO_DE_SCROLL:

		ld	a,202
		ld	(DONDE_VA_LA_INTERRUPCION_LINEAL),a 

		ld	a,240
		ld	(Y_PINTA_SCROLL),a

 		ld	a,159
		ld	(LIM_Y_INF),a	
			
		ld	a,190
		ld	(LIM_MUERTE),a

		ld	a,195
		ld	(Y_LINEA_INT),a

.CARGA_ERRECENYX_PARTE_1:

        ld      a,56
        ld		b,57
        call	.CARGA_PANTALLA_COMPLETA

.CARGA_STATUS_BOSS:

        ld      a,58
        call	CHANGE_BANK_2

        ld		hl,STATUS_BOSS_4												; Carga gráficos status
        ld		de,#0000+(256*200)/2
        ld		bc,(256*54)/2
        call	PON_COLOR_2.sin_bc_impuesta

        ld      a,10
        call	CHANGE_BANK_2  

.PINTA_STATUS:

        ld      b,15
        ld      hl,BOSS_4_COPIA_PARTE_PAGE_2_DE_STATUS
		call	DOCOPY 

        ld      b,15
        ld      hl,BOSS_4_COPIA_STATUS_BOSS_A_PAGE_2
		call	DOCOPY 
		call	PINTA_MARCADORES_VIDA_FINAL_BOSS_4

.BORRA_CORAZONES_QUE_SOBRAN:

        ld      a,(CORAZONES)
        ld      b,4
        
.BUCLE_BORRA_CORAZONES_DE_MAS:

        ex      af,af'
        ld      a,b
        ld      (CORAZONES),a
        call    .PINTA_CORAZONES_VIDA_DEPH_ADECUADOS
        ex      af,af'
        cp      b
        jp      z,.FINAL_BUCLE_CORAZONES
        djnz    .BUCLE_BORRA_CORAZONES_DE_MAS

.FINAL_BUCLE_CORAZONES:

        ld      (CORAZONES),a

.PINTA_MAGIAS_REALES:

	ld		ix,PUNTOS_MAGIA_EN_BOSSES
	ld		a,(MAGIAS)
[3]	add		a
	ld		c,25
	add		c
	ld		(ix),a
	ld		hl,PUNTOS_MAGIA_EN_BOSSES
	call	DOCOPY
		
.ANIMACION_ERRECENYX:

	ld		ix,BOSS_4_COPY_ANIMACION_ERRECENYX
	ld		iy,DATAS_COPY_RECUP_SCROLL
	call	.BUCLE_PINTA_DATAS
	ld		a,ERRECENYX_ANIMACION_OFFSET_INICIAL_BOSS_4
	ld		(VARIABLE_UN_USO),a
	xor		a
	ld		(VARIABLE_UN_USO2),a

.BUCLE_ANIMACION_ERRECENYX:

	ld		iy,DATAS_COPY_RECUP_SCROLL
	ld		a,(VARIABLE_UN_USO2)
	and		00000001b
	jr		z,.SX_1_ANIMACION_ERRECENYX
	ld		a,ERRECENYX_ANIMACION_SX_2_BOSS_4
	jr		.GUARDA_SX_ANIMACION_ERRECENYX

.SX_1_ANIMACION_ERRECENYX:

	ld		a,ERRECENYX_ANIMACION_SX_1_BOSS_4

.GUARDA_SX_ANIMACION_ERRECENYX:

	ld		c,a
	ld		a,(VARIABLE_UN_USO)
	add		c
	ld		(iy),a
	ld		a,(VARIABLE_UN_USO)
	ld		c,a
	ld		a,ERRECENYX_ANIMACION_X_FINAL_BOSS_4
	sub		c
	ld		(iy+8),a

	ld		a,(VARIABLE_UN_USO2)
	and		00000010b
	jr		z,.SY_1_ANIMACION_ERRECENYX
	ld		a,ERRECENYX_ANIMACION_SY_2_BOSS_4
	jr		.GUARDA_SY_ANIMACION_ERRECENYX

.SY_1_ANIMACION_ERRECENYX:

	ld		a,ERRECENYX_ANIMACION_SY_1_BOSS_4

.GUARDA_SY_ANIMACION_ERRECENYX:

	ld		(iy+2),a
	ld		hl,DATAS_COPY_RECUP_SCROLL
	call	DOCOPY
	call	VDPREADY
	ld		a,(VARIABLE_UN_USO2)
	and		ERRECENYX_ANIMACION_FX_CADA_COPYS_BOSS_4
	jr		nz,.SIN_FX_ANIMACION_ERRECENYX
	ld		a,ERRECENYX_ANIMACION_FX_BOSS_4
	ld		c,ERRECENYX_ANIMACION_FX_CANAL_BOSS_4
	call	TIRA_FX_BOSS_4

.SIN_FX_ANIMACION_ERRECENYX:

	ld		b,ERRECENYX_ANIMACION_PAUSA_BOSS_4

.PAUSA_ANIMACION_ERRECENYX:

	halt
	djnz	.PAUSA_ANIMACION_ERRECENYX

	ld		a,(VARIABLE_UN_USO2)
	inc		a
	ld		(VARIABLE_UN_USO2),a
	ld		a,(VARIABLE_UN_USO)
	cp		ERRECENYX_ANIMACION_OFFSET_FINAL_BOSS_4
	jp		z,.PREPARACION_PELEA
	sub		2
	ld		(VARIABLE_UN_USO),a
	jp		.BUCLE_ANIMACION_ERRECENYX

.PREPARACION_PELEA:
.EMPIEZA_LA_MUSICA:

		include	"../AUDIOS/INICIA MUSICA_BOSS.asm"


; todo el codigo de enfrentamiento

		jp	BUCLE_PELEA_BOSS_4

.CARGA_PANTALLA_COMPLETA:

		push	bc
        call	CHANGE_BANK_2
                                                                       
        ld		hl,#8000							; Posición de lectura			
        ld		de,#8000							; Posición de escritura
        ld		bc,16384							; Bits a leer
        call	PON_COLOR_2.sin_bc_impuesta

		pop		af
        call	CHANGE_BANK_2
                                                                        
        ld		hl,#8000									
        ld		de,#C000
        ld		bc,16384
        call	PON_COLOR_2.sin_bc_impuesta
		call	VDPREADY

		ld		a,10
        jp		CHANGE_BANK_2

.PINTA_CORAZONES_VIDA_DEPH_ADECUADOS:

	ld		ix,CORAZONES_DEPH_EN_BOSSES
	ld		a,(CORAZONES)
	ld		c,a
[9]	add		c
	ld		c,43
	add		c
	ld		(ix),a
	ld		(ix+4),a
    ld      hl,CORAZONES_DEPH_EN_BOSSES
	push	bc
	call   	DOCOPY
	pop		bc
	ret

.BUCLE_PINTA_DATAS:

        ld      b,15

.BUCLE_PINTA_DATAS_1:

        ld      a,(ix)
        ld      (iy),a
        ld      de,1
        add     ix,de
        add     iy,de
        djnz    .BUCLE_PINTA_DATAS_1
        ret

BUCLE_PELEA_BOSS_4:

		HALT
		ld		a,(CORAZONES)
		or		a
		jp		z,MUERTE_DEPH_EN_BOSS_4
		call	NUCLEO_DE_LA_PELEA_BOSS_4
		call	CONTROLA_INMUNIDAD_DEPH_BOSS_4
		
		call	MOVIMIENTO_DEPH_EN_BOSS_4
		call	SECUENCIA_PROYECTILES_PROPIOS_EN_BOSS_4
		call	PINTA_PROYECTILES_DE_DEPH_EN_BOSS_4
        call    REVISAMOS_COLISION_CON_ERRECENYX_Y_DEPH
		call	ON_SPRITE_GLOBAL_BOSS_4
		call	REVISAMOS_COLISION_CON_ERRECENYX_Y_PROYECTILES_DEPH
		call	MUEVE_ERRECENYX_BOSS_4
		call	PINTA_EXPLOSION_ERRECENYX_BOSS_4


        ld      a,(TIEMPO_DE_ADJUST)
        or      a
        jr      z,.CONTROL_POST_BUCLE_2
        dec     a
	ld      (TIEMPO_DE_ADJUST),a
	jr      nz,.CONTROL_POST_BUCLE_2
	xor     a
	ld      (COLOR_ALEATORIO),a

.CONTROL_POST_BUCLE_2:

		call	PINTA_PROYECTIL_BOSS_4
		jp	BUCLE_PELEA_BOSS_4

NUCLEO_DE_LA_PELEA_BOSS_4:

		call	SECUENCIA_PROYECTIL_BOSS_4
		ret

CONTROLA_INMUNIDAD_DEPH_BOSS_4:

		ld		a,(INMUNE)
		or		a
		ret		z
		dec		a
		ld		(INMUNE),a
		ret

INICIALIZA_POOL_PROYECTILES_BOSS_4:

		xor		a
		ld		(PROYECTIL_BOSS_4_SIGUIENTE_EMISOR),a
		ld		(PROYECTIL_BOSS_4_INDICE_ACTUAL),a
		ld		hl,PROYECTILES_BOSS_4_DIRECCION
		ld		b,PROYECTILES_BOSS_4_CANTIDAD

.INICIALIZA_DIRECCIONES_PROYECTIL_BOSS_4:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_DIRECCIONES_PROYECTIL_BOSS_4
		ld		hl,PROYECTILES_BOSS_4_PASO_TABLA
		ld		b,PROYECTILES_BOSS_4_CANTIDAD

.INICIALIZA_PASOS_PROYECTIL_BOSS_4:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_PASOS_PROYECTIL_BOSS_4
		ld		hl,PROYECTILES_BOSS_4_X
		ld		b,PROYECTILES_BOSS_4_CANTIDAD

.INICIALIZA_X_PROYECTIL_BOSS_4:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_X_PROYECTIL_BOSS_4
		ld		a,PROYECTIL_BOSS_4_Y_OCULTO
		ld		hl,PROYECTILES_BOSS_4_Y
		ld		b,PROYECTILES_BOSS_4_CANTIDAD

.INICIALIZA_Y_PROYECTIL_BOSS_4:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_Y_PROYECTIL_BOSS_4
		xor		a
		ld		hl,SPRITES_ACTIVOS+PROYECTIL_BOSS_4_SPRITES_ACTIVOS_OFS
		ld		b,PROYECTILES_BOSS_4_CANTIDAD

.INICIALIZA_SPRITES_ACTIVOS_PROYECTIL_BOSS_4:

		ld		(hl),a
		inc		hl
		djnz	.INICIALIZA_SPRITES_ACTIVOS_PROYECTIL_BOSS_4
		ld		a,PROYECTIL_BOSS_4_SPRITE_INICIAL
		ld		(PROYECTIL_BOSS_4_SIGUIENTE_SPRITE),a
		ld		(PROYECTIL_BOSS_4_SPRITE_ACTUAL),a
		ld		a,PROYECTIL_BOSS_4_ESPERA_INICIAL
		ld		(PROYECTIL_BOSS_4_ESPERA),a
		ret

ACTIVA_PROYECTIL_BOSS_4:

		call	RESERVA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_4
		ret		z
		ld		a,(ERRECENYX_BOSS_4_DIRECCION)
		or		a
		ld		a,(ERRECENYX_BOSS_4_X)
		jr		nz,.EMISOR_IZQ_PROYECTIL_BOSS_4
		add		PROYECTIL_BOSS_4_OFFSET_DER_X
		jr		.GUARDA_X_EMISOR_PROYECTIL_BOSS_4

.EMISOR_IZQ_PROYECTIL_BOSS_4:

		add		PROYECTIL_BOSS_4_OFFSET_IZQ_X

.GUARDA_X_EMISOR_PROYECTIL_BOSS_4:

		ld		b,a
		ld		(PROYECTIL_BOSS_4_X),a
		ld		a,ERRECENYX_MOVIMIENTO_Y_BOSS_4+PROYECTIL_BOSS_4_OFFSET_Y
		ld		c,a
		ld		(PROYECTIL_BOSS_4_Y),a
		ld		a,(PROYECTIL_BOSS_4_X)
		ld		b,a
		call	CALCULA_DIRECCION_BASE_PROYECTIL_BOSS_4
		ld		(PROYECTIL_BOSS_4_PASO_TABLA),a
		call	CREA_PROYECTIL_ERRECENYX_BOSS_4
		ld		a,(PROYECTIL_BOSS_4_PASO_TABLA)
		dec		a
		cp		PROYECTIL_BOSS_4_DIRECCION_MIN
		jr		nc,.CREA_PROYECTIL_ANTERIOR_ERRECENYX
		ld		a,PROYECTIL_BOSS_4_DIRECCION_MAX

.CREA_PROYECTIL_ANTERIOR_ERRECENYX:

		call	CREA_PROYECTIL_ERRECENYX_BOSS_4
		ld		a,(PROYECTIL_BOSS_4_PASO_TABLA)
		inc		a
		cp		PROYECTIL_BOSS_4_DIRECCION_MAX+1
		jr		c,.CREA_PROYECTIL_POSTERIOR_ERRECENYX
		ld		a,PROYECTIL_BOSS_4_DIRECCION_MIN

.CREA_PROYECTIL_POSTERIOR_ERRECENYX:

		call	CREA_PROYECTIL_ERRECENYX_BOSS_4
		ret

CREA_PROYECTIL_ERRECENYX_BOSS_4:

		ld		(PROYECTIL_BOSS_4_DIRECCION),a
		call	RESERVA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_4
		ret		z
		ld		a,(PROYECTIL_BOSS_4_X)
		ld		b,a
		ld		a,(PROYECTIL_BOSS_4_Y)
		ld		c,a
		call	GUARDA_POSICION_PROYECTIL_BOSS_4_ACTUAL
		call	OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_4_ACTUAL
		xor		a
		ld		(hl),a
		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(PROYECTIL_BOSS_4_DIRECCION)
		ld		(hl),a
		call	CARGA_COLOR_PROYECTIL_BOSS_4_ACTUAL
		ret

SECUENCIA_PROYECTIL_BOSS_4:

		ld		b,PROYECTILES_BOSS_4_CANTIDAD
		xor		a
		ld		(PROYECTIL_BOSS_4_INDICE_ACTUAL),a

.BUCLE_SECUENCIA_PROYECTIL_BOSS_4:

		push	bc
		call	LEE_DIRECCION_TABLA_PROYECTIL_BOSS_4
		or		a
		jr		z,.SIGUIENTE_PROYECTIL_BOSS_4
		cp		2
		jr		z,.PROYECTIL_2
		cp		1
		jr		z,.PROYECTIL_1
		cp		4
		jr		z,.PROYECTIL_4
		cp		3
		jr		z,.PROYECTIL_3
		cp		6
		jr		z,.PROYECTIL_6
		cp		5
		jr		z,.PROYECTIL_5
		cp		8
		jr		z,.PROYECTIL_8
		cp		7
		jr		z,.PROYECTIL_7
		call	DESACTIVA_PROYECTIL_BOSS_4
		jr		.SIGUIENTE_PROYECTIL_BOSS_4

.SIGUIENTE_PROYECTIL_BOSS_4:

		ld		a,(PROYECTIL_BOSS_4_INDICE_ACTUAL)
		inc		a
		ld		(PROYECTIL_BOSS_4_INDICE_ACTUAL),a
		pop		bc
		djnz	.BUCLE_SECUENCIA_PROYECTIL_BOSS_4
		ret

.PROYECTIL_2:

		call	INC_X_PROYECTIL_BOSS_4_ACTUAL

.PROYECTIL_1:

		call	SUB_2_Y_PROYECTIL_BOSS_4_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_4
		jr		.SIGUIENTE_PROYECTIL_BOSS_4

.PROYECTIL_4:

		call	INC_Y_PROYECTIL_BOSS_4_ACTUAL

.PROYECTIL_3:

		call	INC_X_PROYECTIL_BOSS_4_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_4
		jr		.SIGUIENTE_PROYECTIL_BOSS_4

.PROYECTIL_6:

		call	DEC_X_PROYECTIL_BOSS_4_ACTUAL

.PROYECTIL_5:

		call	INC_Y_PROYECTIL_BOSS_4_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_4
		jr		.SIGUIENTE_PROYECTIL_BOSS_4

.PROYECTIL_8:

		call	SUB_2_Y_PROYECTIL_BOSS_4_ACTUAL

.PROYECTIL_7:

		call	DEC_X_PROYECTIL_BOSS_4_ACTUAL
		call	COMPRUEBA_LIMITES_PROYECTIL_BOSS_4
		jr		.SIGUIENTE_PROYECTIL_BOSS_4

COMPRUEBA_LIMITES_PROYECTIL_BOSS_4:

		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		cp		5
		jp		c,DESACTIVA_PROYECTIL_BOSS_4
		cp		192
		jp		nc,DESACTIVA_PROYECTIL_BOSS_4
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		cp		251
		jp		nc,DESACTIVA_PROYECTIL_BOSS_4
		ret

DESACTIVA_PROYECTIL_BOSS_4:

		xor		a
		push	af
		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_4_ACTUAL
		pop		af
		ld		(hl),a
		push	af
		call	OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_4_ACTUAL
		pop		af
		ld		(hl),a
		push	af
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_4_ACTUAL
		pop		af
		ld		(hl),a
		call	OBTIENE_PUNTERO_SPRITES_ACTIVOS_PROYECTIL_BOSS_4
		xor		a
		ld		(hl),a
		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_4_ACTUAL
		ld		a,PROYECTIL_BOSS_4_Y_OCULTO
		ld		(hl),a
		call	OCULTA_SPRITE_PROYECTIL_BOSS_4_EN_VRAM
		ret

PINTA_PROYECTIL_BOSS_4:

		ld		b,PROYECTILES_BOSS_4_CANTIDAD
		xor		a
		ld		(PROYECTIL_BOSS_4_INDICE_ACTUAL),a

.BUCLE_PINTA_PROYECTIL_BOSS_4:

		push	bc
		call	PINTA_UN_PROYECTIL_BOSS_4
		ld		a,(PROYECTIL_BOSS_4_INDICE_ACTUAL)
		inc		a
		ld		(PROYECTIL_BOSS_4_INDICE_ACTUAL),a
		pop		bc
		djnz	.BUCLE_PINTA_PROYECTIL_BOSS_4
		ret

PINTA_UN_PROYECTIL_BOSS_4:

		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		or		a
		ret		z
		jp		CARGA_ATRIBUTOS_PROYECTIL_BOSS_4

PINTA_PROYECTIL_BOSS_4_1:

		ld		(hl),a
		call	OBTIENE_DIRECCION_ATRIBUTOS_PROYECTIL_BOSS_4
		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta
		ret

CARGA_ATRIBUTOS_PROYECTIL_BOSS_4:

		ld		hl,PROPIEDADES_PATRON_SPRITE
		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		(hl),a
		inc		hl
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		ld		hl,PROPIEDADES_PATRON_SPRITE+1
		ld		(hl),a
		inc		hl
		ld		a,PROYECTIL_BOSS_4_PATRON_SPRITE
		jr		PINTA_PROYECTIL_BOSS_4_1

CARGA_COLOR_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_DIRECCION_COLOR_PROYECTIL_BOSS_4
		ld		hl,TABLA_COLOR_SPRITE_CENTRAL_BOSS_4
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta
		ret

OCULTA_SPRITE_PROYECTIL_BOSS_4_EN_VRAM:

		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		a,PROYECTIL_BOSS_4_Y_OCULTO
		ld		(hl),a
		inc		hl
		xor		a
		ld		(hl),a
		inc		hl
		ld		(hl),a
		call	OBTIENE_DIRECCION_ATRIBUTOS_PROYECTIL_BOSS_4
		ld		hl,PROPIEDADES_PATRON_SPRITE
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta
		ret

OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL:

		ld		a,(PROYECTIL_BOSS_4_INDICE_ACTUAL)
		ld		e,a
		ld		d,0
		ret

OBTIENE_PUNTERO_X_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL
		ld		hl,PROYECTILES_BOSS_4_X
		add		hl,de
		ret

OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL
		ld		hl,PROYECTILES_BOSS_4_Y
		add		hl,de
		ret

OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL
		ld		hl,PROYECTILES_BOSS_4_DIRECCION
		add		hl,de
		ret

OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL
		ld		hl,PROYECTILES_BOSS_4_PASO_TABLA
		add		hl,de
		ret

GUARDA_POSICION_PROYECTIL_BOSS_4_ACTUAL:

		push	bc
		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_4_ACTUAL
		pop		bc
		ld		(hl),b
		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_4_ACTUAL
		ld		(hl),c
		ret

INC_X_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_4_ACTUAL
		inc		(hl)
		ret

DEC_X_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_PUNTERO_X_PROYECTIL_BOSS_4_ACTUAL
		dec		(hl)
		ret

INC_Y_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_4_ACTUAL
		inc		(hl)
		ret

SUB_2_Y_PROYECTIL_BOSS_4_ACTUAL:

		call	OBTIENE_PUNTERO_Y_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		sub		2
		ld		(hl),a
		ret

OBTIENE_PUNTERO_SPRITES_ACTIVOS_PROYECTIL_BOSS_4:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL
		ld		hl,SPRITES_ACTIVOS+PROYECTIL_BOSS_4_SPRITES_ACTIVOS_OFS
		add		hl,de
		ret

OBTIENE_DIRECCION_ATRIBUTOS_PROYECTIL_BOSS_4:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL
		ld		a,e
		add		a,a
		ld		e,a
		ld		d,0
		ld		hl,TABLA_DIRECCIONES_VRAM_ATRIBUTOS_PROYECTIL_BOSS_4
		add		hl,de
		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		ret

OBTIENE_DIRECCION_COLOR_PROYECTIL_BOSS_4:

		call	OBTIENE_OFFSET_PROYECTIL_BOSS_4_ACTUAL
		ld		a,e
		add		a,a
		ld		e,a
		ld		d,0
		ld		hl,TABLA_DIRECCIONES_VRAM_COLOR_PROYECTIL_BOSS_4
		add		hl,de
		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		ret

RESERVA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_4:

		ld		a,(PROYECTIL_BOSS_4_SIGUIENTE_SPRITE)
		ld		b,PROYECTILES_BOSS_4_CANTIDAD

.BUSCA_SPRITE_LIBRE_PROYECTIL_BOSS_4:

		ld		c,a
		sub		PROYECTIL_BOSS_4_SPRITE_INICIAL
		ld		e,a
		ld		d,0
		ld		hl,PROYECTILES_BOSS_4_DIRECCION
		add		hl,de
		ld		a,(hl)
		or		a
		jr		z,.RESERVA_SPRITE_LIBRE_PROYECTIL_BOSS_4
		ld		a,c
		inc		a
		cp		PROYECTIL_BOSS_4_SPRITE_FINAL
		jr		c,.SIGUE_BUSQUEDA_SPRITE_LIBRE_PROYECTIL_BOSS_4
		ld		a,PROYECTIL_BOSS_4_SPRITE_INICIAL

.SIGUE_BUSQUEDA_SPRITE_LIBRE_PROYECTIL_BOSS_4:

		djnz	.BUSCA_SPRITE_LIBRE_PROYECTIL_BOSS_4
		xor		a
		ret

.RESERVA_SPRITE_LIBRE_PROYECTIL_BOSS_4:

		ld		a,e
		ld		(PROYECTIL_BOSS_4_INDICE_ACTUAL),a
		ld		a,c
		ld		(PROYECTIL_BOSS_4_SPRITE_ACTUAL),a
		call	OBTIENE_PUNTERO_SPRITES_ACTIVOS_PROYECTIL_BOSS_4
		ld		a,1
		ld		(hl),a
		ld		a,c
		inc		a
		cp		PROYECTIL_BOSS_4_SPRITE_FINAL
		jr		c,.GUARDA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_4
		ld		a,PROYECTIL_BOSS_4_SPRITE_INICIAL

.GUARDA_SIGUIENTE_SPRITE_LIBRE_PROYECTIL_BOSS_4:

		ld		(PROYECTIL_BOSS_4_SIGUIENTE_SPRITE),a
		ld		a,1
		or		a
		ret
CALCULA_DIRECCION_BASE_PROYECTIL_BOSS_4:
		ld      a,11
		ld		c,0
		call 	PAGE_31_A_SEGMENT_2
		call	ayFX_INIT
		call	PAGE_10_A_SEGMENT_2

		ld		a,(X_DEPH)
		ld		e,a
		ld		a,b
		add		8
		ld		d,a
		ld		a,e
		sub		d
		jr		nc,.DEPH_A_LA_DERECHA
		ld		a,d
		sub		e
		ld		h,7
		jr		.COMPARA_DISTANCIAS

.DEPH_A_LA_DERECHA:

		ld		h,2

.COMPARA_DISTANCIAS:

		cp		8
		jr		c,.CENTRO
		ld		l,a
		ld		a,(Y_DEPH)
		cp		c
		jr		c,.ANGULO_EXTREMO
		sub		c
		ld		e,a
		ld		a,l
		add		a,a
		jr		c,.ANGULO_EXTREMO
		add		a,a
		jr		c,.ANGULO_EXTREMO
		cp		e
		jr		c,.ANGULO_CERRADO
		jr		z,.ANGULO_CERRADO
		ld		a,l
		add		a,a
		jr		c,.ANGULO_ABIERTO
		cp		e
		jr		c,.ANGULO_DIAGONAL
		jr		z,.ANGULO_DIAGONAL
		ld		a,l
		cp		e
		jr		c,.ANGULO_MEDIO
		jr		z,.ANGULO_MEDIO
		ld		a,e
		add		a,a
		jr		c,.ANGULO_ABIERTO
		cp		l
		jr		c,.ANGULO_EXTREMO
		jr		z,.ANGULO_ABIERTO

.ANGULO_ABIERTO:

		ld		a,h
		inc		a
		inc		a
		inc		a
		ret

.ANGULO_DIAGONAL:

		ld		a,h
		inc		a
		inc		a
		ret

.ANGULO_MEDIO:

		ld		a,h
		inc		a
		ret

.ANGULO_CERRADO:

		ld		a,h
		ret

.ANGULO_EXTREMO:

		ld		a,h
		inc		a
		inc		a
		inc		a
		inc		a
		ret

.CENTRO:

		ld		a,1
		ret

LEE_DIRECCION_TABLA_PROYECTIL_BOSS_4:

		call	OBTIENE_PUNTERO_DIRECCION_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		or		a
		ret		z
		cp		12
		jr		nc,.DIRECCION_INVALIDA
		dec		a
		ld		b,a
		add		a,a
		add		a,b
		ld		e,a
		ld		d,0
		ld		hl,TABLA_DIRECCIONES_PROYECTIL_BOSS_4
		add		hl,de
		push	hl
		call	OBTIENE_PUNTERO_PASO_TABLA_PROYECTIL_BOSS_4_ACTUAL
		ld		a,(hl)
		ld		c,a
		inc		a
		ld		(hl),a
		cp		3
		jr		c,.NO_REINICIA_PASO_TABLA
		xor		a
		ld		(hl),a

.NO_REINICIA_PASO_TABLA:

		pop		hl
		ld		b,0
		add		hl,bc
		ld		a,(hl)
		ret

.DIRECCION_INVALIDA:

		xor		a
		ret

MOVIMIENTO_DEPH_EN_BOSS_4:

		include	"COMUN/MOVIMIENTO EN BOSSES.asm"

MUEVE_ERRECENYX_BOSS_4:

		push	af
		push	bc
		push	de
		push	hl
		push	ix
		push	iy

		ld		a,(ERRECENYX_BOSS_4_MODO)
		or		a
		jr		nz,.MODO_ERRECENYX_PARADO

		ld		a,(ERRECENYX_BOSS_4_TIEMPO_MODO)
		dec		a
		ld		(ERRECENYX_BOSS_4_TIEMPO_MODO),a
		jr		nz,.MODO_ERRECENYX_MOVIMIENTO

		ld		a,ERRECENYX_MODO_PARADO_BOSS_4
		ld		(ERRECENYX_BOSS_4_MODO),a
		ld		a,ERRECENYX_PARADO_DURACION_BOSS_4
		ld		(ERRECENYX_BOSS_4_TIEMPO_MODO),a
		jp		.FIN_MOVIMIENTO_ERRECENYX

.MODO_ERRECENYX_PARADO:

		ld		a,(ERRECENYX_BOSS_4_TIEMPO_MODO)
		dec		a
		ld		(ERRECENYX_BOSS_4_TIEMPO_MODO),a
		jr		nz,.PINTA_ERRECENYX_PARADO

		ld		a,ERRECENYX_MODO_MOVIMIENTO_BOSS_4
		ld		(ERRECENYX_BOSS_4_MODO),a
		call	NUEVO_TIEMPO_MOVIMIENTO_ERRECENYX_BOSS_4
		call	ACTIVA_PROYECTIL_BOSS_4
		jp		.FIN_MOVIMIENTO_ERRECENYX

.PINTA_ERRECENYX_PARADO:

		ld		a,(ERRECENYX_BOSS_4_ESPERA_MOVIMIENTO)
		dec		a
		ld		(ERRECENYX_BOSS_4_ESPERA_MOVIMIENTO),a
		jp		nz,.FIN_MOVIMIENTO_ERRECENYX

		ld		a,ERRECENYX_MOVIMIENTO_ESPERA_BOSS_4
		ld		(ERRECENYX_BOSS_4_ESPERA_MOVIMIENTO),a
		jr		.PINTA_ERRECENYX_MOVIMIENTO

.MODO_ERRECENYX_MOVIMIENTO:

		ld		a,(ERRECENYX_BOSS_4_ESPERA_MOVIMIENTO)
		dec		a
		ld		(ERRECENYX_BOSS_4_ESPERA_MOVIMIENTO),a
		jp		nz,.FIN_MOVIMIENTO_ERRECENYX

		ld		a,ERRECENYX_MOVIMIENTO_ESPERA_BOSS_4
		ld		(ERRECENYX_BOSS_4_ESPERA_MOVIMIENTO),a

		ld		a,(ERRECENYX_BOSS_4_DIRECCION)
		or		a
		jr		z,.MUEVE_ERRECENYX_DERECHA

.MUEVE_ERRECENYX_IZQUIERDA:

		ld		a,(ERRECENYX_BOSS_4_X)
		or		a
		jr		z,.CAMBIA_ERRECENYX_A_DERECHA
		sub		ERRECENYX_MOVIMIENTO_PASO_X_BOSS_4
		ld		(ERRECENYX_BOSS_4_X),a
		jr		.PINTA_ERRECENYX_MOVIMIENTO_IZQUIERDA

.CAMBIA_ERRECENYX_A_DERECHA:

		xor		a
		ld		(ERRECENYX_BOSS_4_DIRECCION),a
		jr		.PINTA_ERRECENYX_MOVIMIENTO

.MUEVE_ERRECENYX_DERECHA:

		ld		a,(ERRECENYX_BOSS_4_X)
		cp		ERRECENYX_MOVIMIENTO_X_MAX_BOSS_4
		jr		nc,.CAMBIA_ERRECENYX_A_IZQUIERDA
		add		ERRECENYX_MOVIMIENTO_PASO_X_BOSS_4
		ld		(ERRECENYX_BOSS_4_X),a
		jr		.PINTA_ERRECENYX_MOVIMIENTO_DERECHA

.CAMBIA_ERRECENYX_A_IZQUIERDA:

		ld		a,1
		ld		(ERRECENYX_BOSS_4_DIRECCION),a

.PINTA_ERRECENYX_MOVIMIENTO:

		call	.PINTA_ERRECENYX_MOVIMIENTO_COMUN
		jr		.ACTUALIZA_FOTOGRAMA_ERRECENYX

.PINTA_ERRECENYX_MOVIMIENTO_DERECHA:

		call	BORRA_RASTRO_ERRECENYX_BOSS_4
		call	.PINTA_ERRECENYX_MOVIMIENTO_COMUN
		jr		.ACTUALIZA_FOTOGRAMA_ERRECENYX

.PINTA_ERRECENYX_MOVIMIENTO_IZQUIERDA:

		call	.PINTA_ERRECENYX_MOVIMIENTO_COMUN
		call	BORRA_RASTRO_ERRECENYX_BOSS_4
		jr		.ACTUALIZA_FOTOGRAMA_ERRECENYX

.PINTA_ERRECENYX_MOVIMIENTO_COMUN:

		ld		ix,BOSS_4_COPY_MOVIMIENTO_ERRECENYX
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_4.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL

		ld		a,(ERRECENYX_BOSS_4_FOTOGRAMA)
		and		00000001b
		jr		z,.SX_1_MOVIMIENTO_ERRECENYX
		ld		a,ERRECENYX_MOVIMIENTO_SX_2_BOSS_4
		jr		.GUARDA_SX_MOVIMIENTO_ERRECENYX

.SX_1_MOVIMIENTO_ERRECENYX:

		ld		a,ERRECENYX_MOVIMIENTO_SX_1_BOSS_4

.GUARDA_SX_MOVIMIENTO_ERRECENYX:

		ld		(iy),a

		ld		a,(ERRECENYX_BOSS_4_FOTOGRAMA)
		and		00000010b
		jr		z,.SY_1_MOVIMIENTO_ERRECENYX
		ld		a,(ERRECENYX_BOSS_4_MODO)
		or		a
		ld		a,ERRECENYX_MOVIMIENTO_SY_2_BOSS_4
		jr		z,.GUARDA_SY_MOVIMIENTO_ERRECENYX
		ld		a,ERRECENYX_PARADO_SY_2_BOSS_4
		jr		.GUARDA_SY_MOVIMIENTO_ERRECENYX

.SY_1_MOVIMIENTO_ERRECENYX:

		ld		a,(ERRECENYX_BOSS_4_MODO)
		or		a
		ld		a,ERRECENYX_MOVIMIENTO_SY_1_BOSS_4
		jr		z,.GUARDA_SY_MOVIMIENTO_ERRECENYX
		ld		a,ERRECENYX_PARADO_SY_1_BOSS_4

.GUARDA_SY_MOVIMIENTO_ERRECENYX:

		ld		(iy+2),a

		ld		a,(ERRECENYX_BOSS_4_DIRECCION)
		or		a
		ld		a,ERRECENYX_MOVIMIENTO_PAG_DERECHA_BOSS_4
		jr		z,.GUARDA_PAGINA_MOVIMIENTO_ERRECENYX
		ld		a,ERRECENYX_MOVIMIENTO_PAG_IZQUIERDA_BOSS_4

.GUARDA_PAGINA_MOVIMIENTO_ERRECENYX:

		ld		(iy+3),a
		ld		a,(ERRECENYX_BOSS_4_X)
		ld		(iy+4),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY
		ret

.ACTUALIZA_FOTOGRAMA_ERRECENYX:

		ld		a,(ERRECENYX_BOSS_4_FOTOGRAMA)
		inc		a
		and		00000011b
		ld		(ERRECENYX_BOSS_4_FOTOGRAMA),a

.FIN_MOVIMIENTO_ERRECENYX:

		pop		iy
		pop		ix
		pop		hl
		pop		de
		pop		bc
		pop		af
		ret

NUEVO_TIEMPO_MOVIMIENTO_ERRECENYX_BOSS_4:

		ld		a,r
		and		01111111b
		cp		ERRECENYX_MOVIMIENTO_AZAR_MAX_BOSS_4
		jr		c,.GUARDA_NUEVO_TIEMPO_MOVIMIENTO_ERRECENYX
		sub		ERRECENYX_MOVIMIENTO_AZAR_MAX_BOSS_4

.GUARDA_NUEVO_TIEMPO_MOVIMIENTO_ERRECENYX:

		inc		a
		ld		(ERRECENYX_BOSS_4_TIEMPO_MODO),a
		ret

BORRA_RASTRO_ERRECENYX_BOSS_4:

		push	af
		push	bc
		push	hl
		push	ix
		push	iy

		ld		ix,BOSS_4_BORRA_MOVIMIENTO_ERRECENYX
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_4.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL

		ld		a,(ERRECENYX_BOSS_4_DIRECCION)
		or		a
		jr		nz,.BORRA_RASTRO_ERRECENYX_IZQUIERDA

		ld		a,(ERRECENYX_BOSS_4_X)
		sub		ERRECENYX_MOVIMIENTO_BORRA_ANCHO_BOSS_4
		jr		nc,.GUARDA_X_BORRA_RASTRO_ERRECENYX
		xor		a
		jr		.GUARDA_X_BORRA_RASTRO_ERRECENYX

.BORRA_RASTRO_ERRECENYX_IZQUIERDA:

		ld		a,(ERRECENYX_BOSS_4_X)
		add		ERRECENYX_MOVIMIENTO_ANCHO_BOSS_4

.GUARDA_X_BORRA_RASTRO_ERRECENYX:

		ld		(iy+4),a
		xor		a
		ld		(iy+5),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY

		pop		iy
		pop		ix
		pop		hl
		pop		bc
		pop		af
		ret

SECUENCIA_PROYECTILES_PROPIOS_EN_BOSS_4:

		include	"COMUN/SECUENCIA PROYECTILES PROPIOS EN BOSSES.asm"

PINTA_PROYECTILES_DE_DEPH_EN_BOSS_4:

		include	"COMUN/PINTADO PROYECTILES PROPIOS EN BOSSES.asm"

ON_SPRITE_GLOBAL_BOSS_4:

	jp	BUCLE_REVISION_TODOS_LOS_PROYECTILES_OJO_BOSS_4

PINTA_MARCADORES_VIDA_FINAL_BOSS_4:

		ld		a,(VIDA_ERRECENYX_BOSS_4)
		call	CONVIERTE_VIDA_FINAL_A_BARRA_BOSS_4

        ; Si es el ancho total, lo dejamos tal cual
        ; para que al morir borre la barra completa.
        cp      VIDA_ANCHO_BARRA_BOSS_4
        jr      z,.ANCHO_BARRA_BOSS_4_OK

        ; Redondeamos hacia abajo a múltiplos de 6
        ; 1-5   -> 0
        ; 6-11  -> 6
        ; 12-17 -> 12
        ; 18-23 -> 18
        ; etc.
        ld      b,0

.REDONDEA_BARRA_A_6_BOSS_4:

        cp      6
        jr      c,.FIN_REDONDEA_BARRA_A_6_BOSS_4

        sub     6
        ld      c,a
        ld      a,b
        add     a,6
        ld      b,a
        ld      a,c

        jr      .REDONDEA_BARRA_A_6_BOSS_4

.FIN_REDONDEA_BARRA_A_6_BOSS_4:

        ld      a,b

.ANCHO_BARRA_BOSS_4_OK:

        or      a
        ret     z
        ld      b,a
        ld      a,VIDA_ANCHO_BARRA_BOSS_4
        sub     b
        ld      c,151
        add     c

		ld		ix,DATAS_COR_EMPT_MALO
		ld		(ix+4),a
		ld		a,b
		ld		(ix+8),a
		xor		a
		ld		(ix+9),a

	 	ld	    hl,DATAS_COR_EMPT_MALO
		jp		DOCOPY

CONVIERTE_VIDA_FINAL_A_BARRA_BOSS_4:

		ld		c,a
		ld		a,VIDA_TOTAL_INICIAL_BOSS_4
		sub		c
        ld      b,a
        xor     a
        ld      d,a
        ld      l,a

.BUCLE_ESCALA_VIDA_FINAL_BOSS_4:

        ld      a,b
        or      a
        jr      z,.FIN_ESCALA_VIDA_FINAL_BOSS_4

        dec     b

        ld      a,l
        add     a,VIDA_ANCHO_BARRA_BOSS_4

.AJUSTA_ESCALA_VIDA_FINAL_BOSS_4:

        cp      VIDA_TOTAL_INICIAL_BOSS_4
        jr      c,.GUARDA_RESTO_ESCALA_VIDA_FINAL_BOSS_4

        sub     VIDA_TOTAL_INICIAL_BOSS_4
        inc     d
        jr      .AJUSTA_ESCALA_VIDA_FINAL_BOSS_4

.GUARDA_RESTO_ESCALA_VIDA_FINAL_BOSS_4:

        ld      l,a
        jr      .BUCLE_ESCALA_VIDA_FINAL_BOSS_4

.FIN_ESCALA_VIDA_FINAL_BOSS_4:

        ld      a,d
        ld      h,a
        ld      a,l
        or      a
        ld      a,h
        ret     z
        inc     a
        ret

BUCLE_REVISION_TODOS_LOS_PROYECTILES_OJO_BOSS_4:

		ld		hl,PROYECTILES_BOSS_4_DIRECCION
		ld		ix,PROYECTILES_BOSS_4_X
		ld		iy,PROYECTILES_BOSS_4_Y
		ld		b,PROYECTILES_BOSS_4_CANTIDAD

.BUCLE_REVISION_PROYECTILES_OJO_BOSS_4:

        ld      a,(hl)
        or      a
        jr      z,.SIGUIENTE_PROYECTIL_OJO_BOSS_4

        ; --- Comprobar X ---
        ld      a,(X_DEPH)
        add     a,20
        sub     (ix+0)          ; A = X_DEPH + 20 - X_PROYECTIL
        cp      36              ; 20 + 16
        jr      nc,.SIGUIENTE_PROYECTIL_OJO_BOSS_4

        ; --- Comprobar Y ---
        ld      a,(Y_DEPH)
        add     a,20
        sub     (iy+0)          ; A = Y_DEPH + 20 - Y_PROYECTIL
        cp      36              ; 20 + 16
        jr      nc,.SIGUIENTE_PROYECTIL_OJO_BOSS_4

        ; Si llega aquí, hay colisión

		call	DESACTIVA_PROYECTIL_OJO_BOSS_4_ACTUAL
		call	DANO_DEPH_EN_BOSS_4
		ret

.SIGUIENTE_PROYECTIL_OJO_BOSS_4:

		inc		hl
		inc		ix
		inc		iy
		djnz	.BUCLE_REVISION_PROYECTILES_OJO_BOSS_4
		ret

DESACTIVA_PROYECTIL_OJO_BOSS_4_ACTUAL:

		push	hl
		or		a
		ld		de,PROYECTILES_BOSS_4_DIRECCION
		sbc		hl,de
		ld		a,l
		ld		(PROYECTIL_BOSS_4_INDICE_ACTUAL),a
		pop		hl
		jp		DESACTIVA_PROYECTIL_BOSS_4

REVISAMOS_COLISION_CON_ERRECENYX_Y_DEPH:

		ld		a,(ERRECENYX_BOSS_4_X)
		ld		c,a
		ld		a,(X_DEPH)
		add		20
		cp		c
		ret		c

		ld		a,(ERRECENYX_BOSS_4_X)
		add		ERRECENYX_MOVIMIENTO_ANCHO_BOSS_4
		jr		c,.COMPRUEBA_Y_COLISION_ERRECENYX_DEPH
		ld		c,a
		ld		a,(X_DEPH)
		cp		c
		ret		nc

.COMPRUEBA_Y_COLISION_ERRECENYX_DEPH:

		ld		a,(Y_DEPH)
		add		20
		cp		ERRECENYX_MOVIMIENTO_Y_BOSS_4
		ret		c
		ld		a,(Y_DEPH)
		cp		ERRECENYX_MOVIMIENTO_Y_BOSS_4+ERRECENYX_MOVIMIENTO_ALTO_BOSS_4
		ret		nc

		call	DANO_DEPH_EN_BOSS_4
	ret

DANO_DEPH_EN_BOSS_4:

	call	DANO_DEPH_EN_BOSS_COMUN
	call	RUTINA_BOSS_4.PINTA_CORAZONES_VIDA_DEPH_ADECUADOS
	ret

MUERTE_DEPH_EN_BOSS_4:

	call	PREPARA_VRAM_PARA_MUERTE_DEPH_EN_BOSS
	jp		MUERTE_POR_TOQUES_DESDE_BOSS

REVISAMOS_COLISION_CON_ERRECENYX_Y_PROYECTILES_DEPH:

		ld		iy,PROYECTILES
		ld		b,6

.BUCLE_PROYECTILES_DEPH_ERRECENYX_BOSS_4:

		push	bc
		ld		a,(iy+2)
		cp		#FF
		jp		z,.SIGUIENTE_PROYECTIL_DEPH_ERRECENYX_BOSS_4

		ld		a,(ERRECENYX_BOSS_4_DIRECCION)
		or		a
		jr		nz,.REVISA_IMPACTO_ERRECENYX_IZQUIERDA_BOSS_4

		ld		a,(ERRECENYX_BOSS_4_X)
		add		ERRECENYX_IMPACTO_DER_X_MIN_BOSS_4
		ld		c,a
		ld		d,ERRECENYX_IMPACTO_DER_X_ANCHO_BOSS_4
		jr		.REVISA_X_IMPACTO_ERRECENYX_BOSS_4

.REVISA_IMPACTO_ERRECENYX_IZQUIERDA_BOSS_4:

		ld		a,(ERRECENYX_BOSS_4_X)
		add		ERRECENYX_IMPACTO_IZQ_X_MIN_BOSS_4
		ld		c,a
		ld		d,ERRECENYX_IMPACTO_IZQ_X_ANCHO_BOSS_4

.REVISA_X_IMPACTO_ERRECENYX_BOSS_4:

		ld		a,(iy)
		cp		c
		jp		c,.SIGUIENTE_PROYECTIL_DEPH_ERRECENYX_BOSS_4
		sub		c
		cp		d
		jp		nc,.SIGUIENTE_PROYECTIL_DEPH_ERRECENYX_BOSS_4

		ld		a,ERRECENYX_MOVIMIENTO_Y_BOSS_4+ERRECENYX_IMPACTO_Y_MIN_BOSS_4
		ld		c,a
		ld		a,(iy+1)
		cp		c
		jp		c,.SIGUIENTE_PROYECTIL_DEPH_ERRECENYX_BOSS_4
		sub		c
		cp		ERRECENYX_IMPACTO_Y_ALTO_BOSS_4
		jp		nc,.SIGUIENTE_PROYECTIL_DEPH_ERRECENYX_BOSS_4

		ld		a,(VIDA_ERRECENYX_BOSS_4)
		or		a
		jr		z,.SOBRE_PROYECTIL_DEPH_ERRECENYX_BOSS_4
		call	CALCULA_DANO_PROYECTIL_ERRECENYX_BOSS_4
		ld		c,a
		ld		a,(VIDA_ERRECENYX_BOSS_4)
		cp		c
		jr		nc,.RESTA_DANO_ERRECENYX_BOSS_4
		xor		a
		jr		.GUARDA_VIDA_ERRECENYX_TRAS_IMPACTO_BOSS_4

.RESTA_DANO_ERRECENYX_BOSS_4:

		sub		c

.GUARDA_VIDA_ERRECENYX_TRAS_IMPACTO_BOSS_4:

		ld		(VIDA_ERRECENYX_BOSS_4),a
		push	af
		call	PINTA_MARCADORES_VIDA_FINAL_BOSS_4
		pop		af
		or		a
		jr		z,.MUERE_ERRECENYX_POR_PROYECTIL_BOSS_4

.SOBRE_PROYECTIL_DEPH_ERRECENYX_BOSS_4:

		call	.LIMPIA_PROYECTIL_TRAS_IMPACTO_ERRECENYX_BOSS_4
		pop		bc
		ret

.MUERE_ERRECENYX_POR_PROYECTIL_BOSS_4:

		call	.LIMPIA_PROYECTIL_TRAS_IMPACTO_ERRECENYX_BOSS_4
		pop		bc
		jp		MUERTE_DE_ERRECENYX_BOSS_4

.LIMPIA_PROYECTIL_TRAS_IMPACTO_ERRECENYX_BOSS_4:

		ld		a,5
		ld		c,0
		call	TIRA_FX_BOSS_4

		ld		ix,VALORES_EXPLOSION_CON_ROCK
		ld		a,(iy)
		ld		(ix+1),a
		ld		a,(iy+1)
		sub		8
		ld		(ix),a
		ld		a,23*4
		ld		(ix+2),a

		ld		a,(iy+12)
		ld		e,a
		ld		d,0
		ld		hl,#4A00
		add		hl,de
		ex		de,hl
		ld		hl,.SPRITE_OCULTO_TRAS_IMPACTO_ERRECENYX_BOSS_4
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta

		xor		a
		ld		(iy+8),a
		dec		a
		ld		(iy+2),a
		ld		(iy),a
		ld		a,(iy+12)
		call	SECUENCIA_PROYECTILES_PROPIOS_EN_BOSS_4.DEJA_LIBRE_SPRITE_EN_RAM
		ret

.SPRITE_OCULTO_TRAS_IMPACTO_ERRECENYX_BOSS_4:

		db		217,255,0

.SIGUIENTE_PROYECTIL_DEPH_ERRECENYX_BOSS_4:

		ld		de,16
		add		iy,de
		pop		bc
		dec		b
		jp		nz,.BUCLE_PROYECTILES_DEPH_ERRECENYX_BOSS_4
		ret

CALCULA_DANO_PROYECTIL_ERRECENYX_BOSS_4:

		ld		a,(iy+4)
		cp		2
		jr		z,.DANO_HACHA_ERRECENYX_BOSS_4
		cp		1
		jr		z,.DANO_FUEGO_ERRECENYX_BOSS_4

.DANO_FLECHA_ERRECENYX_BOSS_4:

		ld		a,8
		ret

.DANO_HACHA_ERRECENYX_BOSS_4:

		ld		a,2
		ret

.DANO_FUEGO_ERRECENYX_BOSS_4:

		ld		a,1
		ret

PINTA_EXPLOSION_ERRECENYX_BOSS_4:

		ld		ix,VALORES_EXPLOSION_CON_ROCK
		ld		a,(ix+2)
		or		a
		ret		z
		cp		25*4
		jr		nz,.PINTAMOS_EXPLOSION_ERRECENYX_BOSS_4

		xor		a
		ld		(ix+2),a

.PINTAMOS_EXPLOSION_ERRECENYX_BOSS_4:

		ld		de,#4A00+17*4
		ld		hl,VALORES_EXPLOSION_CON_ROCK
		ld		bc,3
		call	PON_COLOR_2.sin_bc_impuesta

		ld		de,#4800+17*16
		ld		hl,BOSS_4_COLOR_EXPLOSION_ERRECENYX
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,(ix+2)
		or		a
		ret		z
		add		4
		ld		(ix+2),a
		ret

INICIALIZA_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		ix,RATAS_MUERTE_ERRECENYX_X
		ld		iy,BOSS_4_RATAS_MUERTE_OFFSET_X
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_4

.BUCLE_INICIALIZA_X_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		a,(ERRECENYX_BOSS_4_X)
		add		a,(iy)
		ld		(ix),a
		inc		ix
		inc		iy
		djnz	.BUCLE_INICIALIZA_X_RATAS_MUERTE_ERRECENYX_BOSS_4

		ld		ix,RATAS_MUERTE_ERRECENYX_ESPERA
		ld		hl,BOSS_4_RATAS_MUERTE_VELOCIDAD
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_4

.BUCLE_INICIALIZA_ESPERA_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		a,(hl)
		ld		(ix),a
		inc		hl
		inc		ix
		djnz	.BUCLE_INICIALIZA_ESPERA_RATAS_MUERTE_ERRECENYX_BOSS_4

		ld		hl,RATAS_MUERTE_ERRECENYX_ACTIVA
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_4
		ld		a,1

.BUCLE_INICIALIZA_ACTIVA_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		(hl),a
		inc		hl
		djnz	.BUCLE_INICIALIZA_ACTIVA_RATAS_MUERTE_ERRECENYX_BOSS_4

		call	PAGE_32_A_SEGMENT_2
		ld		de,RATAS_MUERTE_COLOR_VRAM_BOSS_4
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_4

.BUCLE_COLOR_RATAS_MUERTE_ERRECENYX_BOSS_4:

		push	bc
		push	de
		ld		hl,COLOR_RATA
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta
		pop		de
		ld		a,e
		add		16
		ld		e,a
		jr		nc,.SIN_ACARREO_COLOR_RATAS_MUERTE_ERRECENYX_BOSS_4
		inc		d

.SIN_ACARREO_COLOR_RATAS_MUERTE_ERRECENYX_BOSS_4:

		pop		bc
		djnz	.BUCLE_COLOR_RATAS_MUERTE_ERRECENYX_BOSS_4
		jp		PAGE_10_A_SEGMENT_2

ENTRAN_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		ix,RATAS_MUERTE_ERRECENYX_X
		ld		hl,RATAS_MUERTE_ERRECENYX_ACTIVA
		ld		c,0

.BUCLE_PREPARA_ENTRADA_RATAS_MUERTE_ERRECENYX_BOSS_4:

		bit		0,c
		jr		nz,.RATA_ENTRA_DESDE_DERECHA_BOSS_4

		xor		a
		jr		.GUARDA_X_ENTRADA_RATA_MUERTE_ERRECENYX_BOSS_4

.RATA_ENTRA_DESDE_DERECHA_BOSS_4:

		ld		a,255

.GUARDA_X_ENTRADA_RATA_MUERTE_ERRECENYX_BOSS_4:

		ld		(ix),a
		ld		(hl),1
		inc		ix
		inc		hl
		inc		c
		ld		a,c
		cp		RATAS_MUERTE_CANTIDAD_BOSS_4
		jr		c,.BUCLE_PREPARA_ENTRADA_RATAS_MUERTE_ERRECENYX_BOSS_4

.BUCLE_ENTRAN_RATAS_MUERTE_ERRECENYX_BOSS_4:

		call	MUEVE_RATAS_ENTRADA_ERRECENYX_BOSS_4
		ld		a,RATAS_MUERTE_ENTRADA_PAUSA_BOSS_4
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		ld		a,(RATAS_MUERTE_ERRECENYX_CONTADOR)
		or		a
		jr		nz,.BUCLE_ENTRAN_RATAS_MUERTE_ERRECENYX_BOSS_4
		call	ACTIVA_RATAS_MUERTE_ERRECENYX_BOSS_4
		ret

ACTIVA_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		hl,RATAS_MUERTE_ERRECENYX_ACTIVA
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_4
		ld		a,1

.BUCLE_ACTIVA_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		(hl),a
		inc		hl
		djnz	.BUCLE_ACTIVA_RATAS_MUERTE_ERRECENYX_BOSS_4
		ret

MUEVE_RATAS_ENTRADA_ERRECENYX_BOSS_4:

		xor		a
		ld		(RATAS_MUERTE_ERRECENYX_CONTADOR),a
		ld		de,RATAS_MUERTE_ERRECENYX_ATRIBUTOS
		ld		c,a

.BUCLE_MUEVE_RATAS_ENTRADA_ERRECENYX_BOSS_4:

		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_ERRECENYX_ACTIVA
		add		hl,bc
		ld		a,(hl)
		or		a
		jr		z,.PINTA_RATA_ENTRADA_ERRECENYX_BOSS_4

		push	hl
		ld		hl,BOSS_4_RATAS_MUERTE_OFFSET_X
		add		hl,bc
		ld		a,(ERRECENYX_BOSS_4_X)
		add		a,(hl)
		ld		d,a
		ld		hl,RATAS_MUERTE_ERRECENYX_X
		add		hl,bc
		ld		a,(hl)
		bit		0,c
		jr		nz,.MUEVE_RATA_ENTRADA_IZQUIERDA_ERRECENYX_BOSS_4

.MUEVE_RATA_ENTRADA_DERECHA_ERRECENYX_BOSS_4:

		add		a,RATAS_MUERTE_PASO_X_BOSS_4
		cp		d
		jr		nc,.FIJA_RATA_ENTRADA_ERRECENYX_BOSS_4
		ld		(hl),a
		pop		hl
		jr		.SIGUE_RATA_ENTRANDO_ERRECENYX_BOSS_4

.MUEVE_RATA_ENTRADA_IZQUIERDA_ERRECENYX_BOSS_4:

		ld		e,a
		ld		a,d
		add		a,RATAS_MUERTE_PASO_X_BOSS_4
		cp		e
		jr		nc,.FIJA_RATA_ENTRADA_ERRECENYX_BOSS_4
		ld		a,e
		sub		RATAS_MUERTE_PASO_X_BOSS_4
		ld		(hl),a
		pop		hl

.SIGUE_RATA_ENTRANDO_ERRECENYX_BOSS_4:

		ld		a,(RATAS_MUERTE_ERRECENYX_CONTADOR)
		inc		a
		ld		(RATAS_MUERTE_ERRECENYX_CONTADOR),a
		jr		.PINTA_RATA_ENTRADA_ERRECENYX_BOSS_4

.FIJA_RATA_ENTRADA_ERRECENYX_BOSS_4:

		ld		a,d
		ld		(hl),a
		pop		hl
		xor		a
		ld		(hl),a

.PINTA_RATA_ENTRADA_ERRECENYX_BOSS_4:

		pop		de
		ld		a,RATAS_MUERTE_Y_BOSS_4
		ld		(de),a
		inc		de
		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_ERRECENYX_X
		add		hl,bc
		ld		a,(hl)
		pop		de
		ld		(de),a
		inc		de
		bit		0,c
		jr		nz,.PATRON_RATA_ENTRADA_IZQUIERDA_ERRECENYX_BOSS_4

.PATRON_RATA_ENTRADA_DERECHA_ERRECENYX_BOSS_4:

		ld		a,RATA_PATRON_DERECHA_BOSS_4
		jr		.GUARDA_PATRON_RATA_ENTRADA_ERRECENYX_BOSS_4

.PATRON_RATA_ENTRADA_IZQUIERDA_ERRECENYX_BOSS_4:

		ld		a,RATA_PATRON_IZQUIERDA_BOSS_4

.GUARDA_PATRON_RATA_ENTRADA_ERRECENYX_BOSS_4:

		ld		(de),a
		inc		de
		xor		a
		ld		(de),a
		inc		de
		inc		c
		ld		a,c
		cp		RATAS_MUERTE_CANTIDAD_BOSS_4
		jp		c,.BUCLE_MUEVE_RATAS_ENTRADA_ERRECENYX_BOSS_4

		ld		hl,RATAS_MUERTE_ERRECENYX_ATRIBUTOS
		ld		de,RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_4
		ld		bc,RATAS_MUERTE_CANTIDAD_BOSS_4*4
		jp		PON_COLOR_2.sin_bc_impuesta

MUEVE_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		ix,RATAS_MUERTE_ERRECENYX_X
		ld		iy,RATAS_MUERTE_ERRECENYX_ESPERA
		ld		hl,BOSS_4_RATAS_MUERTE_VELOCIDAD
		ld		de,RATAS_MUERTE_ERRECENYX_ATRIBUTOS
		ld		b,RATAS_MUERTE_CANTIDAD_BOSS_4

.BUCLE_MUEVE_RATAS_MUERTE_ERRECENYX_BOSS_4:

		ld		a,(iy)
		dec		a
		ld		(iy),a
		jr		nz,.PINTA_RATA_MUERTE_ERRECENYX_BOSS_4

		ld		a,(hl)
		ld		(iy),a
		ld		a,(ix)
		bit		0,b
		jr		nz,.MUEVE_RATA_DERECHA_MUERTE_ERRECENYX_BOSS_4

.MUEVE_RATA_IZQUIERDA_MUERTE_ERRECENYX_BOSS_4:

		sub		RATAS_MUERTE_PASO_X_BOSS_4
		ld		(ix),a
		ld		c,a
		ld		a,(ERRECENYX_BOSS_4_X)
		add		a,RATAS_MUERTE_X_MIN_OFFSET_BOSS_4
		cp		c
		jr		z,.PINTA_RATA_MUERTE_ERRECENYX_BOSS_4
		jr		c,.PINTA_RATA_MUERTE_ERRECENYX_BOSS_4

		ld		a,(ERRECENYX_BOSS_4_X)
		add		a,RATAS_MUERTE_X_MAX_OFFSET_BOSS_4
		ld		(ix),a
		jr		.PINTA_RATA_MUERTE_ERRECENYX_BOSS_4

.MUEVE_RATA_DERECHA_MUERTE_ERRECENYX_BOSS_4:

		add		a,RATAS_MUERTE_PASO_X_BOSS_4
		ld		(ix),a
		ld		c,a
		ld		a,(ERRECENYX_BOSS_4_X)
		add		a,RATAS_MUERTE_X_MAX_OFFSET_BOSS_4
		cp		c
		jr		nc,.PINTA_RATA_MUERTE_ERRECENYX_BOSS_4

		ld		a,(ERRECENYX_BOSS_4_X)
		add		a,RATAS_MUERTE_X_MIN_OFFSET_BOSS_4
		ld		(ix),a

.PINTA_RATA_MUERTE_ERRECENYX_BOSS_4:

		ld		a,RATAS_MUERTE_Y_BOSS_4
		ld		(de),a
		inc		de
		ld		a,(ix)
		ld		(de),a
		inc		de
		ld		a,b
		and		00000001b
		jr		nz,.PATRON_RATA_DERECHA_MUERTE_ERRECENYX_BOSS_4

.PATRON_RATA_IZQUIERDA_MUERTE_ERRECENYX_BOSS_4:

		ld		a,RATA_PATRON_IZQUIERDA_BOSS_4
		jr		.GUARDA_PATRON_RATA_MUERTE_ERRECENYX_BOSS_4

.PATRON_RATA_DERECHA_MUERTE_ERRECENYX_BOSS_4:

		ld		a,RATA_PATRON_DERECHA_BOSS_4

.GUARDA_PATRON_RATA_MUERTE_ERRECENYX_BOSS_4:

		ld		(de),a
		inc		de
		xor		a
		ld		(de),a
		inc		de

		inc		ix
		inc		iy
		inc		hl
		djnz	.BUCLE_MUEVE_RATAS_MUERTE_ERRECENYX_BOSS_4

		ld		hl,RATAS_MUERTE_ERRECENYX_ATRIBUTOS
		ld		de,RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_4
		ld		bc,RATAS_MUERTE_CANTIDAD_BOSS_4*4
		jp		PON_COLOR_2.sin_bc_impuesta

ESCAPA_RATAS_MUERTE_ERRECENYX_BOSS_4:

		call	MUEVE_RATAS_SALIDA_ERRECENYX_BOSS_4
		ld		a,RATAS_MUERTE_SALIDA_PAUSA_BOSS_4
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		ld		a,(RATAS_MUERTE_ERRECENYX_CONTADOR)
		or		a
		jr		nz,ESCAPA_RATAS_MUERTE_ERRECENYX_BOSS_4
		ret

MUEVE_RATAS_SALIDA_ERRECENYX_BOSS_4:

		xor		a
		ld		(RATAS_MUERTE_ERRECENYX_CONTADOR),a
		ld		de,RATAS_MUERTE_ERRECENYX_ATRIBUTOS
		ld		c,a

.BUCLE_MUEVE_RATAS_SALIDA_ERRECENYX_BOSS_4:

		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_ERRECENYX_ACTIVA
		add		hl,bc
		ld		a,(hl)
		pop		de
		or		a
		jr		z,.PINTA_RATA_OCULTA_SALIDA_ERRECENYX_BOSS_4

		ld		a,(RATAS_MUERTE_ERRECENYX_CONTADOR)
		inc		a
		ld		(RATAS_MUERTE_ERRECENYX_CONTADOR),a

		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_ERRECENYX_ESPERA
		add		hl,bc
		ld		a,(hl)
		dec		a
		ld		(hl),a
		pop		de
		jr		nz,.PINTA_RATA_ACTIVA_SALIDA_ERRECENYX_BOSS_4

		push	de
		ld		b,0
		ld		hl,BOSS_4_RATAS_MUERTE_VELOCIDAD
		add		hl,bc
		ld		a,(hl)
		ld		hl,RATAS_MUERTE_ERRECENYX_ESPERA
		add		hl,bc
		ld		(hl),a
		ld		hl,RATAS_MUERTE_ERRECENYX_X
		add		hl,bc
		ld		a,(hl)
		bit		0,c
		jr		nz,.MUEVE_RATA_DERECHA_SALIDA_ERRECENYX_BOSS_4

.MUEVE_RATA_IZQUIERDA_SALIDA_ERRECENYX_BOSS_4:

		cp		RATAS_MUERTE_PASO_X_BOSS_4
		jr		c,.MATA_RATA_SALIDA_ERRECENYX_BOSS_4
		sub		RATAS_MUERTE_PASO_X_BOSS_4
		ld		(hl),a
		or		a
		jr		z,.MATA_RATA_SALIDA_ERRECENYX_BOSS_4
		pop		de
		jr		.PINTA_RATA_ACTIVA_SALIDA_ERRECENYX_BOSS_4

.MUEVE_RATA_DERECHA_SALIDA_ERRECENYX_BOSS_4:

		add		a,RATAS_MUERTE_PASO_X_BOSS_4
		jr		c,.MATA_RATA_SALIDA_ERRECENYX_BOSS_4
		ld		(hl),a
		cp		255
		jr		z,.MATA_RATA_SALIDA_ERRECENYX_BOSS_4
		pop		de
		jr		.PINTA_RATA_ACTIVA_SALIDA_ERRECENYX_BOSS_4

.MATA_RATA_SALIDA_ERRECENYX_BOSS_4:

		ld		hl,RATAS_MUERTE_ERRECENYX_ACTIVA
		add		hl,bc
		xor		a
		ld		(hl),a
		ld		a,(RATAS_MUERTE_ERRECENYX_CONTADOR)
		dec		a
		ld		(RATAS_MUERTE_ERRECENYX_CONTADOR),a
		pop		de
		jr		.PINTA_RATA_OCULTA_SALIDA_ERRECENYX_BOSS_4

.PINTA_RATA_ACTIVA_SALIDA_ERRECENYX_BOSS_4:

		ld		a,RATAS_MUERTE_Y_BOSS_4
		ld		(de),a
		inc		de
		push	de
		ld		b,0
		ld		hl,RATAS_MUERTE_ERRECENYX_X
		add		hl,bc
		ld		a,(hl)
		pop		de
		ld		(de),a
		inc		de
		ld		a,c
		and		00000001b
		jr		nz,.PATRON_RATA_DERECHA_SALIDA_ERRECENYX_BOSS_4

.PATRON_RATA_IZQUIERDA_SALIDA_ERRECENYX_BOSS_4:

		ld		a,RATA_PATRON_IZQUIERDA_BOSS_4
		jr		.GUARDA_PATRON_RATA_SALIDA_ERRECENYX_BOSS_4

.PATRON_RATA_DERECHA_SALIDA_ERRECENYX_BOSS_4:

		ld		a,RATA_PATRON_DERECHA_BOSS_4
		jr		.GUARDA_PATRON_RATA_SALIDA_ERRECENYX_BOSS_4

.PINTA_RATA_OCULTA_SALIDA_ERRECENYX_BOSS_4:

		ld		a,RATAS_MUERTE_Y_OCULTA_BOSS_4
		ld		(de),a
		inc		de
		ld		a,RATAS_MUERTE_X_OCULTA_BOSS_4
		ld		(de),a
		inc		de
		xor		a

.GUARDA_PATRON_RATA_SALIDA_ERRECENYX_BOSS_4:

		ld		(de),a
		inc		de
		xor		a
		ld		(de),a
		inc		de

		inc		c
		ld		a,c
		cp		RATAS_MUERTE_CANTIDAD_BOSS_4
		jp		c,.BUCLE_MUEVE_RATAS_SALIDA_ERRECENYX_BOSS_4

		ld		hl,RATAS_MUERTE_ERRECENYX_ATRIBUTOS
		ld		de,RATAS_MUERTE_ATRIBUTOS_VRAM_BOSS_4
		ld		bc,RATAS_MUERTE_CANTIDAD_BOSS_4*4
		jp		PON_COLOR_2.sin_bc_impuesta

TIRA_FX_BOSS_4:

		call	PAGE_31_A_SEGMENT_2
		call	ayFX_INIT
		jp		PAGE_10_A_SEGMENT_2

MUERTE_DE_ERRECENYX_BOSS_4:
; paramos la música
		call	stpmus

; Nos aseguramos que el prota no está en modo transparente ni el fondo en colores varios
		ld		a,COLOR_ALEATORIO_SIN_CAMBIOS_BOSS_4
		ld		(COLOR_ALEATORIO),a
		xor		a
		ld		(INMUNE),a

; pequeña pausa
		ld		a,ERRECENYX_PAUSA_BOCA_BOSS_4
		call	BUCLE_PINTA_TILES.rutina_de_pausa

; limpiamos sprites
		xor		a
		ld		hl,SPRITES_ATRIBUTOS_VRAM_BOSS_4+ERRECENYX_LIMPIA_SPRITE_INICIAL_BOSS_4*4
		ld		bc,ERRECENYX_LIMPIA_SPRITES_CANT_BOSS_4*4
		call	FILVRM_RAM
		call	INICIALIZA_RATAS_MUERTE_ERRECENYX_BOSS_4
		call	ENTRAN_RATAS_MUERTE_ERRECENYX_BOSS_4


; animamos la muerte de AGONIX		
		ld		b,ERRECENYX_MUERTE_BUCLES_BOSS_4

.BUCLE_ANIMA_MUERTE_ERRECENYX_BOSS_4:

		push	bc
		
; audio de terremoto
		ld		a,ERRECENYX_MUERTE_FX_BOSS_4
		ld		c,ERRECENYX_MUERTE_FX_CANAL_BOSS_4
        call    PAGE_31_A_SEGMENT_2
		call	ayFX_INIT
        call   	PAGE_10_A_SEGMENT_2

		ld		ix,COPY_ANIMA_MUERTE_ERRECENYX_A_BUFFER_BOSS_4
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_4.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL
		ld		a,(ERRECENYX_BOSS_4_X)
		ld		(iy),a
		xor		a
		ld		(iy+1),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY

		ld		ix,COPY_ANIMA_MUERTE_ERRECENYX_DESDE_BUFFER_BOSS_4
		ld		iy,DATAS_COPY_RECUP_SCROLL
		call	RUTINA_BOSS_4.BUCLE_PINTA_DATAS
		ld		iy,DATAS_COPY_RECUP_SCROLL
		ld		a,(ERRECENYX_BOSS_4_X)
		ld		(iy+4),a
		xor		a
		ld		(iy+5),a
		ld		hl,DATAS_COPY_RECUP_SCROLL
		call	DOCOPY
		call	VDPREADY

		ld		b,RATAS_MUERTE_PASOS_ENTRE_COPY_BOSS_4

.BUCLE_RATAS_ENTRE_COPY_MUERTE_ERRECENYX_BOSS_4:

		push	bc
		call	MUEVE_RATAS_MUERTE_ERRECENYX_BOSS_4
		pop		bc
		djnz	.BUCLE_RATAS_ENTRE_COPY_MUERTE_ERRECENYX_BOSS_4

		ld		a,ERRECENYX_MUERTE_PAUSA_BOSS_4
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		pop		bc
		djnz	.BUCLE_ANIMA_MUERTE_ERRECENYX_BOSS_4

		call	ESCAPA_RATAS_MUERTE_ERRECENYX_BOSS_4
		call	PREPARA_VRAM_PARA_MUERTE_DEPH_EN_BOSS

TERMINANDO_LA_BATALLA_b4:

		include	"../AUDIOS/INICIA MUSICA_WIN.asm"

		ld		hl,TODOS_LOS_SPRITES
		call	PAGE_32_A_SEGMENT_2
		ld		de,PATRONES_SPRITES_VRAM_BOSS_4+DEPH_SALIDA_SPRITES_INICIO_BOSS_4*8*4
		ld		bc,DEPH_SALIDA_SPRITES_CANT_BOSS_4*8*4
		call	PON_COLOR_2.sin_bc_impuesta
		call	PAGE_10_A_SEGMENT_2
		call	VUELCA_DATOS_COLORES_DEPH_A_VRAM
		call	PAGE_10_A_SEGMENT_2

CAMINITO_A_PUERTA_b4:

		include	"../ANIMACIONES/PASEITO HASTA PUERTA.asm"		
SALUDO_b4:

		include	"../ANIMACIONES/SALUDO_GANA_FASE.asm"		

ULTIMO_DESPLAZAMIENTO_b4:

		include	"../ANIMACIONES/PASEITO DENTRO DE PUERTA.asm"	

VOLVEMOS_b4:

		jp		CARGA_SLOT_REGRESO_A_JUEGO

	include	"BOSS 4 DATA.asm"
