TABLA_MOVIMIENTO_PROYECTIL_ENEMIGO:

		dw		RETORNO
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_1
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_2
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_3
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_4
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_5
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_6
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_7
		dw		SECUENCIAS_DE_LOS_ENEMIGOS.PROYECTIL_8
		
TABLA_DE_SALIDA_SIN_CREAR_ENEMIGOS:


		dw		RETORNO
		dw		SACA_4
		dw		PRIMA_AF

TABLA_DE_TAMANO_DE_FASE:

		dw		0,403,349,403,468,421

TABLA_DE_ARMA_O_ENEMIGO_A_DEFINIR:

		dw	NUEVO_PROYECTIL.FLECHA									; 0
		dw	NUEVO_PROYECTIL.FLECHA									; 1
		dw	NUEVO_PROYECTIL.FLECHA									; 2
		dw	NUEVO_PROYECTIL.FUEGO									; 3
		dw	NUEVO_PROYECTIL.FUEGO									; 4
		dw	NUEVO_PROYECTIL.FUEGO									; 5
		dw	NUEVO_PROYECTIL.HACHA									; 6
		dw	NUEVO_PROYECTIL.HACHA									; 7
		dw	NUEVO_PROYECTIL.HACHA									; 8
		dw	UN_NUEVO_ENEMIGO.DEFINE_SKRULLEX 						; 9
		dw	COVIDS.DEFINE_COVID										; 10
		dw	COVIDS.DEFINE_COVID_CORTO_IZQUIERDA						; 11
		dw	COVIDS.DEFINE_COVID_CORTO_DERECHA						; 12
		dw	COVIDS.DEFINE_COVID_CORTO_CENTRO						; 13
		dw	SLIMES.DEFINE_SLIME_AZUL_BAJANDO						; 14
		dw	UN_NUEVO_ENEMIGO.DEFINE_MEGADEATH_CABEZA_E				; 15
		dw	UN_NUEVO_ENEMIGO.DEFINE_MEGADEATH_E						; 16
		dw	SLIMES.DEFINE_SLIME_AZUL_HACIA_DERECHA					; 17
		dw	SLIMES.DEFINE_SLIME_AZUL_QUIETO							; 18
        dw  UN_NUEVO_ENEMIGO.DEFINE_ALFONSERRIX_SO          		; 19 
		dw	SLIMES.DEFINE_SLIME_VERDE_BAJANDO						; 20
        dw  UN_NUEVO_ENEMIGO.DEFINE_ALFONSERRIX_SE          		; 21  
		dw	SLIMES.DEFINE_SLIME_AZUL_HACIA_IZQUIERDA				; 22
		dw	SLIMES.DEFINE_SLIME_VERDE_HACIA_IZQUIERDA				; 23
        dw  UN_NUEVO_ENEMIGO.DEFINE_ALFONSERRIX_NO          		; 24    
        dw  UN_NUEVO_ENEMIGO.DEFINE_ALFONSERRIX_NE          		; 25 
		dw	UN_NUEVO_ENEMIGO.DEFINE_CORAZON							; 26
		dw	UN_NUEVO_ENEMIGO.DEFINE_1_FINAL							; 27
		dw	SLIMES.DEFINE_SLIME_BLANCO								; 28
		dw	UN_NUEVO_ENEMIGO.DEFINE_ALFONSERRIX_SE_S4				; 29
		dw	UN_NUEVO_ENEMIGO.DEFINE_PROYECTIL_NORMAL				; 30
		dw	UN_NUEVO_ENEMIGO.DEFINE_ALFONSERRIX_SO_S4				; 31
		dw	UN_NUEVO_ENEMIGO.DEFINE_CHECK_POINT						; 32
		dw	UN_NUEVO_ENEMIGO.DEFINE_S								; 33
		dw	UN_NUEVO_ENEMIGO.DEFINE_T								; 34
		dw	UN_NUEVO_ENEMIGO.DEFINE_A								; 35
		dw	UN_NUEVO_ENEMIGO.DEFINE_G								; 36
		dw	UN_NUEVO_ENEMIGO.DEFINE_E								; 37
		dw	SLIMES.DEFINE_SLIME_FUEGO_QUIETO						; 38
		dw	UN_NUEVO_ENEMIGO.DEFINE_CORAZON_CONTENEDOR				; 39
		dw	UN_NUEVO_ENEMIGO.DEFINE_D_PREMIO						; 40
		dw	UN_NUEVO_ENEMIGO.DEFINE_E_PREMIO						; 41
		dw	UN_NUEVO_ENEMIGO.DEFINE_P_PREMIO						; 42
		dw	UN_NUEVO_ENEMIGO.DEFINE_H_PREMIO						; 43
		dw	COVIDS.DEFINE_COVID_ABAJO_IZQUIERDA						; 44
		dw  SLIMES.DEFINE_SLIME_FUEGO_HACIA_IZQUIERDA				; 45
		dw	UN_NUEVO_ENEMIGO.DEFINE_LETRAS_AVISO_PREMIO_D			; 46
		dw	UN_NUEVO_ENEMIGO.DEFINE_LETRAS_AVISO_PREMIO_E			; 47
		dw	UN_NUEVO_ENEMIGO.DEFINE_LETRAS_AVISO_PREMIO_P			; 48
		dw	UN_NUEVO_ENEMIGO.DEFINE_LETRAS_AVISO_PREMIO_H			; 49
		dw	ECTO_PALLERS.DEFINE_ECTO_PALLERS_CIRCLE					; 50
		dw	SLIMES.DEFINE_SLIME_FUEGO_RONDA							; 51
		dw	FIREWORKS.DEFINE_FIREWORKS								; 52
		dw	FIREWORKS.DEFINE_FIREWORKS_1							; 53
		dw	ECTO_PALLERS.DEFINE_ECTO_PALLERS_TOCA_HUEVOS			; 54
		dw	CORVELLINIS.DEFINE_CORVELLINI_DERECHA					; 55
		dw	CORVELLINIS.DEFINE_CORVELLINI_IZQUIERDA					; 56
		dw	UN_NUEVO_ENEMIGO.DEFINE_CAMINO_CORRECTO_O_INCORRECTO	; 57
		dw	GARGOLAS.DEFINE_GARGOLA 								; 58
		
TABLA_MOVIMIENTO_ALFONSERRYX:

        dw      SECUENCIAS_DE_LOS_ENEMIGOS.ALFONS_IZ_AB				; 22 - 0
        dw      SECUENCIAS_DE_LOS_ENEMIGOS.ALFONS_DE_AB				; 23 - 1
        dw      SECUENCIAS_DE_LOS_ENEMIGOS.ALFONS_IZ_AR				; 24 - 2
        dw      SECUENCIAS_DE_LOS_ENEMIGOS.ALFONS_DE_AR				; 25 - 3

TABLA_PAD_1:

			dw		CONTROL.sigue
			dw		CONTROL.resta_comun_y												; Se salta el punto intermedio de up porque no hay nada relevante allí
			dw		CONTROL.upright
			dw		CONTROL.right
			dw		CONTROL.rightdown
			dw		CONTROL.suma_comun_y												; Se salta el punto intermedio de down porque no hay nada relevante allí
			dw		CONTROL.downleft
			dw		CONTROL.left
			dw		CONTROL.leftup	

TABLA_TECLADO:

			dw		CONTROL.pad1
			dw		CONTROL.resta_comun_y												; Se salta el punto intermedio de up porque no hay nada relevante allí
			dw		CONTROL.upright
			dw		CONTROL.right
			dw		CONTROL.rightdown
			dw		CONTROL.suma_comun_y												; Se salta el punto intermedio de down porque no hay nada relevante allí
			dw		CONTROL.downleft
			dw		CONTROL.left
			dw		CONTROL.leftup			
