; Variables RAM dedicadas al proyectil local del boss 2

VIDA_ROCKAGER_BOSS_2:	#1
VIDA_DAVEANIX_BOSS_2:	#1

PROYECTIL_BOSS_2_X:		#1
PROYECTIL_BOSS_2_Y:		#1
PROYECTIL_BOSS_2_DIRECCION:	#1
PROYECTIL_BOSS_2_PASO_TABLA:	#1
PROYECTIL_BOSS_2_ESPERA:	#1
PROYECTIL_BOSS_2_SPRITE_ACTUAL:	#1
PROYECTIL_BOSS_2_SIGUIENTE_SPRITE:	#1
PROYECTIL_BOSS_2_SIGUIENTE_EMISOR:	#1
PROYECTIL_BOSS_2_PUNTERO_SPRITES_ACTIVOS:	#2
PROYECTIL_BOSS_2_DIRECCION_VRAM_ATRIBUTOS:	#2
PROYECTIL_BOSS_2_DIRECCION_VRAM_COLOR:	#2
COPIA_PROYECTIL_BOSS_2_X:	#1
COPIA_PROYECTIL_BOSS_2_Y:	#1
COPIA_PROYECTIL_BOSS_2_DIRECCION:	#1
COPIA_PROYECTIL_BOSS_2_PASO_TABLA:	#1
COPIA_PROYECTIL_BOSS_2_ESPERA:	#1
COPIA_PROYECTIL_BOSS_2_SPRITE_ACTUAL:	#1
COPIA_PROYECTIL_BOSS_2_SIGUIENTE_SPRITE:	#1
COPIA_PROYECTIL_BOSS_2_SIGUIENTE_EMISOR:	#1
COPIA_PROYECTIL_BOSS_2_PUNTERO_SPRITES_ACTIVOS:	#2
COPIA_PROYECTIL_BOSS_2_DIRECCION_VRAM_ATRIBUTOS:	#2
COPIA_PROYECTIL_BOSS_2_DIRECCION_VRAM_COLOR:	#2
PROYECTIL_BOSS_2_INDICE_ACTUAL:	#1
PROYECTILES_BOSS_2_X:	#8
PROYECTILES_BOSS_2_Y:	#8
PROYECTILES_BOSS_2_DIRECCION:	#8
PROYECTILES_BOSS_2_PASO_TABLA:	#8
