CINEMATICA_FINAL_FUENTE_Y_ORIGEN              equ     #0300+213
CINEMATICA_FINAL_LETRA_ANCHO                 equ     6
CINEMATICA_FINAL_LETRA_ALTO                  equ     6
CINEMATICA_FINAL_LETRA_ESPECIAL_BASE         equ     26
CINEMATICA_FINAL_LETRA_ESPECIALES_CANT       equ     16
CINEMATICA_FINAL_LETRA_ESPACIO               equ     CINEMATICA_FINAL_LETRA_ESPECIAL_BASE+CINEMATICA_FINAL_LETRA_ESPECIALES_CANT
CINEMATICA_FINAL_FUENTE_CARACTERES           equ     CINEMATICA_FINAL_LETRA_ESPACIO+1
CINEMATICA_FINAL_TEXTO_X                     equ     12
CINEMATICA_FINAL_TEXTO_Y_1                   equ     154
CINEMATICA_FINAL_TEXTO_Y_2                   equ     164
CINEMATICA_FINAL_TEXTO_Y_3                   equ     174
CINEMATICA_FINAL_TEXTO_Y_4                   equ     184
CINEMATICA_FINAL_PAUSA_LETRA                 equ     4
CINEMATICA_FINAL_PAUSA_FINAL                 equ     250
CINEMATICA_FINAL_CREDITOS_Y_INICIAL          equ     216
CINEMATICA_FINAL_CREDITOS_Y_CENTRO           equ     96
CINEMATICA_FINAL_CREDITOS_Y_MAX              equ     209
CINEMATICA_FINAL_CREDITOS_SEPARACION         equ     10
CINEMATICA_FINAL_CREDITOS_POST_CENTRO        equ     105
CINEMATICA_FINAL_CREDITOS_PAUSA_COPYRIGHT    equ     300
CINEMATICA_FINAL_CREDITOS_Y_ACTUAL           equ     CINEMATICA_FINAL_CREDITOS_Y_ACTUAL_RAM
CINEMATICA_FINAL_CREDITOS_FRAMES             equ     CINEMATICA_FINAL_CREDITOS_FRAMES_RAM
CINEMATICA_FINAL_CREDITOS_PAGE               equ     CINEMATICA_FINAL_CREDITOS_PAGE_RAM
CINEMATICA_FINAL_CREDITOS_TOTAL              equ     72
CINEMATICA_FINAL_CREDITOS_SIN_COPYRIGHT      equ     CINEMATICA_FINAL_CREDITOS_TOTAL-1
CINEMATICA_FINAL_CREDITOS_FRAMES_COPYRIGHT   equ     120+(CINEMATICA_FINAL_CREDITOS_SIN_COPYRIGHT*CINEMATICA_FINAL_CREDITOS_SEPARACION)


COMIENZA_CINEMATICA_FINAL:	

    	di
		ld		a,#C9
		ld		(HTIMI),a
		ld		(HKEYI),a

		ld		sp,0xE500
		ld 		a,(RG0SAV)
		and		11101111B
		ld		(RG0SAV),a
		ld		b,a
		ld		c,0
		call	WRTVDP_EN_RAM

		call	PAGE_10_A_SEGMENT_2

PRIMEROS_PASOS:

		call	DISSCR_RAM

		ld		a,5
		call	CHGMOD

		call	DISSCR_RAM

		; Limpiamos VRAM completa para no arrastrar restos de otras fases.

		xor		a
		ld		hl,#0000
		ld		bc,#ffff
		call	FILVRM_RAM

		; Pagina visible = 0.

		xor		a
		call	SETPAGE

		; Cargamos fuente en page 3 y las cuatro fotos finales:
		; page 1 = fotos 5/6
		; page 2 = fotos 7/8
		; page 3 = fuente del menu para escribir textos

		call	CARGA_GRAFICOS_CINEMATICA_FINAL
        call    INICIA_MUSICA_CINEMATICA_FINAL
        jp      CINEMATICA_FINAL


INICIA_MUSICA_CINEMATICA_FINAL:

		call	stpmus

		ld		a,73
		ld		(MUSICA_BEST_ON),a

        ld      a,73
        call    CHANGE_BANK_2

		ld		hl,M_FINAL
		ld		(MUSIC_ON),hl

		call	INICIAMOS_MUSICA

		di
		call	strmus

		; strmus instala musint directamente en HTIMI.
		; Para esta cinematica necesitamos envolverla para forzar page 39.

		call	INSTALA_INTERRUPCION_MUSICA_CINEMATICA_FINAL
		ei

		call	PAGE_10_A_SEGMENT_2

		ret


INSTALA_INTERRUPCION_MUSICA_CINEMATICA_FINAL:

		ld		a,#C3
		ld		(HTIMI),a
		ld		hl,INTERRUPCION_MUSICA_CINEMATICA_FINAL
		ld		(HTIMI+1),hl
		ret


INTERRUPCION_MUSICA_CINEMATICA_FINAL:

		ld		a,(DIRPA2)
		push	af
		ld		a,73
		ld		(DIRPA2),a

		call	musint

		pop		af
		ld		(DIRPA2),a

		ret


CINEMATICA_FINAL:

		xor		a
		call	SETPAGE

		ld		hl,DATOS_COPY_CINEMATICA_FINAL_5
		ld		ix,TEXTO_CINEMATICA_FINAL_1
		call	EJECUTA_BLOQUE_CINEMATICA_FINAL_5_6

		ld		hl,DATOS_COPY_CINEMATICA_FINAL_6
		ld		ix,TEXTO_CINEMATICA_FINAL_2
		call	EJECUTA_BLOQUE_CINEMATICA_FINAL_5_6

		ld		hl,DATOS_COPY_CINEMATICA_FINAL_7
		ld		ix,TEXTO_CINEMATICA_FINAL_3
		call	EJECUTA_BLOQUE_CINEMATICA_FINAL_7_8

		ld		hl,DATOS_COPY_CINEMATICA_FINAL_8
		ld		ix,TEXTO_CINEMATICA_FINAL_4
		call	EJECUTA_BLOQUE_CINEMATICA_FINAL_7_8

		call	CREDITOS_CINEMATICA_FINAL

		jp		NOS_VAMOS_AL_INICIO_DEL_TODO


EJECUTA_BLOQUE_CINEMATICA_FINAL_5_6:

		push	hl
		push	ix

		call	PONE_PRIMERA_PALETA_CINEMATICA_FINAL_5_6
		call	LIMPIA_PAGE_0_CINEMATICA_FINAL

		pop		ix
		pop		hl

		push	ix
		call	DOCOPY
		call	VDPREADY
		call	ENASCR_RAM

		call	FADE_IN_CINEMATICA_FINAL_5_6
		call	PONE_PALETA_FINAL_CINEMATICA_FINAL_5_6

		pop		ix
		push	ix
		call	PINTA_CUATRO_FRASES_CINEMATICA_FINAL

		ld		b,CINEMATICA_FINAL_PAUSA_FINAL
		call	ESPERA_CINEMATICA_FINAL_B

		call	FADE_OUT_CINEMATICA_FINAL_5_6

		pop		ix
		ret


EJECUTA_BLOQUE_CINEMATICA_FINAL_7_8:

		push	hl
		push	ix

		call	PONE_PRIMERA_PALETA_CINEMATICA_FINAL_7_8
		call	LIMPIA_PAGE_0_CINEMATICA_FINAL

		pop		ix
		pop		hl

		push	ix
		call	DOCOPY
		call	VDPREADY
		call	ENASCR_RAM

		call	FADE_IN_CINEMATICA_FINAL_7_8
		call	PONE_PALETA_FINAL_CINEMATICA_FINAL_7_8

		pop		ix
		push	ix
		call	PINTA_CUATRO_FRASES_CINEMATICA_FINAL

		ld		b,CINEMATICA_FINAL_PAUSA_FINAL
		call	ESPERA_CINEMATICA_FINAL_B

		call	FADE_OUT_CINEMATICA_FINAL_7_8

		pop		ix
		ret


PONE_PRIMERA_PALETA_CINEMATICA_FINAL_5_6:

		ld		hl,FADE_IN_DATOS_CINEMATICA_FINAL_5_6
		jp		SETPALETE_CINEMATICA_FINAL


PONE_PRIMERA_PALETA_CINEMATICA_FINAL_7_8:

		ld		hl,FADE_IN_DATOS_CINEMATICA_FINAL_7_8
		jp		SETPALETE_CINEMATICA_FINAL


PONE_PALETA_FINAL_CINEMATICA_FINAL_5_6:

		ld		hl,PALETA_DATOS_CINEMATICA_FINAL_5_6
		jp		SETPALETE_CINEMATICA_FINAL


PONE_PALETA_FINAL_CINEMATICA_FINAL_7_8:

		ld		hl,PALETA_DATOS_CINEMATICA_FINAL_7_8
		jp		SETPALETE_CINEMATICA_FINAL


FADE_IN_CINEMATICA_FINAL_5_6:

		ld		hl,FADE_IN_DATOS_CINEMATICA_FINAL_5_6+32
		ld		e,6
		jp		BUCLE_FADE_CINEMATICA_FINAL


FADE_IN_CINEMATICA_FINAL_7_8:

		ld		hl,FADE_IN_DATOS_CINEMATICA_FINAL_7_8+32
		ld		e,6
		jp		BUCLE_FADE_CINEMATICA_FINAL


FADE_OUT_CINEMATICA_FINAL_5_6:

		ld		hl,FADE_OUT_DATOS_CINEMATICA_FINAL_5_6
		ld		e,7
		jp		BUCLE_FADE_CINEMATICA_FINAL


FADE_OUT_CINEMATICA_FINAL_7_8:

		ld		hl,FADE_OUT_DATOS_CINEMATICA_FINAL_7_8
		ld		e,7
		jp		BUCLE_FADE_CINEMATICA_FINAL


BUCLE_FADE_CINEMATICA_FINAL:

		call	SETPALETE_CINEMATICA_FINAL
		push	hl
		push	de
		ld		b,6
		call	ESPERA_CINEMATICA_FINAL_B
		pop		de
		pop		hl

		dec		e
		jp		nz,BUCLE_FADE_CINEMATICA_FINAL
		or		a
		ret


SETPALETE_CINEMATICA_FINAL:

		xor		a
		di
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		ld		c,#9A
[32]	outi
		ei
		ret


PINTA_CUATRO_FRASES_CINEMATICA_FINAL:

		push	ix
		pop		hl

		ld		de,CINEMATICA_FINAL_TEXTO_Y_1
		call	PINTA_FRASE_CINEMATICA_FINAL_DESDE_TABLA

		ld		de,CINEMATICA_FINAL_TEXTO_Y_2
		call	PINTA_FRASE_CINEMATICA_FINAL_DESDE_TABLA

		ld		de,CINEMATICA_FINAL_TEXTO_Y_3
		call	PINTA_FRASE_CINEMATICA_FINAL_DESDE_TABLA

		ld		de,CINEMATICA_FINAL_TEXTO_Y_4
		jp		PINTA_FRASE_CINEMATICA_FINAL_DESDE_TABLA


PINTA_FRASE_CINEMATICA_FINAL_DESDE_TABLA:

		ld		c,(hl)
		inc		hl
		ld		b,(hl)
		inc		hl
		push	hl
		push	bc
		pop		ix
		ld		hl,CINEMATICA_FINAL_TEXTO_X
		call	PINTA_TEXTO_CINEMATICA_FINAL_FORMA_3
		pop		hl
		ret


PINTA_TEXTO_CINEMATICA_FINAL_FORMA_3:

		ld		a,(ix+0)
		or		a
		ret		z

		push	de
		push	hl
		push	ix
		call	PINTA_LETRA_CINEMATICA_FINAL_EN_DESTINO
		pop		ix
		pop		hl
		pop		de

		call	ESPERA_LETRA_CINEMATICA_FINAL

		ld		bc,CINEMATICA_FINAL_LETRA_ANCHO
		add		hl,bc
		inc		ix
		jp		PINTA_TEXTO_CINEMATICA_FINAL_FORMA_3


PINTA_LETRA_CINEMATICA_FINAL_EN_DESTINO:

		push	hl
		push	de
		call	CALCULA_ORIGEN_X_LETRA_CINEMATICA_FINAL
		ld		ix,DATOS_DEL_TILE_PARA_COPY
		ld		(ix),l
		ld		(ix+1),h
		ld		hl,CINEMATICA_FINAL_FUENTE_Y_ORIGEN
		ld		(ix+2),l
		ld		(ix+3),h
		pop		hl
		ld		(ix+6),l
		ld		(ix+7),h
		pop		hl
		ld		(ix+4),l
		ld		(ix+5),h
		ld		(ix+8),CINEMATICA_FINAL_LETRA_ANCHO
		ld		(ix+9),0
		ld		(ix+10),CINEMATICA_FINAL_LETRA_ALTO
		ld		(ix+11),0
		ld		(ix+12),#00
		ld		(ix+13),#00
		ld		(ix+14),11010000b
		call	HL_DATOS_DEL_COPY
		jp		VDPREADY


CALCULA_ORIGEN_X_LETRA_CINEMATICA_FINAL:

		cp		97
		jr		c,.MIRA_MAYUSCULAS
		cp		123
		jr		nc,.MIRA_MAYUSCULAS
		sub		32

.MIRA_MAYUSCULAS:

		cp		65
		jr		c,.MIRA_ESPECIALES
		cp		91
		jr		nc,.MIRA_ESPECIALES
		sub		65
		jr		.MULTIPLICA

.MIRA_ESPECIALES:

		ld		hl,TABLA_ESPECIALES_CINEMATICA_FINAL
		ld		b,CINEMATICA_FINAL_FUENTE_CARACTERES-CINEMATICA_FINAL_LETRA_ESPECIAL_BASE
		ld		c,CINEMATICA_FINAL_LETRA_ESPECIAL_BASE

.BUCLE_ESPECIALES:

		cp		(hl)
		jr		z,.ES_ESPECIAL
		inc		hl
		inc		c
		djnz	.BUCLE_ESPECIALES
		jr		.ES_ESPACIO

.ES_ESPECIAL:

		ld		a,c
		jr		.MULTIPLICA

.ES_ESPACIO:

		ld		a,CINEMATICA_FINAL_LETRA_ESPACIO

.MULTIPLICA:

		ld		e,a
		ld		d,0
		ld		h,d
		ld		l,e
		add		hl,hl
		add		hl,de
		add		hl,hl
		ret


ESPERA_LETRA_CINEMATICA_FINAL:

		ld		b,CINEMATICA_FINAL_PAUSA_LETRA


ESPERA_CINEMATICA_FINAL_B:

		halt
		djnz	ESPERA_CINEMATICA_FINAL_B
		or		a
		ret


LIMPIA_PAGE_0_CINEMATICA_FINAL:

		ld		hl,DATOS_NEGRO_PAGE_0_CINEMATICA_FINAL
		call	DOCOPY
		jp		VDPREADY


CREDITOS_CINEMATICA_FINAL:

		call    stpmus

		ld		a,73
		ld		(MUSICA_BEST_ON),a

        ld      a,73
        call    CHANGE_BANK_2

		ld		hl,M_CREDITS
		ld		(MUSIC_ON),hl
		
		call    INICIAMOS_MUSICA

		di
		call	strmus

		call	PREPARA_CREDITOS_CINEMATICA_FINAL

		ld		hl,CINEMATICA_FINAL_CREDITOS_Y_INICIAL
		ld		(CINEMATICA_FINAL_CREDITOS_Y_ACTUAL),hl

		ld		hl,CINEMATICA_FINAL_CREDITOS_FRAMES_COPYRIGHT
		ld		(CINEMATICA_FINAL_CREDITOS_FRAMES),hl

.BUCLE_HASTA_COPYRIGHT:

		ld		b,CINEMATICA_FINAL_CREDITOS_TOTAL
		call	PINTA_FRAME_CREDITOS_CINEMATICA_FINAL
		call	AVANZA_CREDITOS_CINEMATICA_FINAL
		call	DECREMENTA_FRAMES_CREDITOS_CINEMATICA_FINAL
		jr		nz,.BUCLE_HASTA_COPYRIGHT

		ld		hl,CINEMATICA_FINAL_CREDITOS_POST_CENTRO
		ld		(CINEMATICA_FINAL_CREDITOS_FRAMES),hl

.BUCLE_TEXTO_SALIENDO:

		ld		b,CINEMATICA_FINAL_CREDITOS_SIN_COPYRIGHT
		call	PINTA_FRAME_CREDITOS_COPYRIGHT_FIJO
		call	AVANZA_CREDITOS_CINEMATICA_FINAL
		call	DECREMENTA_FRAMES_CREDITOS_CINEMATICA_FINAL
		jr		nz,.BUCLE_TEXTO_SALIENDO

		ld		b,0
		call	PINTA_FRAME_CREDITOS_COPYRIGHT_FIJO

		ld		b,250
		call	ESPERA_CINEMATICA_FINAL_B
		ld		b,50
		call	ESPERA_CINEMATICA_FINAL_B

		jp		FADE_OUT_COLOR_15_CREDITOS_CINEMATICA_FINAL


PREPARA_CREDITOS_CINEMATICA_FINAL:

		call	DISSCR_RAM

		xor		a
		call	SETPAGE
		ld		a,1
		ld		(CINEMATICA_FINAL_CREDITOS_PAGE),a

		ld		hl,DATOS_NEGRO_PAGE_0_CINEMATICA_FINAL
		call	DOCOPY
		call	VDPREADY

		ld		hl,DATOS_NEGRO_PAGE_1_CINEMATICA_FINAL
		call	DOCOPY
		call	VDPREADY

		call	PONE_PALETA_NEGRA_CREDITOS_CINEMATICA_FINAL
		call	PONE_COLOR_15_BLANCO_CREDITOS_CINEMATICA_FINAL

		jp		ENASCR_RAM


PINTA_FRAME_CREDITOS_COPYRIGHT_FIJO:

		push	bc
		call	LIMPIA_PAGE_BUFFER_CREDITOS_CINEMATICA_FINAL
		pop		bc

		ld		hl,TABLA_CREDITOS_CINEMATICA_FINAL
		ld		de,(CINEMATICA_FINAL_CREDITOS_Y_ACTUAL)
		call	PINTA_LINEAS_CREDITOS_CINEMATICA_FINAL

		ld		ix,TEXTO_CREDITO_COPYRIGHT
		ld		de,CINEMATICA_FINAL_CREDITOS_Y_CENTRO

		ld		a,(CINEMATICA_FINAL_CREDITOS_PAGE)
		or		a
		jr		z,.PAGINA_0
		inc		d

.PAGINA_0:

		call	PINTA_LINEA_CREDITOS_CENTRADA
		call	VDPREADY

		ld		a,(CINEMATICA_FINAL_CREDITOS_PAGE)
		call	SETPAGE

		halt

		ld		a,(CINEMATICA_FINAL_CREDITOS_PAGE)
		xor		1
		ld		(CINEMATICA_FINAL_CREDITOS_PAGE),a

		ret


PINTA_FRAME_CREDITOS_CINEMATICA_FINAL:

		push	bc
		call	LIMPIA_PAGE_BUFFER_CREDITOS_CINEMATICA_FINAL
		pop		bc

		ld		hl,TABLA_CREDITOS_CINEMATICA_FINAL
		ld		de,(CINEMATICA_FINAL_CREDITOS_Y_ACTUAL)
		call	PINTA_LINEAS_CREDITOS_CINEMATICA_FINAL

		call	VDPREADY

		ld		a,(CINEMATICA_FINAL_CREDITOS_PAGE)
		call	SETPAGE

		halt

		ld		a,(CINEMATICA_FINAL_CREDITOS_PAGE)
		xor		1
		ld		(CINEMATICA_FINAL_CREDITOS_PAGE),a

		ret


LIMPIA_PAGE_BUFFER_CREDITOS_CINEMATICA_FINAL:

		ld		a,(CINEMATICA_FINAL_CREDITOS_PAGE)
		or		a
		jr		nz,.PAGE_1

		ld		hl,DATOS_NEGRO_PAGE_0_CINEMATICA_FINAL
		jp		DOCOPY

.PAGE_1:

		ld		hl,DATOS_NEGRO_PAGE_1_CINEMATICA_FINAL
		jp		DOCOPY


PINTA_LINEAS_CREDITOS_CINEMATICA_FINAL:

		ld		a,b

.BUCLE:

		or		a
		ret		z

		push	af

		ld		c,(hl)
		inc		hl
		ld		b,(hl)
		inc		hl

		push	hl
		push	de

		ld		a,d
		or		a
		jr		nz,.NO_PINTA

		ld		a,e
		cp		CINEMATICA_FINAL_CREDITOS_Y_MAX+1
		jr		nc,.NO_PINTA

		push	bc
		pop		ix

		ld		d,0
		ld		a,(CINEMATICA_FINAL_CREDITOS_PAGE)
		or		a
		jr		z,.PAGINA_0
		inc		d

.PAGINA_0:

		call	PINTA_LINEA_CREDITOS_CENTRADA

.NO_PINTA:

		pop		de
		ld		hl,CINEMATICA_FINAL_CREDITOS_SEPARACION
		add		hl,de
		ex		de,hl

		pop		hl
		pop		af
		dec		a
		jr		.BUCLE


PINTA_LINEA_CREDITOS_CENTRADA:

		push	de
		push	ix
		call	CALCULA_X_CENTRADA_CREDITOS_CINEMATICA_FINAL
		pop		ix
		pop		de
		jp		PINTA_TEXTO_CREDITOS_CINEMATICA_FINAL


CALCULA_X_CENTRADA_CREDITOS_CINEMATICA_FINAL:

		push	ix
		ld		b,0

.BUCLE:

		ld		a,(ix+0)
		or		a
		jr		z,.FIN
		inc		b
		inc		ix
		jr		.BUCLE

.FIN:

		pop		ix

		ld		a,b
		add		a,a
		add		a,b
		ld		c,a
		ld		a,128
		sub		c
		ld		l,a
		ld		h,0
		ret


PINTA_TEXTO_CREDITOS_CINEMATICA_FINAL:

		ld		a,(ix+0)
		or		a
		ret		z

		push	de
		push	hl
		push	ix
		call	PINTA_LETRA_CINEMATICA_FINAL_EN_DESTINO
		pop		ix
		pop		hl
		pop		de

		ld		bc,CINEMATICA_FINAL_LETRA_ANCHO
		add		hl,bc
		inc		ix
		jp		PINTA_TEXTO_CREDITOS_CINEMATICA_FINAL


AVANZA_CREDITOS_CINEMATICA_FINAL:

		ld		hl,(CINEMATICA_FINAL_CREDITOS_Y_ACTUAL)
		dec		hl
		ld		(CINEMATICA_FINAL_CREDITOS_Y_ACTUAL),hl
		ret


DECREMENTA_FRAMES_CREDITOS_CINEMATICA_FINAL:

		ld		hl,(CINEMATICA_FINAL_CREDITOS_FRAMES)
		dec		hl
		ld		(CINEMATICA_FINAL_CREDITOS_FRAMES),hl
		ld		a,h
		or		l
		ret


PONE_PALETA_NEGRA_CREDITOS_CINEMATICA_FINAL:

		ld		hl,PALETA_NEGRA_CREDITOS_CINEMATICA_FINAL
		jp		SETPALETE_CINEMATICA_FINAL


PONE_COLOR_15_BLANCO_CREDITOS_CINEMATICA_FINAL:

		ld		hl,COLOR_15_CREDITOS_BLANCO
		jp		PONE_COLOR_15_CREDITOS_DESDE_HL


FADE_OUT_COLOR_15_CREDITOS_CINEMATICA_FINAL:

		ld		hl,FADE_OUT_COLOR_15_CREDITOS
		ld		e,8

.BUCLE:

		call	PONE_COLOR_15_CREDITOS_DESDE_HL
		push	hl
		push	de
		ld		b,8
		call	ESPERA_CINEMATICA_FINAL_B
		pop		de
		pop		hl

		dec		e
		jr		nz,.BUCLE

		ret


PONE_COLOR_15_CREDITOS_DESDE_HL:

		ld		a,15
		di
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		ld		c,#9A
		outi
		outi
		ei
		ret


CARGA_GRAFICOS_CINEMATICA_FINAL:

		; Primero cargamos la imagen del menu en page 1 y la copiamos a page 3.
		; La necesitamos solo como banco oculto de fuente para escribir texto.

		call	CARGA_FUENTE_CINEMATICA_FINAL_EN_PAGE_1
		ld		hl,DATOS_COPY_CINEMATICA_FINAL_PAGE_1_A_PAGE_3
		call	DOCOPY
		call	VDPREADY

		; Despues cargamos las fotos 7/8 en page 1 y las preservamos en page 2.

		call	CARGA_GRAFICOS_CINEMATICA_7_8_EN_PAGE_1
		ld		hl,DATOS_COPY_CINEMATICA_FINAL_PAGE_1_A_PAGE_2
		call	DOCOPY
		call	VDPREADY

		; Finalmente cargamos las fotos 5/6 en page 1.

		jp		CARGA_GRAFICOS_CINEMATICA_5_6_EN_PAGE_1


CARGA_FUENTE_CINEMATICA_FINAL_EN_PAGE_1:

		di
		ld		a,4
		ld		(DIRPA2),a

		ld		hl,PANTALLA_DE_PRESENTACION_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,5
		ld		(DIRPA2),a

		ld		hl,PANTALLA_DE_PRESENTACION_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret


CARGA_GRAFICOS_CINEMATICA_7_8_EN_PAGE_1:

		di
		ld		a,6
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_7_8_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,66
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_7_8_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret


CARGA_GRAFICOS_CINEMATICA_5_6_EN_PAGE_1:

		di
		ld		a,7
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_5_6_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,8
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_5_6_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret


NOS_VAMOS_AL_INICIO_DEL_TODO:

        call    STOP_MUSICA
        jp		MENU

STOP_MUSICA:

		call	stpmus

		xor		a
		ld		(MUSICA_BEST_ON),a

		call	PAGE_10_A_SEGMENT_2

		ret

DATOS_COPY_CINEMATICA_FINAL_PAGE_1_A_PAGE_2:

		dw		#0000,#0100
		dw		#0000,#0200
		dw		#0100,#0100
		db		#00,#00,10010000b


DATOS_COPY_CINEMATICA_FINAL_PAGE_1_A_PAGE_3:

		dw		#0000,#0100
		dw		#0000,#0300
		dw		#0100,#0100
		db		#00,#00,10010000b


DATOS_NEGRO_PAGE_0_CINEMATICA_FINAL:

		; Borra solo la zona visible util de page 0.
		; No baja hasta Y=232/#7400 ni Y=240/#7800.

		dw		#0000,#0000
		dw		#0000,#0000
		dw		#0100,#00D5
		db		#00,#00,11000000b


DATOS_NEGRO_PAGE_1_CINEMATICA_FINAL:

		dw		#0000,#0100
		dw		#0000,#0100
		dw		#0100,#00D5
		db		#00,#00,11000000b


DATOS_COPY_CINEMATICA_FINAL_5:

		; Foto 1: page 1, desde 0,0 hasta 255,99.
		; Destino: page 0, 0,0.

		dw		#0000,#0100
		dw		#0000,#0000
		dw		#0100,#0064
		db		#00,#00,10010000b


DATOS_COPY_CINEMATICA_FINAL_6:

		; Foto 2: page 1, desde 0,100 hasta 255,199.
		; Destino: page 0, 0,0.

		dw		#0000,#0100+100
		dw		#0000,#0000
		dw		#0100,#0064
		db		#00,#00,10010000b


DATOS_COPY_CINEMATICA_FINAL_7:

		; Foto 3: page 2, desde 0,0 hasta 255,99.
		; Destino: page 0, 0,0.

		dw		#0000,#0200
		dw		#0000,#0000
		dw		#0100,#0064
		db		#00,#00,10010000b


DATOS_COPY_CINEMATICA_FINAL_8:

		; Foto 4: page 2, desde 0,100 hasta 255,199.
		; Destino: page 0, 0,0.

		dw		#0000,#0200+100
		dw		#0000,#0000
		dw		#0100,#0064
		db		#00,#00,10010000b


TEXTO_CINEMATICA_FINAL_1:

		dw		TEXTO_CINEMATICA_FINAL_1_1
		dw		TEXTO_CINEMATICA_FINAL_1_2
		dw		TEXTO_CINEMATICA_FINAL_1_3
		dw		TEXTO_CINEMATICA_FINAL_1_4


TEXTO_CINEMATICA_FINAL_2:

		dw		TEXTO_CINEMATICA_FINAL_2_1
		dw		TEXTO_CINEMATICA_FINAL_2_2
		dw		TEXTO_CINEMATICA_FINAL_2_3
		dw		TEXTO_CINEMATICA_FINAL_2_4


TEXTO_CINEMATICA_FINAL_3:

		dw		TEXTO_CINEMATICA_FINAL_3_1
		dw		TEXTO_CINEMATICA_FINAL_3_2
		dw		TEXTO_CINEMATICA_FINAL_3_3
		dw		TEXTO_CINEMATICA_FINAL_3_4


TEXTO_CINEMATICA_FINAL_4:

		dw		TEXTO_CINEMATICA_FINAL_4_1
		dw		TEXTO_CINEMATICA_FINAL_4_2
		dw		TEXTO_CINEMATICA_FINAL_4_3
		dw		TEXTO_CINEMATICA_FINAL_4_4


TEXTO_CINEMATICA_FINAL_1_1:
		db		"dEPH se lanzo a hacer pooldance.",0
TEXTO_CINEMATICA_FINAL_1_2:
		db		"era su ilusion desde pequeño y",0
TEXTO_CINEMATICA_FINAL_1_3:
		db		"ahora que ya no tenia obligaciones",0
TEXTO_CINEMATICA_FINAL_1_4:
		db		"podia cumplir su verdadero sueño.",0


TEXTO_CINEMATICA_FINAL_2_1:
		db		"Alli conocio a alguien que le ",0
TEXTO_CINEMATICA_FINAL_2_2:
		db		"marco profundamente.",0
TEXTO_CINEMATICA_FINAL_2_3:
		db		"sobretodo la garganta",0
TEXTO_CINEMATICA_FINAL_2_4:
		db		"y los dientes.",0


TEXTO_CINEMATICA_FINAL_3_1:
		db		"construyo una vida con ese ",0
TEXTO_CINEMATICA_FINAL_3_2:
		db		"desconocido. se convirtio",0
TEXTO_CINEMATICA_FINAL_3_3:
		db		"en el perfecto amo de casa",0
TEXTO_CINEMATICA_FINAL_3_4:
		db		"hasta que .....",0


TEXTO_CINEMATICA_FINAL_4_1:
		db		"Se quedo embarazado del",0
TEXTO_CINEMATICA_FINAL_4_2:
		db		"desconocido.",0
TEXTO_CINEMATICA_FINAL_4_3:
		db		"Ese hombre no era otro que",0
TEXTO_CINEMATICA_FINAL_4_4:
		db		"su creador: Manuel dopico.",0


TABLA_ESPECIALES_CINEMATICA_FINAL:

		db		"-/()1234567890%."


TABLA_CREDITOS_CINEMATICA_FINAL:

		dw		TEXTO_CREDITO_001
		dw		TEXTO_CREDITO_002
		dw		TEXTO_CREDITO_003
		dw		TEXTO_CREDITO_004
		dw		TEXTO_CREDITO_005
		dw		TEXTO_CREDITO_006
		dw		TEXTO_CREDITO_007
		dw		TEXTO_CREDITO_008
		dw		TEXTO_CREDITO_009
		dw		TEXTO_CREDITO_010
		dw		TEXTO_CREDITO_011
		dw		TEXTO_CREDITO_012
		dw		TEXTO_CREDITO_013
		dw		TEXTO_CREDITO_014
		dw		TEXTO_CREDITO_015
		dw		TEXTO_CREDITO_016
		dw		TEXTO_CREDITO_017
		dw		TEXTO_CREDITO_018
		dw		TEXTO_CREDITO_019
		dw		TEXTO_CREDITO_020
		dw		TEXTO_CREDITO_021
		dw		TEXTO_CREDITO_022
		dw		TEXTO_CREDITO_023
		dw		TEXTO_CREDITO_024
		dw		TEXTO_CREDITO_025
		dw		TEXTO_CREDITO_026
		dw		TEXTO_CREDITO_027
		dw		TEXTO_CREDITO_028
		dw		TEXTO_CREDITO_029
		dw		TEXTO_CREDITO_030
		dw		TEXTO_CREDITO_031
		dw		TEXTO_CREDITO_032
		dw		TEXTO_CREDITO_033
		dw		TEXTO_CREDITO_034
		dw		TEXTO_CREDITO_035
		dw		TEXTO_CREDITO_036
		dw		TEXTO_CREDITO_037
		dw		TEXTO_CREDITO_038
		dw		TEXTO_CREDITO_039
		dw		TEXTO_CREDITO_040
		dw		TEXTO_CREDITO_041
		dw		TEXTO_CREDITO_042
		dw		TEXTO_CREDITO_043
		dw		TEXTO_CREDITO_044
		dw		TEXTO_CREDITO_045
		dw		TEXTO_CREDITO_046
		dw		TEXTO_CREDITO_047
		dw		TEXTO_CREDITO_048
		dw		TEXTO_CREDITO_049
		dw		TEXTO_CREDITO_050
		dw		TEXTO_CREDITO_051
		dw		TEXTO_CREDITO_052
		dw		TEXTO_CREDITO_053
		dw		TEXTO_CREDITO_054
		dw		TEXTO_CREDITO_055
		dw		TEXTO_CREDITO_056
		dw		TEXTO_CREDITO_057
		dw		TEXTO_CREDITO_058
		dw		TEXTO_CREDITO_059
		dw		TEXTO_CREDITO_060
		dw		TEXTO_CREDITO_061
		dw		TEXTO_CREDITO_062
		dw		TEXTO_CREDITO_063
		dw		TEXTO_CREDITO_064
		dw		TEXTO_CREDITO_065
		dw		TEXTO_CREDITO_066
		dw		TEXTO_CREDITO_067
		dw		TEXTO_CREDITO_068
		dw		TEXTO_CREDITO_069
		dw		TEXTO_CREDITO_070
		dw		TEXTO_CREDITO_071

		dw		TEXTO_CREDITO_COPYRIGHT

TEXTO_CREDITO_001:	db		"A DIGITAL MOAI PRODUCTION",0
TEXTO_CREDITO_002:	db		0
TEXTO_CREDITO_003:	db		0
TEXTO_CREDITO_004:	db		"PROJECT DIRECTION - PHASE DESIGN",0
TEXTO_CREDITO_005:	db		"STORY SCRIPT - LEVEL DESIGN",0
TEXTO_CREDITO_006:	db		"PIXEL ART - MUSIC COMPOS.",0
TEXTO_CREDITO_007:	db		0
TEXTO_CREDITO_008:	db		"MANUEL DOPICO",0
TEXTO_CREDITO_009:	db		0
TEXTO_CREDITO_010:	db		0
TEXTO_CREDITO_011:	db		"PROGRAMMING - SPRITES",0
TEXTO_CREDITO_012:	db		"PIXEL ART CORRECTIONS - SOUND EFFECTS",0
TEXTO_CREDITO_013:	db		0
TEXTO_CREDITO_014:	db		"BENJAMIN MIGUEL",0
TEXTO_CREDITO_015:	db		0
TEXTO_CREDITO_016:	db		0
TEXTO_CREDITO_017:	db		"GRAPHICS",0
TEXTO_CREDITO_018:	db		0
TEXTO_CREDITO_019:	db		"LUCAS SERA PIAO",0
TEXTO_CREDITO_020:	db		0
TEXTO_CREDITO_021:	db		0
TEXTO_CREDITO_022:	db		0
TEXTO_CREDITO_023:	db		"LEAD BETA TESTER - QUALITY CONTROL",0
TEXTO_CREDITO_024:	db		0
TEXTO_CREDITO_025:	db		"XAVI SORINAS",0
TEXTO_CREDITO_026:	db		0
TEXTO_CREDITO_027:	db		0
TEXTO_CREDITO_028:	db		"PACKAGING",0
TEXTO_CREDITO_029:	db		0
TEXTO_CREDITO_030:	db		"XXX",0
TEXTO_CREDITO_031:	db		0
TEXTO_CREDITO_032:	db		"COVER ILLUSTRATION",0
TEXTO_CREDITO_033:	db		0
TEXTO_CREDITO_034:	db		"XXX",0
TEXTO_CREDITO_035:	db		0
TEXTO_CREDITO_036:	db		"BETA TESTERS TEAM",0
TEXTO_CREDITO_037:	db		0
TEXTO_CREDITO_038:	db		"XAVI SORINAS",0
TEXTO_CREDITO_039:	db		"FULANITO",0
TEXTO_CREDITO_040:	db		"MENGANITO",0
TEXTO_CREDITO_041:	db		"SOTANITO",0
TEXTO_CREDITO_042:	db		0
TEXTO_CREDITO_043:	db		"ACKNOWLEDGMENTS",0
TEXTO_CREDITO_044:	db		0
TEXTO_CREDITO_045:	db		"VICTOR MARTINEZ",0
TEXTO_CREDITO_046:	db		"FERNANDO GARCIA",0
TEXTO_CREDITO_047:	db		0
TEXTO_CREDITO_048:	db		0
TEXTO_CREDITO_049:	db		"DIGITAL MOAI SINCERELY THANKS",0
TEXTO_CREDITO_050:	db		"THE FOLLOWING ENTITIES",0
TEXTO_CREDITO_051:	db		"FOR HELPING KEEP THE MSX ALIVE",0
TEXTO_CREDITO_052:	db		0
TEXTO_CREDITO_053:	db		"AAMSX (SPAIN)",0
TEXTO_CREDITO_054:	db		0
TEXTO_CREDITO_055:	db		"MSX BOIXOS CLUB (SPAIN)",0
TEXTO_CREDITO_056:	db		0
TEXTO_CREDITO_057:	db		"MSX.ORG (HOLLAND)",0
TEXTO_CREDITO_058:	db		0
TEXTO_CREDITO_059:	db		0
TEXTO_CREDITO_060:	db		0
TEXTO_CREDITO_061:	db		0
TEXTO_CREDITO_062:	db		0
TEXTO_CREDITO_063:	db		0
TEXTO_CREDITO_064:	db		0
TEXTO_CREDITO_065:	db		0
TEXTO_CREDITO_066:	db		0
TEXTO_CREDITO_067:	db		0
TEXTO_CREDITO_068:	db		0
TEXTO_CREDITO_069:	db		0
TEXTO_CREDITO_070:	db		0
TEXTO_CREDITO_071:	db		0

TEXTO_CREDITO_COPYRIGHT:
		db		"(C) DIGITAL MOAI 2026",0


PALETA_NEGRA_CREDITOS_CINEMATICA_FINAL:

[15]	db		#00,#00
COLOR_15_CREDITOS_BLANCO:
		db		#77,#07

FADE_OUT_COLOR_15_CREDITOS:

		db		#77,#07
		db		#66,#06
		db		#55,#05
		db		#44,#04
		db		#33,#03
		db		#22,#02
		db		#11,#01
		db		#00,#00

PALETA_DATOS_CINEMATICA_FINAL_5_6:
       	incbin  "../PALETAS/PRESENTACION/CINEMATICA56.palete"
FADE_IN_DATOS_CINEMATICA_FINAL_5_6:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA56.fadein"
FADE_OUT_DATOS_CINEMATICA_FINAL_5_6:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA56.fadeout"

PALETA_DATOS_CINEMATICA_FINAL_7_8:
        incbin  "../PALETAS/PRESENTACION/CINEMATICA78.palete"
FADE_IN_DATOS_CINEMATICA_FINAL_7_8:
        incbin  "../PALETAS/PRESENTACION/CINEMATICA78.fadein"
FADE_OUT_DATOS_CINEMATICA_FINAL_7_8:
        incbin  "../PALETAS/PRESENTACION/CINEMATICA78.fadeout"
