ACPAGE		equ		#FAF6

MENU_FUENTE_Y_ORIGEN			equ		#0300+213
MENU_FUENTE_Y_ORIGEN_ACENTOS	equ		#0300+221
MENU_LETRA_ANCHO				equ		6
MENU_LETRA_ALTO					equ		6
MENU_LETRA_ESPECIAL_BASE		equ		26
MENU_LETRA_ESPECIALES_CANT		equ		16
MENU_LETRA_ESPACIO				equ		MENU_LETRA_ESPECIAL_BASE+MENU_LETRA_ESPECIALES_CANT
MENU_FUENTE_CARACTERES			equ		MENU_LETRA_ESPACIO+1
MENU_FUENTE_ANCHO				equ		MENU_LETRA_ANCHO*MENU_FUENTE_CARACTERES
MENU_CARACTER_ACENTO_A			equ		#80
MENU_CARACTER_ACENTO_E			equ		#81
MENU_CARACTER_ACENTO_I			equ		#82
MENU_CARACTER_ACENTO_O			equ		#83
MENU_CARACTER_ACENTO_U			equ		#84
PUSH_SPACE_KEY_X				equ		86
PUSH_SPACE_KEY_Y				equ		181
CINEMATICA_TEXTO_X				equ		12
CINEMATICA_TEXTO_Y_1				equ		154
CINEMATICA_TEXTO_Y_2				equ		164
CINEMATICA_TEXTO_Y_3				equ		174
CINEMATICA_TEXTO_Y_4				equ		184
CINEMATICA_PAUSA_LETRA			equ		4
CINEMATICA_PAUSA_FINAL			equ		155

CINEMATICA_PARPADEO_X_DESTINO              equ     72
CINEMATICA_PARPADEO_Y_DESTINO_ORIGINAL     equ     56
CINEMATICA_PARPADEO_Y_DESTINO_FRAMES       equ     56
CINEMATICA_PARPADEO_ANCHO                  equ     47
CINEMATICA_PARPADEO_ALTO                   equ     23
CINEMATICA_PARPADEO_ESPERA_MIN             equ     96
CINEMATICA_PARPADEO_ESPERA_RANDOM          equ     01111111b
CINEMATICA_PARPADEO_PAUSA_FRAME            equ     2
CINEMATICA_5_COPI_CADA_CICLOS              equ     8
CINEMATICA_LATIDO_CADA_CICLOS              equ     8
CINEMATICA_LATIDO_PASOS                    equ     12

MENU_SPRITE_PATRON_INICIAL        equ     1
MENU_SPRITE_CANTIDAD              equ     22
MENU_SPRITE_PATRONES_VRAM         equ     #7800+MENU_SPRITE_PATRON_INICIAL*32
MENU_SPRITE_COLORES_VRAM          equ     #7400
MENU_SPRITE_ATRIBUTOS_VRAM        equ     #7600

CINEMATICA_BANDERA_X              equ     157
CINEMATICA_BANDERA_Y              equ     11
CINEMATICA_BANDERA_2_X            equ     198
CINEMATICA_BANDERA_2_Y            equ     4
CINEMATICA_BANDERA_3_X            equ     222
CINEMATICA_BANDERA_3_Y            equ     22
CINEMATICA_BANDERITA_X            equ     187
CINEMATICA_BANDERITA_Y            equ     24
CINEMATICA_BANDERA_Y_OCULTA       equ     217
CINEMATICA_BANDERA_CADA_CICLOS    equ     8
CINEMATICA_NUBE_X_INICIAL         equ     88
CINEMATICA_NUBE_X_FINAL           equ     172
CINEMATICA_NUBE_Y                 equ     0
CINEMATICA_NUBE_CADA_CICLOS       equ     12
CINEMATICA_NUBE_2_X_INICIAL       equ     50
CINEMATICA_NUBE_2_X_FINAL         equ     255
CINEMATICA_NUBE_2_Y               equ     50
CINEMATICA_NUBE_2_CADA_CICLOS     equ     6
CINEMATICA_NUBE_3_X_INICIAL       equ     128
CINEMATICA_NUBE_3_X_FINAL         equ     190
CINEMATICA_NUBE_3_Y               equ     13
CINEMATICA_NUBE_3_CADA_CICLOS     equ     16
CINEMATICA_NUBE_4_X_INICIAL       equ     50
CINEMATICA_NUBE_4_X_FINAL         equ     255
CINEMATICA_NUBE_4_Y               equ     44
CINEMATICA_NUBE_4_CADA_CICLOS     equ     5
CINEMATICA_NUBE_5_X_INICIAL       equ     8
CINEMATICA_NUBE_5_X_FINAL         equ     246
CINEMATICA_NUBE_5_Y               equ     15
CINEMATICA_NUBE_5_CADA_CICLOS     equ     4
CINEMATICA_NUBE_6_X_INICIAL       equ     180
CINEMATICA_NUBE_6_X_FINAL         equ     255
CINEMATICA_NUBE_6_Y               equ     11
CINEMATICA_NUBE_6_CADA_CICLOS     equ     15
CINEMATICA_NUBE_7_X_INICIAL       equ     20
CINEMATICA_NUBE_7_X_FINAL         equ     220
CINEMATICA_NUBE_7_Y               equ     4
CINEMATICA_NUBE_7_CADA_CICLOS     equ     18
CINEMATICA_COLOR_0_NORMAL         equ     0
CINEMATICA_COLOR_0_NEGRO          equ     1
CINEMATICA_COLOR_0_FADEIN         equ     2
CINEMATICA_COLOR_0_FINAL          equ     3
CINEMATICA_COLOR_0_FADEOUT        equ     4

; Los patrones 16x16 empiezan en VRAM en bloques de 32 bytes.
; En el byte de patron de la SAT usamos el numero hardware: 4, 8, 12...
CINEMATICA_BANDERA_PATRON_0_1     equ     (MENU_SPRITE_PATRON_INICIAL+0)*4
CINEMATICA_BANDERA_PATRON_0_2     equ     (MENU_SPRITE_PATRON_INICIAL+1)*4
CINEMATICA_BANDERA_PATRON_1_1     equ     (MENU_SPRITE_PATRON_INICIAL+2)*4
CINEMATICA_BANDERA_PATRON_1_2     equ     (MENU_SPRITE_PATRON_INICIAL+3)*4
CINEMATICA_BANDERA_PATRON_2_1     equ     (MENU_SPRITE_PATRON_INICIAL+4)*4
CINEMATICA_BANDERA_PATRON_2_2     equ     (MENU_SPRITE_PATRON_INICIAL+5)*4
CINEMATICA_BANDERITA_PATRON_0_1   equ     (MENU_SPRITE_PATRON_INICIAL+16)*4
CINEMATICA_BANDERITA_PATRON_0_2   equ     (MENU_SPRITE_PATRON_INICIAL+17)*4
CINEMATICA_BANDERITA_PATRON_1_1   equ     (MENU_SPRITE_PATRON_INICIAL+18)*4
CINEMATICA_BANDERITA_PATRON_1_2   equ     (MENU_SPRITE_PATRON_INICIAL+19)*4
CINEMATICA_BANDERITA_PATRON_2_1   equ     (MENU_SPRITE_PATRON_INICIAL+20)*4
CINEMATICA_BANDERITA_PATRON_2_2   equ     (MENU_SPRITE_PATRON_INICIAL+21)*4
CINEMATICA_NUBE_PATRON_0_1        equ     (MENU_SPRITE_PATRON_INICIAL+6)*4
CINEMATICA_NUBE_PATRON_0_2        equ     (MENU_SPRITE_PATRON_INICIAL+7)*4
CINEMATICA_NUBE_PATRON_0_3        equ     (MENU_SPRITE_PATRON_INICIAL+8)*4
CINEMATICA_NUBE_PATRON_1_1        equ     (MENU_SPRITE_PATRON_INICIAL+9)*4
CINEMATICA_NUBE_PATRON_1_2        equ     (MENU_SPRITE_PATRON_INICIAL+10)*4
CINEMATICA_NUBE_PATRON_1_3        equ     (MENU_SPRITE_PATRON_INICIAL+11)*4
CINEMATICA_NUBE_PATRON_2_1        equ     (MENU_SPRITE_PATRON_INICIAL+12)*4
CINEMATICA_NUBE_PATRON_2_2        equ     (MENU_SPRITE_PATRON_INICIAL+13)*4
CINEMATICA_NUBE_PATRON_3_1        equ     (MENU_SPRITE_PATRON_INICIAL+14)*4
CINEMATICA_NUBE_PATRON_3_2        equ     (MENU_SPRITE_PATRON_INICIAL+15)*4
CINEMATICA_NUBE_A_PATRON_0        equ     CINEMATICA_NUBE_PATRON_0_1
CINEMATICA_NUBE_A_PATRON_1        equ     CINEMATICA_NUBE_PATRON_0_2
CINEMATICA_NUBE_A_PATRON_2        equ     CINEMATICA_NUBE_PATRON_0_3
CINEMATICA_NUBE_A_PATRON_3        equ     CINEMATICA_NUBE_PATRON_1_1
CINEMATICA_NUBE_B_PATRON_0        equ     CINEMATICA_NUBE_PATRON_1_2
CINEMATICA_NUBE_B_PATRON_1        equ     CINEMATICA_NUBE_PATRON_1_3
CINEMATICA_NUBE_B_PATRON_2        equ     CINEMATICA_NUBE_PATRON_2_1
CINEMATICA_NUBE_B_PATRON_3        equ     CINEMATICA_NUBE_PATRON_2_2
CINEMATICA_NUBE_C_PATRON_0        equ     CINEMATICA_NUBE_PATRON_3_1
CINEMATICA_NUBE_C_PATRON_1        equ     CINEMATICA_NUBE_PATRON_3_2

WRTVDP:     equ     #0047

COMIENZA_MENU:

		di
		ld		a,#C9
		ld		(HTIMI),a
		ld		(HKEYI),a
		ei

		call	PAGE_10_A_SEGMENT_2
		ld		hl,0
		xor		a
		ld		(SCORE_REAL),hl
		ld		(V_DECEN_MIL),a
		ld		(V_UNIDA_MIL),a
		ld		(V_CENTENAS),a
		ld		(V_DECENAS),a
		ld		(V_UNIDADES),a
		ld		(DEMO),a

		call	MUESTRA_PRESENTACION_PROVISIONAL
		jp		PULSA_UNA_TECLA_PARA_EMPEZAR


MUESTRA_PRESENTACION_PROVISIONAL:

		call	DISSCR_RAM

		ld		a,5
		call	CHGMOD

		call	DISSCR_RAM

		; La segunda parte de la imagen de menu solo ocupa #2A00 bytes.
		; Limpiamos VRAM para que no queden restos de la pantalla SC7 del logo.

		xor		a
		ld		hl,#0000
		ld		bc,#ffff
		call	FILVRM_RAM

		; Página visible = 0

		xor		a
		call	SETPAGE

		; 1 - Cargamos los gráficos de presentación en page 1, no visible.

		call	CARGA_GRAFICOS_MENU_Y_CINEMATICA
		call    ACTIVA_SPRITES_16X16_MENU
		call	CARGA_SPRITES_Y_COLORES_MENU
		call	INICIA_MUSICA_MENU_PRESENTACION
		call	CINEMATICA

TITULO:

		; 2 - Ponemos la primera paleta del fade in.

		call	PONE_PRIMERA_PALETA_PRESENTACION

		; 3 - Copiamos la imagen de page 1 a page visible 0.

		ld		hl,DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_0
		call	DOCOPY
		call	VDPREADY

		ld		hl,DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_1
		call	DOCOPY
		call	VDPREADY

		; 4 - Mostramos pantalla y hacemos fade in.

		call	ENASCR_RAM
		call	FADE_IN_PRESENTACION

		; 5 - Pintamos texto de aviso.

		call	PINTA_TEXTO_PUSH_SPACE_KEY_EN_DOS_PAGES

		; 7 - Preparamos rotativo inferior.

		call	INICIALIZA_ROTATIVO_PRESENTACION
		call	INICIALIZA_TRUCOS_PRESENTACION

		ret

PINTA_TEXTO_PUSH_SPACE_KEY:

		call	OBTIENE_DESTINO_Y_PUSH_SPACE_KEY
		ld		hl,PUSH_SPACE_KEY_X
		ld		iy,TEXTO_PUSH_SPACE_KEY
		ld		a,(LENGUAJE)
		dec		a
		jr		nz,.AL_BUCLE
		ld		iy,TEXTO_PULSA_ESPACIO

.AL_BUCLE:
		jp		BUCLE_PINTA_TEXTO_PUSH_SPACE_KEY


PINTA_TEXTO_PUSH_SPACE_KEY_EN_DOS_PAGES:

		xor		a

.BUCLE_PAGES:

		ld		(ACPAGE),a
		push	af
		call	PINTA_TEXTO_PUSH_SPACE_KEY
		pop		af
		inc		a
		cp		2
		jr		nz,.BUCLE_PAGES

		xor		a
		ld		(ACPAGE),a
		ret

BUCLE_PINTA_TEXTO_PUSH_SPACE_KEY:

		call	OBTIENE_CARACTER_MENU_DESDE_IY
		or		a
		ret		z

		push	bc
		push	de
		push	hl
		call	PINTA_LETRA_MENU_EN_DESTINO
		pop		hl
		pop		de
		pop		bc

		push	bc
		ld		bc,MENU_LETRA_ANCHO
		add		hl,bc
		pop		bc

		inc		iy
		ld		a,b
		or		a
		jr		z,.SIN_BYTE_EXTRA_UTF8
		inc		iy

.SIN_BYTE_EXTRA_UTF8:
		jp		BUCLE_PINTA_TEXTO_PUSH_SPACE_KEY


TEXTO_PUSH_SPACE_KEY:

		db		"PUSH SPACE KEY",0

TEXTO_PULSA_ESPACIO:

		db		"PULSA  ESPACIO",0

OBTIENE_DESTINO_Y_PUSH_SPACE_KEY:

		ld		de,PUSH_SPACE_KEY_Y
		ld		a,(ACPAGE)
		or		a
		ret		z
		inc		d
		ret

OBTIENE_DESTINO_Y_ROTATIVO_DESDE_A:

		ld		de,ROTATIVO_Y_PRESENTACION
		or		a
		ret		z
		inc		d
		ret

PINTA_LETRA_MENU_EN_DESTINO:

		push	hl
		push	de
		call	CALCULA_ORIGEN_X_LETRA_MENU
		ld		ix,DATOS_DEL_TILE_PARA_COPY
		ld		(ix),l
		ld		(ix+1),h
		ld		(ix+2),e
		ld		(ix+3),d
		pop		hl
		ld		(ix+6),l
		ld		(ix+7),h
		pop		hl
		ld		(ix+4),l
		ld		(ix+5),h
		ld		(ix+8),MENU_LETRA_ANCHO
		ld		(ix+9),0
		ld		(ix+10),MENU_LETRA_ALTO
		ld		(ix+11),0
		ld		(ix+12),#00
		ld		(ix+13),#00
		ld		(ix+14),11010000b
		call	HL_DATOS_DEL_COPY
		jp		VDPREADY

CALCULA_ORIGEN_X_LETRA_MENU:

		cp		97
		jr		c,.MIRA_MAYUSCULAS
		cp		123
		jr		nc,.MIRA_MAYUSCULAS
		sub		32

.MIRA_MAYUSCULAS:

		cp		65
		jr		c,.MIRA_ACENTOS
		cp		91
		jr		nc,.MIRA_ACENTOS
		sub		65
		jr		.MULTIPLICA

.MIRA_ACENTOS:

		push	af
		ld		hl,TABLA_ACENTOS_MENU
		ld		b,15

.BUCLE_ACENTOS:

		cp		(hl)
		jr		z,.ES_ACENTO
		inc		hl
		inc		hl
		djnz	.BUCLE_ACENTOS
		pop		af
		jr		.MIRA_ESPECIALES

.ES_ACENTO:

		inc		hl
		ld		l,(hl)
		ld		h,0
		pop		af
		ld		de,MENU_FUENTE_Y_ORIGEN_ACENTOS
		ret

.MIRA_ESPECIALES:

		ld		hl,TABLA_ESPECIALES_MENU
		ld		b,MENU_LETRA_ESPECIALES_CANT
		ld		c,MENU_LETRA_ESPECIAL_BASE

.BUCLE_ESPECIALES:

		cp		(hl)
		jr		z,.ES_ESPECIAL
		inc		hl
		inc		c
		djnz	.BUCLE_ESPECIALES
		jr		.ES_ESPACIO

.ES_ESPECIAL:

		ld		a,c
		jr		.MULTIPLICA

.ES_ESPACIO:

		ld		a,MENU_LETRA_ESPACIO

.MULTIPLICA:

		ld		e,a
		ld		d,0
		ld		h,d
		ld		l,e
		add		hl,hl
		add		hl,de
		add		hl,hl
		ld		de,MENU_FUENTE_Y_ORIGEN
		ret

TABLA_ESPECIALES_MENU:

		db		"-(,)1234567890'."

TABLA_ACENTOS_MENU:

		db		MENU_CARACTER_ACENTO_A,0
		db		MENU_CARACTER_ACENTO_E,6
		db		MENU_CARACTER_ACENTO_I,12
		db		MENU_CARACTER_ACENTO_O,18
		db		MENU_CARACTER_ACENTO_U,24
		db		#C1,0,#E1,0
		db		#C9,6,#E9,6
		db		#CD,12,#ED,12
		db		#D3,18,#F3,18
		db		#DA,24,#FA,24

OBTIENE_CARACTER_MENU_DESDE_IY:

		ld		b,0
		ld		a,(iy+0)
		cp		#C3
		ret		nz
		ld		a,(iy+1)
		call	DECODIFICA_UTF8_ACENTO_MENU
		ret		c
		ld		a,#C3
		ret

OBTIENE_CARACTER_MENU_DESDE_IX_PAGE_2:

		ld		a,(DIRPA2)
		push	af
		ld		a,2
		ld		(DIRPA2),a
		ld		b,0
		ld		a,(ix+0)
		cp		#C3
		jr		nz,.FIN_IX
		ld		a,(ix+1)
		call	DECODIFICA_UTF8_ACENTO_MENU
		jr		c,.FIN_IX
		ld		a,#C3

.FIN_IX:

		ld		c,a
		pop		af
		ld		(DIRPA2),a
		ld		a,c
		ret

OBTIENE_CARACTER_MENU_DESDE_HL:

		ld		b,0
		ld		a,(hl)
		cp		#C3
		ret		nz
		inc		hl
		ld		a,(hl)
		dec		hl
		call	DECODIFICA_UTF8_ACENTO_MENU
		ret		c
		ld		a,#C3
		ret

DECODIFICA_UTF8_ACENTO_MENU:

		ld		hl,TABLA_UTF8_ACENTOS_MENU
		ld		b,10

.BUCLE_UTF8_ACENTOS:

		cp		(hl)
		jr		z,.ES_UTF8_ACENTO
		inc		hl
		inc		hl
		djnz	.BUCLE_UTF8_ACENTOS
		or		a
		ret

.ES_UTF8_ACENTO:

		inc		hl
		ld		a,(hl)
		ld		b,1
		scf
		ret

TABLA_UTF8_ACENTOS_MENU:

		db		#81,MENU_CARACTER_ACENTO_A
		db		#A1,MENU_CARACTER_ACENTO_A
		db		#89,MENU_CARACTER_ACENTO_E
		db		#A9,MENU_CARACTER_ACENTO_E
		db		#8D,MENU_CARACTER_ACENTO_I
		db		#AD,MENU_CARACTER_ACENTO_I
		db		#93,MENU_CARACTER_ACENTO_O
		db		#B3,MENU_CARACTER_ACENTO_O
		db		#9A,MENU_CARACTER_ACENTO_U
		db		#BA,MENU_CARACTER_ACENTO_U

PINTA_TEXTO_MENU_FORMA_3:

		call	OBTIENE_CARACTER_MENU_DESDE_IX_PAGE_2
		or		a
		ret		z

		push	bc
		push	de
		push	hl
		push	ix
		call	PINTA_LETRA_MENU_EN_DESTINO
		pop		ix
		pop		hl
		pop		de

		call	ESPERA_LETRA_CINEMATICA
		pop		bc
		ret		c

		push	bc
		ld		bc,MENU_LETRA_ANCHO
		add		hl,bc
		pop		bc

		inc		ix
		ld		a,b
		or		a
		jr		z,.SIN_BYTE_EXTRA_UTF8
		inc		ix

.SIN_BYTE_EXTRA_UTF8:
		jp		PINTA_TEXTO_MENU_FORMA_3

CINEMATICA:

		xor		a
		call	SETPAGE

		ld		iy,TABLA_BLOQUES_CINEMATICA

.BUCLE_BLOQUES_CINEMATICA:

		ld		a,(iy+0)
		or		a
		ret		z

		ld		(CINEMATICA_BLOQUE_ACTUAL),a

		call	REINICIA_PARPADEO_CINEMATICA_2

		ld		a,(iy+1)
		bit		0,a
		jr		z,.SIN_REINICIAR_NUBES
		push	iy
		call	REINICIA_NUBE_CINEMATICA
		pop		iy

.SIN_REINICIAR_NUBES:

		ld		a,(iy+1)
		bit		1,a
		jr		z,.SIN_REINICIAR_BANDERA
		push	iy
		call	REINICIA_BANDERA_CINEMATICA
		pop		iy

.SIN_REINICIAR_BANDERA:

		ld		a,(iy+1)
		bit		2,a
		jr		z,.SIN_REINICIAR_LATIDO
		push	iy
		call	REINICIA_LATIDO_CINEMATICA_2
		pop		iy

.SIN_REINICIAR_LATIDO:

		ld		a,(iy+1)
		bit		3,a
		jr		z,.SIN_OCULTAR_BANDERA
		push	iy
		call	OCULTA_BANDERA_CINEMATICA
		pop		iy

.SIN_OCULTAR_BANDERA:

		ld		l,(iy+2)
		ld		h,(iy+3)

		ld		e,(iy+4)
		ld		d,(iy+5)

		push	iy
		push	de
		pop		ix
		call	EJECUTA_BLOQUE_CINEMATICA
		pop		iy
		jp		c,SALIDA_FORZADA_CINEMATICA

		ld		bc,6
		add		iy,bc
		jr		.BUCLE_BLOQUES_CINEMATICA

TABLA_BLOQUES_CINEMATICA:

		; bloque, flags, datos_copy, texto
		; bit 0 = reinicia nubes
		; bit 1 = reinicia bandera
		; bit 2 = reinicia latido
		; bit 3 = oculta bandera
		db		1,00000011b
		dw		DATOS_COPY_CINEMATICA_1,TEXTO_CINEMATICA_1

		db		2,00001000b
		dw		DATOS_COPY_CINEMATICA_3,TEXTO_CINEMATICA_2

		db		3,00000100b
		dw		DATOS_COPY_CINEMATICA_2,TEXTO_CINEMATICA_3

		db		4,00001100b
		dw		DATOS_COPY_CINEMATICA_3,TEXTO_CINEMATICA_4

		db		5,00001100b
		dw		DATOS_COPY_CINEMATICA_4,TEXTO_CINEMATICA_5

		db		0

SALIDA_FORZADA_CINEMATICA:

		call	FADE_OUT_CINEMATICA
		jp		FADE_OUT_MUSICA_CINEMATICA

EJECUTA_BLOQUE_CINEMATICA:

		push	hl
		push	ix

		call	PONE_PRIMERA_PALETA_CINEMATICA
		call	LIMPIA_PAGE_0_CINEMATICA

		pop		ix
		pop		hl

		push	ix
		call	DOCOPY
		call	VDPREADY
		call	PINTA_PRIMER_FRAME_COPI_CINEMATICA_5
		call	PREPARA_SPRITES_CINEMATICA_ACTUAL
		call	ENASCR_RAM

		call	FADE_IN_CINEMATICA
		jr		c,.FIN_BLOQUE_CINEMATICA

		call	PONE_PALETA_FINAL_CINEMATICA

		pop		ix
		push	ix
		call	PINTA_CUATRO_FRASES_CINEMATICA
		jr		c,.FIN_BLOQUE_CINEMATICA

		ld		b,CINEMATICA_PAUSA_FINAL
		call	ESPERA_CINEMATICA_B
		jr		c,.FIN_BLOQUE_CINEMATICA

		call	FADE_OUT_CINEMATICA

.FIN_BLOQUE_CINEMATICA:

		pop		ix
		ret

PONE_PRIMERA_PALETA_CINEMATICA:

		call	COLOR_0_NORMAL_CINEMATICA
		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_24
		cp		4
		jr		z,.PALETA_24
		cp		5
		jr		z,.PALETA_5
		ld		hl,FADE_IN_CINEMATICA_1_2
		jp		SETPALETE_CINEMATICA

.PALETA_24:

		ld		hl,FADE_IN_CINEMATICA_2_4
		jp		SETPALETE_CINEMATICA

.PALETA_5:

		ld		hl,FADE_IN_CINEMATICA_5
		jp		SETPALETE_CINEMATICA

PONE_PALETA_FINAL_CINEMATICA:

		call	COLOR_0_NORMAL_CINEMATICA
		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_24
		cp		4
		jr		z,.PALETA_24
		cp		5
		jr		z,.PALETA_5
		ld		hl,PALETA_CINEMATICA_1_2
		jp		SETPALETE_CINEMATICA

.PALETA_24:

		ld		hl,PALETA_CINEMATICA_2_4
		jp		SETPALETE_CINEMATICA

.PALETA_5:

		ld		hl,PALETA_CINEMATICA_5
		jp		SETPALETE_CINEMATICA

FADE_IN_CINEMATICA:

		call	COLOR_0_NORMAL_CINEMATICA
		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_24
		cp		4
		jr		z,.PALETA_24
		cp		5
		jr		z,.PALETA_5
		ld		hl,FADE_IN_CINEMATICA_1_2+32
		ld		e,6
		jp		BUCLE_FADE_CINEMATICA

.PALETA_24:

		ld		hl,FADE_IN_CINEMATICA_2_4+32
		ld		e,6
		jp		BUCLE_FADE_CINEMATICA

.PALETA_5:

		ld		hl,FADE_IN_CINEMATICA_5+32
		ld		e,6
		jp		BUCLE_FADE_CINEMATICA

FADE_OUT_CINEMATICA:

		call	COLOR_0_NORMAL_CINEMATICA
		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_24
		cp		4
		jr		z,.PALETA_24
		cp		5
		jr		z,.PALETA_5
		ld		hl,FADE_OUT_CINEMATICA_1_2
		ld		e,7
		jr		BUCLE_FADE_CINEMATICA

.PALETA_24:

		ld		hl,FADE_OUT_CINEMATICA_2_4
		ld		e,7
		jr		BUCLE_FADE_CINEMATICA

.PALETA_5:

		ld		hl,FADE_OUT_CINEMATICA_5
		ld		e,7

BUCLE_FADE_CINEMATICA:

		call	SETPALETE_CINEMATICA
		push	hl
		push	de
		ld		b,6
		call	ESPERA_CINEMATICA_B
		pop		de
		pop		hl
		ret		c
		dec		e
		jp		nz,BUCLE_FADE_CINEMATICA
		or		a
		ret

SETPALETE_CINEMATICA:

		bit		7,h
		jr		z,.ENVIA_PALETA
		ld		a,(DIRPA2)
		push	af
		ld		a,2
		ld		(DIRPA2),a
		call	.ENVIA_PALETA
		pop		af
		ld		(DIRPA2),a
		ret

.ENVIA_PALETA:

		xor		a
		di
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		ld		c,#9A
[32]	outi
		ei
		ret

COLOR_0_NORMAL_CINEMATICA:

		xor		a
		ld		(CINEMATICA_COLOR_0_MODO),a
		ret

PINTA_CUATRO_FRASES_CINEMATICA:

		push	ix
		pop		hl

		ld		a,(LENGUAJE)
		cp		2
		jr		nz,.TEXTOS_CINEMATICA_LISTOS
		ld		bc,TEXTO_CINEMATICAS_INGLES-TEXTO_CINEMATICA_1
		add		hl,bc

.TEXTOS_CINEMATICA_LISTOS:

		ld		de,CINEMATICA_TEXTO_Y_1
		call	PINTA_FRASE_CINEMATICA_DESDE_TABLA
		ret		c

		ld		de,CINEMATICA_TEXTO_Y_2
		call	PINTA_FRASE_CINEMATICA_DESDE_TABLA
		ret		c

		ld		de,CINEMATICA_TEXTO_Y_3
		call	PINTA_FRASE_CINEMATICA_DESDE_TABLA
		ret		c

		ld		de,CINEMATICA_TEXTO_Y_4
		jp		PINTA_FRASE_CINEMATICA_DESDE_TABLA

PINTA_FRASE_CINEMATICA_DESDE_TABLA:

		ld		a,(DIRPA2)
		push	af
		ld		a,2
		ld		(DIRPA2),a
		ld		c,(hl)
		inc		hl
		ld		b,(hl)
		inc		hl
		pop		af
		ld		(DIRPA2),a
		push	hl
		push	bc
		pop		ix
		ld		hl,CINEMATICA_TEXTO_X
		call	PINTA_TEXTO_MENU_FORMA_3
		pop		hl
		ret

LIMPIA_PAGE_0_CINEMATICA:

		ld		hl,DATOS_NEGRO_PAGE_0_CINEMATICA
		call	DOCOPY
		jp		VDPREADY

ESPERA_LETRA_CINEMATICA:

		ld		b,CINEMATICA_PAUSA_LETRA

ESPERA_CINEMATICA_B:

		halt
		call	COMPRUEBA_SPACE_CINEMATICA
		ret		c

		push	af
		push	bc
		push	de
		push	hl
		push	ix
		push	iy

		call	CONTROL_PARPADEO_CINEMATICA_2
		call	CONTROL_COPI_CINEMATICA_5
		call	CONTROL_LATIDO_CINEMATICA_2
		call	CONTROL_NUBE_CINEMATICA
		call	CONTROL_BANDERA_CINEMATICA

		pop		iy
		pop		ix
		pop		hl
		pop		de
		pop		bc
		pop		af

		djnz	ESPERA_CINEMATICA_B
		or		a
		ret

REINICIA_PARPADEO_CINEMATICA_2:

		xor		a
		ld		(CINEMATICA_PARPADEO_ESTADO),a
		ld		(CINEMATICA_PARPADEO_VECES),a
		ld		(CINEMATICA_PARPADEO_ACTIVO),a

		ld		a,120
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret

PINTA_PRIMER_FRAME_COPI_CINEMATICA_5:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		5
		ret		nz

		ld		a,CINEMATICA_5_COPI_CADA_CICLOS
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		xor		a
		ld		(CINEMATICA_PARPADEO_ESTADO),a
		jr		EJECUTA_FRAME_COPI_CINEMATICA_5

CONTROL_COPI_CINEMATICA_5:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		5
		ret		nz

		ld		a,(CINEMATICA_PARPADEO_CONTADOR)
		dec		a
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret		nz

		ld		a,CINEMATICA_5_COPI_CADA_CICLOS
		ld		(CINEMATICA_PARPADEO_CONTADOR),a

		ld		a,(CINEMATICA_PARPADEO_ESTADO)
		inc		a
		cp		4
		jr		c,.GUARDA_FRAME_COPI
		xor		a

.GUARDA_FRAME_COPI:

		ld		(CINEMATICA_PARPADEO_ESTADO),a

EJECUTA_FRAME_COPI_CINEMATICA_5:

		add		a,a
		ld		l,a
		ld		h,0
		ld		de,TABLA_COPY_COPI_CINEMATICA_5
		add		hl,de

		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		ex		de,hl

		call	DOCOPY
		jp		VDPREADY

TABLA_COPY_COPI_CINEMATICA_5:

		dw		DATOS_COPY_COPI_CINEMATICA_5_0
		dw		DATOS_COPY_COPI_CINEMATICA_5_1
		dw		DATOS_COPY_COPI_CINEMATICA_5_2
		dw		DATOS_COPY_COPI_CINEMATICA_5_3

REINICIA_LATIDO_CINEMATICA_2:

		xor		a
		ld		(CINEMATICA_LATIDO_INDICE),a
		ld		a,CINEMATICA_LATIDO_CADA_CICLOS
		ld		(CINEMATICA_LATIDO_CONTADOR),a
		ret

CONTROL_LATIDO_CINEMATICA_2:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		5
		jp		z,CONTROL_LATIDO_CINEMATICA_5
		cp		3
		jr		z,.LATIDO_ACTIVO
		cp		4
		ret		nz

.LATIDO_ACTIVO:

		ld		a,(CINEMATICA_LATIDO_CONTADOR)
		dec		a
		ld		(CINEMATICA_LATIDO_CONTADOR),a
		ret		nz

		ld		a,CINEMATICA_LATIDO_CADA_CICLOS
		ld		(CINEMATICA_LATIDO_CONTADOR),a

		ld		a,(CINEMATICA_LATIDO_INDICE)
		inc		a
		cp		CINEMATICA_LATIDO_PASOS
		jr		c,.GUARDA_INDICE_LATIDO
		xor		a

.GUARDA_INDICE_LATIDO:

		ld		(CINEMATICA_LATIDO_INDICE),a
		add		a,a
		ld		l,a
		ld		h,0
		add		hl,hl
		ld		de,TABLA_LATIDO_CINEMATICA_2
		add		hl,de
		jp		SETPALETE_LATIDO_CINEMATICA_2

SETPALETE_LATIDO_CINEMATICA_2:

		di
		ld		c,#9A

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		4
		jr		z,.COLOR_8_CINEMATICA_4

		ld		a,3
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		outi
		outi

		ld		a,9
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		outi
		outi
		ei
		ret

.COLOR_8_CINEMATICA_4:

		ld		a,8
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		outi
		outi
		ei
		ret

CONTROL_LATIDO_CINEMATICA_5:

		ld		a,(CINEMATICA_LATIDO_INDICE)
		inc		a
		and		00000011b
		ld		(CINEMATICA_LATIDO_INDICE),a

		ld		l,a
		ld		h,0
		ld		de,TABLA_DELTA_LATIDO_CINEMATICA_5
		add		hl,de
		ld		b,(hl)

		ld		a,5
		ld		hl,PALETA_CINEMATICA_5+10
		call	SETPALETE_LATIDO_CINEMATICA_5
		ret

TABLA_DELTA_LATIDO_CINEMATICA_5:

		db		#00,#FF,#00,#01		; normal, -1 brillo, normal, +1 brillo

SETPALETE_LATIDO_CINEMATICA_5:

		bit		7,h
		jr		z,.ENVIA_COLOR_LATIDO
		ld		c,a
		ld		a,(DIRPA2)
		push	af
		ld		a,2
		ld		(DIRPA2),a
		ld		a,c
		call	.ENVIA_COLOR_LATIDO
		pop		af
		ld		(DIRPA2),a
		ret

.ENVIA_COLOR_LATIDO:

		push	af
		call	AJUSTA_COLOR_LATIDO_CINEMATICA_5
		pop		af

		di
		ld		c,#9A
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		out		(c),d
		out		(c),e
		ei
		ret

AJUSTA_COLOR_LATIDO_CINEMATICA_5:

		ld		a,(hl)
		and		#07
		call	AJUSTA_COMPONENTE_LATIDO_CINEMATICA_5
		ld		e,a

		ld		a,(hl)
		and		#70
		rrca
		rrca
		rrca
		rrca
		call	AJUSTA_COMPONENTE_LATIDO_CINEMATICA_5
		add		a,a
		add		a,a
		add		a,a
		add		a,a
		or		e
		ld		d,a

		inc		hl
		ld		a,(hl)
		and		#07
		call	AJUSTA_COMPONENTE_LATIDO_CINEMATICA_5
		ld		e,a
		ret

AJUSTA_COMPONENTE_LATIDO_CINEMATICA_5:

		ld		c,a
		ld		a,b
		or		a
		jr		z,.DEVUELVE_COMPONENTE
		cp		#FF
		jr		z,.BAJA_BRILLO

.SUBE_BRILLO:

		ld		a,c
		cp		7
		ret		z
		inc		a
		ret

.BAJA_BRILLO:

		ld		a,c
		or		a
		ret		z
		dec		a
		ret

.DEVUELVE_COMPONENTE:

		ld		a,c
		ret

CONTROL_PARPADEO_CINEMATICA_2:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PARPADEO_ACTIVO
		cp		4
		ret		nz

.PARPADEO_ACTIVO:

		ld		a,(CINEMATICA_PARPADEO_ACTIVO)
		or		a
		jr		nz,.PARPADEO_EN_MARCHA

		ld		a,(CINEMATICA_PARPADEO_CONTADOR)
		dec		a
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret		nz

		ld		a,1
		ld		(CINEMATICA_PARPADEO_ACTIVO),a
		ld		(CINEMATICA_PARPADEO_CONTADOR),a

		xor		a
		ld		(CINEMATICA_PARPADEO_ESTADO),a
		jr		.PARPADEO_EN_MARCHA

.PARPADEO_EN_MARCHA:

		ld		a,(CINEMATICA_PARPADEO_CONTADOR)
		dec		a
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret		nz
		ld		a,CINEMATICA_PARPADEO_PAUSA_FRAME
		ld		(CINEMATICA_PARPADEO_CONTADOR),a

		call	EJECUTA_FRAME_PARPADEO_CINEMATICA_2

		ld		a,(CINEMATICA_PARPADEO_ESTADO)
		inc		a
		ld		(CINEMATICA_PARPADEO_ESTADO),a

		cp		9
		ret		c

		xor		a
		ld		(CINEMATICA_PARPADEO_ACTIVO),a
		ld		(CINEMATICA_PARPADEO_ESTADO),a

		ld		a,r
		and		CINEMATICA_PARPADEO_ESPERA_RANDOM
		add		CINEMATICA_PARPADEO_ESPERA_MIN
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret

EJECUTA_FRAME_PARPADEO_CINEMATICA_2:

		ld		a,(CINEMATICA_PARPADEO_ESTADO)
		add		a,a
		ld		l,a
		ld		h,0
		ld		de,TABLA_COPY_PARPADEO_CINEMATICA_2
		add		hl,de

		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		ex		de,hl

		call	DOCOPY
		jp		VDPREADY

TABLA_COPY_PARPADEO_CINEMATICA_2:

		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_ORIGINAL
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_A
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_B
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_C
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_D
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_C
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_B
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_A
		dw		DATOS_COPY_PARPADEO_CINEMATICA_2_ORIGINAL

REINICIA_BANDERA_CINEMATICA:

		xor		a
		ld		(CINEMATICA_BANDERA_ESTADO),a
		ld		a,CINEMATICA_BANDERA_CADA_CICLOS
		ld		(CINEMATICA_BANDERA_CONTADOR),a
		call	PINTA_NUBE_CINEMATICA
		call	PINTA_NUBE_2_CINEMATICA
		jp		PINTA_BANDERA_CINEMATICA

REINICIA_NUBE_CINEMATICA:

		ld		a,CINEMATICA_NUBE_X_INICIAL
		ld		(CINEMATICA_NUBE_X),a
		ld		a,CINEMATICA_NUBE_CADA_CICLOS
		ld		(CINEMATICA_NUBE_CONTADOR),a
		call	COPIA_COLORES_NUBES_SIMPLIFICADAS_CINEMATICA

		ld		a,CINEMATICA_NUBE_2_X_INICIAL
		ld		(CINEMATICA_NUBE_2_X),a
		ld		a,CINEMATICA_NUBE_2_CADA_CICLOS
		ld		(CINEMATICA_NUBE_2_CONTADOR),a
		ld		a,CINEMATICA_NUBE_3_X_INICIAL
		ld		(CINEMATICA_NUBE_3_X),a
		ld		a,CINEMATICA_NUBE_3_CADA_CICLOS
		ld		(CINEMATICA_NUBE_3_CONTADOR),a
		ld		a,CINEMATICA_NUBE_4_X_INICIAL
		ld		(CINEMATICA_NUBE_4_X),a
		ld		a,CINEMATICA_NUBE_4_CADA_CICLOS
		ld		(CINEMATICA_NUBE_4_CONTADOR),a
		ld		a,CINEMATICA_NUBE_5_X_INICIAL
		ld		(CINEMATICA_NUBE_5_X),a
		ld		a,CINEMATICA_NUBE_5_CADA_CICLOS
		ld		(CINEMATICA_NUBE_5_CONTADOR),a
		ld		a,CINEMATICA_NUBE_6_X_INICIAL
		ld		(CINEMATICA_NUBE_6_X),a
		ld		a,CINEMATICA_NUBE_6_CADA_CICLOS
		ld		(CINEMATICA_NUBE_6_CONTADOR),a
		ld		a,CINEMATICA_NUBE_7_X_INICIAL
		ld		(CINEMATICA_NUBE_7_X),a
		ld		a,CINEMATICA_NUBE_7_CADA_CICLOS
		ld		(CINEMATICA_NUBE_7_CONTADOR),a
		ret

CONTROL_BANDERA_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		1
		jr		z,.BANDERA_ACTIVA
		cp		3
		ret		nz

.BANDERA_ACTIVA:

		ld		a,(CINEMATICA_BANDERA_CONTADOR)
		dec		a
		ld		(CINEMATICA_BANDERA_CONTADOR),a
		ret		nz

		ld		a,CINEMATICA_BANDERA_CADA_CICLOS
		ld		(CINEMATICA_BANDERA_CONTADOR),a

		ld		a,(CINEMATICA_BANDERA_ESTADO)
		inc		a
		cp		3
		jr		c,.GUARDA_ESTADO_BANDERA
		xor		a

.GUARDA_ESTADO_BANDERA:

		ld		(CINEMATICA_BANDERA_ESTADO),a
		jp		PINTA_BANDERA_CINEMATICA

CONTROL_NUBE_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		1
		ret		nz

		ld		a,(CINEMATICA_NUBE_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_CONTADOR),a
		jr		nz,.CONTROLA_NUBE_3

		ld		a,CINEMATICA_NUBE_CADA_CICLOS
		ld		(CINEMATICA_NUBE_CONTADOR),a

		ld		a,(CINEMATICA_NUBE_X)
		inc		a
		cp		CINEMATICA_NUBE_X_FINAL
		jr		c,.GUARDA_X_NUBE
		ld		a,CINEMATICA_NUBE_X_INICIAL

.GUARDA_X_NUBE:

		ld		(CINEMATICA_NUBE_X),a
		call	PINTA_NUBE_CINEMATICA

.CONTROLA_NUBE_3:

		ld		a,(CINEMATICA_NUBE_3_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_3_CONTADOR),a
		jr		nz,.CONTROLA_NUBE_2
		ld		a,CINEMATICA_NUBE_3_CADA_CICLOS
		ld		(CINEMATICA_NUBE_3_CONTADOR),a
		ld		a,(CINEMATICA_NUBE_3_X)
		inc		a
		cp		CINEMATICA_NUBE_3_X_FINAL
		jr		c,.GUARDA_X_NUBE_3
		ld		a,CINEMATICA_NUBE_3_X_INICIAL

.GUARDA_X_NUBE_3:

		ld		(CINEMATICA_NUBE_3_X),a
		call	PINTA_NUBE_3_CINEMATICA

.CONTROLA_NUBE_2:

		ld		a,(CINEMATICA_NUBE_2_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_2_CONTADOR),a
		jr		nz,.CONTROLA_NUBE_4

		ld		a,CINEMATICA_NUBE_2_CADA_CICLOS
		ld		(CINEMATICA_NUBE_2_CONTADOR),a

		ld		a,(CINEMATICA_NUBE_2_X)
		inc		a
		cp		CINEMATICA_NUBE_2_X_FINAL
		jr		c,.GUARDA_X_NUBE_2
		ld		a,CINEMATICA_NUBE_2_X_INICIAL

.GUARDA_X_NUBE_2:

		ld		(CINEMATICA_NUBE_2_X),a
		call	PINTA_NUBE_2_CINEMATICA

.CONTROLA_NUBE_4:

		ld		a,(CINEMATICA_NUBE_4_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_4_CONTADOR),a
		jr		nz,.CONTROLA_NUBE_5
		ld		a,CINEMATICA_NUBE_4_CADA_CICLOS
		ld		(CINEMATICA_NUBE_4_CONTADOR),a
		ld		a,(CINEMATICA_NUBE_4_X)
		inc		a
		cp		CINEMATICA_NUBE_4_X_FINAL
		jr		c,.GUARDA_X_NUBE_4
		ld		a,CINEMATICA_NUBE_4_X_INICIAL

.GUARDA_X_NUBE_4:

		ld		(CINEMATICA_NUBE_4_X),a
		call	PINTA_NUBE_4_CINEMATICA

.CONTROLA_NUBE_5:

		ld		a,(CINEMATICA_NUBE_5_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_5_CONTADOR),a
		jr		nz,.CONTROLA_NUBE_6
		ld		a,CINEMATICA_NUBE_5_CADA_CICLOS
		ld		(CINEMATICA_NUBE_5_CONTADOR),a
		ld		a,(CINEMATICA_NUBE_5_X)
		inc		a
		cp		CINEMATICA_NUBE_5_X_FINAL
		jr		c,.GUARDA_X_NUBE_5
		ld		a,CINEMATICA_NUBE_5_X_INICIAL

.GUARDA_X_NUBE_5:

		ld		(CINEMATICA_NUBE_5_X),a
		call	PINTA_NUBE_5_CINEMATICA

.CONTROLA_NUBE_6:

		ld		a,(CINEMATICA_NUBE_6_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_6_CONTADOR),a
		jr		nz,.CONTROLA_NUBE_7
		ld		a,CINEMATICA_NUBE_6_CADA_CICLOS
		ld		(CINEMATICA_NUBE_6_CONTADOR),a
		ld		a,(CINEMATICA_NUBE_6_X)
		inc		a
		cp		CINEMATICA_NUBE_6_X_FINAL
		jr		c,.GUARDA_X_NUBE_6
		ld		a,CINEMATICA_NUBE_6_X_INICIAL

.GUARDA_X_NUBE_6:

		ld		(CINEMATICA_NUBE_6_X),a
		call	PINTA_NUBE_6_CINEMATICA

.CONTROLA_NUBE_7:

		ld		a,(CINEMATICA_NUBE_7_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_7_CONTADOR),a
		ret		nz
		ld		a,CINEMATICA_NUBE_7_CADA_CICLOS
		ld		(CINEMATICA_NUBE_7_CONTADOR),a
		ld		a,(CINEMATICA_NUBE_7_X)
		inc		a
		cp		CINEMATICA_NUBE_7_X_FINAL
		jr		c,.GUARDA_X_NUBE_7
		ld		a,CINEMATICA_NUBE_7_X_INICIAL

.GUARDA_X_NUBE_7:

		ld		(CINEMATICA_NUBE_7_X),a
		jp		PINTA_NUBE_7_CINEMATICA

PREPARA_SPRITES_CINEMATICA_ACTUAL:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		1
		jr		z,.NUBES_Y_BANDERAS
		cp		3
		jr		z,.SOLO_BANDERAS
		jr		.OCULTA_SPRITES_CINEMATICA

.NUBES_Y_BANDERAS:

		call	PINTA_NUBE_CINEMATICA
		call	PINTA_NUBE_5_CINEMATICA
		call	PINTA_NUBE_3_CINEMATICA
		call	PINTA_NUBE_6_CINEMATICA
		call	PINTA_NUBE_7_CINEMATICA
		call	PINTA_BANDERA_CINEMATICA
		call	PINTA_NUBE_2_CINEMATICA
		jp		PINTA_NUBE_4_CINEMATICA

.SOLO_BANDERAS:

		call	OCULTA_NUBE_CINEMATICA
		jp		PINTA_BANDERA_CINEMATICA

.OCULTA_SPRITES_CINEMATICA:

		jp		OCULTA_BANDERA_CINEMATICA

PINTA_BANDERA_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		3
		jr		z,PINTA_BANDERA_CINEMATICA_Y30

		ld		a,(CINEMATICA_BANDERA_ESTADO)
		or		a
		jr		z,.FRAME_0
		cp		1
		jr		z,.FRAME_1

.FRAME_2:

		call	COPIA_COLORES_BANDERA_CINEMATICA_2
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_2
		jr		COPIA_ATRIBUTOS_BANDERA_CINEMATICA

.FRAME_0:

		call	COPIA_COLORES_BANDERA_CINEMATICA_0
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_0
		jr		COPIA_ATRIBUTOS_BANDERA_CINEMATICA

.FRAME_1:

		call	COPIA_COLORES_BANDERA_CINEMATICA_1
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_1
		jr		COPIA_ATRIBUTOS_BANDERA_CINEMATICA

PINTA_BANDERA_CINEMATICA_Y30:

		ld		a,(CINEMATICA_BANDERA_ESTADO)
		or		a
		jr		z,.FRAME_0_Y30
		cp		1
		jr		z,.FRAME_1_Y30

.FRAME_2_Y30:

		call	COPIA_COLORES_BANDERA_CINEMATICA_2
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_Y30_2
		jr		COPIA_ATRIBUTOS_BANDERA_CINEMATICA

.FRAME_0_Y30:

		call	COPIA_COLORES_BANDERA_CINEMATICA_0
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_Y30_0
		jr		COPIA_ATRIBUTOS_BANDERA_CINEMATICA

.FRAME_1_Y30:

		call	COPIA_COLORES_BANDERA_CINEMATICA_1
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_Y30_1

COPIA_ATRIBUTOS_BANDERA_CINEMATICA:

		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM
		ld		bc,8*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

OCULTA_BANDERA_CINEMATICA:

		call	OCULTA_NUBE_CINEMATICA
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_OCULTA
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM
		ld		bc,8*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

OCULTA_NUBE_CINEMATICA:

		ld		hl,ATRIBUTOS_NUBE_CINEMATICA_OCULTA
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+8*4
		ld		bc,16*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

COPIA_COLOR_SPRITE_MENU:

		ld		bc,16
		jp		PON_COLOR_2.sin_bc_impuesta

COPIA_COLORES_BANDERA_CINEMATICA_0:

		ld		hl,TABLA_COLORES_BANDERA_CINEMATICA_0
		jr		COPIA_COLORES_BANDERA_DESDE_TABLA

COPIA_COLORES_BANDERA_CINEMATICA_1:

		ld		hl,TABLA_COLORES_BANDERA_CINEMATICA_1
		jr		COPIA_COLORES_BANDERA_DESDE_TABLA

COPIA_COLORES_BANDERA_CINEMATICA_2:

		ld		hl,TABLA_COLORES_BANDERA_CINEMATICA_2

COPIA_COLORES_BANDERA_DESDE_TABLA:

		ld		a,8

.BUCLE_COLORES_BANDERA:

		push	af

		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		inc		hl
		push	de

		ld		e,(hl)
		inc		hl
		ld		d,(hl)
		inc		hl

		pop		bc
		push	hl

		ld		h,b
		ld		l,c
		call	COPIA_COLOR_SPRITE_MENU

		pop		hl
		pop		af
		dec		a
		jr		nz,.BUCLE_COLORES_BANDERA
		ret

TABLA_COLORES_BANDERA_CINEMATICA_0:

		dw		MENU_SPRITE_ATTR_01,MENU_SPRITE_COLORES_VRAM+0*16
		dw		MENU_SPRITE_ATTR_02,MENU_SPRITE_COLORES_VRAM+1*16
		dw		MENU_SPRITE_ATTR_03,MENU_SPRITE_COLORES_VRAM+2*16
		dw		MENU_SPRITE_ATTR_04,MENU_SPRITE_COLORES_VRAM+3*16
		dw		MENU_SPRITE_ATTR_05,MENU_SPRITE_COLORES_VRAM+4*16
		dw		MENU_SPRITE_ATTR_06,MENU_SPRITE_COLORES_VRAM+5*16
		dw		MENU_SPRITE_ATTR_17,MENU_SPRITE_COLORES_VRAM+6*16
		dw		MENU_SPRITE_ATTR_18,MENU_SPRITE_COLORES_VRAM+7*16

TABLA_COLORES_BANDERA_CINEMATICA_1:

		dw		MENU_SPRITE_ATTR_03,MENU_SPRITE_COLORES_VRAM+0*16
		dw		MENU_SPRITE_ATTR_04,MENU_SPRITE_COLORES_VRAM+1*16
		dw		MENU_SPRITE_ATTR_05,MENU_SPRITE_COLORES_VRAM+2*16
		dw		MENU_SPRITE_ATTR_06,MENU_SPRITE_COLORES_VRAM+3*16
		dw		MENU_SPRITE_ATTR_01,MENU_SPRITE_COLORES_VRAM+4*16
		dw		MENU_SPRITE_ATTR_02,MENU_SPRITE_COLORES_VRAM+5*16
		dw		MENU_SPRITE_ATTR_19,MENU_SPRITE_COLORES_VRAM+6*16
		dw		MENU_SPRITE_ATTR_20,MENU_SPRITE_COLORES_VRAM+7*16

TABLA_COLORES_BANDERA_CINEMATICA_2:

		dw		MENU_SPRITE_ATTR_05,MENU_SPRITE_COLORES_VRAM+0*16
		dw		MENU_SPRITE_ATTR_06,MENU_SPRITE_COLORES_VRAM+1*16
		dw		MENU_SPRITE_ATTR_01,MENU_SPRITE_COLORES_VRAM+2*16
		dw		MENU_SPRITE_ATTR_02,MENU_SPRITE_COLORES_VRAM+3*16
		dw		MENU_SPRITE_ATTR_03,MENU_SPRITE_COLORES_VRAM+4*16
		dw		MENU_SPRITE_ATTR_04,MENU_SPRITE_COLORES_VRAM+5*16
		dw		MENU_SPRITE_ATTR_21,MENU_SPRITE_COLORES_VRAM+6*16
		dw		MENU_SPRITE_ATTR_22,MENU_SPRITE_COLORES_VRAM+7*16

COPIA_COLORES_NUBES_SIMPLIFICADAS_CINEMATICA:

		ld		de,MENU_SPRITE_COLORES_VRAM+8*16
		ld		b,16

.BUCLE_COLORES_NUBE_SIMPLIFICADA:

		push	bc
		push	de
		ld		hl,MENU_SPRITE_ATTR_NUBE_BLANCA
		call	COPIA_COLOR_SPRITE_MENU
		pop		de
		ld		a,e
		add		16
		ld		e,a
		jr		nc,.COLOR_NUBE_1_SIN_ACARREO
		inc		d

.COLOR_NUBE_1_SIN_ACARREO:

		pop		bc
		djnz	.BUCLE_COLORES_NUBE_SIMPLIFICADA
		ret

PINTA_NUBE_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_SIMPLE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+8*4
		ld		bc,2*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

PINTA_NUBE_2_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_2_SIMPLE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_2_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+16*4
		ld		bc,2*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

PINTA_NUBE_3_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_3_SIMPLE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_3_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+12*4
		ld		bc,2*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

PINTA_NUBE_4_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_4_SIMPLE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_4_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+18*4
		ld		bc,2*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

PINTA_NUBE_5_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_5_SIMPLE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_5_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+10*4
		ld		bc,2*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

PINTA_NUBE_6_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_6_SIMPLE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_6_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+14*4
		ld		bc,2*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

PINTA_NUBE_7_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_7_SIMPLE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_7_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+20*4
		ld		bc,2*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

CREA_ATRIBUTOS_NUBE_SIMPLE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_ATRIBUTOS
		ld		a,(CINEMATICA_NUBE_X)
		ld		b,a
		ld		a,CINEMATICA_NUBE_Y
		ld		hl,TABLA_PATRONES_NUBE_A_ARRIBA_CINEMATICA
		jr		CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB

CREA_ATRIBUTOS_NUBE_2_SIMPLE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_2_ATRIBUTOS
		ld		a,(CINEMATICA_NUBE_2_X)
		ld		b,a
		ld		a,CINEMATICA_NUBE_2_Y
		ld		hl,TABLA_PATRONES_NUBE_B_ABAJO_CINEMATICA
		jr		CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB

CREA_ATRIBUTOS_NUBE_3_SIMPLE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_3_ATRIBUTOS
		ld		a,(CINEMATICA_NUBE_3_X)
		ld		b,a
		ld		a,CINEMATICA_NUBE_3_Y
		ld		hl,TABLA_PATRONES_NUBE_C_CINEMATICA
		jr		CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB

CREA_ATRIBUTOS_NUBE_4_SIMPLE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_4_ATRIBUTOS
		ld		a,(CINEMATICA_NUBE_4_X)
		ld		b,a
		ld		a,CINEMATICA_NUBE_4_Y
		ld		hl,TABLA_PATRONES_NUBE_A_ARRIBA_CINEMATICA
		jr		CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB

CREA_ATRIBUTOS_NUBE_5_SIMPLE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_5_ATRIBUTOS
		ld		a,(CINEMATICA_NUBE_5_X)
		ld		b,a
		ld		a,CINEMATICA_NUBE_5_Y
		ld		hl,TABLA_PATRONES_NUBE_A_ABAJO_CINEMATICA
		jr		CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB

CREA_ATRIBUTOS_NUBE_6_SIMPLE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_6_ATRIBUTOS
		ld		a,(CINEMATICA_NUBE_6_X)
		ld		b,a
		ld		a,CINEMATICA_NUBE_6_Y
		ld		hl,TABLA_PATRONES_NUBE_B_ARRIBA_CINEMATICA
		jr		CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB

CREA_ATRIBUTOS_NUBE_7_SIMPLE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_7_ATRIBUTOS
		ld		a,(CINEMATICA_NUBE_7_X)
		ld		b,a
		ld		a,CINEMATICA_NUBE_7_Y
		ld		hl,TABLA_PATRONES_NUBE_B_ABAJO_CINEMATICA
		jr		CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB

TABLA_PATRONES_NUBE_A_ARRIBA_CINEMATICA:

		db		CINEMATICA_NUBE_A_PATRON_0,CINEMATICA_NUBE_A_PATRON_1

TABLA_PATRONES_NUBE_A_ABAJO_CINEMATICA:

		db		CINEMATICA_NUBE_A_PATRON_2,CINEMATICA_NUBE_A_PATRON_3

TABLA_PATRONES_NUBE_B_ARRIBA_CINEMATICA:

		db		CINEMATICA_NUBE_B_PATRON_0,CINEMATICA_NUBE_B_PATRON_1

TABLA_PATRONES_NUBE_B_ABAJO_CINEMATICA:

		db		CINEMATICA_NUBE_B_PATRON_2,CINEMATICA_NUBE_B_PATRON_3

TABLA_PATRONES_NUBE_C_CINEMATICA:

		db		CINEMATICA_NUBE_C_PATRON_0,CINEMATICA_NUBE_C_PATRON_1

CREA_ATRIBUTOS_NUBE_DOS_SPRITES_DESDE_AB:

		ld		d,a
		ld		e,b
		ld		(ix+0),d
		ld		(ix+1),e
		ld		a,(hl)
		inc		hl
		ld		(ix+2),a
		ld		(ix+3),0
		ld		(ix+4),d
		ld		a,e
		add		16
		ld		(ix+5),a
		ld		a,(hl)
		ld		(ix+6),a
		ld		(ix+7),0
		ld		(ix+8),CINEMATICA_BANDERA_Y_OCULTA
		ld		(ix+9),0
		ld		(ix+10),CINEMATICA_NUBE_C_PATRON_0
		ld		(ix+11),0
		ld		(ix+12),CINEMATICA_BANDERA_Y_OCULTA
		ld		(ix+13),0
		ld		(ix+14),CINEMATICA_NUBE_C_PATRON_1
		ld		(ix+15),0
		ret

COMPRUEBA_SPACE_CINEMATICA:

		ld		a,8
		call	SNSMAT_RAM
		bit		0,a
		jr		z,.SPACE_PULSADO
		or		a
		ret

.SPACE_PULSADO:

		scf
		ret

FADE_OUT_MUSICA_CINEMATICA:

		ld		b,20
		call	ESPERA_CINEMATICA_B
		jp		PARA_MUSICA_MENU_PRESENTACION

CARGA_GRAFICOS_MENU_Y_CINEMATICA:

		call	CARGA_GRAFICOS_PRESENTACION_EN_PAGE_1
		ld		hl,DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_3
		call	DOCOPY
		call	VDPREADY

		call	CARGA_GRAFICOS_CINEMATICA_3_4_EN_PAGE_1
		ld		hl,DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_2
		call	DOCOPY
		call	VDPREADY

		jp		CARGA_GRAFICOS_CINEMATICA_1_2_EN_PAGE_1

CARGA_GRAFICOS_PRESENTACION_EN_PAGE_1:

		; Página 4 ROM -> primera mitad de VRAM page 1

		di
		ld		a,4
		ld		(DIRPA2),a

		ld		hl,PANTALLA_DE_PRESENTACION_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta


		; Página 5 ROM -> segunda mitad de VRAM page 1
		; Copiamos sólo hasta donde empiezan las paletas.

		ld		a,5
		ld		(DIRPA2),a

		ld		hl,PANTALLA_DE_PRESENTACION_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret

CARGA_GRAFICOS_CINEMATICA_1_2_EN_PAGE_1:

		di
		ld		a,60
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_1_2_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,61
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_1_2_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret

CARGA_GRAFICOS_CINEMATICA_3_4_EN_PAGE_1:

		di
		ld		a,62
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_3_4_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,63
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_3_4_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret

ACTIVA_SPRITES_16X16_MENU:

        ld      a,(RG1SAV)
        or      00000010b          ; bit 1 = sprites 16x16
        and     11111110b          ; bit 0 = sin ampliación x2
        ld      (RG1SAV),a

        ld      b,a
        ld      c,1
        call    WRTVDP

        ret

CARGA_SPRITES_Y_COLORES_MENU:

		call	PAGE_10_A_SEGMENT_2

		ld		ix,TABLA_CARGA_SPRITES_MENU
		ld		a,22

.BUCLE_CARGA_SPRITES_MENU:

		push	af

		ld		l,(ix+0)
		ld		h,(ix+1)
		ld		e,(ix+4)
		ld		d,(ix+5)
		push	ix
		call	CARGA_PATRON_MENU_16X16
		pop		ix

		ld		l,(ix+2)
		ld		h,(ix+3)
		ld		e,(ix+6)
		ld		d,(ix+7)
		ld		bc,16
		push	ix
		call	PON_COLOR_2.sin_bc_impuesta
		pop		ix

		ld		bc,8
		add		ix,bc

		pop		af
		dec		a
		jr		nz,.BUCLE_CARGA_SPRITES_MENU
		ret

TABLA_CARGA_SPRITES_MENU:

		dw		MENU_SPRITE_MASK_01,MENU_SPRITE_ATTR_01,MENU_SPRITE_PATRONES_VRAM+0*32,MENU_SPRITE_COLORES_VRAM+0*16
		dw		MENU_SPRITE_MASK_02,MENU_SPRITE_ATTR_02,MENU_SPRITE_PATRONES_VRAM+1*32,MENU_SPRITE_COLORES_VRAM+1*16
		dw		MENU_SPRITE_MASK_03,MENU_SPRITE_ATTR_03,MENU_SPRITE_PATRONES_VRAM+2*32,MENU_SPRITE_COLORES_VRAM+2*16
		dw		MENU_SPRITE_MASK_04,MENU_SPRITE_ATTR_04,MENU_SPRITE_PATRONES_VRAM+3*32,MENU_SPRITE_COLORES_VRAM+3*16
		dw		MENU_SPRITE_MASK_05,MENU_SPRITE_ATTR_05,MENU_SPRITE_PATRONES_VRAM+4*32,MENU_SPRITE_COLORES_VRAM+4*16
		dw		MENU_SPRITE_MASK_06,MENU_SPRITE_ATTR_06,MENU_SPRITE_PATRONES_VRAM+5*32,MENU_SPRITE_COLORES_VRAM+5*16
		dw		MENU_SPRITE_MASK_07,MENU_SPRITE_ATTR_07,MENU_SPRITE_PATRONES_VRAM+6*32,MENU_SPRITE_COLORES_VRAM+6*16
		dw		MENU_SPRITE_MASK_08,MENU_SPRITE_ATTR_08,MENU_SPRITE_PATRONES_VRAM+7*32,MENU_SPRITE_COLORES_VRAM+7*16
		dw		MENU_SPRITE_MASK_09,MENU_SPRITE_ATTR_09,MENU_SPRITE_PATRONES_VRAM+8*32,MENU_SPRITE_COLORES_VRAM+8*16
		dw		MENU_SPRITE_MASK_10,MENU_SPRITE_ATTR_10,MENU_SPRITE_PATRONES_VRAM+9*32,MENU_SPRITE_COLORES_VRAM+9*16
		dw		MENU_SPRITE_MASK_11,MENU_SPRITE_ATTR_11,MENU_SPRITE_PATRONES_VRAM+10*32,MENU_SPRITE_COLORES_VRAM+10*16
		dw		MENU_SPRITE_MASK_12,MENU_SPRITE_ATTR_12,MENU_SPRITE_PATRONES_VRAM+11*32,MENU_SPRITE_COLORES_VRAM+11*16
		dw		MENU_SPRITE_MASK_13,MENU_SPRITE_ATTR_13,MENU_SPRITE_PATRONES_VRAM+12*32,MENU_SPRITE_COLORES_VRAM+12*16
		dw		MENU_SPRITE_MASK_14,MENU_SPRITE_ATTR_14,MENU_SPRITE_PATRONES_VRAM+13*32,MENU_SPRITE_COLORES_VRAM+13*16
		dw		MENU_SPRITE_MASK_15,MENU_SPRITE_ATTR_15,MENU_SPRITE_PATRONES_VRAM+14*32,MENU_SPRITE_COLORES_VRAM+14*16
		dw		MENU_SPRITE_MASK_16,MENU_SPRITE_ATTR_16,MENU_SPRITE_PATRONES_VRAM+15*32,MENU_SPRITE_COLORES_VRAM+15*16
		dw		MENU_SPRITE_MASK_17,MENU_SPRITE_ATTR_17,MENU_SPRITE_PATRONES_VRAM+16*32,MENU_SPRITE_COLORES_VRAM+16*16
		dw		MENU_SPRITE_MASK_18,MENU_SPRITE_ATTR_18,MENU_SPRITE_PATRONES_VRAM+17*32,MENU_SPRITE_COLORES_VRAM+17*16
		dw		MENU_SPRITE_MASK_19,MENU_SPRITE_ATTR_19,MENU_SPRITE_PATRONES_VRAM+18*32,MENU_SPRITE_COLORES_VRAM+18*16
		dw		MENU_SPRITE_MASK_20,MENU_SPRITE_ATTR_20,MENU_SPRITE_PATRONES_VRAM+19*32,MENU_SPRITE_COLORES_VRAM+19*16
		dw		MENU_SPRITE_MASK_21,MENU_SPRITE_ATTR_21,MENU_SPRITE_PATRONES_VRAM+20*32,MENU_SPRITE_COLORES_VRAM+20*16
		dw		MENU_SPRITE_MASK_22,MENU_SPRITE_ATTR_22,MENU_SPRITE_PATRONES_VRAM+21*32,MENU_SPRITE_COLORES_VRAM+21*16

CARGA_PATRON_MENU_16X16:

		ld		bc,32
		jp		PON_COLOR_2.sin_bc_impuesta


PONE_PRIMERA_PALETA_PRESENTACION:

		ld		hl,PALETA_MENU_LOCAL_FADE_IN
		jp		SETPALETE_CINEMATICA

INICIA_MUSICA_MENU_PRESENTACION:

		call	stpmus

		ld		a,39
		ld		(MUSICA_BEST_ON),a
		
        ld      a,39
        call    CHANGE_BANK_2

		ld		hl,M_MENU
		ld		(MUSIC_ON),hl

		call	INICIAMOS_MUSICA

		di
		call	strmus

		; strmus instala musint directamente en HTIMI.
		; Para el menú necesitamos envolverla para forzar page 39.

		call	INSTALA_INTERRUPCION_MUSICA_MENU
		ei

		call	PAGE_10_A_SEGMENT_2

		ret

INSTALA_INTERRUPCION_MUSICA_MENU:

		ld		a,#C3
		ld		(HTIMI),a
		ld		hl,INTERRUPCION_MUSICA_MENU
		ld		(HTIMI+1),hl
		ret


INTERRUPCION_MUSICA_MENU:

		ld		a,(DIRPA2)
		push	af
		ld		a,39
		ld		(DIRPA2),a

		call	musint

		pop		af
		ld		(DIRPA2),a

		ret

PARA_MUSICA_MENU_PRESENTACION:

		call	stpmus

		xor		a
		ld		(MUSICA_BEST_ON),a

		call	PAGE_10_A_SEGMENT_2

		ret

FADE_IN_PRESENTACION:

		; La primera paleta ya se ha puesto antes.
		; Empezamos en la segunda.

		ld		hl,PALETA_MENU_LOCAL_FADE_IN+32
		ld		e,6

.BUCLE_FADE_IN_PRESENTACION:

		call	SETPALETE_CINEMATICA

		push	hl
		push	de
		ld		a,6
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		pop		de
		pop		hl

		dec		e
		jp		nz,.BUCLE_FADE_IN_PRESENTACION

		; Dejamos la paleta final fija por seguridad.

		ld		hl,PALETA_MENU_LOCAL_FIJA
		jp		SETPALETE_CINEMATICA

FADE_OUT_PRESENTACION:

		ld		hl,PALETA_MENU_LOCAL_FADE_OUT
		ld		e,7

.BUCLE_FADE_OUT_PRESENTACION:

		call	SETPALETE_CINEMATICA

		push	hl
		push	de
		ld		a,6
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		pop		de
		pop		hl

		dec		e
		jp		nz,.BUCLE_FADE_OUT_PRESENTACION

		ret

LIMPIA_VRAM_SALIDA_MENU:

		ld		hl,DATOS_LIMPIA_VRAM_MENU_PAGE_0
		call	DOCOPY
		call	VDPREADY
		ld		hl,DATOS_LIMPIA_VRAM_MENU_PAGE_1
		call	DOCOPY
		call	VDPREADY
		ld		hl,DATOS_LIMPIA_VRAM_MENU_PAGE_2
		call	DOCOPY
		call	VDPREADY
		ld		hl,DATOS_LIMPIA_VRAM_MENU_PAGE_3
		call	DOCOPY
		jp		VDPREADY

DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_3:

		dw		#0000,#0100
		dw		#0000,#0300
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_2:

		dw		#0000,#0100
		dw		#0000,#0200
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_0:

		dw		#0000,#0300
		dw		#0000,#0000
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_1:

		dw		#0000,#0300
		dw		#0000,#0100
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_NEGRO_PAGE_0_CINEMATICA:

		; Borra solo la zona visible util de page 0.
		; No baja hasta Y=232/#7400 ni Y=240/#7800,
		; donde viven colores/patrones de sprites.
		dw		#0000,#0000
		dw		#0000,#0000
		dw		#0100,#00D5
		db		#00,#00,11000000b

DATOS_LIMPIA_VRAM_MENU_PAGE_0:

		dw		#0000,#0000
		dw		#0000,#0000
		dw		#0100,#0100
		db		#00,#00,11000000b

DATOS_LIMPIA_VRAM_MENU_PAGE_1:

		dw		#0000,#0000
		dw		#0000,#0100
		dw		#0100,#0100
		db		#00,#00,11000000b

DATOS_LIMPIA_VRAM_MENU_PAGE_2:

		dw		#0000,#0000
		dw		#0000,#0200
		dw		#0100,#0100
		db		#00,#00,11000000b

DATOS_LIMPIA_VRAM_MENU_PAGE_3:

		dw		#0000,#0000
		dw		#0000,#0300
		dw		#0100,#0100
		db		#00,#00,11000000b

DATOS_COPY_PARPADEO_CINEMATICA_2_ORIGINAL:

		dw		#0048,#0200+36
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_ORIGINAL
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

DATOS_COPY_PARPADEO_CINEMATICA_2_A:

		dw		#0000,#0200+115
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_FRAMES
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

DATOS_COPY_PARPADEO_CINEMATICA_2_B:

		dw		#002F,#0200+115
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_FRAMES
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

DATOS_COPY_PARPADEO_CINEMATICA_2_C:

		dw		#005E,#0200+115
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_FRAMES
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

DATOS_COPY_PARPADEO_CINEMATICA_2_D:

		dw		#008D,#0200+115
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_FRAMES
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

ATRIBUTOS_BANDERA_CINEMATICA_0:

		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_0_1,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_0_2,#00

ATRIBUTOS_BANDERA_CINEMATICA_1:

		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_1_1,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_1_2,#00

ATRIBUTOS_BANDERA_CINEMATICA_2:

		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_2_1,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_2_2,#00


ATRIBUTOS_BANDERA_CINEMATICA_Y30_0:

		db		51,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		51,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		44,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		44,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		62,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		62,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		64,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_0_1,#00
		db		64,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_0_2,#00

ATRIBUTOS_BANDERA_CINEMATICA_Y30_1:

		db		51,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		51,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		44,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		44,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		62,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		62,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		64,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_1_1,#00
		db		64,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_1_2,#00

ATRIBUTOS_BANDERA_CINEMATICA_Y30_2:

		db		51,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		51,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		44,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		44,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		62,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		62,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		64,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_2_1,#00
		db		64,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_2_2,#00


ATRIBUTOS_BANDERA_CINEMATICA_OCULTA:

		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERITA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERITA_PATRON_0_2,#00

ATRIBUTOS_NUBE_CINEMATICA_OCULTA:

		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_3,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_3,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_3_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_3_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_3_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_1,#00

DATOS_COPY_CINEMATICA_1:

		dw		#0000,#0100
		dw		#0000,#0000
		dw		#0100,#008C
		db		#00,#00,10010000b

DATOS_COPY_CINEMATICA_2:

		dw		#0000,#0100+140
		dw		#0000,#0000+30
		dw		#0100,#004C
		db		#00,#00,10010000b

DATOS_COPY_CINEMATICA_3:

		dw		#0000,#0200
		dw		#0000,#0000+20
		dw		#0100,#0072
		db		#00,#00,10010000b

DATOS_COPY_CINEMATICA_4:

		dw		#0000,#0200+138
		dw		#0027,#0000+30
		dw		#00B2,#0059
		db		#00,#00,10010000b

DATOS_COPY_COPI_CINEMATICA_5_0:

		dw		#000A,#0200+155
		dw		#0030,#0000+47
		dw		#0027,#001D
		db		#00,#00,10010000b

DATOS_COPY_COPI_CINEMATICA_5_1:

		dw		#00B2,#0200+138
		dw		#0030,#0000+47
		dw		#0027,#001D
		db		#00,#00,10010000b

DATOS_COPY_COPI_CINEMATICA_5_2:

		dw		#00B2,#0200+167
		dw		#0030,#0000+47
		dw		#0027,#001D
		db		#00,#00,10010000b

DATOS_COPY_COPI_CINEMATICA_5_3:

		dw		#00B2,#0200+196
		dw		#0030,#0000+47
		dw		#0027,#001D
		db		#00,#00,10010000b

ROTATIVO_Y_PRESENTACION                  equ     195

; Cada cuántos frames se actualiza el rotativo.
; 1 = cada frame, 2 = cada dos frames, etc.
ROTATIVO_VELOCIDAD_PRESENTACION          equ     3

; El nuevo rotativo avanza copiando la franja 2 píxeles a la izquierda.
; Cada letra mide 6 píxeles, así que se introduce en 3 pasos:
;   paso 0 -> X=254
;   paso 1 -> X=252
;   paso 2 -> X=250
ROTATIVO_PIXELES_POR_PASO_PRESENTACION   equ     2
ROTATIVO_PASOS_POR_LETRA_PRESENTACION    equ     3
ROTATIVO_X_ENTRADA_PRESENTACION          equ     254
ROTATIVO_ANCHO_SCROLL_PRESENTACION       equ     254
ROTATIVO_ALTO_PRESENTACION               equ     8

; Cuando se acaba el texto, metemos espacios hasta que toda la cola sale
; por la izquierda. 43 espacios * 6 píxeles = 258 píxeles.
ROTATIVO_ESPACIOS_SALIDA_PRESENTACION    equ     43


INICIALIZA_ROTATIVO_PRESENTACION:

        xor     a
        ld      (ROTATIVO_CONTADOR_PRESENTACION),a
        ld      (ROTATIVO_PAGINA_VISIBLE_PRESENTACION),a
        ld      (ROTATIVO_REPETICION_LETRA_PRESENTACION),a
        ld      (ROTATIVO_MODO_SALIDA_PRESENTACION),a

        ld      a,ROTATIVO_ESPACIOS_SALIDA_PRESENTACION
        ld      (ROTATIVO_PASOS_SALIDA_PRESENTACION),a

        ld      hl,TEXTO_ROTATIVO_PRESENTACION
        ld      (ROTATIVO_PUNTERO_TEXTO_PRESENTACION),hl

        ; Dejamos limpia la franja en las dos páginas. Así el primer paso
        ; parte de una zona negra y la página oculta no hereda basura.

        ld      hl,DATOS_NEGRO_ROTATIVO_EN_PAGE_0
        call    DOCOPY
        call    VDPREADY

        ld      hl,DATOS_NEGRO_ROTATIVO_EN_PAGE_1
        call    DOCOPY
        jp      VDPREADY


ACTUALIZA_ROTATIVO_PRESENTACION:

        ld      a,(ROTATIVO_CONTADOR_PRESENTACION)
        inc     a
        cp      ROTATIVO_VELOCIDAD_PRESENTACION
        jr      nc,.MUEVE_ROTATIVO_PRESENTACION

        ld      (ROTATIVO_CONTADOR_PRESENTACION),a
        ret


.MUEVE_ROTATIVO_PRESENTACION:

        xor     a
        ld      (ROTATIVO_CONTADOR_PRESENTACION),a

        ; 1 - Copiamos el rotativo ya visible hacia la página oculta,
        ;     desplazándolo 2 píxeles a la izquierda.
        ;     OJO: se usa la visible como origen para que el doble buffer
        ;     no vaya alternando dos estados distintos del scroll.

        call    COPIA_SCROLL_ROTATIVO_A_PAGE_OCULTA

        ; 2 - Borramos en la página oculta la parte derecha que ha quedado libre.

        call    BORRA_DERECHA_ROTATIVO_EN_PAGE_OCULTA

        ; 3 - Pintamos la letra que toca. La misma letra se pinta 3 veces,
        ;     cada vez 2 píxeles más a la izquierda: 254, 252 y 250.

        call    PINTA_ENTRADA_LETRA_ROTATIVO

        ; 4 - Mostramos la página que acabamos de preparar.

        jp      MUESTRA_PAGE_OCULTA_ROTATIVO


OBTIENE_PAGE_OCULTA_ROTATIVO:

        ld      a,(ROTATIVO_PAGINA_VISIBLE_PRESENTACION)
        xor     1
        ret


OBTIENE_Y_ROTATIVO_DESDE_A_EN_HL:

        or      a
        ld      hl,ROTATIVO_Y_PRESENTACION
        ret     z
        ld      hl,#0100+ROTATIVO_Y_PRESENTACION
        ret


COPIA_SCROLL_ROTATIVO_A_PAGE_OCULTA:

        ld      ix,DATOS_COPY_SCROLL_ROTATIVO_PRESENTACION

        ; Origen X = 2.

        ld      (ix+0),2
        ld      (ix+1),0

        ; Origen Y = página actualmente visible + Y del rotativo.

        ld      a,(ROTATIVO_PAGINA_VISIBLE_PRESENTACION)
        call    OBTIENE_Y_ROTATIVO_DESDE_A_EN_HL
        ld      (ix+2),l
        ld      (ix+3),h

        ; Destino X = 0.

        ld      (ix+4),0
        ld      (ix+5),0

        ; Destino Y = página oculta + Y del rotativo.

        call    OBTIENE_PAGE_OCULTA_ROTATIVO
        call    OBTIENE_Y_ROTATIVO_DESDE_A_EN_HL
        ld      (ix+6),l
        ld      (ix+7),h

        ; Ancho = 254, alto = 8, comando HMMM.

        ld      (ix+8),ROTATIVO_ANCHO_SCROLL_PRESENTACION
        ld      (ix+9),0
        ld      (ix+10),ROTATIVO_ALTO_PRESENTACION
        ld      (ix+11),0
        ld      (ix+12),#00
        ld      (ix+13),#00
        ld      (ix+14),11010000b

        ld      hl,DATOS_COPY_SCROLL_ROTATIVO_PRESENTACION
        call    DOCOPY
        jp      VDPREADY


BORRA_DERECHA_ROTATIVO_EN_PAGE_OCULTA:

        ld      ix,DATOS_NEGRO_DERECHA_ROTATIVO_PRESENTACION

        ; Para HMMV el origen no importa.

        ld      (ix+0),0
        ld      (ix+1),0
        ld      (ix+2),0
        ld      (ix+3),0

        ; Destino X = 254.

        ld      (ix+4),ROTATIVO_X_ENTRADA_PRESENTACION
        ld      (ix+5),0

        ; Destino Y = página oculta + Y del rotativo.

        call    OBTIENE_PAGE_OCULTA_ROTATIVO
        call    OBTIENE_Y_ROTATIVO_DESDE_A_EN_HL
        ld      (ix+6),l
        ld      (ix+7),h

        ; Ancho = 2, alto = 8, color 0, comando HMMV.

        ld      (ix+8),ROTATIVO_PIXELES_POR_PASO_PRESENTACION
        ld      (ix+9),0
        ld      (ix+10),ROTATIVO_ALTO_PRESENTACION
        ld      (ix+11),0
        ld      (ix+12),#00
        ld      (ix+13),#00
        ld      (ix+14),11000000b

        ld      hl,DATOS_NEGRO_DERECHA_ROTATIVO_PRESENTACION
        call    DOCOPY
        jp      VDPREADY


PINTA_ENTRADA_LETRA_ROTATIVO:

        call    OBTIENE_PAGE_OCULTA_ROTATIVO
        ld      (ACPAGE),a
        call    OBTIENE_DESTINO_Y_ROTATIVO_DESDE_A

        ; X = 254 - repeticion*2

        ld      a,(ROTATIVO_REPETICION_LETRA_PRESENTACION)
        add     a,a
        ld      c,a
        ld      a,ROTATIVO_X_ENTRADA_PRESENTACION
        sub     c
        ld      l,a
        ld      h,0

        push    hl
        push    de
        call    OBTIENE_CARACTER_ROTATIVO_ACTUAL
        pop     de
        pop     hl
        call    PINTA_LETRA_MENU_ROTATIVO_PARCIAL_EN_DESTINO
        jp      AVANZA_ESTADO_ROTATIVO_PRESENTACION


PINTA_LETRA_MENU_ROTATIVO_PARCIAL_EN_DESTINO:

        ; Entrada:
        ;   A  = caracter a pintar
        ;   HL = X destino: 254, 252 o 250
        ;   DE = Y destino con page incluida
        ;
        ; Copiamos solo la parte visible de la letra:
        ;   repeticion 0 -> ancho 2
        ;   repeticion 1 -> ancho 4
        ;   repeticion 2 -> ancho 6
        ;
        ; Así respetamos la entrada progresiva sin escribir fuera de X=255.

        push    hl
        push    de
        call    CALCULA_ORIGEN_X_LETRA_MENU

        ld      ix,DATOS_DEL_TILE_PARA_COPY
        ld      (ix+0),l
        ld      (ix+1),h
        ld      (ix+2),e
        ld      (ix+3),d

        pop     hl
        ld      (ix+6),l
        ld      (ix+7),h

        pop     hl
        ld      (ix+4),l
        ld      (ix+5),h

        ld      a,(ROTATIVO_REPETICION_LETRA_PRESENTACION)
        inc     a
        add     a,a
        ld      (ix+8),a
        ld      (ix+9),0
        ld      (ix+10),MENU_LETRA_ALTO
        ld      (ix+11),0
        ld      (ix+12),#00
        ld      (ix+13),#00
        ld      (ix+14),11010000b

        call    HL_DATOS_DEL_COPY
        jp      VDPREADY


OBTIENE_CARACTER_ROTATIVO_ACTUAL:

        ; Si ya se ha terminado el texto, seguimos metiendo espacios
        ; hasta que la cola del rotativo salga por completo.

        ld      a,(ROTATIVO_MODO_SALIDA_PRESENTACION)
        or      a
        jr      nz,.PINTA_ESPACIO

        ld      hl,(ROTATIVO_PUNTERO_TEXTO_PRESENTACION)
        call    OBTIENE_CARACTER_MENU_DESDE_HL
        or      a
        ret     nz

        ; Hemos llegado al 0 final del texto: activamos modo salida.

        ld      a,1
        ld      (ROTATIVO_MODO_SALIDA_PRESENTACION),a
        ld      a,ROTATIVO_ESPACIOS_SALIDA_PRESENTACION
        ld      (ROTATIVO_PASOS_SALIDA_PRESENTACION),a

.PINTA_ESPACIO:

        ld      a,32
        ret


AVANZA_ESTADO_ROTATIVO_PRESENTACION:

        ld      a,(ROTATIVO_REPETICION_LETRA_PRESENTACION)
        inc     a
        cp      ROTATIVO_PASOS_POR_LETRA_PRESENTACION
        jr      nc,.LETRA_COMPLETA

        ld      (ROTATIVO_REPETICION_LETRA_PRESENTACION),a
        ret


.LETRA_COMPLETA:

        xor     a
        ld      (ROTATIVO_REPETICION_LETRA_PRESENTACION),a

        ld      a,(ROTATIVO_MODO_SALIDA_PRESENTACION)
        or      a
        jr      nz,.AVANZA_SALIDA

        ld      hl,(ROTATIVO_PUNTERO_TEXTO_PRESENTACION)
        call    OBTIENE_CARACTER_MENU_DESDE_HL
        inc     hl
        ld      a,b
        or      a
        jr      z,.GUARDA_PUNTERO_TEXTO
        inc     hl

.GUARDA_PUNTERO_TEXTO:
        ld      (ROTATIVO_PUNTERO_TEXTO_PRESENTACION),hl
        ret


.AVANZA_SALIDA:

        ld      a,(ROTATIVO_PASOS_SALIDA_PRESENTACION)
        dec     a
        ld      (ROTATIVO_PASOS_SALIDA_PRESENTACION),a
        ret     nz

        ; Ya ha salido toda la cola. Si nadie ha tocado nada, lanzamos demo.

		call	PAGE_10_A_SEGMENT_2
		jp		ACTIVA_DEMO_ROTATIVO


MUESTRA_PAGE_OCULTA_ROTATIVO:

        call    OBTIENE_PAGE_OCULTA_ROTATIVO

        push    af
        call    SETPAGE
        pop     af

        ld      (ROTATIVO_PAGINA_VISIBLE_PRESENTACION),a
        ld      (ACPAGE),a

        ret


; Rutinas antiguas del rotativo por repintado completo eliminadas.
; Ahora el movimiento se hace con copia de 2 píxeles + entrada parcial de letra.

DATOS_NEGRO_ROTATIVO_EN_PAGE_0:

        ; Rectángulo negro en page 0.
        ; X=0, Y=ROTATIVO_Y_PRESENTACION, ancho 256, alto 8.

        dw      #0000,#0000
        dw      #0000,#0000+ROTATIVO_Y_PRESENTACION
        dw      #0100,#0008
        db      #00,#00,11000000b


DATOS_NEGRO_ROTATIVO_EN_PAGE_1:

        ; Rectángulo negro en page 1.
        ; X=0, Y=ROTATIVO_Y_PRESENTACION, ancho 256, alto 8.

        dw      #0000,#0000
        dw      #0000,#0100+ROTATIVO_Y_PRESENTACION
        dw      #0100,#0008
        db      #00,#00,11000000b


; Editar estas lineas al sacar una version nueva.
; Regla del porcentaje: cada fase vale 2, cada enemigo y bloque auxiliar vale 1.
; EN TOTAL HAY 
; 5 PUNTOS DE 2(FASES) 5 HECHOS
; 6 PUNTOS DE 2(ENEMIGOS) 6 HECHOS
; 4 PUNTOS DE 1(LOGO, MENU, ANIMACION PRESENTACION Y ANIMACION CIERRE) 4 HECHO
; PUNTOS ACTUALES = (5+6)*2 + 4*1 = 26, PORCENTAJE ACTUAL = 26/26 = 100% APROXIMADAMENTE

TEXTO_ROTATIVO_PRESENTACION:

		db		"BLUE WARRIOR II   -   Beta version 5.01.76  -  09-07-2026 - 98 por ciento - (C) Digital Moai",0

TEXTO_ROTATIVO_PRESENTACION_FIN:

INICIALIZA_TRUCOS_PRESENTACION:

		xor		a
		ld		(TRUCO_FASES_ACTIVO),a
		ld		(TRUCO_CORAZONES_ACTIVO),a
		ld		(TRUCO_ELSLUCKIS_POS),a
		ld		(TRUCO_CARAMBALAN_POS),a
		ld		(TRUCO_TECLA_PRESENTACION),a
		ret


ACTUALIZA_TRUCOS_PRESENTACION:

		call	LEE_TECLA_TRUCO_PRESENTACION
		or		a
		ret		z

		ld		c,a
		push	bc
		call	ACTUALIZA_TRUCO_ELSLUCKIS
		pop		bc
		jp		ACTUALIZA_TRUCO_CARAMBALAN


ACTUALIZA_TRUCO_ELSLUCKIS:

		ld		hl,TEXTO_TRUCO_ELSLUCKIS
		ld		a,(TRUCO_ELSLUCKIS_POS)
		ld		e,a
		ld		d,0
		add		hl,de
		ld		a,(hl)
		cp		c
		jr		z,.ACIERTO

		ld		a,c
		cp		"E"
		jr		z,.PRIMERA_LETRA
		xor		a
		ld		(TRUCO_ELSLUCKIS_POS),a
		ret

.PRIMERA_LETRA:

		ld		a,1
		ld		(TRUCO_ELSLUCKIS_POS),a
		ret

.ACIERTO:

		ld		a,(TRUCO_ELSLUCKIS_POS)
		inc		a
		ld		(TRUCO_ELSLUCKIS_POS),a
		ld		e,a
		ld		d,0
		ld		hl,TEXTO_TRUCO_ELSLUCKIS
		add		hl,de
		ld		a,(hl)
		or		a
		ret		nz

		ld		a,1
		ld		(TRUCO_FASES_ACTIVO),a
		xor		a
		ld		(TRUCO_ELSLUCKIS_POS),a
		jp		FLASH_TRUCO_PRESENTACION


ACTUALIZA_TRUCO_CARAMBALAN:

		ld		hl,TEXTO_TRUCO_CARAMBALAN
		ld		a,(TRUCO_CARAMBALAN_POS)
		ld		e,a
		ld		d,0
		add		hl,de
		ld		a,(hl)
		cp		c
		jr		z,.ACIERTO

		ld		a,c
		cp		"C"
		jr		z,.PRIMERA_LETRA
		xor		a
		ld		(TRUCO_CARAMBALAN_POS),a
		ret

.PRIMERA_LETRA:

		ld		a,1
		ld		(TRUCO_CARAMBALAN_POS),a
		ret

.ACIERTO:

		ld		a,(TRUCO_CARAMBALAN_POS)
		inc		a
		ld		(TRUCO_CARAMBALAN_POS),a
		ld		e,a
		ld		d,0
		ld		hl,TEXTO_TRUCO_CARAMBALAN
		add		hl,de
		ld		a,(hl)
		or		a
		ret		nz

		ld		a,1
		ld		(TRUCO_CORAZONES_ACTIVO),a
		xor		a
		ld		(TRUCO_CARAMBALAN_POS),a
		jp		FLASH_TRUCO_PRESENTACION


LEE_TECLA_TRUCO_PRESENTACION:

		call	LEE_TECLA_ACTUAL_TRUCO_PRESENTACION
		ld		b,a
		or		a
		jr		nz,.HAY_TECLA

		ld		(TRUCO_TECLA_PRESENTACION),a
		ret

.HAY_TECLA:

		ld		a,(TRUCO_TECLA_PRESENTACION)
		cp		b
		jr		nz,.TECLA_NUEVA
		xor		a
		ret

.TECLA_NUEVA:

		ld		a,b
		ld		(TRUCO_TECLA_PRESENTACION),a
		ret


LEE_TECLA_ACTUAL_TRUCO_PRESENTACION:

		ld		ix,TABLA_TECLAS_TRUCO_PRESENTACION

.BUCLE_TECLAS:

		ld		a,(ix+0)
		cp		#FF
		jr		z,.SIN_TECLA
		call	SNSMAT_RAM
		ld		b,a
		ld		a,(ix+1)
		and		b
		jr		z,.TECLA_ENCONTRADA
		ld		de,3
		add		ix,de
		jr		.BUCLE_TECLAS

.TECLA_ENCONTRADA:

		ld		a,(ix+2)
		ret

.SIN_TECLA:

		ld		c,9
		ld		e,0

.BUSCA_CUALQUIER_TECLA:

		ld		a,e
		call	SNSMAT_RAM
		cp		#FF
		jr		nz,.TECLA_DESCONOCIDA
		inc		e
		dec		c
		jr		nz,.BUSCA_CUALQUIER_TECLA

		xor		a
		ret

.TECLA_DESCONOCIDA:

		ld		a,#FE
		ret


FLASH_TRUCO_PRESENTACION:

		ld		hl,PALETA_BLANCA_PRESENTACION
		call	SETPALETE_CINEMATICA
		ld		a,5
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		ld		hl,PALETA_MENU_LOCAL_FIJA
		jp		SETPALETE_CINEMATICA


TEXTO_TRUCO_ELSLUCKIS:

		db		"ELSLUCKIS",0

TEXTO_TRUCO_CARAMBALAN:

		db		"CARAMBALAN",0

TABLA_TECLAS_TRUCO_PRESENTACION:

		db		0,00000010b,"1"
		db		0,00000100b,"2"
		db		0,00001000b,"3"
		db		0,00010000b,"4"
		db		0,00100000b,"5"
		db		2,01000000b,"A"
		db		2,10000000b,"B"
		db		3,00000001b,"C"
		db		3,00000100b,"E"
		db		3,01000000b,"I"
		db		4,00000001b,"K"
		db		4,00000010b,"L"
		db		4,00000100b,"M"
		db		4,00001000b,"N"
		db		4,10000000b,"R"
		db		5,00000001b,"S"
		db		5,00000100b,"U"
		db		8,00000001b," "
		db		#FF,0,0

PALETA_BLANCA_PRESENTACION:

		db		$77,$07,$77,$07,$77,$07,$77,$07
		db		$77,$07,$77,$07,$77,$07,$77,$07
		db		$77,$07,$77,$07,$77,$07,$77,$07
		db		$77,$07,$77,$07,$77,$07,$77,$07


PULSA_UNA_TECLA_PARA_EMPEZAR:

		call	ACTUALIZA_TRUCOS_PRESENTACION

		xor		a
		call	GTTRIG_RAM
		or		a
		jp		nz,INICIA_EN_FASE_1

		ld		a,0
		call	SNSMAT_RAM
		bit		1,a
		jp		z,INICIA_EN_FASE_1

		; ld		a,(TRUCO_FASES_ACTIVO)		;XXXXXXXXXX Sin esto se libera el ir a fase directo con números
		; or		a							
		; jp		z,.NO_MIRA_FASES_DIRECTAS	

		ld		a,0
		call	SNSMAT_RAM
		bit		2,a
		jp		z,INICIA_EN_FASE_2

		ld		a,0
		call	SNSMAT_RAM
		bit		3,a
		jp		z,INICIA_EN_FASE_3

		ld		a,0
		call	SNSMAT_RAM
		bit		4,a
		jp		z,INICIA_EN_FASE_4

		ld		a,0
		call	SNSMAT_RAM
		bit		5,a
		jp		z,INICIA_EN_FASE_5

.NO_MIRA_FASES_DIRECTAS:

		halt
		call 	ACTUALIZA_ROTATIVO_PRESENTACION
		ld		a,(DEMO)
		or		a
		jp		nz,INICIA_EN_FASE_DIRECTA
		jp		PULSA_UNA_TECLA_PARA_EMPEZAR

INICIA_EN_FASE_1:

		ld		a,1
		ld		(FASE),a
		jp		SEGUIMOS

INICIA_EN_FASE_2:

		ld		a,2
		jr		INICIA_EN_FASE_DIRECTA

INICIA_EN_FASE_3:

		ld		a,3
		jr		INICIA_EN_FASE_DIRECTA

INICIA_EN_FASE_4:

		ld		a,4
		jr		INICIA_EN_FASE_DIRECTA

INICIA_EN_FASE_5:

		ld		a,5

INICIA_EN_FASE_DIRECTA:

		ld		(FASE),a
		ld		(TRUCO_FASES_ACTIVO),a

SEGUIMOS:

		di
		ld		a,#C9
		ld		(HTIMI),a
		ld		(HKEYI),a
		ei

		call	PARA_MUSICA_MENU_PRESENTACION

		call	FADE_OUT_PRESENTACION
		call	LIMPIA_VRAM_SALIDA_MENU

		call	DISSCR_RAM
		ld		a,5
		call	CHGMOD
		call	DISSCR_RAM

		ld		hl,0
		xor		a
		ld		(ARMA_USANDO),a										; 0 1 2 para flecha 3 4 5 para fuego 6 7 8 para hacha
		ld		(V_DECEN_MIL),a
		ld		(V_UNIDA_MIL),a
		ld		(V_CENTENAS),a
		ld		(V_DECENAS),a
		ld		(V_UNIDADES),a
		ld		(SCORE_REAL),hl
		add		2
		ld		(MAGIAS),a
		ld		(VIDAS),a
		ld		(CORAZONES),a
		inc		a
		ld		(CORAZONES_MAXIMOS),a

		call	DISSCR_RAM

RECUPERAMOS_INTERRUPCIONES_LIMPIAS:

		di
		ld		a,#C9													; A tiene el valor de ret
		ld		(HTIMI),a												; Colocamos ese ret en el gancho H.Timi POR SI EL ORDENADOR TUVIERA ALGO (ALGUN MSX 2 CONTROL DE DISQUETERA)
		ld		(HKEYI),a												; Colocamos ese ret en el gancho H.Key POR SI EL ORDENADOR TUVIERA ALGO
		ei

DESACTIVAMOS_INTERRUPCIONES_DE_LINEA_TRAS_EL_MENU:

		di
		ld 		a,(RG0SAV)												; Disable Line Interrupt: Reset R#0 bit 4
		and		11101111B
		ld		(RG0SAV),a
		ld		b,a
		ld		c,0
		call	WRTVDP_EN_RAM
		ei

NOS_VAMOS_AL_JUEGO:

		ld		a,8
		ld      (DIRPA2),a										    ; Banco 1, pagina 3 del MEGAROM
		jp		CARGA_SLOT_MAPA

TABLA_LATIDO_CINEMATICA_2:

		db		#20,#00,#40,#00
		db		#30,#00,#51,#01
		db		#40,#00,#62,#02
		db		#51,#01,#73,#03
		db		#62,#12,#74,#14
		db		#73,#23,#75,#25
		db		#74,#34,#76,#36
		db		#73,#23,#75,#25
		db		#62,#12,#74,#14
		db		#51,#01,#73,#03
		db		#40,#00,#62,#02
		db		#30,#00,#51,#01

PALETA_CINEMATICA_1_2:
       	incbin  "../PALETAS/PRESENTACION/CINEMATICA12.palete"
FADE_IN_CINEMATICA_1_2:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA12.fadein"
FADE_OUT_CINEMATICA_1_2:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA12.fadeout"
PALETA_MENU_LOCAL_FIJA:
		incbin  "../PALETAS/PRESENTACION/MENUIMAG.palete"

PALETA_MENU_LOCAL_FADE_IN:
		incbin  "../PALETAS/PRESENTACION/MENUIMAG.fadein"

PALETA_MENU_LOCAL_FADE_OUT:
		incbin  "../PALETAS/PRESENTACION/MENUIMAG.fadeout"

SPRITES_Y_PALETAS:
	; --- BANDERA 0
MENU_SPRITE_MASK_01:
	; mask 0
	DB $01,$01,$00,$00,$00,$00,$01,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
	DB $00,$E0,$E0,$F0,$FE,$8C,$8C,$00
	DB $00,$80,$80,$80,$00,$00,$00,$00
MENU_SPRITE_ATTR_01:
	; attr 0
	DB $01,$01,$0E,$0E,$0E,$0E,$01,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
MENU_SPRITE_MASK_02:
	; mask 1
	DB $00,$00,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$F0,$FF,$FF,$FE,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_02:
	; attr 1
	DB $00,$00,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- BANDERA 1
MENU_SPRITE_MASK_03:
	; mask 0
	DB $01,$00,$00,$00,$00,$00,$01,$01
	DB $01,$01,$01,$00,$00,$00,$00,$00
	DB $0F,$0E,$FC,$F0,$E0,$80,$80,$00
	DB $00,$80,$80,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_03:
	; attr 0
	DB $01,$0E,$0E,$0E,$0E,$0E,$01,$01
	DB $01,$01,$01,$00,$00,$00,$00,$00
MENU_SPRITE_MASK_04:
	; mask 1
	DB $00,$01,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$FF,$FE,$FC,$F0,$E0,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_04:
	; attr 1
	DB $00,$01,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- BANDERA 2
MENU_SPRITE_MASK_05:
	; mask 0
	DB $01,$01,$00,$00,$00,$00,$00,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
	DB $00,$E0,$E0,$F0,$FC,$8C,$06,$06
	DB $00,$80,$80,$80,$00,$00,$00,$00
MENU_SPRITE_ATTR_05:
	; attr 0
	DB $01,$01,$0E,$0E,$0E,$0E,$0E,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
MENU_SPRITE_MASK_06:
	; mask 1
	DB $00,$00,$01,$01,$01,$01,$01,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$F0,$FC,$FE,$FE,$8F,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_06:
	; attr 1
	DB $00,$00,$01,$01,$01,$01,$01,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- NUBE 0
MENU_SPRITE_MASK_07:
	; nube A arriba izquierda
	DB $00,$00,$00,$72,$03,$1B,$00,$00
	DB $01,$36,$1E,$00,$0D,$00,$00,$00
	DB $18,$E4,$70,$A8,$B8,$2A,$E0,$38
	DB $9E,$57,$00,$D8,$56,$7F,$0C,$3C
MENU_SPRITE_ATTR_07:
MENU_SPRITE_MASK_08:
	; nube A arriba derecha
	DB $C0,$F7,$7B,$39,$57,$FF,$95,$AA
	DB $13,$30,$16,$E2,$78,$79,$06,$3E
	DB $00,$00,$00,$70,$00,$00,$80,$00
	DB $00,$00,$00,$00,$00,$70,$C0,$00
MENU_SPRITE_ATTR_08:
MENU_SPRITE_MASK_09:
	; nube A abajo izquierda
	DB $00,$1C,$00,$01,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $5B,$86,$0E,$FE,$08,$73,$3A,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_09:
	;
	; --- NUBE 0
MENU_SPRITE_MASK_10:
	; nube A abajo derecha
	DB $E0,$70,$74,$E0,$4C,$20,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$A0,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_10:
	;
	; --- NUBE 1
MENU_SPRITE_MASK_11:
	; nube B arriba izquierda
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$07,$00,$3A,$01,$05
	DB $00,$00,$05,$07,$06,$07,$16,$07
	DB $3E,$07,$2C,$80,$38,$B0,$D5,$56
MENU_SPRITE_ATTR_11:
MENU_SPRITE_MASK_12:
	; nube B arriba derecha
	DB $40,$F0,$F0,$20,$F0,$AE,$38,$00
	DB $60,$00,$F4,$10,$63,$09,$4F,$2A
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$38,$00,$13,$C0
MENU_SPRITE_ATTR_12:
MENU_SPRITE_MASK_13:
	; nube B abajo izquierda
	DB $07,$01,$01,$03,$00,$04,$01,$3C
	DB $03,$06,$00,$00,$00,$00,$00,$00
	DB $1C,$B8,$C0,$4E,$E0,$05,$60,$07
	DB $0F,$40,$05,$C0,$A9,$14,$02,$18
MENU_SPRITE_ATTR_13:
MENU_SPRITE_MASK_14:
	; nube B abajo derecha
	DB $F7,$68,$2F,$5C,$3D,$6C,$DC,$80
	DB $3D,$20,$D8,$40,$00,$70,$C0,$00
	DB $C0,$00,$00,$00,$80,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_14:
	;
	; --- NUBE 3
MENU_SPRITE_MASK_15:
	; nube C arriba izquierda
	DB $00,$00,$00,$00,$00,$0E,$3F,$03
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$D3,$0E,$93,$FE,$A6
	DB $1E,$00,$00,$02,$0B,$26,$00,$00
MENU_SPRITE_ATTR_15:
MENU_SPRITE_MASK_16:
		; nube C arriba derecha
	DB $00,$00,$00,$F8,$7C,$D3,$AB,$3C
	DB $B6,$00,$00,$C0,$70,$40,$00,$00
	DB $00,$00,$00,$00,$A0,$00,$01,$00
	DB $90,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_16:
MENU_SPRITE_ATTR_NUBE_BLANCA:
	DB $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
	DB $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
	;
	; --- BANDERITA 0
MENU_SPRITE_MASK_17:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$E0,$60,$70,$F0,$80,$80
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_17:
	; attr 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$01,$0E,$0E,$01,$01,$01
MENU_SPRITE_MASK_18:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$F8,$F8,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_18:
	; attr 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$01,$01,$00,$00,$00
	;
	; --- BANDERITA 1
MENU_SPRITE_MASK_19:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$10,$10,$70,$60,$F0,$80,$80
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_19:
	; attr 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$01,$0E,$0E,$0E,$01,$01,$01
MENU_SPRITE_MASK_20:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$F8,$F8,$F8,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_20:
	; attr 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$01,$01,$01,$00,$00,$00
	;
	; --- BANDERITA 2
MENU_SPRITE_MASK_21:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$E0,$60,$70,$30,$B0,$80
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_21:
	; attr 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$01,$0E,$0E,$0E,$01,$01
MENU_SPRITE_MASK_22:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$F0,$F8,$F8,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_22:
	; attr 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$01,$01,$01,$00,$00
