ACPAGE		equ		#FAF6

MENU_FUENTE_Y_ORIGEN			equ		#0300+213
MENU_LETRA_ANCHO				equ		6
MENU_LETRA_ALTO					equ		6
MENU_LETRA_ESPECIAL_BASE		equ		26
MENU_LETRA_ESPECIALES_CANT		equ		16
MENU_LETRA_ESPACIO				equ		MENU_LETRA_ESPECIAL_BASE+MENU_LETRA_ESPECIALES_CANT
MENU_FUENTE_CARACTERES			equ		MENU_LETRA_ESPACIO+1
MENU_FUENTE_ANCHO				equ		MENU_LETRA_ANCHO*MENU_FUENTE_CARACTERES
PUSH_SPACE_KEY_X				equ		86
PUSH_SPACE_KEY_Y				equ		181
CINEMATICA_TEXTO_X				equ		12
CINEMATICA_TEXTO_Y_1				equ		154
CINEMATICA_TEXTO_Y_2				equ		164
CINEMATICA_TEXTO_Y_3				equ		174
CINEMATICA_TEXTO_Y_4				equ		184
CINEMATICA_PAUSA_LETRA			equ		4
CINEMATICA_PAUSA_FINAL			equ		250

CINEMATICA_PARPADEO_X_DESTINO              equ     74
CINEMATICA_PARPADEO_Y_DESTINO_ORIGINAL     equ     38
CINEMATICA_PARPADEO_Y_DESTINO_FRAMES       equ     38
CINEMATICA_PARPADEO_ANCHO                  equ     46
CINEMATICA_PARPADEO_ALTO                   equ     20
CINEMATICA_PARPADEO_ESPERA_MIN             equ     32
CINEMATICA_PARPADEO_MAX_VECES              equ     10
CINEMATICA_LATIDO_CADA_CICLOS              equ     8
CINEMATICA_LATIDO_PASOS                    equ     12

MENU_SPRITE_PATRON_INICIAL        equ     1
MENU_SPRITE_CANTIDAD              equ     22
MENU_SPRITE_PATRONES_VRAM         equ     #7800+MENU_SPRITE_PATRON_INICIAL*32
MENU_SPRITE_COLORES_VRAM          equ     #7400
MENU_SPRITE_ATRIBUTOS_VRAM        equ     #7600

CINEMATICA_BANDERA_X              equ     157
CINEMATICA_BANDERA_Y              equ     11
CINEMATICA_BANDERA_2_X            equ     198
CINEMATICA_BANDERA_2_Y            equ     4
CINEMATICA_BANDERA_3_X            equ     222
CINEMATICA_BANDERA_3_Y            equ     22
CINEMATICA_BANDERITA_X            equ     187
CINEMATICA_BANDERITA_Y            equ     24
CINEMATICA_BANDERA_Y_OCULTA       equ     217
CINEMATICA_BANDERA_CADA_CICLOS    equ     8
CINEMATICA_NUBE_X_INICIAL         equ     88
CINEMATICA_NUBE_X_FINAL           equ     172
CINEMATICA_NUBE_Y                 equ     0
CINEMATICA_NUBE_CADA_CICLOS       equ     12
CINEMATICA_NUBE_2_X_INICIAL       equ     50
CINEMATICA_NUBE_2_X_FINAL         equ     255
CINEMATICA_NUBE_2_Y               equ     50
CINEMATICA_NUBE_2_CADA_CICLOS     equ     6

; Los patrones 16x16 empiezan en VRAM en bloques de 32 bytes.
; En el byte de patron de la SAT usamos el numero hardware: 4, 8, 12...
CINEMATICA_BANDERA_PATRON_0_1     equ     (MENU_SPRITE_PATRON_INICIAL+0)*4
CINEMATICA_BANDERA_PATRON_0_2     equ     (MENU_SPRITE_PATRON_INICIAL+1)*4
CINEMATICA_BANDERA_PATRON_1_1     equ     (MENU_SPRITE_PATRON_INICIAL+2)*4
CINEMATICA_BANDERA_PATRON_1_2     equ     (MENU_SPRITE_PATRON_INICIAL+3)*4
CINEMATICA_BANDERA_PATRON_2_1     equ     (MENU_SPRITE_PATRON_INICIAL+4)*4
CINEMATICA_BANDERA_PATRON_2_2     equ     (MENU_SPRITE_PATRON_INICIAL+5)*4
CINEMATICA_BANDERITA_PATRON_0_1   equ     (MENU_SPRITE_PATRON_INICIAL+16)*4
CINEMATICA_BANDERITA_PATRON_0_2   equ     (MENU_SPRITE_PATRON_INICIAL+17)*4
CINEMATICA_BANDERITA_PATRON_1_1   equ     (MENU_SPRITE_PATRON_INICIAL+18)*4
CINEMATICA_BANDERITA_PATRON_1_2   equ     (MENU_SPRITE_PATRON_INICIAL+19)*4
CINEMATICA_BANDERITA_PATRON_2_1   equ     (MENU_SPRITE_PATRON_INICIAL+20)*4
CINEMATICA_BANDERITA_PATRON_2_2   equ     (MENU_SPRITE_PATRON_INICIAL+21)*4
CINEMATICA_NUBE_PATRON_0_1        equ     (MENU_SPRITE_PATRON_INICIAL+6)*4
CINEMATICA_NUBE_PATRON_0_2        equ     (MENU_SPRITE_PATRON_INICIAL+7)*4
CINEMATICA_NUBE_PATRON_0_3        equ     (MENU_SPRITE_PATRON_INICIAL+8)*4
CINEMATICA_NUBE_PATRON_1_1        equ     (MENU_SPRITE_PATRON_INICIAL+9)*4
CINEMATICA_NUBE_PATRON_1_2        equ     (MENU_SPRITE_PATRON_INICIAL+10)*4
CINEMATICA_NUBE_PATRON_1_3        equ     (MENU_SPRITE_PATRON_INICIAL+11)*4
CINEMATICA_NUBE_PATRON_2_1        equ     (MENU_SPRITE_PATRON_INICIAL+12)*4
CINEMATICA_NUBE_PATRON_2_2        equ     (MENU_SPRITE_PATRON_INICIAL+13)*4
CINEMATICA_NUBE_PATRON_3_1        equ     (MENU_SPRITE_PATRON_INICIAL+14)*4
CINEMATICA_NUBE_PATRON_3_2        equ     (MENU_SPRITE_PATRON_INICIAL+15)*4

WRTVDP:     equ     #0047

COMIENZA_MENU:

		di
		ld		a,#C9
		ld		(HTIMI),a
		ld		(HKEYI),a
		ei

		call	PAGE_10_A_SEGMENT_2

		call	MUESTRA_PRESENTACION_PROVISIONAL
		jp		PULSA_UNA_TECLA_PARA_EMPEZAR


MUESTRA_PRESENTACION_PROVISIONAL:

		call	DISSCR_RAM

		ld		a,5
		call	CHGMOD

		call	DISSCR_RAM

		; La segunda parte de la imagen de menu solo ocupa #2A00 bytes.
		; Limpiamos VRAM para que no queden restos de la pantalla SC7 del logo.

		xor		a
		ld		hl,#0000
		ld		bc,#ffff
		call	FILVRM_RAM

		; Página visible = 0

		xor		a
		call	SETPAGE

		; 1 - Cargamos los gráficos de presentación en page 1, no visible.

		call	CARGA_GRAFICOS_MENU_Y_CINEMATICA
		call    ACTIVA_SPRITES_16X16_MENU
		call	CARGA_SPRITES_Y_COLORES_MENU
		call	INICIA_MUSICA_MENU_PRESENTACION
		call	CINEMATICA

TITULO:

		; 2 - Ponemos la primera paleta del fade in.

		call	PONE_PRIMERA_PALETA_PRESENTACION

		; 3 - Copiamos la imagen de page 1 a page visible 0.

		ld		hl,DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_0
		call	DOCOPY
		call	VDPREADY

		ld		hl,DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_1
		call	DOCOPY
		call	VDPREADY

		; 4 - Mostramos pantalla y hacemos fade in.

		call	ENASCR_RAM
		call	FADE_IN_PRESENTACION

		; 5 - Pintamos texto de aviso.

		call	PINTA_TEXTO_PUSH_SPACE_KEY_EN_DOS_PAGES

		; 7 - Preparamos rotativo inferior.

		call	INICIALIZA_ROTATIVO_PRESENTACION

		ret

PINTA_TEXTO_PUSH_SPACE_KEY:

		call	OBTIENE_DESTINO_Y_PUSH_SPACE_KEY
		ld		hl,PUSH_SPACE_KEY_X
		ld		ix,TEXTO_PUSH_SPACE_KEY
		jp		BUCLE_PINTA_TEXTO_PUSH_SPACE_KEY


PINTA_TEXTO_PUSH_SPACE_KEY_EN_DOS_PAGES:

		xor		a
		ld		(ACPAGE),a
		call	PINTA_TEXTO_PUSH_SPACE_KEY

		ld		a,1
		ld		(ACPAGE),a
		call	PINTA_TEXTO_PUSH_SPACE_KEY

		xor		a
		ld		(ACPAGE),a
		ret

BUCLE_PINTA_TEXTO_PUSH_SPACE_KEY:

		ld		a,(ix+0)
		or		a
		ret		z

		push	de
		push	hl
		push	ix
		call	PINTA_LETRA_MENU_EN_DESTINO
		pop		ix
		pop		hl
		pop		de

		ld		bc,MENU_LETRA_ANCHO
		add		hl,bc
		inc		ix
		jp		BUCLE_PINTA_TEXTO_PUSH_SPACE_KEY


TEXTO_PUSH_SPACE_KEY:

		db		"PUSH SPACE KEY",0

OBTIENE_DESTINO_Y_PUSH_SPACE_KEY:

		ld		a,(ACPAGE)
		or		a
		ld		de,PUSH_SPACE_KEY_Y
		ret		z
		ld		de,#0100+PUSH_SPACE_KEY_Y
		ret

OBTIENE_DESTINO_Y_ROTATIVO_DESDE_A:

		or		a
		ld		de,ROTATIVO_Y_PRESENTACION
		ret		z
		ld		de,#0100+ROTATIVO_Y_PRESENTACION
		ret

PINTA_LETRA_MENU_EN_DESTINO:

		push	hl
		push	de
		call	CALCULA_ORIGEN_X_LETRA_MENU
		ld		ix,DATOS_DEL_TILE_PARA_COPY
		ld		(ix),l
		ld		(ix+1),h
		ld		hl,MENU_FUENTE_Y_ORIGEN
		ld		(ix+2),l
		ld		(ix+3),h
		pop		hl
		ld		(ix+6),l
		ld		(ix+7),h
		pop		hl
		ld		(ix+4),l
		ld		(ix+5),h
		ld		(ix+8),MENU_LETRA_ANCHO
		ld		(ix+9),0
		ld		(ix+10),MENU_LETRA_ALTO
		ld		(ix+11),0
		ld		(ix+12),#00
		ld		(ix+13),#00
		ld		(ix+14),11010000b
		call	HL_DATOS_DEL_COPY
		jp		VDPREADY

CALCULA_ORIGEN_X_LETRA_MENU:

		cp		97
		jr		c,.MIRA_MAYUSCULAS
		cp		123
		jr		nc,.MIRA_MAYUSCULAS
		sub		32

.MIRA_MAYUSCULAS:

		cp		65
		jr		c,.MIRA_ESPECIALES
		cp		91
		jr		nc,.MIRA_ESPECIALES
		sub		65
		jr		.MULTIPLICA

.MIRA_ESPECIALES:

		ld		hl,TABLA_ESPECIALES_MENU
		ld		b,MENU_FUENTE_CARACTERES-MENU_LETRA_ESPECIAL_BASE
		ld		c,MENU_LETRA_ESPECIAL_BASE

.BUCLE_ESPECIALES:

		cp		(hl)
		jr		z,.ES_ESPECIAL
		inc		hl
		inc		c
		djnz	.BUCLE_ESPECIALES
		jr		.ES_ESPACIO

.ES_ESPECIAL:

		ld		a,c
		jr		.MULTIPLICA

.ES_ESPACIO:

		ld		a,MENU_LETRA_ESPACIO

.MULTIPLICA:

		ld		e,a
		ld		d,0
		ld		h,d
		ld		l,e
		add		hl,hl
		add		hl,de
		add		hl,hl
		ret

TABLA_ESPECIALES_MENU:

		db		"-/()1234567890%."

PINTA_TEXTO_MENU_FORMA_3:

		ld		a,(ix+0)
		or		a
		ret		z

		push	de
		push	hl
		push	ix
		call	PINTA_LETRA_MENU_EN_DESTINO
		pop		ix
		pop		hl
		pop		de

		call	ESPERA_LETRA_CINEMATICA
		ret		c

		ld		bc,MENU_LETRA_ANCHO
		add		hl,bc
		inc		ix
		jp		PINTA_TEXTO_MENU_FORMA_3

CINEMATICA:

		xor		a
		call	SETPAGE

		ld		a,1
		ld		(CINEMATICA_BLOQUE_ACTUAL),a
		call	REINICIA_PARPADEO_CINEMATICA_2
		call	REINICIA_NUBE_CINEMATICA
		call	REINICIA_BANDERA_CINEMATICA

		ld		hl,DATOS_COPY_CINEMATICA_1
		ld		ix,TEXTO_CINEMATICA_1
		call	EJECUTA_BLOQUE_CINEMATICA
		jp		c,SALIDA_FORZADA_CINEMATICA

		ld		a,2
		ld		(CINEMATICA_BLOQUE_ACTUAL),a
		call	REINICIA_PARPADEO_CINEMATICA_2
		call	OCULTA_BANDERA_CINEMATICA

		ld		hl,DATOS_COPY_CINEMATICA_3
		ld		ix,TEXTO_CINEMATICA_2
		call	EJECUTA_BLOQUE_CINEMATICA
		jp		c,SALIDA_FORZADA_CINEMATICA

		ld		a,3
		ld		(CINEMATICA_BLOQUE_ACTUAL),a
		call	REINICIA_PARPADEO_CINEMATICA_2
		call	REINICIA_LATIDO_CINEMATICA_2

		ld		hl,DATOS_COPY_CINEMATICA_2
		ld		ix,TEXTO_CINEMATICA_3
		call	EJECUTA_BLOQUE_CINEMATICA
		jp		c,SALIDA_FORZADA_CINEMATICA

		ld		a,4
		ld		(CINEMATICA_BLOQUE_ACTUAL),a
		call	REINICIA_PARPADEO_CINEMATICA_2
		call	OCULTA_BANDERA_CINEMATICA

		ld		hl,DATOS_COPY_CINEMATICA_3
		ld		ix,TEXTO_CINEMATICA_4
		call	EJECUTA_BLOQUE_CINEMATICA
		jp		c,SALIDA_FORZADA_CINEMATICA

		ld		a,5
		ld		(CINEMATICA_BLOQUE_ACTUAL),a
		call	REINICIA_PARPADEO_CINEMATICA_2
		call	OCULTA_BANDERA_CINEMATICA

		ld		hl,DATOS_COPY_CINEMATICA_4
		ld		ix,TEXTO_CINEMATICA_5
		call	EJECUTA_BLOQUE_CINEMATICA
		ret		nc

SALIDA_FORZADA_CINEMATICA:

		call	FADE_OUT_CINEMATICA
		jp		FADE_OUT_MUSICA_CINEMATICA

EJECUTA_BLOQUE_CINEMATICA:

		push	hl
		push	ix

		call	PONE_PRIMERA_PALETA_CINEMATICA
		call	LIMPIA_PAGE_0_CINEMATICA

		pop		ix
		pop		hl

		push	ix
		call	DOCOPY
		call	VDPREADY
		call	PREPARA_SPRITES_CINEMATICA_ACTUAL
		call	ENASCR_RAM

		call	FADE_IN_CINEMATICA
		jr		c,.FIN_BLOQUE_CINEMATICA

		call	PONE_PALETA_FINAL_CINEMATICA

		pop		ix
		push	ix
		call	PINTA_CUATRO_FRASES_CINEMATICA
		jr		c,.FIN_BLOQUE_CINEMATICA

		ld		b,CINEMATICA_PAUSA_FINAL
		call	ESPERA_CINEMATICA_B
		jr		c,.FIN_BLOQUE_CINEMATICA

		call	FADE_OUT_CINEMATICA

.FIN_BLOQUE_CINEMATICA:

		pop		ix
		ret

PONE_PRIMERA_PALETA_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_34
		cp		4
		jr		nc,.PALETA_34
		ld		hl,FADE_IN_CINEMATICA_1_2
		jp		SETPALETE_CINEMATICA

.PALETA_34:

		ld		hl,FADE_IN_CINEMATICA_3_4
		jp		SETPALETE_CINEMATICA

PONE_PALETA_FINAL_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_34
		cp		4
		jr		nc,.PALETA_34
		ld		hl,PALETA_CINEMATICA_1_2
		jp		SETPALETE_CINEMATICA

.PALETA_34:

		ld		hl,PALETA_CINEMATICA_3_4
		jp		SETPALETE_CINEMATICA

FADE_IN_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_34
		cp		4
		jr		nc,.PALETA_34
		ld		hl,FADE_IN_CINEMATICA_1_2+32
		ld		e,6
		jp		BUCLE_FADE_CINEMATICA

.PALETA_34:

		ld		hl,FADE_IN_CINEMATICA_3_4+32
		ld		e,6
		jp		BUCLE_FADE_CINEMATICA

FADE_OUT_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PALETA_34
		cp		4
		jr		nc,.PALETA_34
		ld		hl,FADE_OUT_CINEMATICA_1_2
		ld		e,7
		jr		BUCLE_FADE_CINEMATICA

.PALETA_34:

		ld		hl,FADE_OUT_CINEMATICA_3_4
		ld		e,7

BUCLE_FADE_CINEMATICA:

		call	SETPALETE_CINEMATICA
		push	hl
		push	de
		ld		b,6
		call	ESPERA_CINEMATICA_B
		pop		de
		pop		hl
		ret		c
		dec		e
		jp		nz,BUCLE_FADE_CINEMATICA
		or		a
		ret

SETPALETE_CINEMATICA:

		xor		a
		di
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		ld		c,#9A
[32]	outi
		call	FUERZA_COLOR_5_CINEMATICA_4
		ei
		ret

FUERZA_COLOR_5_CINEMATICA_4:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		4
		ret		nz

		ld		a,5
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		ld		a,#03
		out		(#9A),a
		xor		a
		out		(#9A),a
		ret

PINTA_CUATRO_FRASES_CINEMATICA:

		push	ix
		pop		hl

		ld		de,CINEMATICA_TEXTO_Y_1
		call	PINTA_FRASE_CINEMATICA_DESDE_TABLA
		ret		c

		ld		de,CINEMATICA_TEXTO_Y_2
		call	PINTA_FRASE_CINEMATICA_DESDE_TABLA
		ret		c

		ld		de,CINEMATICA_TEXTO_Y_3
		call	PINTA_FRASE_CINEMATICA_DESDE_TABLA
		ret		c

		ld		de,CINEMATICA_TEXTO_Y_4
		jp		PINTA_FRASE_CINEMATICA_DESDE_TABLA

PINTA_FRASE_CINEMATICA_DESDE_TABLA:

		ld		c,(hl)
		inc		hl
		ld		b,(hl)
		inc		hl
		push	hl
		push	bc
		pop		ix
		ld		hl,CINEMATICA_TEXTO_X
		call	PINTA_TEXTO_MENU_FORMA_3
		pop		hl
		ret

LIMPIA_PAGE_0_CINEMATICA:

		ld		hl,DATOS_NEGRO_PAGE_0_CINEMATICA
		call	DOCOPY
		jp		VDPREADY

ESPERA_LETRA_CINEMATICA:

		ld		b,CINEMATICA_PAUSA_LETRA

ESPERA_CINEMATICA_B:

		halt
		call	COMPRUEBA_SPACE_CINEMATICA
		ret		c

		push	af
		push	bc
		push	de
		push	hl
		push	ix
		push	iy

		call	CONTROL_PARPADEO_CINEMATICA_2
		call	CONTROL_LATIDO_CINEMATICA_2
		call	CONTROL_NUBE_CINEMATICA
		call	CONTROL_BANDERA_CINEMATICA

		pop		iy
		pop		ix
		pop		hl
		pop		de
		pop		bc
		pop		af

		djnz	ESPERA_CINEMATICA_B
		or		a
		ret

REINICIA_PARPADEO_CINEMATICA_2:

		xor		a
		ld		(CINEMATICA_PARPADEO_ESTADO),a
		ld		(CINEMATICA_PARPADEO_VECES),a
		ld		(CINEMATICA_PARPADEO_ACTIVO),a

		ld		a,48
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret

REINICIA_LATIDO_CINEMATICA_2:

		xor		a
		ld		(CINEMATICA_LATIDO_INDICE),a
		ld		a,CINEMATICA_LATIDO_CADA_CICLOS
		ld		(CINEMATICA_LATIDO_CONTADOR),a
		ret

CONTROL_LATIDO_CINEMATICA_2:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		3
		ret		nz

		ld		a,(CINEMATICA_LATIDO_CONTADOR)
		dec		a
		ld		(CINEMATICA_LATIDO_CONTADOR),a
		ret		nz

		ld		a,CINEMATICA_LATIDO_CADA_CICLOS
		ld		(CINEMATICA_LATIDO_CONTADOR),a

		ld		a,(CINEMATICA_LATIDO_INDICE)
		inc		a
		cp		CINEMATICA_LATIDO_PASOS
		jr		c,.GUARDA_INDICE_LATIDO
		xor		a

.GUARDA_INDICE_LATIDO:

		ld		(CINEMATICA_LATIDO_INDICE),a
		add		a,a
		ld		l,a
		ld		h,0
		add		hl,hl
		ld		de,TABLA_LATIDO_CINEMATICA_2
		add		hl,de
		jp		SETPALETE_LATIDO_CINEMATICA_2

SETPALETE_LATIDO_CINEMATICA_2:

		di
		ld		c,#9A

		ld		a,6
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		outi
		outi

		ld		a,9
		out		(#99),a
		ld		a,16+128
		out		(#99),a
		outi
		outi
		ei
		ret

CONTROL_PARPADEO_CINEMATICA_2:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		2
		jr		z,.PARPADEO_ACTIVO
		cp		4
		ret		nz

.PARPADEO_ACTIVO:

		ld		a,(CINEMATICA_PARPADEO_VECES)
		cp		CINEMATICA_PARPADEO_MAX_VECES
		ret		nc

		ld		a,(CINEMATICA_PARPADEO_ACTIVO)
		or		a
		jr		nz,.PARPADEO_EN_MARCHA

		ld		a,(CINEMATICA_PARPADEO_CONTADOR)
		dec		a
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret		nz

		ld		a,1
		ld		(CINEMATICA_PARPADEO_ACTIVO),a

		xor		a
		ld		(CINEMATICA_PARPADEO_ESTADO),a
		jr		.PARPADEO_EN_MARCHA

.PARPADEO_EN_MARCHA:

		call	EJECUTA_FRAME_PARPADEO_CINEMATICA_2

		ld		a,(CINEMATICA_PARPADEO_ESTADO)
		inc		a
		ld		(CINEMATICA_PARPADEO_ESTADO),a

		cp		7
		ret		c

		xor		a
		ld		(CINEMATICA_PARPADEO_ACTIVO),a
		ld		(CINEMATICA_PARPADEO_ESTADO),a

		ld		a,(CINEMATICA_PARPADEO_VECES)
		inc		a
		ld		(CINEMATICA_PARPADEO_VECES),a

		ld		a,r
		and		00011111b
		add		CINEMATICA_PARPADEO_ESPERA_MIN
		ld		(CINEMATICA_PARPADEO_CONTADOR),a
		ret

EJECUTA_FRAME_PARPADEO_CINEMATICA_2:

		ld		a,(CINEMATICA_PARPADEO_ESTADO)

		or		a
		jr		z,.COPIA_ORIGINAL

		cp		1
		jr		z,.COPIA_A

		cp		2
		jr		z,.COPIA_B

		cp		3
		jr		z,.COPIA_C

		cp		4
		jr		z,.COPIA_B

		cp		5
		jr		z,.COPIA_A

		jr		.COPIA_ORIGINAL

.COPIA_ORIGINAL:

		ld		hl,DATOS_COPY_PARPADEO_CINEMATICA_2_ORIGINAL
		jr		.HACE_COPY_PARPADEO_CINEMATICA_2

.COPIA_A:

		ld		hl,DATOS_COPY_PARPADEO_CINEMATICA_2_A
		jr		.HACE_COPY_PARPADEO_CINEMATICA_2

.COPIA_B:

		ld		hl,DATOS_COPY_PARPADEO_CINEMATICA_2_B
		jr		.HACE_COPY_PARPADEO_CINEMATICA_2

.COPIA_C:

		ld		hl,DATOS_COPY_PARPADEO_CINEMATICA_2_C

.HACE_COPY_PARPADEO_CINEMATICA_2:

		call	DOCOPY
		jp		VDPREADY

REINICIA_BANDERA_CINEMATICA:

		xor		a
		ld		(CINEMATICA_BANDERA_ESTADO),a
		ld		a,CINEMATICA_BANDERA_CADA_CICLOS
		ld		(CINEMATICA_BANDERA_CONTADOR),a
		call	PINTA_NUBE_CINEMATICA
		call	PINTA_NUBE_2_CINEMATICA
		jp		PINTA_BANDERA_CINEMATICA

REINICIA_NUBE_CINEMATICA:

		ld		a,CINEMATICA_NUBE_X_INICIAL
		ld		(CINEMATICA_NUBE_X),a
		ld		a,CINEMATICA_NUBE_CADA_CICLOS
		ld		(CINEMATICA_NUBE_CONTADOR),a
		call	COPIA_COLORES_NUBE_CINEMATICA

		ld		a,CINEMATICA_NUBE_2_X_INICIAL
		ld		(CINEMATICA_NUBE_2_X),a
		ld		a,CINEMATICA_NUBE_2_CADA_CICLOS
		ld		(CINEMATICA_NUBE_2_CONTADOR),a
		jp		COPIA_COLORES_NUBE_2_CINEMATICA

CONTROL_BANDERA_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		1
		jr		z,.BANDERA_ACTIVA
		cp		3
		ret		nz

.BANDERA_ACTIVA:

		ld		a,(CINEMATICA_BANDERA_CONTADOR)
		dec		a
		ld		(CINEMATICA_BANDERA_CONTADOR),a
		ret		nz

		ld		a,CINEMATICA_BANDERA_CADA_CICLOS
		ld		(CINEMATICA_BANDERA_CONTADOR),a

		ld		a,(CINEMATICA_BANDERA_ESTADO)
		inc		a
		cp		3
		jr		c,.GUARDA_ESTADO_BANDERA
		xor		a

.GUARDA_ESTADO_BANDERA:

		ld		(CINEMATICA_BANDERA_ESTADO),a
		jp		PINTA_BANDERA_CINEMATICA

CONTROL_NUBE_CINEMATICA:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		1
		ret		nz

		ld		a,(CINEMATICA_NUBE_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_CONTADOR),a
		jr		nz,.CONTROLA_NUBE_2

		ld		a,CINEMATICA_NUBE_CADA_CICLOS
		ld		(CINEMATICA_NUBE_CONTADOR),a

		ld		a,(CINEMATICA_NUBE_X)
		inc		a
		cp		CINEMATICA_NUBE_X_FINAL
		jr		c,.GUARDA_X_NUBE
		ld		a,CINEMATICA_NUBE_X_INICIAL

.GUARDA_X_NUBE:

		ld		(CINEMATICA_NUBE_X),a
		call	PINTA_NUBE_CINEMATICA

.CONTROLA_NUBE_2:

		ld		a,(CINEMATICA_NUBE_2_CONTADOR)
		dec		a
		ld		(CINEMATICA_NUBE_2_CONTADOR),a
		ret		nz

		ld		a,CINEMATICA_NUBE_2_CADA_CICLOS
		ld		(CINEMATICA_NUBE_2_CONTADOR),a

		ld		a,(CINEMATICA_NUBE_2_X)
		inc		a
		cp		CINEMATICA_NUBE_2_X_FINAL
		jr		c,.GUARDA_X_NUBE_2
		ld		a,CINEMATICA_NUBE_2_X_INICIAL

.GUARDA_X_NUBE_2:

		ld		(CINEMATICA_NUBE_2_X),a
		jp		PINTA_NUBE_2_CINEMATICA

PREPARA_SPRITES_CINEMATICA_ACTUAL:

		ld		a,(CINEMATICA_BLOQUE_ACTUAL)
		cp		1
		jr		z,.NUBES_Y_BANDERAS
		cp		3
		jr		z,.SOLO_BANDERAS
		jr		.OCULTA_SPRITES_CINEMATICA

.NUBES_Y_BANDERAS:

		call	PINTA_NUBE_CINEMATICA
		call	PINTA_NUBE_2_CINEMATICA
		jp		PINTA_BANDERA_CINEMATICA

.SOLO_BANDERAS:

		call	OCULTA_NUBE_CINEMATICA
		jp		PINTA_BANDERA_CINEMATICA

.OCULTA_SPRITES_CINEMATICA:

		jp		OCULTA_BANDERA_CINEMATICA

PINTA_BANDERA_CINEMATICA:

		ld		a,(CINEMATICA_BANDERA_ESTADO)
		or		a
		jr		z,.FRAME_0
		cp		1
		jr		z,.FRAME_1

.FRAME_2:

		call	COPIA_COLORES_BANDERA_CINEMATICA_2
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_2
		jp		COPIA_ATRIBUTOS_BANDERA_CINEMATICA

.FRAME_0:

		call	COPIA_COLORES_BANDERA_CINEMATICA_0
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_0
		jp		COPIA_ATRIBUTOS_BANDERA_CINEMATICA

.FRAME_1:

		call	COPIA_COLORES_BANDERA_CINEMATICA_1
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_1

COPIA_ATRIBUTOS_BANDERA_CINEMATICA:

		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM
		ld		bc,8*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

OCULTA_BANDERA_CINEMATICA:

		call	OCULTA_NUBE_CINEMATICA
		ld		hl,ATRIBUTOS_BANDERA_CINEMATICA_OCULTA
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM
		ld		bc,8*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

OCULTA_NUBE_CINEMATICA:

		ld		hl,ATRIBUTOS_NUBE_CINEMATICA_OCULTA
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+8*4
		ld		bc,10*4
		call	PON_COLOR_2.sin_bc_impuesta
		ld		hl,ATRIBUTOS_NUBE_CINEMATICA_OCULTA
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+18*4
		ld		bc,10*4
		jp		PON_COLOR_2.sin_bc_impuesta

COPIA_COLOR_SPRITE_MENU:

		ld		bc,16
		jp		PON_COLOR_2.sin_bc_impuesta

COPIA_COLORES_BANDERA_CINEMATICA_0:

		ld		hl,MENU_SPRITE_ATTR_01
		ld		de,MENU_SPRITE_COLORES_VRAM+0*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_02
		ld		de,MENU_SPRITE_COLORES_VRAM+1*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_03
		ld		de,MENU_SPRITE_COLORES_VRAM+2*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_04
		ld		de,MENU_SPRITE_COLORES_VRAM+3*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_05
		ld		de,MENU_SPRITE_COLORES_VRAM+4*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_06
		ld		de,MENU_SPRITE_COLORES_VRAM+5*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_17
		ld		de,MENU_SPRITE_COLORES_VRAM+6*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_18
		ld		de,MENU_SPRITE_COLORES_VRAM+7*16
		jp		COPIA_COLOR_SPRITE_MENU

COPIA_COLORES_BANDERA_CINEMATICA_1:

		ld		hl,MENU_SPRITE_ATTR_03
		ld		de,MENU_SPRITE_COLORES_VRAM+0*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_04
		ld		de,MENU_SPRITE_COLORES_VRAM+1*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_05
		ld		de,MENU_SPRITE_COLORES_VRAM+2*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_06
		ld		de,MENU_SPRITE_COLORES_VRAM+3*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_01
		ld		de,MENU_SPRITE_COLORES_VRAM+4*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_02
		ld		de,MENU_SPRITE_COLORES_VRAM+5*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_19
		ld		de,MENU_SPRITE_COLORES_VRAM+6*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_20
		ld		de,MENU_SPRITE_COLORES_VRAM+7*16
		jp		COPIA_COLOR_SPRITE_MENU

COPIA_COLORES_BANDERA_CINEMATICA_2:

		ld		hl,MENU_SPRITE_ATTR_05
		ld		de,MENU_SPRITE_COLORES_VRAM+0*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_06
		ld		de,MENU_SPRITE_COLORES_VRAM+1*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_01
		ld		de,MENU_SPRITE_COLORES_VRAM+2*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_02
		ld		de,MENU_SPRITE_COLORES_VRAM+3*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_03
		ld		de,MENU_SPRITE_COLORES_VRAM+4*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_04
		ld		de,MENU_SPRITE_COLORES_VRAM+5*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_21
		ld		de,MENU_SPRITE_COLORES_VRAM+6*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_22
		ld		de,MENU_SPRITE_COLORES_VRAM+7*16
		jp		COPIA_COLOR_SPRITE_MENU

COPIA_COLORES_NUBE_CINEMATICA:

		ld		hl,MENU_SPRITE_ATTR_07
		ld		de,MENU_SPRITE_COLORES_VRAM+8*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_08
		ld		de,MENU_SPRITE_COLORES_VRAM+9*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_09
		ld		de,MENU_SPRITE_COLORES_VRAM+10*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_10
		ld		de,MENU_SPRITE_COLORES_VRAM+11*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_11
		ld		de,MENU_SPRITE_COLORES_VRAM+12*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_12
		ld		de,MENU_SPRITE_COLORES_VRAM+13*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_13
		ld		de,MENU_SPRITE_COLORES_VRAM+14*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_14
		ld		de,MENU_SPRITE_COLORES_VRAM+15*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_15
		ld		de,MENU_SPRITE_COLORES_VRAM+16*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_16
		ld		de,MENU_SPRITE_COLORES_VRAM+17*16
		jp		COPIA_COLOR_SPRITE_MENU

COPIA_COLORES_NUBE_2_CINEMATICA:

		ld		hl,MENU_SPRITE_ATTR_07
		ld		de,MENU_SPRITE_COLORES_VRAM+18*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_08
		ld		de,MENU_SPRITE_COLORES_VRAM+19*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_09
		ld		de,MENU_SPRITE_COLORES_VRAM+20*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_10
		ld		de,MENU_SPRITE_COLORES_VRAM+21*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_11
		ld		de,MENU_SPRITE_COLORES_VRAM+22*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_12
		ld		de,MENU_SPRITE_COLORES_VRAM+23*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_13
		ld		de,MENU_SPRITE_COLORES_VRAM+24*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_14
		ld		de,MENU_SPRITE_COLORES_VRAM+25*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_15
		ld		de,MENU_SPRITE_COLORES_VRAM+26*16
		call	COPIA_COLOR_SPRITE_MENU
		ld		hl,MENU_SPRITE_ATTR_16
		ld		de,MENU_SPRITE_COLORES_VRAM+27*16
		jp		COPIA_COLOR_SPRITE_MENU

PINTA_NUBE_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_CINEMATICA
		ld		hl,CINEMATICA_NUBE_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+8*4
		ld		bc,10*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

PINTA_NUBE_2_CINEMATICA:

		call	CREA_ATRIBUTOS_NUBE_2_CINEMATICA
		ld		hl,CINEMATICA_NUBE_2_ATRIBUTOS
		ld		de,MENU_SPRITE_ATRIBUTOS_VRAM+18*4
		ld		bc,10*4
		call	PON_COLOR_2.sin_bc_impuesta
		jp		VDPREADY

CREA_ATRIBUTOS_NUBE_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_ATRIBUTOS

		ld		a,CINEMATICA_NUBE_Y
		ld		(ix+0),a
		ld		a,(CINEMATICA_NUBE_X)
		ld		(ix+1),a
		ld		a,CINEMATICA_NUBE_PATRON_0_1
		ld		(ix+2),a
		ld		(ix+3),0

		ld		a,CINEMATICA_NUBE_Y
		ld		(ix+4),a
		ld		a,(CINEMATICA_NUBE_X)
		ld		(ix+5),a
		ld		a,CINEMATICA_NUBE_PATRON_0_2
		ld		(ix+6),a
		ld		(ix+7),0

		ld		a,CINEMATICA_NUBE_Y
		ld		(ix+8),a
		ld		a,(CINEMATICA_NUBE_X)
		ld		(ix+9),a
		ld		a,CINEMATICA_NUBE_PATRON_0_3
		ld		(ix+10),a
		ld		(ix+11),0

		ld		a,CINEMATICA_NUBE_Y
		ld		(ix+12),a
		ld		a,(CINEMATICA_NUBE_X)
		add		a,16
		ld		(ix+13),a
		ld		a,CINEMATICA_NUBE_PATRON_1_1
		ld		(ix+14),a
		ld		(ix+15),0

		ld		a,CINEMATICA_NUBE_Y
		ld		(ix+16),a
		ld		a,(CINEMATICA_NUBE_X)
		add		a,16
		ld		(ix+17),a
		ld		a,CINEMATICA_NUBE_PATRON_1_2
		ld		(ix+18),a
		ld		(ix+19),0

		ld		a,CINEMATICA_NUBE_Y
		ld		(ix+20),a
		ld		a,(CINEMATICA_NUBE_X)
		add		a,16
		ld		(ix+21),a
		ld		a,CINEMATICA_NUBE_PATRON_1_3
		ld		(ix+22),a
		ld		(ix+23),0

		ld		a,CINEMATICA_NUBE_Y+16
		ld		(ix+24),a
		ld		a,(CINEMATICA_NUBE_X)
		ld		(ix+25),a
		ld		a,CINEMATICA_NUBE_PATRON_2_1
		ld		(ix+26),a
		ld		(ix+27),0

		ld		a,CINEMATICA_NUBE_Y+16
		ld		(ix+28),a
		ld		a,(CINEMATICA_NUBE_X)
		ld		(ix+29),a
		ld		a,CINEMATICA_NUBE_PATRON_2_2
		ld		(ix+30),a
		ld		(ix+31),0

		ld		a,CINEMATICA_NUBE_Y+16
		ld		(ix+32),a
		ld		a,(CINEMATICA_NUBE_X)
		add		a,16
		ld		(ix+33),a
		ld		a,CINEMATICA_NUBE_PATRON_3_1
		ld		(ix+34),a
		ld		(ix+35),0

		ld		a,CINEMATICA_NUBE_Y+16
		ld		(ix+36),a
		ld		a,(CINEMATICA_NUBE_X)
		add		a,16
		ld		(ix+37),a
		ld		a,CINEMATICA_NUBE_PATRON_3_2
		ld		(ix+38),a
		ld		(ix+39),0
		ret

CREA_ATRIBUTOS_NUBE_2_CINEMATICA:

		ld		ix,CINEMATICA_NUBE_2_ATRIBUTOS

		ld		a,CINEMATICA_NUBE_2_Y
		ld		(ix+0),a
		ld		a,(CINEMATICA_NUBE_2_X)
		ld		(ix+1),a
		ld		a,CINEMATICA_NUBE_PATRON_0_1
		ld		(ix+2),a
		ld		(ix+3),0

		ld		a,CINEMATICA_NUBE_2_Y
		ld		(ix+4),a
		ld		a,(CINEMATICA_NUBE_2_X)
		ld		(ix+5),a
		ld		a,CINEMATICA_NUBE_PATRON_0_2
		ld		(ix+6),a
		ld		(ix+7),0

		ld		a,CINEMATICA_NUBE_2_Y
		ld		(ix+8),a
		ld		a,(CINEMATICA_NUBE_2_X)
		ld		(ix+9),a
		ld		a,CINEMATICA_NUBE_PATRON_0_3
		ld		(ix+10),a
		ld		(ix+11),0

		ld		a,CINEMATICA_NUBE_2_Y
		ld		(ix+12),a
		ld		a,(CINEMATICA_NUBE_2_X)
		add		a,16
		ld		(ix+13),a
		ld		a,CINEMATICA_NUBE_PATRON_1_1
		ld		(ix+14),a
		ld		(ix+15),0

		ld		a,CINEMATICA_NUBE_2_Y
		ld		(ix+16),a
		ld		a,(CINEMATICA_NUBE_2_X)
		add		a,16
		ld		(ix+17),a
		ld		a,CINEMATICA_NUBE_PATRON_1_2
		ld		(ix+18),a
		ld		(ix+19),0

		ld		a,CINEMATICA_NUBE_2_Y
		ld		(ix+20),a
		ld		a,(CINEMATICA_NUBE_2_X)
		add		a,16
		ld		(ix+21),a
		ld		a,CINEMATICA_NUBE_PATRON_1_3
		ld		(ix+22),a
		ld		(ix+23),0

		ld		a,CINEMATICA_NUBE_2_Y+16
		ld		(ix+24),a
		ld		a,(CINEMATICA_NUBE_2_X)
		ld		(ix+25),a
		ld		a,CINEMATICA_NUBE_PATRON_2_1
		ld		(ix+26),a
		ld		(ix+27),0

		ld		a,CINEMATICA_NUBE_2_Y+16
		ld		(ix+28),a
		ld		a,(CINEMATICA_NUBE_2_X)
		ld		(ix+29),a
		ld		a,CINEMATICA_NUBE_PATRON_2_2
		ld		(ix+30),a
		ld		(ix+31),0

		ld		a,CINEMATICA_NUBE_2_Y+16
		ld		(ix+32),a
		ld		a,(CINEMATICA_NUBE_2_X)
		add		a,16
		ld		(ix+33),a
		ld		a,CINEMATICA_NUBE_PATRON_3_1
		ld		(ix+34),a
		ld		(ix+35),0

		ld		a,CINEMATICA_NUBE_2_Y+16
		ld		(ix+36),a
		ld		a,(CINEMATICA_NUBE_2_X)
		add		a,16
		ld		(ix+37),a
		ld		a,CINEMATICA_NUBE_PATRON_3_2
		ld		(ix+38),a
		ld		(ix+39),0
		ret

COMPRUEBA_SPACE_CINEMATICA:

		ld		a,8
		call	SNSMAT_RAM
		bit		0,a
		jr		z,.SPACE_PULSADO
		or		a
		ret

.SPACE_PULSADO:

		scf
		ret

FADE_OUT_MUSICA_CINEMATICA:

		ld		b,20
		call	ESPERA_CINEMATICA_B
		jp		PARA_MUSICA_MENU_PRESENTACION

CARGA_GRAFICOS_MENU_Y_CINEMATICA:

		call	CARGA_GRAFICOS_PRESENTACION_EN_PAGE_1
		ld		hl,DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_3
		call	DOCOPY
		call	VDPREADY

		call	CARGA_GRAFICOS_CINEMATICA_3_4_EN_PAGE_1
		ld		hl,DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_2
		call	DOCOPY
		call	VDPREADY

		jp		CARGA_GRAFICOS_CINEMATICA_1_2_EN_PAGE_1

CARGA_GRAFICOS_PRESENTACION_EN_PAGE_1:

		; Página 4 ROM -> primera mitad de VRAM page 1

		di
		ld		a,4
		ld		(DIRPA2),a

		ld		hl,PANTALLA_DE_PRESENTACION_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta


		; Página 5 ROM -> segunda mitad de VRAM page 1
		; Copiamos sólo hasta donde empiezan las paletas.

		ld		a,5
		ld		(DIRPA2),a

		ld		hl,PANTALLA_DE_PRESENTACION_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret

CARGA_GRAFICOS_CINEMATICA_1_2_EN_PAGE_1:

		di
		ld		a,60
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_1_2_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,61
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_1_2_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret

CARGA_GRAFICOS_CINEMATICA_3_4_EN_PAGE_1:

		di
		ld		a,62
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_3_4_1
		ld		de,#8000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ld		a,63
		ld		(DIRPA2),a

		ld		hl,CINEMATICA_3_4_2
		ld		de,#C000
		ld		bc,#4000
		call	PON_COLOR_2.sin_bc_impuesta

		ei
		ret

ACTIVA_SPRITES_16X16_MENU:

        ld      a,(RG1SAV)
        or      00000010b          ; bit 1 = sprites 16x16
        and     11111110b          ; bit 0 = sin ampliación x2
        ld      (RG1SAV),a

        ld      b,a
        ld      c,1
        call    WRTVDP

        ret

CARGA_SPRITES_Y_COLORES_MENU:

		call	PAGE_10_A_SEGMENT_2

		ld		hl,MENU_SPRITE_MASK_01
		ld		de,MENU_SPRITE_PATRONES_VRAM+0*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_01
		ld		de,MENU_SPRITE_COLORES_VRAM+0*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_02
		ld		de,MENU_SPRITE_PATRONES_VRAM+1*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_02
		ld		de,MENU_SPRITE_COLORES_VRAM+1*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_03
		ld		de,MENU_SPRITE_PATRONES_VRAM+2*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_03
		ld		de,MENU_SPRITE_COLORES_VRAM+2*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_04
		ld		de,MENU_SPRITE_PATRONES_VRAM+3*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_04
		ld		de,MENU_SPRITE_COLORES_VRAM+3*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_05
		ld		de,MENU_SPRITE_PATRONES_VRAM+4*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_05
		ld		de,MENU_SPRITE_COLORES_VRAM+4*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_06
		ld		de,MENU_SPRITE_PATRONES_VRAM+5*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_06
		ld		de,MENU_SPRITE_COLORES_VRAM+5*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_07
		ld		de,MENU_SPRITE_PATRONES_VRAM+6*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_07
		ld		de,MENU_SPRITE_COLORES_VRAM+6*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_08
		ld		de,MENU_SPRITE_PATRONES_VRAM+7*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_08
		ld		de,MENU_SPRITE_COLORES_VRAM+7*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_09
		ld		de,MENU_SPRITE_PATRONES_VRAM+8*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_09
		ld		de,MENU_SPRITE_COLORES_VRAM+8*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_10
		ld		de,MENU_SPRITE_PATRONES_VRAM+9*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_10
		ld		de,MENU_SPRITE_COLORES_VRAM+9*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_11
		ld		de,MENU_SPRITE_PATRONES_VRAM+10*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_11
		ld		de,MENU_SPRITE_COLORES_VRAM+10*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_12
		ld		de,MENU_SPRITE_PATRONES_VRAM+11*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_12
		ld		de,MENU_SPRITE_COLORES_VRAM+11*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_13
		ld		de,MENU_SPRITE_PATRONES_VRAM+12*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_13
		ld		de,MENU_SPRITE_COLORES_VRAM+12*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_14
		ld		de,MENU_SPRITE_PATRONES_VRAM+13*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_14
		ld		de,MENU_SPRITE_COLORES_VRAM+13*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_15
		ld		de,MENU_SPRITE_PATRONES_VRAM+14*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_15
		ld		de,MENU_SPRITE_COLORES_VRAM+14*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_16
		ld		de,MENU_SPRITE_PATRONES_VRAM+15*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_16
		ld		de,MENU_SPRITE_COLORES_VRAM+15*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_17
		ld		de,MENU_SPRITE_PATRONES_VRAM+16*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_17
		ld		de,MENU_SPRITE_COLORES_VRAM+16*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_18
		ld		de,MENU_SPRITE_PATRONES_VRAM+17*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_18
		ld		de,MENU_SPRITE_COLORES_VRAM+17*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_19
		ld		de,MENU_SPRITE_PATRONES_VRAM+18*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_19
		ld		de,MENU_SPRITE_COLORES_VRAM+18*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_20
		ld		de,MENU_SPRITE_PATRONES_VRAM+19*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_20
		ld		de,MENU_SPRITE_COLORES_VRAM+19*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_21
		ld		de,MENU_SPRITE_PATRONES_VRAM+20*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_21
		ld		de,MENU_SPRITE_COLORES_VRAM+20*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ld		hl,MENU_SPRITE_MASK_22
		ld		de,MENU_SPRITE_PATRONES_VRAM+21*32
		call	CARGA_PATRON_MENU_16X16

		ld		hl,MENU_SPRITE_ATTR_22
		ld		de,MENU_SPRITE_COLORES_VRAM+21*16
		ld		bc,16
		call	PON_COLOR_2.sin_bc_impuesta

		ret


CARGA_PATRON_MENU_16X16:

		ld		bc,32
		jp		PON_COLOR_2.sin_bc_impuesta


PONE_PRIMERA_PALETA_PRESENTACION:

		ld		hl,PALETA_MENU_LOCAL_FADE_IN
		jp		SETPALETE_CINEMATICA

INICIA_MUSICA_MENU_PRESENTACION:

		call	stpmus

		ld		a,1
		ld		(MUSICA_BEST_ON),a
		
        ld      a,39
        call    CHANGE_BANK_2

		ld		hl,M_MENU
		ld		(MUSIC_ON),hl

		call	INICIAMOS_MUSICA

		di
		call	strmus

		; strmus instala musint directamente en HTIMI.
		; Para el menú necesitamos envolverla para forzar page 39.

		call	INSTALA_INTERRUPCION_MUSICA_MENU
		ei

		call	PAGE_10_A_SEGMENT_2

		ret

INSTALA_INTERRUPCION_MUSICA_MENU:

		ld		a,#C3
		ld		(HTIMI),a
		ld		hl,INTERRUPCION_MUSICA_MENU
		ld		(HTIMI+1),hl
		ret


INTERRUPCION_MUSICA_MENU:

		ld		a,(DIRPA2)
		push	af
		ld		a,39
		ld		(DIRPA2),a

		call	musint

		pop		af
		ld		(DIRPA2),a

		ret

PARA_MUSICA_MENU_PRESENTACION:

		call	stpmus

		xor		a
		ld		(MUSICA_BEST_ON),a

		call	PAGE_10_A_SEGMENT_2

		ret

FADE_IN_PRESENTACION:

		; La primera paleta ya se ha puesto antes.
		; Empezamos en la segunda.

		ld		hl,PALETA_MENU_LOCAL_FADE_IN+32
		ld		e,6

.BUCLE_FADE_IN_PRESENTACION:

		call	SETPALETE_CINEMATICA

		push	hl
		push	de
		ld		a,6
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		pop		de
		pop		hl

		dec		e
		jp		nz,.BUCLE_FADE_IN_PRESENTACION

		; Dejamos la paleta final fija por seguridad.

		ld		hl,PALETA_MENU_LOCAL_FIJA
		jp		SETPALETE_CINEMATICA

FADE_OUT_PRESENTACION:

		ld		hl,PALETA_MENU_LOCAL_FADE_OUT
		ld		e,7

.BUCLE_FADE_OUT_PRESENTACION:

		call	SETPALETE_CINEMATICA

		push	hl
		push	de
		ld		a,6
		call	BUCLE_PINTA_TILES.rutina_de_pausa
		pop		de
		pop		hl

		dec		e
		jp		nz,.BUCLE_FADE_OUT_PRESENTACION

		ret

DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_3:

		dw		#0000,#0100
		dw		#0000,#0300
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_COPY_PRESENTACION_PAGE_1_A_PAGE_2:

		dw		#0000,#0100
		dw		#0000,#0200
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_0:

		dw		#0000,#0300
		dw		#0000,#0000
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_COPY_PRESENTACION_PAGE_3_A_PAGE_1:

		dw		#0000,#0300
		dw		#0000,#0100
		dw		#0100,#0100
		db		#00,#00,10010000b

DATOS_NEGRO_PAGE_0_CINEMATICA:

		; Borra solo la zona visible util de page 0.
		; No baja hasta Y=232/#7400 ni Y=240/#7800,
		; donde viven colores/patrones de sprites.
		dw		#0000,#0000
		dw		#0000,#0000
		dw		#0100,#00D5
		db		#00,#00,11000000b

DATOS_COPY_PARPADEO_CINEMATICA_2_ORIGINAL:

		dw		#004A,#0200+38
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_ORIGINAL
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

DATOS_COPY_PARPADEO_CINEMATICA_2_A:

		dw		#0000,#0200+216
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_FRAMES
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

DATOS_COPY_PARPADEO_CINEMATICA_2_B:

		dw		#002E,#0200+216
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_FRAMES
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

DATOS_COPY_PARPADEO_CINEMATICA_2_C:

		dw		#0000,#0200+236
		dw		CINEMATICA_PARPADEO_X_DESTINO,#0000+CINEMATICA_PARPADEO_Y_DESTINO_FRAMES
		dw		CINEMATICA_PARPADEO_ANCHO,CINEMATICA_PARPADEO_ALTO
		db		#00,#00,10010000b

ATRIBUTOS_BANDERA_CINEMATICA_0:

		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_0_1,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_0_2,#00

ATRIBUTOS_BANDERA_CINEMATICA_1:

		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_1_1,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_1_2,#00

ATRIBUTOS_BANDERA_CINEMATICA_2:

		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_Y,CINEMATICA_BANDERA_X,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_2_Y,CINEMATICA_BANDERA_2_X,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_3_Y,CINEMATICA_BANDERA_3_X,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_2_1,#00
		db		CINEMATICA_BANDERITA_Y,CINEMATICA_BANDERITA_X,CINEMATICA_BANDERITA_PATRON_2_2,#00

ATRIBUTOS_BANDERA_CINEMATICA_OCULTA:

		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERA_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERITA_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_BANDERITA_PATRON_0_2,#00

ATRIBUTOS_NUBE_CINEMATICA_OCULTA:

		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_0_3,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_1_3,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_2_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_2_2,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_3_1,#00
		db		CINEMATICA_BANDERA_Y_OCULTA,#00,CINEMATICA_NUBE_PATRON_3_2,#00

DATOS_COPY_CINEMATICA_1:

		dw		#0000,#0100
		dw		#0000,#0000
		dw		#0100,#008C
		db		#00,#00,10010000b

DATOS_COPY_CINEMATICA_2:

		dw		#0000,#0100+140
		dw		#0000,#0000
		dw		#0100,#004C
		db		#00,#00,10010000b

DATOS_COPY_CINEMATICA_3:

		dw		#0000,#0200
		dw		#0000,#0000
		dw		#0100,#0072
		db		#00,#00,10010000b

DATOS_COPY_CINEMATICA_4:

		dw		#004C,#0200+114
		dw		#0000,#0000
		dw		#00B4,#0064
		db		#00,#00,10010000b

TEXTO_CINEMATICA_1:

		dw		TEXTO_CINEMATICA_1_1
		dw		TEXTO_CINEMATICA_1_2
		dw		TEXTO_CINEMATICA_1_3
		dw		TEXTO_CINEMATICA_1_4

TEXTO_CINEMATICA_2:

		dw		TEXTO_CINEMATICA_2_1
		dw		TEXTO_CINEMATICA_2_2
		dw		TEXTO_CINEMATICA_2_3
		dw		TEXTO_CINEMATICA_2_4

TEXTO_CINEMATICA_3:

		dw		TEXTO_CINEMATICA_3_1
		dw		TEXTO_CINEMATICA_3_2
		dw		TEXTO_CINEMATICA_3_3
		dw		TEXTO_CINEMATICA_3_4

TEXTO_CINEMATICA_4:

		dw		TEXTO_CINEMATICA_4_1
		dw		TEXTO_CINEMATICA_4_2
		dw		TEXTO_CINEMATICA_4_3
		dw		TEXTO_CINEMATICA_4_4

TEXTO_CINEMATICA_5:

		dw		TEXTO_CINEMATICA_5_1
		dw		TEXTO_CINEMATICA_5_2
		dw		TEXTO_CINEMATICA_5_3
		dw		TEXTO_CINEMATICA_5_4

TEXTO_CINEMATICA_1_1:
		db		"Mientras amanece y todos se duchan",0
TEXTO_CINEMATICA_1_2:
		db		"Benja, el desarrollador es un poco trucha.",0
TEXTO_CINEMATICA_1_3:
		db		"El sol lo hinunda todo de norte a sur",0
TEXTO_CINEMATICA_1_4:
		db		"por eso no pienso volar con wintertour.",0

TEXTO_CINEMATICA_2_1:
		db		"El chumino se descuelga",0
TEXTO_CINEMATICA_2_2:
		db		"vamos todos a la huelga.",0
TEXTO_CINEMATICA_2_3:
		db		"tulitulitulitu",0
TEXTO_CINEMATICA_2_4:
		db		"visteme con canesu.",0

TEXTO_CINEMATICA_3_1:
		db		"si llego a saber que me dices eso",0
TEXTO_CINEMATICA_3_2:
		db		"te doy con la polla en los sesos.",0
TEXTO_CINEMATICA_3_3:
		db		"si me vas a contestar",0
TEXTO_CINEMATICA_3_4:
		db		"pues te doy en el paladar.",0

TEXTO_CINEMATICA_4_1:
		db		"Ya no se me ocurren mas rimas",0
TEXTO_CINEMATICA_4_2:
		db		"por eso he llamado a mi prima.",0
TEXTO_CINEMATICA_4_3:
		db		"esta es la ultima frase",0
TEXTO_CINEMATICA_4_4:
		db		"el pan me pide que lo amase.",0

TEXTO_CINEMATICA_5_1:
		db		"Un potorro esta palpitando",0
TEXTO_CINEMATICA_5_2:
		db		"es la Conchi que esta meando",0
TEXTO_CINEMATICA_5_3:
		db		"si tuviera fuerzas y humor",0
TEXTO_CINEMATICA_5_4:
		db		"imitaria a conde mor",0

ROTATIVO_X_PRESENTACION				equ		VARIABLE_UN_USO
ROTATIVO_CONTADOR_PRESENTACION		equ		VARIABLE_UN_USO2
ROTATIVO_PAGINA_VISIBLE_PRESENTACION	equ		VARIABLE_UN_USO3

ROTATIVO_Y_PRESENTACION				equ		195

; Cada cuántos frames se actualiza el rotativo.
; 1 = cada frame, 2 = cada dos frames, etc.
ROTATIVO_VELOCIDAD_PRESENTACION		equ		1

; Cuántos píxeles avanza cada actualización.
; 1 = suave, 2 = más rápido, 3 = más rápido pero menos fino.
ROTATIVO_PIXELES_POR_PASO_PRESENTACION	equ		3

ROTATIVO_LIMITE_PRESENTACION		equ		65536-((TEXTO_ROTATIVO_PRESENTACION_FIN-TEXTO_ROTATIVO_PRESENTACION-1)*MENU_LETRA_ANCHO)


INICIALIZA_ROTATIVO_PRESENTACION:

		ld		hl,255
		ld		(ROTATIVO_X_PRESENTACION),hl

		xor		a
		ld		(ROTATIVO_CONTADOR_PRESENTACION),a

		; Ahora mismo la visible es page 0.

		ld		(ROTATIVO_PAGINA_VISIBLE_PRESENTACION),a

		call	PREPARA_ROTATIVO_EN_PAGE_OCULTA
		call	PINTA_ROTATIVO_PRESENTACION_EN_PAGE_OCULTA
		call	TAPA_BORDES_ROTATIVO_EN_PAGE_OCULTA
		call	MUESTRA_PAGE_OCULTA_ROTATIVO
		ret


ACTUALIZA_ROTATIVO_PRESENTACION:

		ld		a,(ROTATIVO_CONTADOR_PRESENTACION)
		inc		a
		cp		ROTATIVO_VELOCIDAD_PRESENTACION
		jr		nc,.MUEVE_ROTATIVO_PRESENTACION

		ld		(ROTATIVO_CONTADOR_PRESENTACION),a
		ret


.MUEVE_ROTATIVO_PRESENTACION:

		xor		a
		ld		(ROTATIVO_CONTADOR_PRESENTACION),a

		call	PREPARA_ROTATIVO_EN_PAGE_OCULTA
		call	PINTA_ROTATIVO_PRESENTACION_EN_PAGE_OCULTA
		call	TAPA_BORDES_ROTATIVO_EN_PAGE_OCULTA
		call	MUESTRA_PAGE_OCULTA_ROTATIVO

		ld		hl,(ROTATIVO_X_PRESENTACION)
		ld		de,ROTATIVO_PIXELES_POR_PASO_PRESENTACION
		or		a
		sbc		hl,de
		ld		(ROTATIVO_X_PRESENTACION),hl

		; Si sigue en zona positiva, continuamos.
		ld		a,h
		or		a
		ret		z

		; Si ya ha pasado el límite negativo, reiniciamos.
		ld		de,ROTATIVO_LIMITE_PRESENTACION
		or		a
		sbc		hl,de
		ret		nc

		ld		hl,255
		ld		(ROTATIVO_X_PRESENTACION),hl
		ret

		ld		hl,255
		ld		(ROTATIVO_X_PRESENTACION),hl
		ret


OBTIENE_PAGE_OCULTA_ROTATIVO:

		ld		a,(ROTATIVO_PAGINA_VISIBLE_PRESENTACION)
		xor		1
		ret


PREPARA_ROTATIVO_EN_PAGE_OCULTA:

		call	OBTIENE_PAGE_OCULTA_ROTATIVO
		or		a
		jr		z,.PREPARA_ROTATIVO_EN_PAGE_0

		ld		hl,DATOS_NEGRO_ROTATIVO_EN_PAGE_1
		call	DOCOPY
		jp		VDPREADY


.PREPARA_ROTATIVO_EN_PAGE_0:

		ld		hl,DATOS_NEGRO_ROTATIVO_EN_PAGE_0
		call	DOCOPY
		jp		VDPREADY


MUESTRA_PAGE_OCULTA_ROTATIVO:

		call	OBTIENE_PAGE_OCULTA_ROTATIVO

		push	af
		call	SETPAGE
		pop		af

		ld		(ROTATIVO_PAGINA_VISIBLE_PRESENTACION),a
		ld		(ACPAGE),a

		ret


PINTA_ROTATIVO_PRESENTACION_EN_PAGE_OCULTA:

		call	OBTIENE_PAGE_OCULTA_ROTATIVO
		ld		(ACPAGE),a
		call	OBTIENE_DESTINO_Y_ROTATIVO_DESDE_A

		ld		ix,TEXTO_ROTATIVO_PRESENTACION
		ld		hl,(ROTATIVO_X_PRESENTACION)


.BUCLE_PINTA_ROTATIVO_PRESENTACION:

		ld		a,(ix+0)
		or		a
		jp		z,.FIN_PINTA_ROTATIVO_PRESENTACION

		; Sólo pintamos caracteres cuyo inicio esté entre 0 y 247.
		; Luego sólo copiaremos X=8..247 a page visible.

		ld		a,h
		or		a
		jr		nz,.SALTA_CARACTER_ROTATIVO_PRESENTACION

		ld		a,l
		cp		251
		jr		nc,.SALTA_CARACTER_ROTATIVO_PRESENTACION

		push	de
		push	hl
		push	ix

		ld		a,(ix+0)
		call	PINTA_LETRA_MENU_EN_DESTINO

		pop		ix
		pop		hl
		pop		de


.SALTA_CARACTER_ROTATIVO_PRESENTACION:

		ld		bc,MENU_LETRA_ANCHO
		add		hl,bc

		inc		ix
		jp		.BUCLE_PINTA_ROTATIVO_PRESENTACION


.FIN_PINTA_ROTATIVO_PRESENTACION:

		ret

TAPA_BORDES_ROTATIVO_EN_PAGE_OCULTA:

		call	OBTIENE_PAGE_OCULTA_ROTATIVO
		or		a
		jr		z,.TAPA_BORDES_ROTATIVO_PAGE_0

		ld		hl,DATOS_TAPA_BORDE_IZQ_ROTATIVO_PAGE_1
		call	DOCOPY
		call	VDPREADY

		ld		hl,DATOS_TAPA_BORDE_DER_ROTATIVO_PAGE_1
		call	DOCOPY
		jp		VDPREADY


.TAPA_BORDES_ROTATIVO_PAGE_0:

		ld		hl,DATOS_TAPA_BORDE_IZQ_ROTATIVO_PAGE_0
		call	DOCOPY
		call	VDPREADY

		ld		hl,DATOS_TAPA_BORDE_DER_ROTATIVO_PAGE_0
		call	DOCOPY
		jp		VDPREADY

DATOS_TAPA_BORDE_IZQ_ROTATIVO_PAGE_0:

		dw		#0000,#0000
		dw		#0000,#0000+ROTATIVO_Y_PRESENTACION
		dw		#0008,#0008
		db		#00,#00,11000000b


DATOS_TAPA_BORDE_DER_ROTATIVO_PAGE_0:

		dw		#0000,#0000
		dw		#00F8,#0000+ROTATIVO_Y_PRESENTACION
		dw		#0008,#0008
		db		#00,#00,11000000b


DATOS_TAPA_BORDE_IZQ_ROTATIVO_PAGE_1:

		dw		#0000,#0000
		dw		#0000,#0100+ROTATIVO_Y_PRESENTACION
		dw		#0008,#0008
		db		#00,#00,11000000b


DATOS_TAPA_BORDE_DER_ROTATIVO_PAGE_1:

		dw		#0000,#0000
		dw		#00F8,#0100+ROTATIVO_Y_PRESENTACION
		dw		#0008,#0008
		db		#00,#00,11000000b

DATOS_NEGRO_ROTATIVO_EN_PAGE_0:

		; Rectángulo negro en page 0.
		; X=8, Y=ROTATIVO_Y_PRESENTACION
		; ancho 240, alto 8.

		dw		#0000,#0000
		dw		#0008,#0000+ROTATIVO_Y_PRESENTACION
		dw		#00F0,#0008
		db		#00,#00,11000000b


DATOS_NEGRO_ROTATIVO_EN_PAGE_1:

		; Rectángulo negro en page 1.
		; X=8, Y=ROTATIVO_Y_PRESENTACION
		; ancho 240, alto 8.

		dw		#0000,#0000
		dw		#0008,#0100+ROTATIVO_Y_PRESENTACION
		dw		#00F0,#0008
		db		#00,#00,11000000b

; Editar estas lineas al sacar una version nueva.
; Regla del porcentaje: cada fase vale 2, cada enemigo y bloque auxiliar vale 1.
; EN TOTAL HAY 
; 5 PUNTOS DE 2(FASES) 4 HECHOS
; 6 PUNTOS DE 2(ENEMIGOS) 3 HECHOS
; 4 PUNTOS DE 1(LOGO, MENU, ANIMACION PRESENTACION Y ANIMACION CIERRE) 3 HECHO
; PUNTOS ACTUALES = (4+3)*2 + 3*1 = 17, PORCENTAJE ACTUAL = 17/26 = 65% APROXIMADAMENTE

TEXTO_ROTATIVO_PRESENTACION:

		db		"BLUE WARRIOR II - Beta version 4.5.17 - 19/5/2026 - 65% - (C) Digital Moai - TECLAS 1 - 5 PARA IR DIRECTO A FASE",0
		;db		"A Digital Moai Production - Project Direction, Phase Design, Story, Script, Level Design, Pixel Art and Music Composition: Manuel Dopico - Programming, Sprites, Pixel Art Corrections and Sound Effects: Benjamin Miguel - Graphics: Lucas Sera Piao - Lead Beta Tester and Quality Control: Xavi Sorinas - Packaging: XXX - Cover Illustration: XXX - Digital Moai sincerely thanks the following entities for helping keep the MSX alive: AAMSX (Spain), MSX Boixos Club (Spain), MSX.org (Holland) - (c) Digital Moai 2026",0

TEXTO_ROTATIVO_PRESENTACION_FIN:

PULSA_UNA_TECLA_PARA_EMPEZAR:

		xor		a
		call	GTTRIG_RAM
		or		a
		jp		nz,INICIA_EN_FASE_1

		ld		a,0
		call	SNSMAT_RAM
		bit		1,a
		jp		z,INICIA_EN_FASE_1

		ld		a,0
		call	SNSMAT_RAM
		bit		2,a
		jp		z,INICIA_EN_FASE_2

		ld		a,0
		call	SNSMAT_RAM
		bit		3,a
		jp		z,INICIA_EN_FASE_3

		ld		a,0
		call	SNSMAT_RAM
		bit		4,a
		jp		z,INICIA_EN_FASE_4

		ld		a,0
		call	SNSMAT_RAM
		bit		5,a
		jp		z,INICIA_EN_FASE_5

		halt
		call 	ACTUALIZA_ROTATIVO_PRESENTACION
		jp		PULSA_UNA_TECLA_PARA_EMPEZAR

INICIA_EN_FASE_1:

		ld		a,1
		ld		(FASE),a
		jp		SEGUIMOS

INICIA_EN_FASE_2:

		ld		a,2
		ld		(FASE),a
		jp		SEGUIMOS

INICIA_EN_FASE_3:

		ld		a,3
		ld		(FASE),a
		jp		SEGUIMOS

INICIA_EN_FASE_4:

		ld		a,4
		ld		(FASE),a
		jp		SEGUIMOS

INICIA_EN_FASE_5:

		ld		a,5
		ld		(FASE),a

SEGUIMOS:

		di
		ld		a,#C9
		ld		(HTIMI),a
		ld		(HKEYI),a
		ei
		call	PARA_MUSICA_MENU_PRESENTACION

		call	FADE_OUT_PRESENTACION

		call	DISSCR_RAM
		ld		a,5
		call	CHGMOD
		call	DISSCR_RAM

		ld		hl,0
		xor		a
		ld		(ARMA_USANDO),a										; 0 1 2 para flecha 3 4 5 para fuego 6 7 8 para hacha
		ld		(V_DECEN_MIL),a
		ld		(V_UNIDA_MIL),a
		ld		(V_CENTENAS),a
		ld		(V_DECENAS),a
		ld		(V_UNIDADES),a
		ld		(SCORE_REAL),hl
		add		2
		ld		(MAGIAS),a
		ld		(VIDAS),a
		ld		(CORAZONES),a
		inc		a
		ld		(CORAZONES_MAXIMOS),a

		call	DISSCR_RAM

RECUPERAMOS_INTERRUPCIONES_LIMPIAS:

		di
		ld		a,#C9													; A tiene el valor de ret
		ld		(HTIMI),a												; Colocamos ese ret en el gancho H.Timi POR SI EL ORDENADOR TUVIERA ALGO (ALGUN MSX 2 CONTROL DE DISQUETERA)
		ld		(HKEYI),a												; Colocamos ese ret en el gancho H.Key POR SI EL ORDENADOR TUVIERA ALGO
		ei

DESACTIVAMOS_INTERRUPCIONES_DE_LINEA_TRAS_EL_MENU:

		di
		ld 		a,(RG0SAV)												; Disable Line Interrupt: Reset R#0 bit 4
		and		11101111B
		ld		(RG0SAV),a
		ld		b,a
		ld		c,0
		call	WRTVDP_EN_RAM
		ei

NOS_VAMOS_AL_JUEGO:

		ld		a,8
		ld      (DIRPA2),a										    ; Banco 1, pagina 3 del MEGAROM
		jp		CARGA_SLOT_JUEGO

TABLA_LATIDO_CINEMATICA_2:

		db		#20,#00,#40,#00
		db		#30,#00,#51,#01
		db		#40,#00,#62,#02
		db		#51,#01,#73,#03
		db		#62,#12,#74,#14
		db		#73,#23,#75,#25
		db		#74,#34,#76,#36
		db		#73,#23,#75,#25
		db		#62,#12,#74,#14
		db		#51,#01,#73,#03
		db		#40,#00,#62,#02
		db		#30,#00,#51,#01

PALETA_CINEMATICA_1_2:
       	incbin  "../PALETAS/PRESENTACION/CINEMATICA12.palete"
FADE_IN_CINEMATICA_1_2:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA12.fadein"
FADE_OUT_CINEMATICA_1_2:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA12.fadeout"
PALETA_CINEMATICA_3_4:
       	incbin  "../PALETAS/PRESENTACION/CINEMATICA34.palete"
FADE_IN_CINEMATICA_3_4:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA34.fadein"
FADE_OUT_CINEMATICA_3_4:
		incbin  "../PALETAS/PRESENTACION/CINEMATICA34.fadeout"
PALETA_MENU_LOCAL_FIJA:
		incbin  "../PALETAS/PRESENTACION/MENUIMAG.palete"

PALETA_MENU_LOCAL_FADE_IN:
		incbin  "../PALETAS/PRESENTACION/MENUIMAG.fadein"

PALETA_MENU_LOCAL_FADE_OUT:
		incbin  "../PALETAS/PRESENTACION/MENUIMAG.fadeout"

SPRITES_Y_PALETAS:
	; --- BANDERA 0
MENU_SPRITE_MASK_01:
	; mask 0
	DB $01,$01,$00,$00,$00,$00,$01,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
	DB $00,$E0,$E0,$F0,$FE,$8C,$8C,$00
	DB $00,$80,$80,$80,$00,$00,$00,$00
MENU_SPRITE_ATTR_01:
	; attr 0
	DB $01,$01,$0E,$0E,$0E,$0E,$01,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
MENU_SPRITE_MASK_02:
	; mask 1
	DB $00,$00,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$F0,$FF,$FF,$FE,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_02:
	; attr 1
	DB $00,$00,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- BANDERA 1
MENU_SPRITE_MASK_03:
	; mask 0
	DB $01,$00,$00,$00,$00,$00,$01,$01
	DB $01,$01,$01,$00,$00,$00,$00,$00
	DB $0F,$0E,$FC,$F0,$E0,$80,$80,$00
	DB $00,$80,$80,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_03:
	; attr 0
	DB $01,$0E,$0E,$0E,$0E,$0E,$01,$01
	DB $01,$01,$01,$00,$00,$00,$00,$00
MENU_SPRITE_MASK_04:
	; mask 1
	DB $00,$01,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$FF,$FE,$FC,$F0,$E0,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_04:
	; attr 1
	DB $00,$01,$01,$01,$01,$01,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- BANDERA 2
MENU_SPRITE_MASK_05:
	; mask 0
	DB $01,$01,$00,$00,$00,$00,$00,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
	DB $00,$E0,$E0,$F0,$FC,$8C,$06,$06
	DB $00,$80,$80,$80,$00,$00,$00,$00
MENU_SPRITE_ATTR_05:
	; attr 0
	DB $01,$01,$0E,$0E,$0E,$0E,$0E,$01
	DB $01,$01,$01,$01,$00,$00,$00,$00
MENU_SPRITE_MASK_06:
	; mask 1
	DB $00,$00,$01,$01,$01,$01,$01,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$F0,$FC,$FE,$FE,$8F,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_06:
	; attr 1
	DB $00,$00,$01,$01,$01,$01,$01,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- NUBE 0
MENU_SPRITE_MASK_07:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $01,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$07,$07,$1F,$05,$9D,$0D
	DB $67,$3F,$EF,$1D,$12,$0B,$07,$05
MENU_SPRITE_ATTR_07:
	; attr 0
	DB $00,$00,$0E,$0E,$0E,$0E,$0A,$0A
	DB $0A,$0B,$0E,$0E,$0A,$0E,$0E,$0E
MENU_SPRITE_MASK_08:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $01,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$03,$0E,$04,$9F,$3F
	DB $6F,$7F,$E9,$09,$1E,$09,$00,$00
MENU_SPRITE_ATTR_08:
	; attr 1
	DB $00,$00,$00,$41,$41,$41,$44,$44
	DB $44,$44,$41,$41,$44,$41,$00,$00
MENU_SPRITE_MASK_09:
	; mask 2
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $01,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$9C,$04
	DB $66,$00,$00,$00,$02,$00,$00,$00
MENU_SPRITE_ATTR_09:
	; attr 2
	DB $00,$00,$00,$00,$00,$00,$41,$41
	DB $41,$00,$00,$00,$41,$00,$00,$00
	;
	; --- NUBE 1
MENU_SPRITE_MASK_10:
	; mask 0
	DB $00,$00,$80,$00,$50,$90,$A8,$20
	DB $C1,$DB,$FF,$9F,$E0,$C0,$BE,$EE
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$80,$A0,$3E,$00,$00,$00,$00
MENU_SPRITE_ATTR_10:
	; attr 0
	DB $00,$00,$04,$00,$0A,$04,$0A,$0B
	DB $0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A
MENU_SPRITE_MASK_11:
	; mask 1
	DB $00,$00,$00,$00,$58,$00,$EA,$A8
	DB $E1,$FB,$FF,$9F,$FF,$F3,$FF,$EE
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$C0,$F8,$3F,$EF,$BC,$E0,$80
MENU_SPRITE_ATTR_11:
	; attr 1
	DB $00,$00,$00,$00,$44,$00,$44,$44
	DB $44,$44,$44,$44,$44,$44,$44,$44
MENU_SPRITE_MASK_12:
	; mask 2
	DB $00,$00,$00,$00,$40,$00,$20,$00
	DB $81,$DB,$1E,$10,$A0,$00,$14,$02
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$20,$0E,$00,$00,$00,$00
MENU_SPRITE_ATTR_12:
	; attr 2
	DB $00,$00,$00,$00,$41,$00,$41,$00
	DB $41,$41,$41,$41,$41,$00,$41,$41
	;
	; --- NUBE 2
MENU_SPRITE_MASK_13:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $06,$01,$01,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_13:
	; attr 0
	DB $0A,$04,$0E,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_MASK_14:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $07,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_14:
	; attr 1
	DB $44,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- NUBE 3
MENU_SPRITE_MASK_15:
	; mask 0
	DB $76,$84,$A0,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_15:
	; attr 0
	DB $04,$0A,$0A,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_MASK_16:
	; mask 1
	DB $00,$DC,$A8,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_16:
	; attr 1
	DB $00,$44,$44,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	;
	; --- BANDERITA 0
MENU_SPRITE_MASK_17:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$E0,$60,$70,$F0,$80,$80
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_17:
	; attr 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$01,$0E,$0E,$01,$01,$01
MENU_SPRITE_MASK_18:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$F8,$F8,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_18:
	; attr 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$01,$01,$00,$00,$00
	;
	; --- BANDERITA 1
MENU_SPRITE_MASK_19:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$10,$10,$70,$60,$F0,$80,$80
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_19:
	; attr 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$01,$0E,$0E,$0E,$01,$01,$01
MENU_SPRITE_MASK_20:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$F8,$F8,$F8,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_20:
	; attr 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$01,$01,$01,$00,$00,$00
	;
	; --- BANDERITA 2
MENU_SPRITE_MASK_21:
	; mask 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$E0,$60,$70,$30,$B0,$80
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_21:
	; attr 0
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$01,$0E,$0E,$0E,$01,$01
MENU_SPRITE_MASK_22:
	; mask 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$F0,$F8,$F8,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$00,$00,$00,$00,$00
MENU_SPRITE_ATTR_22:
	; attr 1
	DB $00,$00,$00,$00,$00,$00,$00,$00
	DB $00,$00,$00,$01,$01,$01,$00,$00
