; PÀLETAS
		
PALETA_FASE_1_1_FADE_IN:

		incbin "FASE1-1.FADIN"

PALETA_GRISES:

		incbin	"GRISES.palete"

PALETA_GRISES_FADE_OUT:

		incbin	"GRISES.FADEOUT"

TABLA_COLOR_SPRITE_CENTRAL_BOSS_2:
	db		$0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
	db		$0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
		